### ISSUE TITLE
inquierer-search-list always selects the first value when validation function return false / error

### ISSUE THREAD

**Issue by NullVoxPopuli** [SBoudrias/Inquirer.js#1007]
using this plugin: https://github.com/robin-rpr/inquirer-search-list (they have issues turned off?)

But, when I have a list with choices, and I type in an option that doesn't exist, I would expect that when I press enter that the question isn't accepted -- what's happening now is that the top option of `choices` is accepted as what I selected -- I don't think that makes sense :thinking:

**Comment by SBoudrias** [comment]
Of interest, proposal to add a search prompt to the core https://github.com/SBoudrias/Inquirer.js/pull/1479
