### ISSUE TITLE
Awesome work people. This is a great project

### ISSUE THREAD

**Issue by chidioguejiofor** [SBoudrias/Inquirer.js#1010]
This package really helped me today. I really love the documentation/examples you added to this. 

Really awesome work!

I was able to build my first CLI application in less than an hour thanks to how well this was built and documented

Wasn't sure where else to put this so I thought I could add an issue you don't need to fix 😁.

Kudos!

**Comment by LitoMore** [comment]
Thank you so much! Enjoy your code!
