### ISSUE TITLE
skipping question if already answered

### ISSUE THREAD

**Issue by realrecordzLab** [SBoudrias/Inquirer.js#1011]
I'm using inquirer to prompt some questions to the user. I've included it inside a class and I need to skip a question if it was already answered from the user. I've noticed that the question will be anyway asked also if the user already answered it. Is there a good solution for this? 

```js
this.settings = await inquirer.prompt([
            {
                type: 'input',
                name: 'username',
                message: 'Welcome! Insert your name: ',
                validate: (input) => {
                    if( input.trim() === '' ){
                        console.log(chalk.red('Please insert username!'));
                        return false;
                    }else{
                        return true;
                    }
                },
                // Tried with this but seems not work
                when: (input) => {
                    if( input.username !== 'undefined' ){
                        return true;
                    }else{
                        return false;
                    }
                }
            },
            {
                type: 'list',
                name: 'inboxNumber',
                message: 'Select a number',
                choices: [5, 10, 20, 25]
            }
        ]);
```

**Comment by LitoMore** [comment]
My solution is to set a default value for users. Then they just need to press enter to go to the next question.

My example is [here](https://github.com/fanfoujs/nofan/blob/main/src/prompts/colors.js).

**Comment by realrecordzLab** [comment]
> My solution is to set a default value for users. Then they just need to press enter to go to the next question.
> 
> My example is [here](https://github.com/fanfoujs/nofan/blob/main/src/prompts/colors.js).

I've figured out that the `when` method will get the user input and the previous answers hash. This mean that I'm able to access to previous answer and store the needed information inside a variable to check when needed to skip the question.
