### ISSUE TITLE
Using `terminal-link` causes question text to get broken into two lines

### ISSUE THREAD

**Issue by doitadrian** [SBoudrias/Inquirer.js#1014]
Hi everybody..

So I tried to use the [`terminal-link`](https://www.npmjs.com/package/terminal-link) package to create a link in one of the questions in my wizard, and what happens is the text gets broken into two lines (the red arrow):

![image](https://user-images.githubusercontent.com/5121148/117996875-d18fae80-b342-11eb-8626-b2178b909b0d.png)

If I do a regular `console.log`, everything seems to be printed correctly (green arrow).

Not sure if this is related to Inquirer.js or not.

I searched the issues and found there was an issue with a child dependency before, but it seems that was resolved and it didn't have much to do with this issue.

Anyone have any ideas on how to debug this maybe?

Thank you!

---
`terminal-link` version: `2.1.1`
` Inquirer.js` version: `8.0.0`

**Comment by doitadrian** [comment]
Maybe this?

https://github.com/sindresorhus/ansi-escapes/blob/main/index.js#L92

**Comment by starpit** [comment]
It doesn't seem to be in the `clean` function. I am seeing the problem in `breakLines`. Here is an example of the `chunk` (from `breakLines`) that terminal-link creates for a link equivalent to this markdown [kind](https://kind.sigs.k8s.io/kind)

```
[
  '\x1B[36m❯ \x1B[1mOn kind\x1B[22m: You may choose to install Knative and Kubernetes on a local Docker daemon via \x1B]8;;https://kind.sigs.k8s.io/\x07kind',
  '\x1B]8;;\x07.\x1B[39m',
  ''
]
```

I note how there are two chunks resulting from the `breakLines` regex: 

```
    const regex = new RegExp(`(?:(?:\\033[[0-9;]*m)*.?){1,${width}}`, 'g');
```

So it looks like the `\x1B]8` character used by `terminal-link` is matched by the `\\033[[0-9;]` part?
