### ISSUE TITLE
UX Improvement: Use square checkboxes, not round ones

### ISSUE THREAD

**Issue by Chaphasilor** [SBoudrias/Inquirer.js#1015]
I noticed in the readme and also in the actual examples that the "checkboxes" are either actual emojis/chars of literal radio buttons (round, with dot inside if selected) or round brackets (parentheses), as opposed to square checkboxes.

Screenshot from the readme ([link](https://github.com/SBoudrias/Inquirer.js#checkbox---type-checkbox)):  
<img alt="Screenshot from the readme" src="https://camo.githubusercontent.com/babdae40c1d2ec3da40b789998814cd42e93a43dd961837bef56cd525aeacac0/68747470733a2f2f63646e2e7261776769742e636f6d2f53426f7564726961732f496e7175697265722e6a732f323861653833333762613531643933653335396566346637656532346537396236393839383936322f6173736574732f73637265656e73686f74732f636865636b626f782e737667" height="150"/>

Screenshot from Windows Terminal (using the examples from Github):  
<img alt="Screenshot from Windows Terminal" src="https://user-images.githubusercontent.com/18015147/118546256-fa0b1480-b757-11eb-989f-33ec0e3d3d21.png" height="150"/>

Users, however, are used to the following, based on how every browser and GUI program implements it:

- Checkboxes, where you can select *multiple* options per group/choice/question, are **square** (with a cross or a checkmark when selected)
- Radio buttons, where you can select *only one* option per group/choice/question, are **round** (with a dot/circle, on completely filled, inside)

`Inquirer.js`, of course, uses `list` for a radio button/group equivalent, and `checkbox` for a checkbox equivalent, the problem is that the user doesn't know that.  
They see a **round, selectable option**, and are likely to think that they are looking at a radio button/group, potentially resulting in them only selecting a single option because they didn't even try selecting a second one.

So, all in all I propose to change the way checkboxes are rendered by `Inquirer.js`, from the current way to something more akin to checkboxes in the browser.

Here are some examples:

- Change the parentheses `()` to brackets `[]`: `( ), (*) => [ ], [x]`
- Change the character used in the Readme-screenshots from 🔘 to ✅ (I don't know where the radio button symbol in the screenshots is coming from, so I don't know if there is a checkbox alternative)

It's a simple change, really, so it shouldn't break anything, but it would improve the UX of end users and dev reading the Readme *a lot*, I think :)

**Comment by SBoudrias** [comment]
Oh I wonder how we ever ended up with this indeed 😂 

PR welcomed!!

**Comment by SBoudrias** [comment]
BTW the characters are coming from https://github.com/sindresorhus/figures - it might've just been because the checkboxes aren't looking great.

**Comment by Chaphasilor** [comment]
Hey @SBoudrias, I'm absolutely willing to make a PR for this! :)  
You are right that the checkbox from [figures](https://github.com/sindresorhus/figures) doesn't look too nice, although for a CLI app I'd honestly go with `[ ]` and `[x]` anyway, I think it fits better..

But your package, your call: use the checkbox, always use brackets or leave it the way it is? 🤔

**Comment by SBoudrias** [comment]
Yeah, so I thought a bit about this. Let's keep as-is; the checkboxes figures aren't looking good, and the drawback of `[ ]` is it takes 3 characters space, making it quite visually heavy.

Thanks for raising it up though, I do agree this can be confusing when compared to OS defaults.
