### ISSUE TITLE
[Feature request] Support description for choices

### ISSUE THREAD

**Issue by nliu-ms** [SBoudrias/Inquirer.js#1019]
Hi there!

I noticed that only @inquirer/select support description for choices. Others like list/checkbox doesn't support it.

It seems that `short` value for choice can help. But this only shows after selecting, which may be too late for the user.

Do you have plan to add description for choices! That would be very helpful! Thank you!

**Comment by nliu-ms** [comment]
And it would be better if description can be the same line with the option, e.g.
![image](https://user-images.githubusercontent.com/71362691/121303686-f66d4680-c92d-11eb-92ed-6afb98424078.png)

**Comment by doitadrian** [comment]
@nliu-ms Maybe the solution in my duplicate issue could help you in the meantime. Not ideal, but at the same time, not that bad.

![image](https://user-images.githubusercontent.com/5121148/122187225-24eba400-ce8f-11eb-81bb-bf92c66cf5da.png)

**Comment by SBoudrias** [comment]
This is something I'd prefer to keep in user land.

I'd recommend checking different text/table formatting modules on NPM. Then you should be able to use the output as the `name` of each choice.
