### ISSUE TITLE
Is it possible to add descriptions for items in the list?

### ISSUE THREAD

**Issue by doitadrian** [SBoudrias/Inquirer.js#1021]
Something like this maybe?

![image](https://user-images.githubusercontent.com/5121148/122158414-e9d87900-ce6c-11eb-9a5a-ebaff1861426.png)

I was thinking of adding a couple of `\t`s that might emulate this, but I can see this won't get me too far :)

![image](https://user-images.githubusercontent.com/5121148/122158649-4e93d380-ce6d-11eb-8ef5-84cbea2514f7.png)

Maybe there's a plugin that enables this feature?

Sorry if this was already discussed and I missed the issue. Was searching GH but could not find anything.

Thanks! 🍻

**Comment by doitadrian** [comment]
I went with the following approach in the end:

![image](https://user-images.githubusercontent.com/5121148/122166763-5148f580-ce7a-11eb-9f93-e9261176c591.png)

So, I just bolded the first line, and in the next line, added a description.

I'm satisfied how it looks.

**Comment by SBoudrias** [comment]
I like how that prompt looks! Well done :)

**Comment by doitadrian** [comment]
Thanks ☺️
