### ISSUE TITLE
Passing answers with nested properties to prompt() doesn't seem to work

### ISSUE THREAD

**Issue by atava** [SBoudrias/Inquirer.js#1024]
As per the doc about [prompt()](https://github.com/SBoudrias/Inquirer.js#inquirerpromptquestions-answers---promise), passing an "answers" hash should have it skip those questions for which values are set in the hash.

It doesn't seem to work with nested properties (e.g. "foo.bar").
I tested changing the property to "fooBar" and it works, so I presume it's the nesting/path that is not dealt with properly.

**Comment by SBoudrias** [comment]
Can you provide a code example?

**Comment by atava** [comment]
I think this could be one: [InquirerPromptAnswersTest](https://replit.com/@atava/InquirerPromptAnswersTest#index.js)

When using a property path for the question instead of a simple property (e.g. 'info.sex' instead of 'sex') the default behavior of skipping the question fails.

**Comment by owings1** [comment]
pull request #1028

**Comment by ovidiu141** [comment]
This can be closed?
