### ISSUE TITLE
在终端粘贴（cmd+v）时，如果粘贴的内容超出终端的宽度，则会触发render方法，addendContent 一直输出。

### ISSUE THREAD

**Issue by BluesVN** [SBoudrias/Inquirer.js#1034]
![image](https://user-images.githubusercontent.com/27759401/130072336-a7d35da1-de67-4caa-8960-8c0b4a941582.png)

type: input

**Comment by xutaocc** [comment]
var questions = [{
    type: 'input',
    message: 'message有中文不行',//'message有中文不行\n' 
    name: 'gitHashStr'
    // default: "" // 默认值
},



message里面有中文 我会出现这个问题。
在中文后面添加\n临时解决这个问题

**Comment by LitoMore** [comment]
English, please. Closing.
