### ISSUE TITLE
Question: xargs and prompt

### ISSUE THREAD

**Issue by sheeeeep** [SBoudrias/Inquirer.js#1037]
When I use xargs to pass arguments as inquirer's prompt，it terminated.

This is a demo: 

```javascript
var name = process.argv[2];
var inquirer = require('inquirer');
inquirer
  .prompt([
    {
      type: 'input',
      name: 'age',
      message: `Hi ${name}, How old are you?`,
    }
  ])
  .then((answers) => {
    console.log(answers)
  })
```

When I exec `echo jack |xargs node index.js`, it output 'Hi jack, How old are you? %' and then terminated.

**Comment by houfeng0923** [comment]
is this issue not exist ?

**Comment by SBoudrias** [comment]
This is because xargs doesn't assign stdin/stdout to your CLI steams.

Some more information about this here https://stackoverflow.com/questions/30044927/xargs-exec-command-with-prompt
