### ISSUE TITLE
EventListener Memory Leak

### ISSUE THREAD

**Issue by IntelliDigitalOPS** [SBoudrias/Inquirer.js#1038]
My code's pretty similar to the recursive example given in /examples. Yet I keep getting and EventListener Memory Leak error and the UI starts glitching. I've read previous issues related to this but no avail. I'm not making any HTTP requests from within node. 

Screenshot:
![Image](https://java.is-inside.me/uzADcACl.png)

Node Version: 16.8.0
Inquirer Version: 8.1.2
OS: Windows

**Comment by scottwestover** [comment]
I also started running into this issue as well while using the `@inquirer/input` npm package. 

Example code to recreate the issue:
```javascript
const input = require('@inquirer/input');

(async () => {
  let quitGame = false;

  while (!quitGame) {
    const answer = await input({
      message: 'Which position would you like to place your X?',
    });

    if (answer === 'exit') {
      quitGame = true;
    }
  }
  console.log('exiting game');
})();
```

After providing input 10 times, you should get the following error:
```
? Which position would you like to place your X? (node:27714) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27714) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:27714) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
```

Additional Information:
`@inquirer/input` npm package version: `0.0.16-alpha.0`
Node version: `v16.9.0`
OS: macOS Mojave Version 10.14.6

**Comment by nanomosfet** [comment]
this is happening in 7.3.3 of inquierer

going to have to move off this package for this reason

**Comment by Kief5555** [comment]
Issue here on 8.2.3
