### ISSUE TITLE
Unexpected token '??'

### ISSUE THREAD

**Issue by stephenwoosley** [SBoudrias/Inquirer.js#1046]
Looks like on line 126 of `packages/inquirer/lib/prompts/rawlist.js`, there is a ternary with an accidental added ?

**Comment by zhouxiongking** [comment]
i am also getting this trouble。
![image](https://user-images.githubusercontent.com/15647000/133362863-bcb98e8d-342d-4954-9192-9fc7d9205bdc.png)

**Comment by sxxhlx** [comment]
same problem ，this `??` token is not supported below node@14.0.0

**Comment by Alexixyc** [comment]
HELP!!!!!!!!!!!!!!!  Please fix ！！！
![image](https://user-images.githubusercontent.com/17401583/133363773-1b575ec4-924a-4af8-a76e-32df61cb97d5.png)

**Comment by stephenwoosley** [comment]
After looking into it more, looks like the nullish coalescing operator (??) was introduced in ES2020. I'm using node v12 so I'm sure that's the problem, but when I rolled back to inquirer@8.1.3 all was well.

**Comment by stephenwoosley** [comment]
> same problem ，this `??` token is not supported below node@14.0.0

@sxxhlx probably want to roll back to 8.1.3?

**Comment by yiyu-liao** [comment]
save error

**Comment by hotoo** [comment]
+1

**Comment by B2D1** [comment]
![image](https://user-images.githubusercontent.com/36991862/133369500-c7c2d429-a7ae-42e7-920e-9afea7374270.png)
 
my node version is below v14!

**Comment by ViniSiva** [comment]
Is this issue resolved. we are still facing it.  Do we need to downgrade the version ?

**Comment by enclairfarron** [comment]
breaking change

**Comment by jlipps** [comment]
Yes, this was a breaking change in Node engine support on a patch release. recommended to pin to previous version until something like #1047 is merged and published.

**Comment by splurgeop** [comment]
Same issue for us 
this is breaking our build.
When we upgraded to the latest version. This broke our pipeline

/build/node_modules/inquirer/lib/prompts/rawlist.js:126
this.selected = this.selected ?? -1;
^
SyntaxError: Unexpected token '?'
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module._compile (internal/modules/cjs/loader.js:963:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Function.promptModule.restoreDefaultPrompts (/build/node_modules/inquirer/lib/inquirer.js:65:36)
at Object.inquirer.createPromptModule (/build/node_modules/inquirer/lib/inquirer.js:72:16)
at Object. (/build/node_modules/inquirer/lib/inquirer.js:84:28)

**Comment by SanariSan** [comment]
#1042 #1045
Replaced es2020 operator with explicit check.
_
I apologise for making breaking change.

**Comment by monsterboom** [comment]
please roll back to 8.1.3   ......
all my new users install my package which dependency it , error now ...
i dont want to lock it in my package.json

**Comment by SBoudrias** [comment]
Please do lock your versions on your project and save yourself some trouble when issues like this arise in any OSS package you're using. We're unfortunately not having a 24/7 red line.

We'll have a fix out soon; but a breaking build due to automatically updated dependencies is something you can prevent in many ways.

**Comment by SBoudrias** [comment]
8.1.5 is out fixing the Node compatibility issue.
