### ISSUE TITLE
Need styling options

### ISSUE THREAD

**Issue by WerdoxDev** [SBoudrias/Inquirer.js#1049]
One of the first things that disappointed me from using inquirer is the **lack** of styling options.
I know this isn't something that makes Inquirer **work** but it is something that people can use to give a unique look to their cli.
This could also benefit those who want different language support for their cli, because most of the texts like **(Use arrow keys)** in lists, are not changeable.

Just to be clear by styling i dont mean choosing color, thats already done by chalk. i mean being able to change the text.

this could either be:
 A - a object where you define all styles for different things like **list**, **confirm** and all other ones
 B - defining the style on each question object

**Things that imo could get a custom styling option**
   Entered input - when you are done with a question the answer will change to a blueish color which should be changeable.
   List options - the list options are always a blueish color with a > mark when active which again should be changable
   The gray () texts - things like **confirm** and **list** have a little note to inform user what to do which should be changeable for 
      language support purposes

Also the **Entered input** one might be weird because its literally what the user typed i guess it could be changed with a placeholder thingy like "{text}" where **{text}** is what the user typed and because its a string you can color it or add things to it.

**Comment by SBoudrias** [comment]
This is something that'll be quite hard to inject in the current architecture. But as part of the refactor, it is something I want to bring in as a react context like API.

Most prompts are already re-implemented in beta versions on the `master` branch. Any help getting this feature implemented or help with the refactor itself so it eventually replace the `inquirer` package is welcomed. Plan is here https://github.com/SBoudrias/Inquirer.js/issues/692 - and I'm happy to help and discuss the right approach.

**Comment by WerdoxDev** [comment]
I would have loved to help with this but i have other important things to do and i have little to no time to do then.
though i will consider helping after I'm done with those.

All in all I'm really happy this is a consideration for Inquirer keep up the amazing work!

**Comment by SBoudrias** [comment]
All new prompts now support theming. PRs welcomed to add more options.
