### ISSUE TITLE
How do I turn off the requirement  to hit enter?

### ISSUE THREAD

**Issue by pabrams** [SBoudrias/Inquirer.js#1051]
When the answer keys are 1 digit long, hitting enter is obviously not necessary, but inquirer seems to always require enter, by  default, and I can't figure out how to turn it off.

**Comment by pabrams** [comment]
Oh, I just found this, which looks like exactly what I wanted...
https://github.com/yaodingyd/inquirer-autosubmit-prompt

**Comment by SBoudrias** [comment]
great :)
