### ISSUE TITLE
Feature: display default value "confirm" type input message

### ISSUE THREAD

**Issue by veryspry** [SBoudrias/Inquirer.js#1058]
It would be nice if the default value passed to the `confirm` type options was automatically displayed in the options message.

One could obviously hard code the default in the `message` string, but this is a) easily forgotten and b) prone to error, especially if the default is changed in the future.

For instance, if the passed option was:

```js
{
  type: 'confirm'
  name: 'clearCache',
  message: 'Do you want to clear the cache before building?'
  default: false,
}
```

Then the standard out written to the terminal would be:

```sh
? Do you want to clear the cache before building? (default is no):
```

I'm happy to create a PR for this if it is worth adding :raised_hands: 

## ***Edit***
It looks like this feature already exists [here](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/confirm/index.js#L27)

IIRC, this is how the `apt update` confirm option defaults are communicated, but I've never really paid close attention since I always enter an explicit answer. I always wandered why one letter in the `y/N` was uppercase and the other lowercase.

That said, I always prefer the more verbose style as suggested above. Thoughts on using the more verbose style?

**Comment by SBoudrias** [comment]
One concern is that `y/N` does hint to the type of input expected. I'm not sure the alternative makes it as clear that we expect a "yes" or "no" answer.

Any thoughts/opinions from other users?

**Comment by veryspry** [comment]
> One concern is that `y/N` does hint to the type of input expected. I'm not sure the alternative makes it as clear that we expect a "yes" or "no" answer.
> 
> Any thoughts/opinions from other users?

That's a good point! I'm going to close this since the feature technically exists and has the upside of communicating the available choices :slightly_smiling_face:
