### ISSUE TITLE
Async when causes unexpected behavior

### ISSUE THREAD

**Issue by baileyherbert** [SBoudrias/Inquirer.js#1062]
**Platforms:** Windows 10, 11
**Node versions:** 14, 16

When a prompt has an async `when` which returns false after some time, the next prompt will not start registering input until the enter key is pressed, and the question is duplicated. 

- If the async `when` resolves immediately, or within a single tick (e.g. setTimeout with 1ms) then the issue does _not_ occur.
- If `when` is set to false directly, the issue also does _not_ occur.

Reproduced on both the latest version `8.2.0` and the much older `6.5.0`.

Here's an example:

![repro](https://i.bailey.sh/LooEauY.gif)

And the code used:

```js
const inquirer = require('inquirer');

(async function () {
	await inquirer.prompt({
		name: 'cancelled',
		type: 'input',
		message: 'Enter some text (hidden)',
		when: async () => {
			// Set this timeout to 0, 1 or remove it and the issue goes away??
			await new Promise(r => setTimeout(r, 50));
			return false
		}
	});

	console.log(await inquirer.prompt({
		name: 'input1',
		type: 'input',
		message: 'Enter some text (#1)'
	}));

	console.log(await inquirer.prompt({
		name: 'input2',
		type: 'input',
		message: 'Enter some text (#2)'
	}));
})();
```

**Comment by nofear-js** [comment]
The same effect occurs with `async validate`.

**Comment by ovidiu141** [comment]
Could not reproduce this with "inquirer": "^10.2.1". Should probablyclose this issue.
