### ISSUE TITLE
Using dynamic variables as methods?

### ISSUE THREAD

**Issue by sweetnoods** [SBoudrias/Inquirer.js#1064]
This is more of a JavaScript question but I'm having an issue using variables as faker methods. 

For context, I'm trying to write a CLI tool that prompts the user to select from the array of faker methods. The flow starts with: 
![image](https://user-images.githubusercontent.com/56055809/141656316-7dde84fe-acb0-4581-b0df-91cd40b6e5c3.png)

However, I'm getting stuck trying to use the user's input to generate the second array of choices. As an example faker.internet, where internet would be stored in a variable. 

This code might help identify my problematic approach to this problem: 

```
const faker = require('faker');
console.log(faker.internet);
// returns the expected JSON object

var method = "internet";
console.log(faker.method)
// undefined

// remove the quotes from "internet"
var method = method.replace(/['"]+/g, '')
console.log(method)
// internet

console.log(faker.method)
// undefined
```

EDIT: From what I've been reading [online](https://www.w3schools.com/js/js_object_constructors.asp) - it looks like I need to construct this as a new object. Will follow-up if solution found.

**Comment by SBoudrias** [comment]
To transform a string into a variable reference, you would need to use `eval`; but I highly discourage this approach for multiple reasons.

Instead a map is what you'd want. In your case, sounds like just `faker[method]` is getting what you need.
