### ISSUE TITLE
Editor Prompt causes next question to hang

### ISSUE THREAD

**Issue by shelbykauth** [SBoudrias/Inquirer.js#1070]
When I add an Editor question to a list of otherwise-working questions, it will cause the next question to malfunction, and it will make the process hang and not close.

This occurs when I add the following to a list of prompts:
```
    {
      when: (answers: Answers) => answers.login.whatToDo === OPTS.editRaw,
      name: "login.rawData",
      type: "editor",
      message: "Edit the logins list in raw json format.",
      postfix: "json",
      default: () => {
        if (logins.length) {
          return JSON.stringify(logins, null, 2);
        } else {
          const defaultLogins = [
            {
              url: "[redacted]",
              username: "MyUser",
              password: "someP@ssw0rd",
            },
          ];
          return JSON.stringify(defaultLogins, null, 2);
        }
      },
    },
 ```

Symptoms:
(note, all occur after closing the editor)
- When used as the last Promise in a program, I must hit "enter" again to close it out, even after the other code has run.
- When other code runs afterwards, the stuff it prints is visible before it hangs
- When another question is in the same `prompt(question[])` queue after this one, it fixes the problem.
- When another prompt queue is started, making sure that the async/awaits are used properly in that it doesn't start until after the editor closes and all questions are asked, I can move up and down and edit the response, but when I hit enter, it doesn't register the enter for _that_ question.  It drops to a new line and continues to ask that question.

**Comment by ovidiu141** [comment]
Could not reproduce. This really needs a **minimal reproducible example**
