### ISSUE TITLE
Inquirer Operate is not waiting for user prompt on looping

### ISSUE THREAD

**Issue by josecobo1** [SBoudrias/Inquirer.js#1072]
I have an array of changes to apply to the database and for every change I need user confirmation. Therefore I'm using inquirer js to ask the user if he wants to apply those changes.

I tried outside the loop and works but if I do it inside the loop it don't. It shows the question but the loop keeps going not letting the user to answer yes or no. 

This is my code:

```javascript
changes.map(change => {
                      inquirer.prompt([{
                        name: "operate",
                        type: "confirm",
                        message: `Updatade database with ${change.description}?`,
                    }, ])
                    .then((operate) => {
                        if (operate.replace) {
                            green(
                                `Database has been updated`
                            );
                        } else {
                            red(
                                `Database hs not been updated`
                            );
                        }
                    });}
```

**Comment by LitoMore** [comment]
Hey @josecobo1!

The `inquirer.prompt` is an asynchronous function. Please use [for await...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of) instead.

**Comment by SBoudrias** [comment]
Another option (less modern) is https://github.com/caolan/async

Good luck!
