### ISSUE TITLE
Feature request: Question comment

### ISSUE THREAD

**Issue by GHNewbiee** [SBoudrias/Inquirer.js#1074]
**The case**
a) After answering a question, some following questions may have not to be asked.
b) In that case, I need to display a message, right after the answer and before the next question is asked, informing the user about those questions that will not be asked, etc.

**The problem**
- For a), `when` is used to by-pass questions
- For b), if no other question object `function` property cannot be used (*) a `comment` property might be added

**Remark**(\*): I have tried to write in console through a `filter` or `transformer` function, but it failed.

**Example**
```js
import inquirer from "inquirer";

inquirer
  .prompt([
    {
      type: 'confirm',
      name: 'fruit',
      message: 'Is it a fruit?',
      default: true,
      comment: input => input ? 'Question "sweet" is omitted!' : '',
    },
    {
      type: 'confirm',
      name: 'sweet',
      message: 'Is it sweet?',
      default: true,
      when: answers => answers.fruit ? false : true,
    },
    {
      type: 'confirm',
      name: 'example',
      message: 'Is it a good example?',
      default: true,
    }
  ])
  .then(() => {
    ...
  })
```
```
? Is it a fruit? Yes
Question "sweet" is omitted!
? is it a good example? Y/n
...
```
*Tia*

**Comment by GHNewbiee** [comment]
Next workarounds would be used to by-pass this issue, although both are not so elegant.
- `prefix` of the **next** question (if exists), or
- within `then()` (when it's the last question)

A form of a question is like:

- `prefix` \<the space before question>
- `message` \<the question>
- `suffix` \<the space after question and before answer ie the space between question and answer>
- `answer`

It makes sense that one would assume that also \<the space after answer> should exist and is missing; that could be the `comment` or any other name.

- `comment` \<the space after answer>

If a new property does not break backward compatibility, then `comment` (string|function) would be added.

*Tia*

**Comment by GHNewbiee** [comment]
Other names could be: `epilogue`, `afterword`, `postscript`, `ps`, `coda`, `codicil`, `appendix`, `supplement`, `addendum`

**Comment by comatory** [comment]
I have the same need but I would actually like to display something before question is asked 😆 . It's too long to be part of "prefix".

It would be great to  have some kind of support for scenarios where you need to output something to output between questions.

**Comment by SBoudrias** [comment]
@comatory could you just `console.log` before calling `inquirer.prompt` (and maybe just split in 2 `prompt` calls)?

**Comment by SBoudrias** [comment]
Hi, I'll close this issue as the new package `@inquirer/prompts` is aiming at a simpler the API releasing more control to the end user.

As such, this request doesn't fit the current philosophy of the project core. But thanks for proposing the idea!
