### ISSUE TITLE
Horizontally display the list items

### ISSUE THREAD

**Issue by DhiaDjobbi** [SBoudrias/Inquirer.js#1078]
Hello,
Is it possible to display the type: 'list' items horizontally instead of showing them vertically ? 
Here is my code:
```
const { fieldRequired } = await inquirer.prompt([
  {
    type: "list",
    name: "fieldRequired",
    message: `Is the field required? ${white}:`,
    choices: ["Yes", "No"]
  }
]);
```

I want the output to be Like this:

> ? Is the field required? : (Use arrow keys)
> `>Yes  >No`
> 

Instead of the current one: 

> ? Is the field required? : (Use arrow keys)
> ```
> > Yes
>   No
> ```
>

**Comment by SBoudrias** [comment]
Hey, I would highly recommend implementing a [custom prompt](https://github.com/SBoudrias/Inquirer.js#plugins) for this.

I think the current prompts included in the core are enough for most use cases.
