### ISSUE TITLE
 Feature request: prefix / suffix function support 

### ISSUE THREAD

**Issue by GHNewbiee** [SBoudrias/Inquirer.js#1079]
**The case**
A wish to **conditionally** display the answer line separate of that of the question line.

**The problem**
Although <code>suffix: '\n'</code> can be used, sometimes it is not convenient when answer returns nothing.

**Potential solution**
A `prefix` / `suffix` function support will give more freedom to styling.

**Example**
```js
import inquirer from "inquirer";

inquirer
  .prompt([
    {
      type: 'checkbox',
      name: 'fruits',
      message: 'Select the fruits you like:',
      default: ['apple', 'apricot', 'banana', 'mandarin', 'orange'] ,
      choices: ['apple', 'apricot', 'banana', 'mandarin', 'orange'],
      prefix: '',
      suffix: answers => answers.fruits.length === 0 ? '' : '\n  ',
    },
  ])
  .then(() => {
    ...
  })
```

```
? Select the fruits you like:
  orange
? Next question
```

And, instead of

```
? Select the fruits you like:

? Next question
```

next is better:

```
? Select the fruits you like:
? Next question
```

*Tia*

**Comment by SBoudrias** [comment]
A bit of an old issue, so I'm not diving too deep. But there's now full customization of the prompt look and style through theming; see the new `@inquirer/prompts` package for this.
