### ISSUE TITLE
Enter empty value for input with default

### ISSUE THREAD

**Issue by bajtos** [SBoudrias/Inquirer.js#108]
Consider the following prompt:

``` js
    { name: 'proxy',
      message: 'HTTP proxy',
      default: 'http://proxy' }

// renders
// [?] HTTP Proxy: (http://proxy)
```

It is not possible to submit an empty value now (meaning "do not use any proxy"), because an empty response is always converted to the default value. See [lib/prompts/input.js#L70](https://github.com/SBoudrias/Inquirer.js/blob/e744e57b19b63f77807c21951afabc479b25b0dc/lib/prompts/input.js#L70).

A workaround is to add a special non-empty token (e.g. `none`) and modify the code handling the answers to replace this token with empty string.

IMHO it would be better to have a solution provided by inquirer, to get a consistent user experience across all CLI tools built on this module.

**Comment by magland** [comment]
For anyone coming across this, here's the solution I am using

```
{
  name: 'proxy',
  message: 'HTTP proxy (use . for no proxy)',
  default: defaultProxy || '.' 
}
```

Then check the answer and replace '.' with undefined or empty string.
