### ISSUE TITLE
Feature request: a function property for confirm type

### ISSUE THREAD

**Issue by GHNewbiee** [SBoudrias/Inquirer.js#1080]
**The case**
After answering a confirm type question, third values have to be conditionally calculated and get saved to a (generator's config) file. Some of these values, later on, will also be used as defaults to some other questions.

**The problem**
- Third value calculations and their storage cannot be done right after the answer of the questions but later on.
- Some third value calculations have to be done in the next questions in 'default' property which is not the ideal place and at the same time to get stored in the config file since they are ready.
- The remaining values have to be calculated and get stored in the promise part.
- So, there are two different places from which calculations and storage take place.

**Potential solution**
A new function property (eg `action`) could be added as a degree of freedom. User would decide in which part - question object or promise (`then()`) - additional tasks will be written. For example, tasks that require different answers are written in the promise part but tasks based only on a question input could be written in the `action` property.

Note: In other types where `filter` is available, local tasks "smartly & abusively" take place through its function which finally just returns the input unchanged; a solution not so elegant. So, imho, a separate function property for individual tasks based on single input would be a nice feature which does not break backward compatibility, too.

*Tia*

**Comment by GHNewbiee** [comment]
Consider also #1082.

**Comment by SBoudrias** [comment]
Hi, I'll close this issue as the new package `@inquirer/prompts` is aiming at a simpler the API releasing more control to the end user.

As such, this request doesn't fit the current philosophy of the project core. But thanks for proposing the idea!
