### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by GHNewbiee** [SBoudrias/Inquirer.js#1081]
I've found that `when` property is missing from `confirm` prompt type in documentation.

Please (author(s)) check for other essential missing and update.

*Tia*

**Comment by GHNewbiee** [comment]
In fact it is missing from all types.

**Global** properties: `type`, `name`, `message`, `default` (o), `when` (o), `prefix` (o), `suffix` (o) and `askAnswered` (o)

**Non-global** properties:

| type\property | choices | validate | filter | transformer | pageSize | loop | mask | postfix |
| --- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | 
| **input** | | o | o | o | | | | |
| **number** | | o | o | o | | | | |
| **confirm** | | | | | | | | |
| **list** | X | | o | | o | o | | |
| **rawlist** | X | | o | | o | o | | |
| **expand** | X | | | | o | | | |
| **checkbox** | X | o | o | | o | o | | |
| **password** | | o | o | | | | X | |
| **editor** | | o | o | | | | | o |

where (o) stands for **optional**.

Any remark?

*Tia*

**Comment by SBoudrias** [comment]
I'll close as we're not actively investing in this version of the package/api anymore. The documentation was fully rewritten since; see repository homepage https://github.com/SBoudrias/Inquirer.js
