### ISSUE TITLE
Feature request: Infrastructure for speech and sound support

### ISSUE THREAD

**Issue by GHNewbiee** [SBoudrias/Inquirer.js#1082]
Necessary infrastructure features for letting us add speech and sound effects at each part of a question (`prefix`, `suffix`, `comment` (#1074))

*Tia*

**Comment by GHNewbiee** [comment]
Examples:

- question and answer narrator,
- after answering a list question the national anthem should play before the next question is asked.

**Comment by SBoudrias** [comment]
If someone wants to contribute better speech support for CLI; I'll accept a PR. But I'll close this issue as not something planned in the project roadmap.
