### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by Kreijstal** [SBoudrias/Inquirer.js#1085]
Would it be possible if Iniquirer.js also supported Deno?

**Comment by SBoudrias** [comment]
I'm not quite sure what would be involved. But I think this could be complicated since Inquirer depends heavily on Node.js readline module.

**Comment by Kreijstal** [comment]
when importing the module let the user provide a Readline implementation
https://deno.land/x/readline@v1.0.0
if none provided, then feel free to require("readline")

**Comment by LitoMore** [comment]
Hi @Kreijstal, @guillaume86. Simply import `npm:@inquirer/prompts` to your Deno project.

See https://docs.deno.com/runtime/manual/node/npm_specifiers.

Closing.

**Comment by Kreijstal** [comment]
now do browser support, say xterm.js
