### ISSUE TITLE
multiple questions with same name, hydrating an array as answer

### ISSUE THREAD

**Issue by VaN-dev** [SBoudrias/Inquirer.js#1086]
Hello,
using inquirer to build an Object generator, I would like to ask for the object properties, asking alternatively for the property name then the property type. is there a way to ask the same question multiple times, and push every answer in an array, let say `properties` ?

tried 
```
questions.push({
    type: 'input',
    name: 'properties[]',
    message: 'New property name?',
});
questions.push({
    type: 'input',
    name: 'properties[]',
    message: 'New property name?',
});
```
but it clearly doesn't behave as I would expect.

**Comment by SBoudrias** [comment]
For this I'd recommend calling inquirer recursively or in a loop and for each prompt push the answer to an array.

Otherwise, asking for a `,` delimited list input is pretty common. Then you just `.split(/,\s*/)`

**Comment by VaN-dev** [comment]
thank you, but I don't understand how can I trigger custom code to handle the answer. Maybe I missed that part in the documentation, but I didn't find anything to trigger a callback after a question.

Since you're there, I will face another problem soon. As I don't know in advance the number of properties the user want to add to his Object being generated by the Inquirer, I should indeed use a recursive loop, but how what should I do to allow the user to end that loop when he has set all the properties he wants, and go to the next question ?

**Comment by SBoudrias** [comment]
:+1: I think that's great.
