### ISSUE TITLE
How to increase the number of list items of checkbox?

### ISSUE THREAD

**Issue by henryhu712** [SBoudrias/Inquirer.js#1088]
The maximum of items of checkbox are 7. How to change it?

**Comment by thanpolas** [comment]
@henryhu712 did you find a way to do this? I need this too

**Comment by henryhu712** [comment]
@thanpolas Yes. pageSize is the solution.

> pageSize: (Number) Change the number of lines that will be rendered when using list, rawList, expand or checkbox.
