### ISSUE TITLE
Double key entry

### ISSUE THREAD

**Issue by stephenplusplus** [SBoudrias/Inquirer.js#109]
I'm not sure if this is an issue here or with the generator, but the ghost issue we had before has reappeared. Here's a gif to help me explain:

![yo-uh-oh mov](https://cloud.githubusercontent.com/assets/723048/2821290/6312e35c-cf04-11e3-9699-c87c502df890.gif)

**Comment by 7nights** [comment]
@rodriguise 
The same problem. Have you found a solution?

**Comment by masondesu** [comment]
FWIW, I ran into the same issue when I when requiring (and using) Inquirer in two separate modules, both of which were being required by a third module.

I resolved the issue temporarily by reducing it to a single `var inquirer = require('inquirer');` for my entire app, and passing that var around when needed, which obviously isn't ideal. Hope that helps :dancer:

**Comment by knownasilya** [comment]
Might be unrelated, but I ran into this when I instantiated two instances of `readline`.

**Comment by SBoudrias** [comment]
@knownasilya Yes, that will effectively happen currently if two inquirer or readlines run at the same time.

**Comment by ruizb** [comment]
Got the same problem here with this piece of code:

```
var inquirer = require('inquirer');

var ui = new inquirer.ui.BottomBar();

var questions = [
  {
    name: 'firstname',
    message: 'First name?',
    validate: function (data) {
      // there are as many character duplicates as there are instanciations of BottomBar
      new inquirer.ui.BottomBar();
      new inquirer.ui.BottomBar();
      return true;
    }
  },
  {
    name: 'lastname',
    message: 'Last name?'
  }
];

inquirer.prompt(questions, function (answers) {
  console.log(answers);
});
```

It seems like the more there are instances of BottomBar, the more there are duplicates.

Tested on `OS X Yosemite v10.10.4`, `node v0.10.33` and `iTerm2 v2.1.1`.

![Screenshot](https://dl.dropboxusercontent.com/u/14445263/screenshot_inquirer_issue109.png)

**Comment by SBoudrias** [comment]
I cannot reproduce in the latest release. I did some cleanup to events listeners a while ago, so that might just've fixed the issue.

Either way, feel free to reopen if the issue still occurs for you.

**Comment by ccostel** [comment]
I am having the same issue.. 
Node v8.9.4
NPM 5.6.0
iTerm 
OSX 10.12.6 (16G29)

**Comment by Poyoman39** [comment]
Hey ! Same for me on windows10 with git bash (aka cygwin) and OSX terminal (using last LTS v8 nodejs and inquirer 5.2.0)

**Comment by devzsolt** [comment]
Broken for me now, inquirer 6.0.0, node v10.6.0
Btw. the old prompt package caused the same issue. Any idea guys?

**Comment by AlbertEmil** [comment]
Same problem here. Working with nodejs v10.14.2 and inquirer 6.2.1 on Windows 7 Pro, x64.

**Comment by Poyoman39** [comment]
I did a work around for this bug, if you can't wait for a bug fix. Just decorate the original prompt function like this =>

```
  const inquirer = require('inquirer');

  const decoratedPrompt = async (...args) => {
    const r = await inquirer.prompt.call(inquirer, ...args);
    await pause(200);
    return r;
  }

 module.exports = {
  prompt: decoratedPrompt,
 }
```

**Comment by kristianoye** [comment]
I think the multiple character echo stems from multiple calls to readline.createInterface.  If you have more than one module that does this, then you end up with the duplicate.  Look for and eliminate any redundant calls to fix your problem.
