### ISSUE TITLE
Refactor to TypeScript

### ISSUE THREAD

**Issue by Exortions** [SBoudrias/Inquirer.js#1101]
Refactoring the codebase to TypeScript in my opinion would have a few advantages:

  1. Much easier to understand how things work for new/aspiring contributors
  2. Because TypeScript compiles to minified JavaScript, the bundle size for users would be smaller, and run times would be faster.
  3. Overall, it's just a good idea as Types add a lot of functionality to JavaScript.

Of course, I understand if TypeScript isn't your thing, but if it is, I'd be happy to make a PR for at least some (if not most) of the packages.

**Comment by SBoudrias** [comment]
I'm happy to review PRs starting on the new packages. I wanted to add TS, just doesn't have the time.

**Comment by denik1981** [comment]
With a progressive strategy and a nice roadmap, this could be done.

**Comment by SBoudrias** [comment]
The first stab is launched over https://github.com/SBoudrias/Inquirer.js/pull/1112 - there's a fair amount of work, but I explained which files to focus on there. We can do them one by one!

**Comment by Exortions** [comment]
Yep, you should create a new branch for TypeScript.

**Comment by Exortions** [comment]
Nevermind, looks like you already did 😅

**Comment by Exortions** [comment]
@SBoudrias I'll be working on packages/core/src/lib/screen-manager.js.

**Comment by TDP17** [comment]
@SBoudrias I'd like to help migrate the other packages. Can I work on @inquirer/password and @inquirer/select and others if they are free as well?

I'll take @inquirer/checkbox as a reference

**Comment by SBoudrias** [comment]
@TDP17 that'd be great! I'll leave you those for a week, feel free to send an incomplete PR if you get stuck somewhere; that way I'll know the progress and can help take the branch over if I want to wrap this up sooner 😄

**Comment by mokkabonna** [comment]
If I want to convert my plugin to typescript https://github.com/mokkabonna/inquirer-autocomplete-prompt is the approach here the way to go? Import from @inquirer/core and use the createprompt?

```ts
type SelectConfig = AsyncPromptConfig & {
  choices: { value: string; name?: string; description?: string; disabled?: boolean }[];
  pageSize?: number;
};

export default createPrompt<string, SelectConfig>((config, done) => {
```

**Comment by SBoudrias** [comment]
Hey @mokkabonna, yes that'd be the ideal. One thing to note is that afterward your custom prompt will be usable standalone (which I think overall is better.)

But it won't be register-able through `inquirer.registerPrompt` since I didn't wrap up writing the new core inquirer module yet. If you're curious, the WIP is in https://github.com/SBoudrias/Inquirer.js/pull/1173, but there's still missing a lot (and I'm considering the need to add a backward compatibility layer since otherwise all custom prompt would stop working with an eventual new major release.)

**Comment by mokkabonna** [comment]
Ok nice to know. I try to stay as aligned with what you are doing here as I can so I will then probably go down this route as well.
