### ISSUE TITLE
can list input show larger set or options?

### ISSUE THREAD

**Issue by thanpolas** [SBoudrias/Inquirer.js#1102]
Currently a "list" input with multiple choices, will display 7 rows or records for selection.

Is there a way to display more if not full-height of terminal? And if not, is it planned to happen?

Thank you for the awesome tool :pray:

**Comment by SBoudrias** [comment]
Try the `pageSize` option. If it's missing from the README, a PR adding documentation for the option would be awesome.

Ideally we'd want to use the terminal size, but there's some complexity around this (like it need to handle resizes gracefully) - so no one spent time diving into a solution for this yet.

**Comment by thanpolas** [comment]
yes, that works, I saw the option on the README too, thank you
