### ISSUE TITLE
when the length of list is over default pageSize ,arrow up and down key  actions incorrect

### ISSUE THREAD

**Issue by daring123** [SBoudrias/Inquirer.js#1107]
os: macos Catalina
version: 8.2.3

code :

```
import inquirer from 'inquirer';

const choices = Array.apply(0, new Array(26)).map((_: any, y: any) => String.fromCharCode(y + 65));
inquirer
  .prompt([
    {
      type: 'list',
      loop: false,
      name: 'letter',
      message: "What's your favorite letter?",
      choices,
    },
    {
      type: 'checkbox',
      name: 'name',
      message: 'Select the letter contained in your name:',
      choices,
    },
  ])
  .then((answers: any) => {
    console.log(JSON.stringify(answers, null, '  '));
  });
``` 

when I press the "down key" , it will page down ，not point  the next one  selection

<img width="447" alt="image" src="https://user-images.githubusercontent.com/5986074/165527539-6504c453-2f69-40b2-bfc2-a4ff138aaf21.png">

<img width="622" alt="image" src="https://user-images.githubusercontent.com/5986074/165666504-a8e67e1c-a579-4b6e-8e05-a12520c18805.png">

**Comment by lukahartwig** [comment]
I can confirm the bug. Seems to be a regression in 8.2.3. Downgrading to 8.2.2 works for me.

**Comment by truesteps** [comment]
Can confirm, this is happening since 8.2.3. Downgrade to 8.2.2 fixes it for me

**Comment by SBoudrias** [comment]
Hey @starpit, I was wondering if there was any chance you could look into this? It seems to occur starting with the ansi-wrap change 😓

**Comment by starpit** [comment]
The bug seems to be that breakLines is expected, by the paginator, to return a doubly-nested array, where the inner array are the lines into which a line might be broken.

The main screen manager does not rely on this aspect.

I'll send a PR.

**Comment by starpit** [comment]
@SBoudrias PR in flight: https://github.com/SBoudrias/Inquirer.js/pull/1108

**Comment by SBoudrias** [comment]
`8.2.4` is out with the fix! Send thanks towards @starpit 😉

**Comment by truesteps** [comment]
Fixed the issue for me! Thanks for the quick fix <3
