### ISSUE TITLE
Select value - issue in terminal

### ISSUE THREAD

**Issue by ivodolenc** [SBoudrias/Inquirer.js#1114]
Hi, nice work on `inquirer`!

When I select value everything works great (example bellow), but when I `exit/interrupt` process, for example `control + c`, then cursor and last value (Major) disappears from vscode terminal.

```js
const select = require('@inquirer/select')

const selectVersion = async () => {
  const answer = await select({
    message: 'Select new version:',
    choices: [
      { name: 'Patch', value: 'patch' },
      { name: 'Minor', value: 'minor' },
      { name: 'Major', value: 'major' }
    ]
  })

  console.log(`New version: ${answer}`) // Works normal after selecting
}
```

However, this example works normal on `selecting` and `exit`:

```js
const inquirer = require('inquirer')

inquirer
  .prompt([
    {
      type: 'list',
      name: 'version',
      message: 'Select new version:',
      choices: [
        { name: 'Patch', value: 'patch' },
        { name: 'Minor', value: 'minor' },
        { name: 'Major', value: 'major' }
      ]
    }
  ])
  .then(answers => {
    console.log(`New version: ${answers.version}`)
  })
```

Do you have any idea what it might be the issue?

**Comment by SBoudrias** [comment]
Hey, thanks for the heads up. It's possible in the new core we do not print an empty line or reset the cursor position on exit.

The issue would live inside https://github.com/SBoudrias/Inquirer.js/tree/master/packages/core - you can compare to the previous implementation looking for exit listeners and what they do.

**Comment by ivodolenc** [comment]
Ok thanks for the feedback! It’s not urgent so I’m using a working (second) example at the moment!

**Comment by ivodolenc** [comment]
Hi, I just tested this and it seems the problem is still the same, after pressing `control` + `c` (on mac) to exit, the cursor disappears in the terminal.

### Versions

- macos: ventura latest
- node: `18.17.1`
- npm: `9.8.1`
- @inquirer/select: `1.2.9`

### Reproduction

1. Install `@inquirer/select`
2. Add the code from the official [Usage](https://github.com/SBoudrias/Inquirer.js/tree/master/packages/select#usage) example
3. Run it!

The code works fine, but if I manually cancel/quit process, the cursor disappears so I can't see it anymore and need to restart the terminal.

**Comment by SBoudrias** [comment]
This should now work properly.

Not sure how it happens, but signals became `0` without names (just `null`.) And so the force exit handler wasn't running anymore. It could be a side-effect of the Node async hooks; but really weird. Anyway, now detection should be more reliable for the future.
