### ISSUE TITLE
Keyboard Inputs not working

### ISSUE THREAD

**Issue by sahibs99** [SBoudrias/Inquirer.js#1115]
Hi there,

When using Inquirer in our project, for whatever reason, the keyboard inputs do not work. It instead prints out what keys are being clicked as such:
![Screen Shot 2022-05-18 at 4 19 53 PM](https://user-images.githubusercontent.com/87778140/169170820-e32c5840-7ef0-40a5-884c-36bda4b1f98a.png)

We are using esbuild to create a script that uses Inquirer and we have tried to use the branch that uses esm as well but we cannot pinpoint why this is happening. Any guidance is would be greatly appreciated. Thanks!

**Comment by SBoudrias** [comment]
This is unlikely to be related to ESM or commonjs module type.

Any chance there is multiple opened readline at the same time? Or maybe multiple processes acting on the stdout/in? At first look, this seems like conflicting processes rather than an issue internal to Inquirer.

**Comment by wlkns** [comment]
I also have this issue, I have a feeling it may be caused by zsh or zshautocomplete.

**Comment by wlkns** [comment]
Infact - update on this, problem was caused by nodemon, ran normally and it was fine.
