### ISSUE TITLE
Resolution of default values when a condition evaluates to false

### ISSUE THREAD

**Issue by hiukky** [SBoudrias/Inquirer.js#1116]
Congratulations on this excellent project!

Regarding the conditions for the prompts, shouldn't the defined default value be resolved with when assuming false?

As you can see in the example, I only want the user to answer this question when my options to display are more than one, otherwise assume the value of the first index and return it to me after the questionnaire.

I saw the documentation for these two properties, correct me if I'm using this wrong lol.

![image](https://user-images.githubusercontent.com/26740246/169666974-e8818ed5-afbb-49b8-afe6-01bd916c35fa.png)

**Comment by trueicecold** [comment]
Just encountered it as well, and since it seems that when "when" is a function getting (answers) as a parameter, it's impossible to add a new property to it (probably a clone of the actual answers object)

**Comment by trueicecold** [comment]
ok, it was a logic bug and it IS possible. in your case for the first question:

`
when: (answers) => {
    if (metadata.targets.length == 1) {
        answers.target = metadata.targets[0];
    }
    return metadata.targets.length > 1;
}
`

**Comment by SBoudrias** [comment]
Thanks for helping out @trueicecold!

I'm not intending to change this behaviour; in part because it's not what everyone would want, and second it'd be a major breaking change for current users.

I would however recommend upgrading to the new inquirer version (`@inquirer/prompts`) #1214. Controlling this behaviour becomes much more explicit:

```js
import { select } from '@inquirer/prompts';

let target = metadata.targets[0];
if (metadata.targets.length > 1) {
    target = await select({
        message: 'type:',
        choices: metadata.targets,
    });
}
```
