### ISSUE TITLE
Prompt is re-stated after user enters any type of input

### ISSUE THREAD

**Issue by jpalmer108** [SBoudrias/Inquirer.js#1118]
Downloaded inquirer to test it out, and when testing with some of this repo's documented examples I noticed that the prompts are repeating themselves once the user starts typing in information.

<img width="786" alt="Screen Shot 2022-05-28 at 5 22 38 PM" src="https://user-images.githubusercontent.com/102994201/170846862-6a4c53d8-d03f-457c-a654-92ef2bbb0cb1.png">
 
In this image, I copied the `rawlist` example from the `examples` folder and ran the project. 

When first running the project, the prompt appears, however when I press any type of key to provide input the prompt doubles up. This happens with at least 3 different examples from the repo. Not sure what to make of it, since I can't find any documented bugs or errors that I'm doing wrong.

**Comment by SBoudrias** [comment]
Hi, let's try to see what happens!

1. First, could you confirm you're using the latest version? Or which version you're using?
2. And could you try this in another terminal and see if the same behaviour occurs? (like terminal or iterm2 on Mac, or cmd.exe on Windows)
