### ISSUE TITLE
Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by Hawley-hy** [SBoudrias/Inquirer.js#1129]
Error detail as bellow:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/inquirer/lib/inquirer.js from csv-to-insert/index.ts not supported.
Instead change the require of inquirer.js in csv-to-insert/index.ts to a dynamic import() which is available in all CommonJS modules.
}
```
code
```
const inquirer = require("inquirer");
inquirer
  .prompt([]).then()
```

Env:
Node version v16.11.1

tsconfig:
```
{
    "compilerOptions": {
        "target": "ES2017",
        "module": "commonjs",
        "allowSyntheticDefaultImports": true,
        "allowUnreachableCode": true,
        "allowUnusedLabels": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "forceConsistentCasingInFileNames": true,
        "noFallthroughCasesInSwitch": true,
        "noUnusedLocals": false,
        "moduleResolution": "node",
        "outDir": "dist",
        "removeComments": true,
        "strict": true,
        "strictFunctionTypes": false,
        "suppressImplicitAnyIndexErrors": true,
        "sourceMap": true,
        "strictPropertyInitialization": false,
        "baseUrl": ".",
        "paths": {
        },
        "plugins": [
            {
                "name": "tslint-language-service"
            }
        ]
    },
    "exclude": [
        "node_modules"
    ]
}
```
script in package.json
```
ts-node --project tsconfig.json index.ts
```

**Comment by AlejandroSotoCastro** [comment]
Same problem

**Comment by softmarshmallow** [comment]
This basically means we can't use Inquirer with ts-node while development.

**Comment by SBoudrias** [comment]
@softmarshmallow that isn't true. I've been using ts-node while developing inquirer itself. You need to add this to your `ts-config.json` file: https://github.com/SBoudrias/Inquirer.js/blob/master/tsconfig.json#L4-L6

**Comment by bali182** [comment]
@SBoudrias what is the recommended way to use Inquirer for commonjs project? Just use v8?

**Comment by SBoudrias** [comment]
@bali182 yeah, that's your best bet for now!

**Comment by gabrielgrover** [comment]
I still get  `Error [ERR_REQUIRE_ESM]: require() of ES Module` when trying to run with ts-node.  Even with the `tsconfig.json` property @SBoudrias mentioned

**Comment by kolarski** [comment]
@SBoudrias Unless you use Typescript Paths (https://www.typescriptlang.org/tsconfig#paths) like import from @core/myModule
then ts-node not work and it will not resolve the paths in esm mode. Basicly will not be able to import anything.
There is a 1-year-old issue that is still not resolved in the ts-node repo: https://github.com/TypeStrong/ts-node/pull/1585

So stuck working with the outdated version.

**Comment by CryptoNawwa** [comment]
What is the workaround @kolarski ? What do you mean outdated version ?

**Comment by FernandoValentim43** [comment]
> 4\. `ts-node `

The second option partially works for me. While the import of inquirer.js now works, literally all of the other regular imports in the rest of the code have stopped working.

**Comment by thebug404** [comment]
> > Second solution
> 
> The second option partially works for me. While the import of inquirer.js now works, literally all of the other regular imports in the rest of the code have stopped working.

You are absolutely right, due to the change that was added with the second option, it is necessary that you add the `.js` extension to your files when importing them.

For example:

```ts
// Bad
import { random } from './utils'

// Good
import { random } from './utils.js'
```

I hope this works for you.

**Comment by wizardpisces** [comment]
fallback to version 8 fix the problem

**Comment by woshiqiji** [comment]
> fallback to version 8 fix the problem
 `npm install inquirer@^8.0.0 -S`     Yes, dropping to version 8 would fix that

**Comment by bitcoinbrisbane** [comment]
> > fallback to version 8 fix the problem
> > `npm install inquirer@^8.0.0 -S`     Yes, dropping to version 8 would fix that

Confirmed. Fixed my issue too.
