### ISSUE TITLE
Conditional Choice show

### ISSUE THREAD

**Issue by JSDUNIYA** [SBoudrias/Inquirer.js#1132]
choices: [
      { name: 'Patch', value: 'patch' },
      { name: 'Minor', value: 'minor' },
      { name: 'Major', value: 'major' }
    ]
    
    In the above list of choices, I would like to show only name 'Major' to user based on previous answer. 
    is this possible to achieve ?

**Comment by SBoudrias** [comment]
@JSDUNIYA yes, for this, call `inquirer.prompt` 2 times conditionally

```js
const answers = await inquirer.prompt(...);

if (answers.example === 'yes') {
    const otherAnswers = await inquirer.prompt(...);
}
```

**Comment by SBoudrias** [comment]
I'm not too familiar with your codebase, so I cannot really answer this question. If that function doesn't have side-effect then it should be safe 🤔
