### ISSUE TITLE
How to hide the help tip in checkbox

### ISSUE THREAD

**Issue by zonemeen** [SBoudrias/Inquirer.js#1138]
Hi! 👋
Firstly, thanks for your work on this project! 🙂
Can you tell me the config to hide the help tip in checkbox, thank you~

```javascript
import inquirer from 'inquirer'
import names from './names'
import { SongInfo } from './types'

const choose = ({ searchSongs, options, serviceName }: SongInfo) =>
  inquirer.prompt([
    {
      type: 'checkbox',
      name: 'songs',
      message: '选择歌曲',
      pageSize: 20,
      dontShowHints: false,
      choices: searchSongs.map((song, index) => names(song, index, options, serviceName)),
    },
  ])

export default choose
```

![1657615293335](https://user-images.githubusercontent.com/44596995/178448620-06c2d672-829f-4016-a6a6-4ab68af0065b.jpg)

inquirer: "^8.2.4"

**Comment by SBoudrias** [comment]
There's no such option as of today. May I ask what's your use-case hiding the hints?

**Comment by zonemeen** [comment]
I expressed it wrong, I would like to ask is it possible to add a setting option to hide or show the help tip? Because I want to use an all Chinese help tip through setting message option in a project of mine.

**Comment by SBoudrias** [comment]
Ah! This isn't possible now. But I think if you're willing to send a PR, you could add an option to the prompt to override the tip message.

This might be easier to do with the new version https://github.com/SBoudrias/Inquirer.js/tree/master/packages/checkbox

**Comment by zonemeen** [comment]
Ok, thanks for your reply😊
