### ISSUE TITLE
editor property "postfix" does not seem to do anything

### ISSUE THREAD

**Issue by hasezoey** [SBoudrias/Inquirer.js#1144]
Currently for question type `editor` the property `postfix` does nothing (not even the default `.txt` is applied), this is probably a error in `external-editor`, but i also open it here because it also affects this library.

repro code:
```ts
import * as inquirer from "inquirer";
await inquirer.prompt([{ type: "editor", default: "testmsg", name: "someprop", postfix: ".md" }])
// the resulting file does not have any extension
// resulting file path is something like "/tmp/tmp-144678H0IG3Le6CyFH"
```

NodeJS 18.6.0
inquirer 9.0.1
Linux Manjaro 21.3.4

**Comment by gabrielgrover** [comment]
I am also seeing this issue

**Comment by NateAyye** [comment]
You Can just go into the folder within your node_modules and mess with the code a bit to get it working.

Here is the location of the file that you are going to want to change.

![image](https://github.com/SBoudrias/Inquirer.js/assets/111668194/3b5db74c-fc4c-4d6c-ab08-e064fec36de3)

Then you are only going to want to change 1 line. The editAsync function is already their but it is only taking in 2 params. You just need to add the last param. The file options. 
To keep it in line with what the documentation says I just added a postfix that looks at the this.opts.postfix value that is set from the options given to the prompts when making a 'editor' prompt if that is not available than it just defaults to .txt

![image](https://github.com/SBoudrias/Inquirer.js/assets/111668194/ecaddaae-dca1-4a0d-b5e6-923056f3b416)

**Comment by SBoudrias** [comment]
Thanks for pointing it out @NateAyye! I made the fix, next release will fixed it.

**Comment by NateAyye** [comment]
> Thanks for pointing it out @NateAyye! I made the fix, next release will fixed it.

Thank you 🙏. I was just trying to fork it and open a pull request but the external-editor package problem caught me up.
