### ISSUE TITLE
response parameter on a question hash

### ISSUE THREAD

**Issue by fMagVen** [SBoudrias/Inquirer.js#1145]
I'm trying to receive an array as response and it seems the currently accepted subtypes as input type are only string and numbers. I saw this somewhat old question from stackoverflow: https://stackoverflow.com/questions/39621088/node-js-inquirer-is-there-a-way-to-prompt-for-an-user-defined-size-array and it seems it was a feature that I could set my response type. I tried to use this syntax but the input still receives either string or text. Has this feature been removed? Is there a replacement workaround?

**Comment by SBoudrias** [comment]
Hi @fMagVen, this has never been a feature; I'm quite confused about that answer on StackOverflow (but then no votes/no approved answer.)

The way to do that would be to use the `filter` option to post-process the answer.

**Comment by fMagVen** [comment]
Yes, thanks!
