### ISSUE TITLE
[Feature request] launch editor prompt without waiting for <enter>

### ISSUE THREAD

**Issue by dellamina** [SBoudrias/Inquirer.js#1149]
I'm currently developing an application where I ask the user for a filename (text) and then for the content (editor) but as far as I know there is no way to remove the prompt for the user to press <enter> before launching the editor.
I understand why it works that way but there are cases like in git commit where it makes more sense to just launch the editor without waiting for user input.

**Comment by SBoudrias** [comment]
I'm happy to review a PR adding an option to skip waiting for the enter key.
