### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by developer-freed** [SBoudrias/Inquirer.js#1153]
When I executed it in the Node environment, it reported navigator is not defined, and then I found this line of code in the packaged code, which may be the exception caused by it`const isBlinkBasedBrowser = /\b(Chrome|Chromium)\//.test(navigator.userAgent)`

**Comment by fabien** [comment]
Hey, I just found the same issue - since you closed the issue, did you find a solution?

**Comment by developer-freed** [comment]
> Hey, I just found the same issue - since you closed the issue, did you find a solution?

Yes, I solved this problem, i am using rollup, the reason is that the correct import method was not configured when rollup was packaged, so that it introduced the default package
```import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';

export default {
  input: {
    index: './src/index.ts',
  },
  output: {
    dir: './bin',
    preserveModules: true,
    preserveModulesRoot: './src',
    entryFileNames: '[name].js',
    generatedCode: 'es2015'
  },
  plugins: [
    nodeResolve({
      exportConditions: ['node'], // add node option here,
      preferBuiltins: false,
    }),
    commonjs({ include: '/node_modules/**', }),
    json(),
    typescript({ exclude: 'node_modules' }),
  ],
  watch: {
    include: './src/**'
  }
}```

**Comment by fabien** [comment]
@developer-freed thank you so much! That worked!

**Comment by Aiden-FE** [comment]
@developer-freed Thank you for shared.

**Comment by SixDjango** [comment]
thinks bro ~, that worked

**Comment by justorez** [comment]
@developer-freed I got a new error......I wanna cry（┬＿┬）
```sh
[!] (plugin commonjs--resolver) TypeError: The "path" argument must be of type string or an instance of URL. Received null
```
