### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]

### ISSUE THREAD

**Issue by emmtte** [SBoudrias/Inquirer.js#1174]
Hi,

Following this:

https://github.com/SBoudrias/Inquirer.js/tree/master/packages/password

Have an error:

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/admin/test/node_modules/@inquirer/input/src' imported from /home/admin/test/node_modules/@inquirer/password/dist/index.js

**Comment by SBoudrias** [comment]
Hey @emmtte thanks for reporting this issue. I think lerna state somehow got messed up. Can you try with the [latest version](https://www.npmjs.com/package/@inquirer/password)? `npm install @inquirer/password@0.0.27-alpha.0`

**Comment by emmtte** [comment]
Thanks, it's working with alpha version.
Thank's too for this amazing package
