### ISSUE TITLE
@inquirer/select set default value

### ISSUE THREAD

**Issue by inselberg** [SBoudrias/Inquirer.js#1176]
How can i set a default value with a select "element"?

**Comment by SBoudrias** [comment]
A `select` enforces the selection under the pointer. So pressing enter will select whichever is the element under the cursor (by default that would be the first one.)

So you could reorder your options putting the default one first.

Does that answer your question?

**Comment by inselberg** [comment]
sadly that was my solution but too. i hoped there was way to select (via code) an element greater than one.
