### ISSUE TITLE
Remove remaning lodash

### ISSUE THREAD

**Issue by jimmywarting** [SBoudrias/Inquirer.js#1178]
there is just but a few handful lodash util function being used. 
it ain't wort keeping lodash around for just those few things.

**Comment by SBoudrias** [comment]
I'll be happy to review a PR about this.

**Comment by SBoudrias** [comment]
The new API doesn't import lodash and is much smaller. I'll mark this one as closed/completed.

https://github.com/SBoudrias/Inquirer.js/discussions/1214
