### ISSUE TITLE
How to not automatically escape in 'input' type

### ISSUE THREAD

**Issue by albertopasqualetto** [SBoudrias/Inquirer.js#1182]
I have seen that if I input `\n`, then it is automatically escaped with `\\n`, is it possible to disable this behavior and get `\n`?

**Comment by SBoudrias** [comment]
Interesting, I don't think this is made on purpose... I wonder if maybe the readline module automatically does escapes?

Feel free to dig a bit in the codebase to research that. I'd be happy to give a few pointers.

**Comment by albertopasqualetto** [comment]
Yes, `rl.line` is the responsible, I have opened an[ issue on node's repo](https://github.com/nodejs/node/issues/45950) in order to investigate.

I think that it could be a wanted behavior, but this way I do not know how to get resolve, probably I should manage and remove by myself that escape or use the 'editor' type (if it registers new lines).

**Comment by V7lanw** [comment]
https://github.com/nodejs/node/issues/45950#issuecomment-1451185706

As for me, editor partly solved my case. How to set the default editor it opened? I've installed vim on Win 10 on a different place.
