### ISSUE TITLE
Prompt displays twice: before input, after input

### ISSUE THREAD

**Issue by Junsang-Mun** [SBoudrias/Inquirer.js#1184]
Sorry for terrible title, but I was not able to explain more. 

Here's a figure for problem:
![image](https://user-images.githubusercontent.com/99532497/210722306-62fccd37-9218-44a9-bd77-d9fb3770fa46.png)
As far I know, the prompt should be re-rendered like this:
![image](https://user-images.githubusercontent.com/99532497/210722877-e5978e01-3030-45da-9dab-3c0eca77bc9d.png)

This is my app.js:
```Javascript
const questions = [
  {
    name: "input",
    type: "input",
    message: "Type your answer here",
  },
  {
    type: "checkbox",
    message: "Select toppings",
    name: "toppings",
    choices: [
      new inquirer.Separator(" = The Meats = "),
      {
        name: "Pepperoni",
      },
      {
        name: "Ham",
      },
      {
        name: "Ground Meat",
      },
      {
        name: "Bacon",
      },
    ],
  },
];

inquirer.prompt(questions).then((answers) => {
  console.log(answers);
});
```

Nothing special, just a basic code. I tried to search bunch of issues and external resources via Google but I had no luck with this.
Is this issue only I got? Or are there any possible ways to address this issue?

Anyway, thank you in advance and for your interest.

#### Debugging informations:
node: v18.12.1
inquirer.js: v9.1.4
zsh: 5.8.1 (x86_64-apple-darwin21.0)
MacBook Air (M1, 2020)
macOS 12.6.2 (21G320)

**Comment by Junsang-Mun** [comment]
Um... Actually I was importing async functions(but not used) from outside of `app.js`, like this:

```Javascript
import { parseTester, createMainFile } from "./file.js";
import { runCommand, CLI } from "./cli.js";
```
After removing these two lines froms from app.js, inquirer worked properly.
I didn't expect that these two lines caused problems because I was not using these functions.

This is full app.js from my project:
```Javascript
#!/usr/bin/env node

import inquirer from "inquirer";
import { parseTester, createMainFile } from "./file.js"; // Removing these two lines
import { runCommand, CLI } from "./cli.js";              // fixed problems

const questions = [
  {
    name: "input",
    type: "input",
    message: "Type your answer here",
  },
  {
    type: "checkbox",
    message: "Select toppings",
    name: "toppings",
    choices: [
      new inquirer.Separator(" = The Meats = "),
      {
        name: "Pepperoni",
      },
      {
        name: "Ham",
      },
      {
        name: "Ground Meat",
      },
      {
        name: "Bacon",
      },
    ],
  },
];

inquirer.prompt(questions).then((answers) => {
  console.log(answers);
});
```

I used `child_process`, `readline`, js-yaml` and `fs` from cli.js and file.js.
Can it be a problem just by importing unused async functions?

**Comment by SBoudrias** [comment]
It's most likely that those files or their own dependencies at import time are setting up a readline.

**Comment by Junsang-Mun** [comment]
After removing readline, everything worked properly, thank you!
I'll close this issue as completed.

**Comment by SBoudrias** [comment]
Ah yeah 😅 Good to hear it was just that. That's a limitation with Node.js readline which is kind of an implicit singleton (and doesn't throw if used multiple times)

**Comment by Junsang-Mun** [comment]
Ah, I didn't know that readline follows singleton pattern - now I clearly understand what happened in my code 😓
Sorry for bothering you and thanks again.
