### ISSUE TITLE
How to test the prompt in CircleCI?

### ISSUE THREAD

**Issue by pdimova** [SBoudrias/Inquirer.js#1189]
We have a CLI tool that asks a couple of questions in the console. 

Is there a way to answer all the questions directly in the pipeline?

**Comment by SBoudrias** [comment]
Hi, there is no convenient way to really do this.

The easiest option is to mock inquirer.

If you want to look further, you can pass custom stdin/stdout and listen/answer to events there. But this is complicated (it's how a CLI work.) I built testing utilities to test single prompts, you might be able to reuse the ideas or expand it to support multi-prompts (in which case a PR would be amazing). You can see usage example with `git grep "@inquirer/testing"` in the repo; the lib is undocumented as of now and part of the [rewrite effort](https://github.com/SBoudrias/Inquirer.js/issues/692).

**Comment by SBoudrias** [comment]
The new release of inquirer now includes a testing library. More here https://github.com/SBoudrias/Inquirer.js/discussions/1214
