### ISSUE TITLE
How are complex questions composed with rxjs?

### ISSUE THREAD

**Issue by anselmo-coolstay** [SBoudrias/Inquirer.js#1191]
I would like to compose the questions that use their answers with rxjs style.
For example, can I compose the questions such as the below flow chart?

![Complex Questions](https://user-images.githubusercontent.com/96411375/219268852-53a50959-165a-48dd-a14d-b98b551bdc64.png)

**Comment by SBoudrias** [comment]
I think I would approach this more with a state machine pattern (rather than rx.js)

FWIW, I'm planning to deprecate the rx.js interface in a future major release. This library is really big and a bit slow.

**Comment by anselmo-coolstay** [comment]
Thank you very much for your advice.
