### ISSUE TITLE
Is there any else method to control the list typed promps?

### ISSUE THREAD

**Issue by BHznJNs** [SBoudrias/Inquirer.js#1192]
In some laptop, it's not so convenient to press the up & down key. Is there any method to control the list typed promps without pressing the up & down key?
Or could I bind the event to other key?

**Comment by SBoudrias** [comment]
Hey, built-in we also have vim and emacs bindings for up/down.

But there's no option exposed to customize the keys at the moment.

**Comment by BHznJNs** [comment]
> Hey, built-in we also have vim and emacs bindings for up/down.
> 
> But there's no option exposed to customize the keys at the moment.

Ok, I know it. Thank you for your reply.
