### ISSUE TITLE
npm installs a version of inquirer that does not exist 9.5.1

### ISSUE THREAD

**Issue by jfadev** [SBoudrias/Inquirer.js#1195]
In Termux, there is a problem with Alpine. When we do the following command 
npm -v inquirer 
returns 9.5.1 
when the most recent version is 9.1.4 🤷‍♂️

![IMG_20230305_214055_596](https://user-images.githubusercontent.com/46567106/222995972-c0851353-21f4-4be2-a8a9-dca00df4eed2.jpg)

**Comment by SBoudrias** [comment]
Any chance the version is entered manually in the `package.json` file as 9.5.1?

**Comment by jfadev** [comment]
The solution was to use Yarn instead of npm inside Termux with Alpine.
