### ISSUE TITLE
Feature Suggestion: allow "other" option in list input

### ISSUE THREAD

**Issue by queengooborg** [SBoudrias/Inquirer.js#1198]
_This was copied from a similar request for `python-inquirer` -- see https://github.com/magmax/python-inquirer/issues/370_

As a part of one of my questions within a script I use, I inquire a `reason` from the user, which is a list of preset entries, as well as an "Other" entry.  In this script, I then check to see if "Other" was selected, and if so, prompt the user for a text input to describe the `reason`.  This looks something like so:

```js
let reason;
const answers = await inquirer.prompt([{
  name: 'reason',
  type: 'list',
  message: "Why is this feature being removed?",
  choices: ['Irrelevant', 'Non-Interface', 'Other']
}]);
reason = answers.reason;

if (reason == "Other") {
  const answers2 = await inquirer.prompt([{
    type: 'input',
    message: "Why is this feature being removed?"
  }]);
  reason = answers2.reason;
}
```

```
? Why is this feature being removed?: Other
   Irrelevant
   Non-Interface
 > Other

? Why is this feature being removed?: I just don't like this feature... >:(
```

I think it would be nice to have an `other` option (or something similar), that adds an option to the end which doubles as a text input, like so:

```js
const {reason} = await inquirer.prompt([{
  name: 'reason',
  type: 'list',
  message: "Why is this feature being removed?",
  choices: ['Irrelevant', 'Non-Interface'],
  other: 'Other Reason' // default: false, setting to "true" will add "Other"
}]);

// ...or...

const {reason} = await inquirer.prompt([{
  name: 'reason',
  type: 'list',
  message: "Why is this feature being removed?",
  choices: ['Irrelevant', 'Non-Interface', inquirer.ListChoiceOther('Other Reason')],
}]);
```

```
? Why is this feature being removed?: Irrelevant
 > Irrelevant
   Non-Interface
   Other

...or...

? Why is this feature being removed?: 
   Irrelevant
   Non-Interface
 > Other: 

...or...

? Why is this feature being removed?: I just don't like this feature... >:(
   Irrelevant
   Non-Interface
 > Other: I just don't like this feature... >:(
```

**Comment by SBoudrias** [comment]
Hi, due to this behaviour being highly custom to different use cases, I'll close this issue as not something we'll fix in the core.

You're however free to:

1. [Implement as a custom prompt](https://github.com/SBoudrias/Inquirer.js#create-your-own-prompts)
2. Follow up with a check if the answer was `Other`, and if so, use an input prompt with your custom validation.
