### ISSUE TITLE
Listen to custom key events on list item

### ISSUE THREAD

**Issue by Explosion-Scratch** [SBoudrias/Inquirer.js#1208]
How would I go about listening for a custom key press while the user is selecting a list item, for example say I prompt the user to select a file like such:
```js
inquirer.prompt([{type: "checkbox", choices: ["file1.txt", "file2.mp4", "file3.md"]}])
```

Now how do I make it so that when selecting if the user presses "o" on the active file it will open the file (similar to how `Press <i> to invert selection` works):

<img width="802" alt="image" src="https://user-images.githubusercontent.com/61319150/230736553-fcf17d10-59a7-45f5-b251-c9de9e18d495.png">
(`obsidian_notes` is the selected item here, I want to be able to press "o" while selecting it to run some function, such as opening it in finder)

**Comment by SBoudrias** [comment]
Hi, this isn't something we support in the base API. I would recommend you to create a custom prompt to handle this use case.

I'd recommend you to use the new API to do so. Maybe replicating the [new select prompt](https://github.com/SBoudrias/Inquirer.js/tree/master/packages/select) code and looking into [`useKeypress()`](https://github.com/SBoudrias/Inquirer.js/tree/master/packages/core#hooks).

Hope this helps!

**Comment by pgibler** [comment]
@SBoudrias I have a similar question, not sure if the useKeyPress will work for this or not, but do let me know.

I have this as my output list:

? Choose an option: 
❯ Run all commands (A) 
  Run setup commands (S) 
  Run main command (M) 
  Quit (Q) 
  
I want it such that the user can either use the arrow keys + Enter to make a selection, or just hit the key corresponding to the option.

Is there a way to achieve this with the new API?

**Comment by SBoudrias** [comment]
@pgibler if you want something out of the box, the `expand` prompt is your best bet. Otherwise, you could fork the code from the [expand prompt](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/expand/src/index.mts) and customize it (with the new core API, the prompt is just ~100 lines of code - so cheap to copy-paste in your project or publish your own custom prompt package).

I think there might be an option to expand the default prompt by default (but I wrote that years ago, so I'm not 100% sure anymore 😅)

**Comment by pgibler** [comment]
I've followed your instructions and I almost have it done, but I've run into one bug that I'm wondering if you may remember the code well enough to know a solution. It occurs when the prompt constructor is picked based on the `question.type`. My customList is now available in the `PromptUI` -> `this.prompts` field:

![image](https://user-images.githubusercontent.com/119892/233559527-84fbb89c-50f1-434b-a512-3b895bb3bbd4.png)

And indeed on moving to the next line, the Prompt field is assigned to the value at the customList prompt key.

![image](https://user-images.githubusercontent.com/119892/233559793-20ff05ba-19b4-4fd8-a982-d64d4a02eb11.png)

But when `this.activePrompt = new Prompt(question, this.rl, this.answers);` is executed, I get this error:

These were the parameters passed into it:

![image](https://user-images.githubusercontent.com/119892/233560084-7c3bfec8-5de5-4295-9a7c-00572d0bf570.png)

Would you know what might be causing this? I can make a repo to allow you to reproduce if it would help.

**Comment by pgibler** [comment]
Figured it out myself after going through your code again @

Here's a working implementation of a list prompt controllable by both up/down + Enter & keypress.

```
import {
  createPrompt,
  useState,
  useKeypress,
  usePrefix,
  isEnterKey,
  isUpKey,
  isDownKey,
} from '@inquirer/core';
import chalk from 'chalk';

export default createPrompt((config, done) => {
  const { choices, default: defaultKey = 'm' } = config;
  const [status, setStatus] = useState('pending');
  const [index, setIndex] = useState(choices.findIndex((choice) => choice.value === defaultKey));
  const prefix = usePrefix();

  useKeypress((key, _rl) => {
    if (isEnterKey(key)) {
      const selectedChoice = choices[index];
      if (selectedChoice) {
        setStatus('done');
        done(selectedChoice.value);
      }
    } else if (isUpKey(key)) {
      setIndex(index > 0 ? index - 1 : 0);
    } else if (isDownKey(key)) {
      setIndex(index < choices.length - 1 ? index + 1 : choices.length - 1);
    } else {
      const foundIndex = choices.findIndex((choice) => choice.value.toLowerCase() === key.name.toLowerCase());
      if (foundIndex !== -1) {
        setIndex(foundIndex);
        // This automatically finishes the prompt. Remove this if you don't want that.
        setStatus('done');
        done(choices[foundIndex].value);
      }
    }
  });

  const message = chalk.bold(config.message);

  if (status === 'done') {
    return `${prefix} ${message} ${chalk.cyan(choices[index].name)}`;
  }

  const renderedChoices = choices
    .map((choice, i) => {
      const line = `  ${choice.name}`;
      if (i === index) {
        return chalk.cyan(`> ${line}`);
      }

      return `  ${line}`;
    })
    .join('\n');

  return [`${prefix} ${message}`, renderedChoices];
});
```

How can I best share this in case other's want to use it? I figure someone else may want this functionality too.

**Comment by SBoudrias** [comment]
> How can I best share this in case other's want to use it? I figure someone else may want this functionality too.

You could put the code in a Github repo, and release it as a new package to npm 😄

**Comment by pgibler** [comment]
Just got a repo up with the code now. Thanks for all the help getting this going @SBoudrias.

https://github.com/pgibler/inquirer-interactive-list-prompt

**Comment by SBoudrias** [comment]
@pgibler you can add your prompt here https://github.com/SBoudrias/Inquirer.js/blob/master/packages/prompts/README.md#community-prompts if you want to advertise it! I'm planning to switch this README to the repo homepage next weekend ([more on that](https://github.com/SBoudrias/Inquirer.js/discussions/1214)).
