### ISSUE TITLE
Feature request: Support for "done" callback for all prompt types

### ISSUE THREAD

**Issue by remisture** [SBoudrias/Inquirer.js#1211]
Could you please add support for some sort of callback for when the prompt is finished (and valid)?

```javascript

const STORAGE_NAME = 'name';

await inquirer.prompt({
	type: 'input',
	name: 'name',
	message: 'What is your name?',
	default: localStorage.getItem(STORAGE_NAME),
	done: (answer) => localStorage.setItem(STORAGE_NAME, answer),
});
```

**Comment by SBoudrias** [comment]
Hi @remisture, how is this different from waiting for the promise to resolve?

**Comment by remisture** [comment]
You're right, that's what I do now. I guess the example is bad :) It's useful when you have an array of prompts, and quit halfway through for some reason :)

```javascript
await inquirer.prompt([
   { type: 'input', name: 'input1', message: 'Message 1' },
   { type: 'input', name: 'input2', message: 'Message 2' },
   { type: 'input', name: 'input3', message: 'Message 3' }
]);
```

**Comment by SBoudrias** [comment]
Hi, with the release of the new API, I'm not really open to adding more control flow. The reasons are somewhat covered in the release announcement https://github.com/SBoudrias/Inquirer.js/discussions/1214 - and with the new API, you'd own control of the flow completely; this mean you'll get the answer after each prompt.

Thanks for reaching out, and I hope that alternative will work for you.

**Comment by remisture** [comment]
No worries :)
