### ISSUE TITLE
Preload input with suggestive text, allow the user to edit.

### ISSUE THREAD

**Issue by j-d-carmichael** [SBoudrias/Inquirer.js#1215]
It would be nice to be able to do something like this:
```
        {
          type: 'input',
          name: 'apiKey',
          message: 'What do you think?',
          preload: 'I think that...'
        }
```

The question would preload the answer in the CLI.

**Comment by SBoudrias** [comment]
Hi! So something similar to the `default` option, but editable?

I wonder if we could think of a nice UX to edit the `default` content instead? Right now pressing `backspace` will remove the default.

**Comment by matteosacchetto** [comment]
How about something like, if you TAB then it fills the input with the default value, and you can start editing it

**Comment by SBoudrias** [comment]
> if you TAB then it fills the input with the default value, and you can start editing it

I like this idea!
