### ISSUE TITLE
Checkbox instructions disappears on space selection

### ISSUE THREAD

**Issue by shinebayar-g** [SBoudrias/Inquirer.js#1217]
Pressing `i` or `a` works as expected. But selecting item with `space`, removes `instructions`.
![image](https://user-images.githubusercontent.com/3091558/236097813-de6b58f5-6b97-4932-839a-a37f93276c3e.png)
![image](https://user-images.githubusercontent.com/3091558/236098283-a0ecf5c8-11f4-49ff-b750-f16c08d2ebc2.png)
![image](https://user-images.githubusercontent.com/3091558/236097862-7f6a5cad-2816-4339-bed0-15081458950b.png)

**Comment by SBoudrias** [comment]
Hey! This is done on purposes to reduce weight on the screen once we assume a user understands how to operate the prompt.

Does it cause a problem? Would you prefer this to be configurable?

**Comment by shinebayar-g** [comment]
Oh I see. Well it was a little bit unexpected since instructions present 3 options and 2 of them doesn't clear up instructions while only 1 of them cleared it. I'd prefer it to be stay consistent tbh. My vote goes to non-clearing path by default. Configuration option doesn't sound bad.

**Comment by SBoudrias** [comment]
Let's combine this request with #963

**Comment by SBoudrias** [comment]
PR #1381 is up with this feature. I'll leave open a few days for review and feedback. Feel free to chip in!
