### ISSUE TITLE
The dist files for CommonJS are not correct

### ISSUE THREAD

**Issue by LitoMore** [SBoudrias/Inquirer.js#1218]
<img width="772" alt="CleanShot 2023-05-04 at 15 10 58@2x" src="https://user-images.githubusercontent.com/8186898/236134917-0d75969a-5bdd-4093-942f-17b4dcf1c821.png">

As you can see here https://www.jsdelivr.com/package/npm/@inquirer/core?tab=files&path=dist%2Fcjs, it runs `require("./lib/screen-manager.mjs")` for importing modules.

This might be related to:

- https://github.com/microsoft/TypeScript/issues/49462

Or we could consider other tools. For example https://github.com/egoist/tsup.

### How to reproduce

```js
// Use CommonJS, and run this line
const {input} = require('@inquirer/prompts');
```

**Comment by saracope** [comment]
Also seeing this issue. Appreciate the quick fix @LitoMore

**Comment by SBoudrias** [comment]
Thanks @LitoMore 

The patch are released to NPM.
