### ISSUE TITLE
Downgrade or use multi-version for those pure ESM packages

### ISSUE THREAD

**Issue by LitoMore** [SBoudrias/Inquirer.js#1221]
<img width="1022" alt="CleanShot 2023-05-05 at 01 53 30@2x" src="https://user-images.githubusercontent.com/8186898/236288219-522166ee-ce90-4d63-bd74-521623195f27.png">

We need to downgrade or use multi-version https://github.com/SBoudrias/Inquirer.js/issues/1159#issuecomment-1286851683 for those pure ESM packages.

**Comment by SBoudrias** [comment]
Ah, we're missing the import maps. Some of it is setup in https://github.com/SBoudrias/Inquirer.js/pull/1185

**Comment by SBoudrias** [comment]
Oh also, one thing I'd really like is having a way to automatically test that. Because the unit tests are going through build tools, correct ESM functionalities aren't enforced.

This makes it really hard to know for certain the build artifacts are/aren't working.

**Comment by SBoudrias** [comment]
Went with the path of least resistance to get a quick fix out. I've downgraded all ESM only dependencies to when they were CJS friendly.

If anyone want to look into getting #1227 working, the bulk of the work is done. The one downside is it'll likely increase the install size; if not dramatic, it's might be a good option.

**Comment by minidonut** [comment]
Thanks :) I just encountered this issues

**Comment by SBoudrias** [comment]
I just sent patch releases of all packages to npm. Let me know if there's still any issues with CJS compatibility 😄

**Comment by LitoMore** [comment]
> Oh also, one thing I'd really like is having a way to automatically test that. Because the unit tests are going through build tools, correct ESM functionalities aren't enforced. (@SBoudrias)

I will try to add some extra GitHub Actions workflows for testing this.
