### ISSUE TITLE
Cannot find package '@inquirer/prompts'

### ISSUE THREAD

**Issue by renatocfrancisco** [SBoudrias/Inquirer.js#1225]
I don't get it. My package.json has the `"type":"module"`, 
I am importing with `import { select } from '@inquirer/prompts';`. But still says `MODULE_NOT_FOUND`.
Using version 9.2.1.

```
import { select } from '@inquirer/prompts';

const period = await select({
    message: 'Select the period of the chart',
    choices: [
        {
            title: '7day',
            value: '7day'
        },
        {
            title: '1month',
            value: '1month'
        },
        {
            title: '3month',
            value: '3month'
        },
        {
            title: '6month',
            value: '6month'
        },
        {
            title: '12month',
            value: '12month'
        },
        {
            title: 'overall',
            value: 'overall'
        }
    ],
});
```

**Comment by SBoudrias** [comment]
Hi @renatocfrancisco, can you print the whole error message?

Sanity check, you did run `npm install @inquirer/prompts`? (or yarn)

**Comment by renatocfrancisco** [comment]
> Hi @renatocfrancisco, can you print the whole error message?
> 
> Sanity check, you did run `npm install @inquirer/prompts`? (or yarn)

I will print later thee error.
I used `npm i inquirer`

**Comment by renatocfrancisco** [comment]
@SBoudrias ay, it worked. dumb mistake, sorry.
![Code_X3QtZ7wWRj](https://user-images.githubusercontent.com/56325092/236585254-9d5b69be-7a06-4193-88c4-201b81a47d3f.png)
