### ISSUE TITLE
Checkbox default selection

### ISSUE THREAD

**Issue by warflash** [SBoudrias/Inquirer.js#1226]
The typing for `checkbox()` don't seem to include a default option.
It seems like this has been added ages ago already https://github.com/SBoudrias/Inquirer.js/issues/73 so perhaps I'm missing something obvious. Just started using inquirer so apologies if thats the case^^

**Comment by SBoudrias** [comment]
Hey, this is possible!

The `@inquirer/**` prompts were all rewritten from scratch. And doing so, some less used features weren't 100% reimplemented.

I'm happy to help review and merge a PR adding this feature to `@inquirer/checkbox`!

You can also use the `inquirer` package who has it built-in already. (At the cost of a larger package size and a slightly less modern API.)

Let's keep the ticket open until the feature is ported to the new prompt. Thanks for reporting!

**Comment by SBoudrias** [comment]
The new interface is a little different. Set `checked: true` on the choices you wish selected by default.

**Comment by warflash** [comment]
Damn that was quick, appreciate you adding it and the thorough response!
