### ISSUE TITLE
Does `select` in @inquirer/prompts support separators?

### ISSUE THREAD

**Issue by tohagan** [SBoudrias/Inquirer.js#1230]
The old list feature included a special seperator do you know if that is supported or planned?

**Comment by SBoudrias** [comment]
Hi! This is a feature I haven't ported yet; but I'm planning to.

If you (or another community member) want to send a PR to introduce this go ahead! I'll help review and merging ASAP. The new prompt uses the same paginator component, so it shouldn't be too hard to port over 🤞🏻

**Comment by SBoudrias** [comment]
Hey, this is now added back to the `select` and `checkbox` prompts.

(@zonemeen there's still rawlist where we need to backport the feature if you're willing to help; I'm disconnecting for today! Cheers!)

**Comment by tohagan** [comment]
Oh that's AWESOME!!! Thank you very much!

**Comment by zonemeen** [comment]
Sorry, I didn't notice this message.😂 And whether to add the corresponding test?

**Comment by SBoudrias** [comment]
Yeah unit test is something I want to add to all prompts eventually. With my time for now, I'm still priorizing backward compatibility issues as they come up.
