### ISSUE TITLE
Allow prompts to keep their current content on validation error

### ISSUE THREAD

**Issue by matteosacchetto** [SBoudrias/Inquirer.js#1232]
I was trying out the `@inquirer/input` and `@inquirer/password` packages and noticed that it currently deletes the content of both prompts on input validation.

I also noticed the TODO comment
https://github.com/SBoudrias/Inquirer.js/blob/5ac98a19c2beb54468c7f1fb5777dc156891a5f6/packages/input/src/index.mts#LL42C9-L43C70

I was wondering if you have any idea on how it could be fixed.
I do not have yet much experience with the code-base but I'm willing to help out

**Comment by SBoudrias** [comment]
Hey, yeah so the need is move the cursor to after the line content. You could do that with the utils over here https://github.com/SBoudrias/Inquirer.js/blob/5ac98a19c2beb54468c7f1fb5777dc156891a5f6/packages/core/src/lib/readline.mts (you'll need to get the readline instance, might be passed to the hook callback)

**Comment by matteosacchetto** [comment]
Ok, so, I've experimented with it a bit, but I was not able through those functions to make it work... (probably I am missing something important 😅 )

Anyway, after a bit of experimentation I found a solution which may not be the best so far, but seem to work.

If you simply want to keep the content as editable with the cursor at the end, a simple `rl.write(...)` did the trick.
Instead, for cases were you want to preserve the cursor position I kept track of it (through a useState) and in the body of the function I used an ugly trick of "pressing" left as many times as the difference between the previous cursor position and the end of line

For reference here is the part I updated starting from the `@inquirer/input` 
```ts
export default createPrompt<string, InputConfig>((config, done) => {
  ...
  const [cursor, setCursor] = useState<number>(0);
  ....
  useKeypress(async (key, rl) => {
    ...
    if (isEnterKey(key)) {
      ...
      const isValid = await config.validate(answer);
      if (isValid === true) {
        ...
      } else {
        const offset = rl.getCursorPos().cols - cursor;
        // Ugly but does the trick
        rl.write(value);
        for (let i = 0; i < offset; i++) rl.write(null, { name: 'left' });

        setError(isValid || 'You must provide a valid value');
        setStatus('pending');
      }
    } else if (isBackspaceKey(key) && !value) {
      setDefaultValue(undefined);
    } else {
      setCursor(rl.getCursorPos().cols); // Update cursor position
      setValue(rl.line);
      setError(undefined);
    }
  });
  ...
}
```

Any suggestion on how to do it right/improve it?

Thank you in advance!! 😃

**Comment by SBoudrias** [comment]
Ohhh, the problem was we didn't want to keep the cursor position, we wanted it to stay after the answer. So if `rl.write` does it, then I think that's the only thing we need.
