### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by matteosacchetto** [SBoudrias/Inquirer.js#1233]
While browsing through the repo I noticed that some of the `@inquirer/*` packages seem to have unused dependencies

In particular:
- `@inquirer/confirm`
  - has `@inquirer/input` listed among the dependencies, but doesn't seem to actually use it
- `@inquirer/core`
  - has `lodash` listed among the dependencies, but doesn't seem to actually use it

Removing those dependencies, if unused, will reduce the install size of any CLI currently using the new `@inquirer/*` packages

Thank you in advance,
Matteo

**Comment by SBoudrias** [comment]
Ohh, those might be dependencies removed, but forgot to remove from the package.json. Thanks for the headsup
