### ISSUE TITLE
inquirer/confirm accepts more than just 'Y' and 'n' answers.

### ISSUE THREAD

**Issue by rrohans** [SBoudrias/Inquirer.js#1239]
When using `confirm`, inquirer will implicitly choose 'n' if the answer does not start with a 'Y' or the answer is not either 'Y' or 'n' explicitly.

For example:
`Yno' -- Implicit Yes
'asdf' -- Implicit No
'nY' -- Implicit No
'Y123' -- Implicit Yes

This bug was initially found in the Create-t3-app cli, which uses Inquirer as a dependency.

**Comment by LitoMore** [comment]
The code is here:

https://github.com/SBoudrias/Inquirer.js/blob/a9a0039474ff9f1629d81e3ff9baccf7463f4f12/packages/inquirer/lib/prompts/confirm.js#L16-L25

@rrohans Could you give more background about your scenario and your expected behavior?

@SBoudrias Maybe we change the logic below will be better:

```js
Object.assign(this.opt, {
  filter(input) {
    if (input != null && input !== '') {
      if (/^y(es)?/i.test(input)) return true;
      if (/^n(o)?/i.test(input)) return false;
    }

    return rawDefault;
  },
});
```

Or change it to:

```js
if (/^(y|yes)$/i.test(input)) return true;
if (/^(n|no)$/i.test(input)) return false;
```

**Comment by rrohans** [comment]
Yeah sure. I was scaffolding a new [T3](https://t3.gg/) app using their [create t3-app](https://create.t3.gg/en/introduction) cli tool when I noticed a bug in the way they accept confirm-style inputs. I created an issue with their cli tool and was told that they use Inquirer as part of their cli tool. Upon further inspection, I found that the bug is not with their cli but with inquirer itself, as you pointed out in the code above. Ideally, if a non 'Yes' or 'no' answer is selected, the program should either throw an error that has to be handled, or it could just ask the question again (specifying that the initial input was wrong).

**Comment by LitoMore** [comment]
> If a non 'Yes' or 'no' answer is selected, the program should either throw an error that has to be handled, or it could just ask the question again (specifying that the initial input was wrong).

Good point. I seem to have seen similar interactions before.
