### ISSUE TITLE
How do I force a re-render from inside the context of createPrompt?

### ISSUE THREAD

**Issue by JonathanCoxLRS** [SBoudrias/Inquirer.js#1250]
I'm creating a custom prompt using ``createPrompt`` and I have need to force a re-render of the custom prompt content.  I see that ``ScreenManager`` is used under the hood to perform certain actions like ``render`` and others.  However, I'm not seeing a way to access the ``ScreenManager`` instance from inside the ``createPrompt`` context.  Thanks in advance for pointing me in the right direction!

**Comment by SBoudrias** [comment]
Hey @JonathanCoxLRS, how about update a counter state?

```js
const [counter, setCounter] = useState(0);
const forceRerender = () => setCounter(n => n + 1);
```
