### ISSUE TITLE
A declaration file cannoty be imported without 'import type'. Did you mean to import an implementation file instead?

### ISSUE THREAD

**Issue by lukeocodes** [SBoudrias/Inquirer.js#1253]
I have `@inquirer/prompt` installed on [my `oclif` CLI project.
](https://github.com/deepgram-devs/deepgram-cli)

I am trying a build, and it's throwing this error at the moment. 

```bash
(1) lukeocodes~/Projects/Deepgram/deepgram-cli(lo/prep-for-beta-release|✚2) % npm run build 

> @deepgram/cli@0.1.0 build
> shx rm -rf dist && tsc -b

node_modules/@inquirer/core/dist/cjs/types/index.d.cts:6:27 - error TS2846: A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './lib/prefix' instead?

6 export { usePrefix } from './lib/prefix.d.cts';
                            ~~~~~~~~~~~~~~~~~~~~

node_modules/@inquirer/core/dist/cjs/types/index.d.cts:7:15 - error TS2846: A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './lib/key' instead?

7 export * from './lib/key.d.cts';
                ~~~~~~~~~~~~~~~~~

node_modules/@inquirer/core/dist/cjs/types/index.d.cts:8:15 - error TS2846: A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './lib/Paginator' instead?

8 export * from './lib/Paginator.d.cts';
                ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@inquirer/core/dist/cjs/types/index.d.cts:9:15 - error TS2846: A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './lib/Separator' instead?

9 export * from './lib/Separator.d.cts';
                ~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors.
```

My use of it: https://github.com/deepgram-devs/deepgram-cli/blob/lo/prep-for-beta-release/src/base.ts

**Comment by SBoudrias** [comment]
Hey, I'm not quite sure that's a problem from inquirer. `d.ts` are type files and generated by Typescript. I think the issue is with your project tsconfig enforcing syntactic preferences to the dependencies; I would revise the configuration or `skipLibCheck`.

Let us know if you end up figure out more!

**Comment by lukeocodes** [comment]
Ahh thanks that was spot on, sorry for the bother! There was always a risk it was me lol <3

**Comment by nfour** [comment]
I think this should be re-opened.

My project built fine, Typescript 5.1.5, NodeJS >= 18, ESM modules.

Once I added @inquirer/prompts the lib check began to produce the same errors as OP.

![image](https://github.com/SBoudrias/Inquirer.js/assets/2108452/f4cb4087-9b82-4518-ad71-a21d758a369d)

Looking at the source code, I notice that .mjs extensions are being used, so perhaps the generated typescript is not correctly being built for the latest typescript versions and just needs the "import type" annotation, as this seems to fix the code:

![image](https://github.com/SBoudrias/Inquirer.js/assets/2108452/3ee039e0-6d37-4416-bc76-b56b214aefe8)

**Comment by SBoudrias** [comment]
Thanks to the minimal repro case from @everhardt! It allowed me to find out quickly the common.js type files were indeed broken. There's a now patch published on npm!

Let me know if anything else comes up!
