### ISSUE TITLE
inquirer.prompt(...).then is not a function

### ISSUE THREAD

**Issue by unofficialdxnny** [SBoudrias/Inquirer.js#1256]
Below is what I have tried and than the error i get.

```js
const inquirer = require('inquirer');

console.clear();
console.log("\x1b[33m    ___\r\n   \/\/_\\\\_\r\n .\"\\\\    \".\r\n\/          \\\r\n|           \\_\r\n|       ,--.-.)\r\n \\     \/  o \\o\\\r\n \/\\\/\\  \\    \/_\/\r\n  (_.   `--\'__)\r\n   |     .-\'  \\    Simple Terminal in JS\r\n   |  .-\'.     )\r\n   | (  _\/--.-\'\r\n   |  `.___.\'\r\n         ( \x1b[0m")

inquirer
  .prompt([
    {
      type: "list",
      name: "prize",
      message: "Select a prize",
      choices: ["cake", "fries"]
    }
  ])
  .then((answers) => { 
    console.log(JSON.stringify(answers, null, "  "));
  });

```
![image](https://github.com/SBoudrias/Inquirer.js/assets/82535503/7e35e851-1487-4c1f-8250-cb4aa0d82de5)

----

```js
const inquirer = import('inquirer');

console.clear();
console.log("\x1b[33m    ___\r\n   \/\/_\\\\_\r\n .\"\\\\    \".\r\n\/          \\\r\n|           \\_\r\n|       ,--.-.)\r\n \\     \/  o \\o\\\r\n \/\\\/\\  \\    \/_\/\r\n  (_.   `--\'__)\r\n   |     .-\'  \\    Simple Terminal in JS\r\n   |  .-\'.     )\r\n   | (  _\/--.-\'\r\n   |  `.___.\'\r\n         ( \x1b[0m")

inquirer
  .prompt([
    {
      type: "list",
      name: "prize",
      message: "Select a prize",
      choices: ["cake", "fries"]
    }
  ])
  .then((answers) => { 
    console.log(JSON.stringify(answers, null, "  "));
  });

```
![image](https://github.com/SBoudrias/Inquirer.js/assets/82535503/5df1e77b-6c26-426a-bb17-549330ba62d9)

----

```js
import inquirer from 'inquirer'

console.clear();
console.log("\x1b[33m    ___\r\n   \/\/_\\\\_\r\n .\"\\\\    \".\r\n\/          \\\r\n|           \\_\r\n|       ,--.-.)\r\n \\     \/  o \\o\\\r\n \/\\\/\\  \\    \/_\/\r\n  (_.   `--\'__)\r\n   |     .-\'  \\    Simple Terminal in JS\r\n   |  .-\'.     )\r\n   | (  _\/--.-\'\r\n   |  `.___.\'\r\n         ( \x1b[0m")

inquirer
  .prompt([
    {
      type: "list",
      name: "prize",
      message: "Select a prize",
      choices: ["cake", "fries"]
    }
  ])
  .then((answers) => { 
    console.log(JSON.stringify(answers, null, "  "));
  });

```
![image](https://github.com/SBoudrias/Inquirer.js/assets/82535503/13824103-c125-4ae2-9095-90ae5ca8c77b)

----

Any help will be greatly appreciated as this is my first proper NodeJS project

**Comment by SBoudrias** [comment]
You're running into cjs/esm module issues.

I'll provide solutions for all 3 versions you shown:

1. Your project is CJS: Use inquirer v8 (`npm install --save inquirer@^8.0.0`)
2. Your project is CJS, but you want to use latest inquirer. `import()` is an asynchronous function. So you need to wait for the promise to resolve. Either `await import('inquirer')` or `import('inquirer').then(() => you code here)`
3. Your project is ESM: you need to add `"type": "module"` to your `package.json`.

**Comment by unofficialdxnny** [comment]
Hi ive ended up using an alternative method for what i wanted in my project. However i have tried the above solutions and they work so this is fin thanks
