### ISSUE TITLE
inquirer/select and readline conflict

### ISSUE THREAD

**Issue by madbaker** [SBoudrias/Inquirer.js#1259]
Hi.  I've been trying to debug this for a couple of days now but am completely flummoxed.

I'm building a CLI with readline, commander and inquirer that interacts with a local mongodb database.

Everything's running locally. 

- WSL2 (Ubuntu 22.04, Windows 11 Pro 10.0.22621 Build 22621)
- Windows Terminal and the VS Code integrated terminal (running zsh)
- Node 18.14.2
- @inquirer/select 1.2.3

I've isolated things down to readline and inquirer.  Readline displays whatever is entered and issues a new prompt.  If "multi" is entered, an inquirer select is performed.

It looks like something extra is returned from inquirer that is stopping readline.  I'm not sure how to identify what is being returned and how I might handle it.

my simplified code:

```
import * as readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import select  from '@inquirer/select';

// Main loop - keep getting lines till 'exit'

const rl = readline.createInterface({ input, output });

let state = "start"
rl.setPrompt(`=> `);
rl.prompt();

rl.on('line',async (line) => {


    switch (line.trim()) {
        default:
            state = line.trim()   
            break 
        case 'exit':
            console.log('all done. Have a great day!')
            rl.close()
            process.exit(0) 
        case 'multi':
            const options = [
                {value: "One"},
                {value:"Two"},
                {value:"Three"},
                {value:"Four"}
            ]  
            state = await select (
                {
                    type: 'list',
                    name: 'countries',
                    message: 'Multiple matches. Select a country:',
                    choices: options
                })
            break
     }   
        
    console.log(`state: ${state}`)
    rl.prompt()    
})


```

Two screenshots, showing how the default case works, followed by the inquirer / select call.
 
![before option selected](https://github.com/SBoudrias/Inquirer.js/assets/17280173/37d85546-b2d9-4b76-9d8b-f87dd40b54a6)

Note the extra character displayed in the final prompt, after Inquirer runs. 
![after option selected](https://github.com/SBoudrias/Inquirer.js/assets/17280173/adbe03c7-e389-427c-87aa-66ed32126920)

**Comment by SBoudrias** [comment]
Node Readline are not quite a singleton; but there effectively can only ever be one running at a time on a given set of streams.

This means before calling a prompt, you need to close the open readline.

I'd recommend you implementing a recursive function that'll ask the free text command, stop, yield to inquirer, then recursively call itself again. And you might want to look into implementing that free text input as a custom inquirer prompt too (depending on how complex it might become).
