### ISSUE TITLE
Vulnerable dependencies ( indirect security issues ?? )

### ISSUE THREAD

**Issue by daudmalik06** [SBoudrias/Inquirer.js#1260]
Hello maintainers,

I wanted to bring to your attention that after installing the package, I ran a vulnerability scan with vulert abom on the lock file and discovered that there are 2 vulnerable dependencies present with High risk. As these vulnerabilities can potentially impact the security of the entire project, I am unsure whether to report this under responsible disclosure.

For your reference, here is a link to the report of the yarn.lock file I scanned: https://vulert.com/vuln-scan/list/c0b083b4-261e-4194-94bf-0518bee7d86c

I recommend that we take immediate action to address these vulnerabilities and ensure the security of the project. Please let me know if you require any further information.

p.s. this is the lock file i scanned: https://github.com/SBoudrias/Inquirer.js/blob/master/yarn.lock

Thank you.

**Comment by SBoudrias** [comment]
These 2 are unit test only dependencies; and there's no fix for those out. But happy if you want to send a PR.

I'll close as for me those security issues from automated tools are just noise with low to no values.
