### ISSUE TITLE
Prompt does not play well with ANSI hyperlinks

### ISSUE THREAD

**Issue by TooTallNate** [SBoudrias/Inquirer.js#1261]
We noticed incorrect line breaks when the prompt `name` value contains an ANSI hyperlink escape code.

<img width="990" alt="253390699-8cda40c5-3b57-422e-927c-ae60f6937654" src="https://github.com/SBoudrias/Inquirer.js/assets/71256/65cf4be9-bc12-496f-890c-afb8030bf6bf">

**Comment by SBoudrias** [comment]
Hey, I'll refer you to this project https://github.com/chalk/wrap-ansi/issues/38

It's likely a bug leaking from the library to Inquirer.

**Comment by TooTallNate** [comment]
Realizing that we are on a rather old version of inquirer (v7). Will see if the same issue persists with latest.

**Comment by SBoudrias** [comment]
Hey @TooTallNate, any news on this issue on later versions? v8 is still CSM compatible (v9 is not) if that caused issue with bumping.

**Comment by TooTallNate** [comment]
Seems like it works fine on the latest version. Sorry for the noise.
