### ISSUE TITLE
@inquirer/input: cursor not showing the updated position when using left/right arrows

### ISSUE THREAD

**Issue by matteosacchetto** [SBoudrias/Inquirer.js#1262]
Today I noticed that `@inquirer/input@1.2.4` does not show the updated position of the cursor when using the left/right arrows, while on `@inquirer/input@1.1.2` arrows were working correctly. The cursor does move but its position is not visible.

I set up a minimal reproduction example here:
 - `@inquirer/input@1.2.4` -> https://stackblitz.com/edit/stackblitz-starters-3cxrpv
 - `@inquirer/input@1.1.2` -> https://stackblitz.com/edit/stackblitz-starters-kvm2pn

Please let me know if I can help in any way

**Comment by matteosacchetto** [comment]
While debugging the behavior I think I found the source of the issue
https://github.com/SBoudrias/Inquirer.js/blob/33677f22a06f1abce38c58284b65fb20cf19e050/packages/core/src/index.mts#L91-L96

In the @inquirer/core package, it re-renders only when the value changes, but in the case of arrow right or left, the value does not change, only the cursor position changes, but since it does not re-render the UI, the cursor gets moved but it not showed in the correct location

I don't know though which could be the good strategy to handle this. Maybe adding a second parameter to the function (second return valye) returned by `useState` function which allows to trigger re-rendering arbitrarily... I don't know

I hope that maybe this can give you some hints on where the issue may be and how to handle it

Best,
Matteo

**Comment by SBoudrias** [comment]
Ohh interesting. I think it'd be better to handle in the core. Maybe a listener that'd always force-rerender on arrow keypresses 🤔 Or maybe more resilient comparing the cursor position on each keypress and trigger a re-render when that value changes.

**Comment by matteosacchetto** [comment]
The idea of rerendering if the cursor position changes sounds the best one

**Comment by SBoudrias** [comment]
Hey @matteosacchetto, this is now fixed! Thanks again for reporting.

I'd really appreciate if you could pull the latest version and let me know if it works well for you. Thanks!!

**Comment by matteosacchetto** [comment]
Hey @SBoudrias, I pulled the latest version and I can confirm that it now works like a charm 🎉 

Thank you very much for fixing this issue!! 🚀
