### ISSUE TITLE
update to a maintained `through`?

### ISSUE THREAD

**Issue by ljharb** [SBoudrias/Inquirer.js#1266]
Hi! You depend on `through`, an excellent package that unfortunately has not been maintained since 2018. I've forked it as https://npmjs.com/@ljharb/through so that I can maintain it (with @dominictarr's blessing), and am using it in https://npmjs.com/tape.

Would you be interested in a PR that switches this project to using my fork instead of the original? It's effectively identical, but it'd ensure any vulnerabilities will be addressed in the future.

**Comment by LitoMore** [comment]
It seems we don't need this package anymore. I just created a PR to remove it.

**Comment by ljharb** [comment]
That would certainly be an alternative solution :-)

**Comment by ljharb** [comment]
Since #1267 is a breaking change, in the meantime, would you accept a PR to replace the dep?

**Comment by SBoudrias** [comment]
Thanks for reaching out @ljharb. I would accept a PR to replace the dep, thanks!
