### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by MONSEFOT** [SBoudrias/Inquirer.js#1274]
I am working on a Nestjs project, the problem suddenly appeared on the screen, it says that I need to use the dynamic `import()` isntead of the common require in `/home/manssif/Projects/tg_universal/node_modules/inquirer/lib/utils/screen-manager.js:4`.

I did that and it all worked perfectly but I just wanted to report the issue, you may be able to fix it guys.

![image](https://github.com/SBoudrias/Inquirer.js/assets/44806415/a9b737a3-2d77-421d-817d-da533fb752c9)

**Comment by joeykamsteeg** [comment]
I got the same problem

**Comment by MONSEFOT** [comment]
@joeykamsteeg they made an update two days ago, probably the update is the reason behind the issue.

**Comment by joeykamsteeg** [comment]
I do have this issue with version 8.2.5 of Inquirer and using 8.1.0 version of wrap-ansi according to my yarn.lock. I was working fine yesterday few hours before this issue showing up in mijn deployment logs in Vercel. I did not update any dependencies in the meantime

**Comment by joeykamsteeg** [comment]
@MONSEFOT Did you found already a solution for this problem?

**Comment by LitoMore** [comment]
@MONSEFOT Please provide your version of the `inquirer` package.

In the meantime, we have released the new package `@inquirer/prompts`. Please consider using the new one instead.

See https://github.com/SBoudrias/Inquirer.js/discussions/1214.

**Comment by SBoudrias** [comment]
There was an issue with `wrap-ansi` being ESM only on the v8 branch of inquirer. A fix has been pushed out on the legacy version https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%408.2.6

```
npm install inquirer@^8.2.6
```

Thanks for reporting!
