### ISSUE TITLE
Wrong version released as latest

### ISSUE THREAD

**Issue by myndco** [SBoudrias/Inquirer.js#1278]
![image](https://github.com/SBoudrias/Inquirer.js/assets/82125648/eb7e5b17-0325-44be-8476-4c2fc3ae23ed)

**Comment by LitoMore** [comment]
@SBoudrias We should publish a new version `9.2.10` to cover up the `8.2.6`.

The `latest-version-cli` is useful for checking the version:

```sh
npm i -g latest-version-cli

latest-version inquirer --range=latest
#=> 8.2.6

latest-version inquirer --range=9
#=> 9.2.9

latest-version inquirer --range=8
#=> 8.2.6

latest-version inquirer --range=7
#=> 7.3.3
```

**Comment by SBoudrias** [comment]
Do you know of a good way to enforce this?

I make new v8 releases so rarely it's very likely the next one would end up tagged as latest anyway. I checked, but don't think we can enforce this through `.npmrc` 🤔

**Comment by LitoMore** [comment]
npm does not support this. I wonder if https://github.com/sindresorhus/np has a feature that gives a warning message when publishing a legacy major version. I can contribute code if they don't have this feature.

Or we can add a `prepublishOnly` script to validate the package version.

**Comment by SBoudrias** [comment]
> Or we can add a prepublishOnly script to validate the package version.

That sounds like a good idea to me. The problem with `np` is that it's not compatible with monorepo; so it wouldn't help here. Are you willing to work on a script?

**Comment by LitoMore** [comment]
>  Are you willing to work on a script?

Sure. I will create a PR for that.
