### ISSUE TITLE
useEffect differs from react behaviour for synchronous state changes

### ISSUE THREAD

**Issue by mokkabonna** [SBoudrias/Inquirer.js#1282]
I am updating https://www.npmjs.com/package/inquirer-autocomplete-prompt to use the new API.

If I update `searchstatus` in a useEffect callback synchronous like below then it does not render pending. This differs from how it works in react. If I do it in a setTimeout of 0ms then it works as expected.

Not sure if you try to align 100% with react behaviour for `useState`, `useRef`and `useEffect` but is a bit of a gotcha IMO.

```js
import { createPrompt, useState, useKeypress, useEffect } from '@inquirer/core';

const autocomplete = createPrompt<
  string,
  {
    message: string;
  }
>((config, done) => {
  const [searchStatus, setSearchStatus] = useState('initial-render');
  const [input, setInput] = useState('');

  useEffect(() => {
    // setTimeout(() => setSearchStatus('pending'), 0); // works!
    setSearchStatus('pending'); // does not trigger rerender

    setTimeout(() => {
      setSearchStatus('done'); // works!
    }, 1000);
  }, [input]);

  useKeypress((key, rl) => {
    setInput(rl.line);
    // setSearchStatus('pending'); // works fine if I set it here
  });

  return searchStatus;
});

const answer = await autocomplete({
  message: 'whatever',
});

```

**Comment by SBoudrias** [comment]
This one was a pesky one! I even had a test covering this; but we were rendering in the wrong order 🤦🏻 

Fix is being released now. Thanks for reporting!

**Comment by mokkabonna** [comment]
Works as expected now.

Thanks for the quick resolution! :)
