### ISSUE TITLE
Contextual help feature

### ISSUE THREAD

**Issue by DavidUrting** [SBoudrias/Inquirer.js#1288]
Hi, we use Inquirer for our developers to set up new applications. The list of questions is rather extended/technical and new developers don't always know the impact of the choices they make when answering a question. Currently we use **iohook** to implement an 'F1' contextual help feature. So, if a developer wants to know more details about a question he/she presses 'F1' and gets contextual information about that question after which the same question is asked again.

But, since iohook is not actively maintained anymore (and gives us issues on new nodejs versions) we would like to know if there is some possibility in Inquirer to show contextual help without using other libraries?

**Comment by SBoudrias** [comment]
Hi, there's no specific features exposed within the core prompts to do this. And I don't plan of adding such a feature.

There is many ways you could go about implementing this in your code.

Including:
1. Implementing custom prompts https://github.com/SBoudrias/Inquirer.js#create-your-own-prompts
2. Maybe canceling the active prompt when a key is pressed, and re-asking one the help screen is closed. https://github.com/SBoudrias/Inquirer.js#canceling-prompt
