### ISSUE TITLE
Go To Type Definitions

### ISSUE THREAD

**Issue by mesmur** [SBoudrias/Inquirer.js#1294]
ℹ️ Context
- Our repo uses `inquirer` (8.2.5) along with the `@types/inquirer` package
- We're planning to move to the refactored `@inquirer/prompts` package
- I've been trying it out on my local machine and there don't seem to be any type definitions (we are a TS project)
- My IDE (Webstorm) does recognize when an invalid field is used BUT I can't seem to navigate to the definition (`Go To > Type Declaration` on WS)
![image](https://github.com/SBoudrias/Inquirer.js/assets/22883661/6484a73b-bf6e-4584-b345-fed54f412dcc)

❓ Question
- Is there no support for this / Is there any way to get type definition support?

**Comment by SBoudrias** [comment]
Hi @mesmur,

I'm not sure I'm following you here. `@inquirer/prompts` re-export other packages; like `@inquirer/confirm` in your example. This package has types, see with the file explorer here https://www.npmjs.com/package/@inquirer/confirm?activeTab=code

For as to why Webstorm doesn't go to the type definition I have no idea. But the project is setup properly with TS, so I'd reach out to webstorm for support instead.

**Comment by mesmur** [comment]
@SBoudrias oh, thanks for the confirmation. That is odd, I guess it might just be an IDE issue then!
