### ISSUE TITLE
Allow file tab-complete/globbing in input type

### ISSUE THREAD

**Issue by lakenen** [SBoudrias/Inquirer.js#130]
From https://github.com/dylang/grunt-prompt/issues/21

Not sure if this is possible, but it would be cool to be able to tab-complete or use globbed filenames in a text input (or maybe a `file` input type?). Thoughts?

**Comment by GeorgeGkas** [comment]
You can use [autocomplete](https://github.com/mokkabonna/inquirer-autocomplete-prompt) plugin for autocomplete prompts and [inquirer-fuzzy-path](https://github.com/adelsz/inquirer-fuzzy-path) for autocomplete in file system level. 

Do those options cover your needs?

**Comment by seanwessmith** [comment]
can we reopen this? inquirer-fuzzy-path is outdated now

**Comment by SBoudrias** [comment]
The new search prompt can do that. There's a demo available in the codebase.

**Comment by seanwessmith** [comment]
Thanks. I missed that when looking earlier.
