### ISSUE TITLE
inquirer prompt is not rendered properly when I use it in lerna

### ISSUE THREAD

**Issue by Amit-limbasiya** [SBoudrias/Inquirer.js#1304]
I am using lerna to handle the monorepo project structure.  

When I run below code 
```
const question = [{
       type: 'input',
       name: 'permission',
       message: chalk.red(logMessages.deleteFeatureReleaseBranch.permissionMessage),
       filter: (input: string) => {
            return input.trim();
       },
       validate: (input: string) => {
         if (!validatePermissionInput(input)) return logMessages.deleteFeatureReleaseBranch.permissionValidationFailedMessage;
              return true;
          }
}];

const permission:string = (await inquirer.prompt(question)).permission;
```

 - **from the perticular project directory with simple node.js command `node dist/src/index.js delete-feature -r`**  
It is showing the proper output as  
`Are you sure you want to delete these branches(Y|N):  `

 - **But when i run the command from the root directory as lerna command like `lerna run start --scope=cli-app -- delete-feature -r`**  
It is not showing the prompt question like above. But when I force close the application or give random input which is failing validation, then it is showing the prompt question.

I don't know whether the issue is with inquirer (like extra configuration for lerna support) or it is the lerna not supporting inquirer prompt question.

**Comment by SBoudrias** [comment]
This is very likely an issue with Lerna. [Similar to this one](https://github.com/lerna/lerna/issues/3214)

Inquirer needs the stdin/stdout to be inherited and being a TTY (interactive) to work. You'd have a similar issue if [using a pre-commit hook for example](https://github.com/SBoudrias/Inquirer.js#using-as-pre-commitgit-hooks-or-scripts); or running with nodemon.

There might be an option to run Lerna with the inherited stdio; or it might be something the tool needs to add.
