### ISSUE TITLE
Compatibility with commonjs

### ISSUE THREAD

**Issue by gabriel-logan** [SBoudrias/Inquirer.js#1324]
![image](https://github.com/SBoudrias/Inquirer.js/assets/96627244/47bfd422-1d29-4404-b9d7-add0d7461721)

Please make a version that supports commonJs, I use typescript in a specific project where I can only use commonjs, that's not cool...

**Comment by gabriel-logan** [comment]
If you are using typescript to produce, I would give you a tip, send it to npm using

     "module": "CommonJS",


in tsconfig because this way it transpiles to CommonJS and whoever uses your code can use it either via import or via require

the way you did it, only import export works

**Comment by gabriel-logan** [comment]
If you are using typescript to produce, I would give you a tip, send it to npm using

     "module": "CommonJS",


in tsconfig because this way it transpiles to CommonJS and whoever uses your code can use it either via import or via require

the way you did it, only import export works

**Comment by SBoudrias** [comment]
Please refer to the [installation guide](https://github.com/SBoudrias/Inquirer.js/tree/master/packages/inquirer#installation). Both version 9 (esm) and 8 (cjs) are in maintenance mode.

Recommendation is to migrate to the new API; see #1214

**Comment by gabriel-logan** [comment]
Ok, I get my answer 

![image](https://github.com/SBoudrias/Inquirer.js/assets/96627244/1433ab51-5662-42e1-b0a1-3d68741b780a)

I just dont know why not use commonJs too.

**Comment by SBoudrias** [comment]
The new API supports both (it's in typescript making it easy)
