### ISSUE TITLE
Readme: The allowEmail example encourages needless use of "let"

### ISSUE THREAD

**Issue by mk-pmb** [SBoudrias/Inquirer.js#1331]
```javascript
// Current readme uses let:
let email;
if (allowEmail) {
  email = await input({ message: 'What is your email address' });
}

// Where it would be perfectly feasible to use const:
const email = (allowEmail && await input({ message: 'What is your email address' }));
```

**Comment by SBoudrias** [comment]
Hi, you're completely free to write it that way in your own code. But for the documentation, I want to keep it as-is for those 2 reasons:

1. The logic is easier to follow, replicate and expand upon. It doesn't rely on "advanced" or a terse syntax of JS that can confuse less experienced readers. And the example with `if` is easier to extend to cover other form of logic.
2. The results is not the same. `const email` in your example will be either `false` or `string`. In the documentation it ends up being `undefined` or `string` (which I would tend to prefer type wise.)
