### ISSUE TITLE
Select hanging on choose option

### ISSUE THREAD

**Issue by andyjessop** [SBoudrias/Inquirer.js#1339]
Here's my code:

```ts
home();

async function home() {
  const answer: Action = await select({
    choices: [
      {
        description: 'Create a note and embed it',
        name: 'Create Note',
        value: 'ADD_NOTE',
      },
      {
        description: 'Fetch similar items',
        name: 'Fetch Similar Items',
        value: 'FETCH_SIMILAR_ITEMS',
      },
      {
        description: 'Query Notes',
        name: 'Query Notes',
        value: 'QUERY',
      },
    ],
    message: 'Select an action',
  });

  const answer2 = await input({ message: 'Enter path to note' });

  console.log(answer, answer2);
}
```

After selecting "Create Note", I get the following:

<img width="326" alt="Screenshot 2023-12-07 at 17 41 35" src="https://github.com/SBoudrias/Inquirer.js/assets/1304307/28f4beff-b12b-4de8-83ae-d722fa026f40">

I would expect it to go to the next prompt, but it hangs. Note that if I type something in (it's hidden), and hit enter, I then see both outputs:

<img width="260" alt="Screenshot 2023-12-07 at 17 42 52" src="https://github.com/SBoudrias/Inquirer.js/assets/1304307/7ea2ebb0-df76-4418-8940-f9cfe5daf113">

**Comment by SBoudrias** [comment]
Hi, did you test it on Node?

This looks like a bun bug. You should report this issue over there.
