### ISSUE TITLE
Use value from list prompt in message for next question?

### ISSUE THREAD

**Issue by paul-uz** [SBoudrias/Inquirer.js#1343]
I have a inquirer prompt with 2 questions, a list and then a choice. I want to use the selected value form the list in the message for the choice question.

Is this possible?

**Comment by SBoudrias** [comment]
Hi Paul, this should be possible. Here's some pseudo code showing an approach:

```js
const answer1 = await input({ ... });

const answer2 = await select({
    message: `... ${answer1} ...`,
	choices: [...]
});
```

**Comment by paul-uz** [comment]
I'm using `inquirer.prompt()`

**Comment by SBoudrias** [comment]
It'd be the same idea, but slightly more verbose:

```js
const { answer1 } = await inquirer.prompt([
    { name: 'answer1', ... }
]);

const { answer2 } = await inquirer.prompt([
    { name: 'answer2', message: `... ${answer1} ...`, ... }
]);
```
