### ISSUE TITLE
A null shows in the prompt using mqtt.js

### ISSUE THREAD

**Issue by muka** [SBoudrias/Inquirer.js#1346]
I found a wired issue which seems to be caused by [mqtt.js](https://github.com/mqttjs/MQTT.js) using typescript

```
npm i mqtt inquirer@8.2.6
```

```typescript
    const askMessage = () => {
      return feature.prompt([
        {
          name: 'message',
          message: 'Your message',
          type: 'input',
        },
      ]);
    };

await askMessage()
```
![image](https://github.com/SBoudrias/Inquirer.js/assets/1021269/1a13ddbc-36f9-4c1d-a910-a807bdb3f019)

```typescript
const client = mqtt.connect('mqtt://test.mosquitto.org')
await askMessage()
```

![image](https://github.com/SBoudrias/Inquirer.js/assets/1021269/99f99196-cd65-4802-9430-9cf157b28aa9)

If `mqtt.connect ` is called, the inquirer prompt will show a `null` and a new line. Any suggestion on why this may be happening ?

**Comment by SBoudrias** [comment]
Ohh that's weird...

It looks like mqtt is either sending events/data to the `process.stdin` or is messing with the readline.

I don't see any obvious note on their README, but I'd check for option to either mute the logging or give the tool a different stream to send their writes to.

Waiting for the connection to complete could also help 🤷🏻
