### ISSUE TITLE
inquirer.js in windows

### ISSUE THREAD

**Issue by Bellamy01** [SBoudrias/Inquirer.js#1347]
Unable to toggle a list of options in the terminal in my CLI though the application seems to work on Linux systems.

**Comment by SBoudrias** [comment]
Windows have a few non-tty (non interactive) command line programs. Make sure you use one that is (git prompt is one that isn't.)

And you can see the readme if you're not running inquirer directly. In those cases you need to pass the right stdio options (like if running with nodemon and such.)
