### ISSUE TITLE
Why is pressing enter needed for one-key shortcuts in an expand? 

### ISSUE THREAD

**Issue by hansvb** [SBoudrias/Inquirer.js#135]
Expand:
- could be more efficient (less keystrokes for user) if `<enter>` was not needed
- needs an option `showHelp` (defaults to `false`)
- perhaps needs an option `browsable` so that it can be a _list-expand-hybrid_

I would like to use inquirer for an application where main menu-items have one-key interface **and** are selectable with arrow-keys. (Keys `j` and `k` should probably not be allowed!)

**Comment by GeorgeGkas** [comment]
@SBoudrias this issue is inactive for years. As you have correctly replied, we can use number keys to select answers in list and checkbox types. Can you close this issue?
