### ISSUE TITLE
Typescript intellisense auto-completion is broken in Inquirer v9

### ISSUE THREAD

**Issue by lightzane** [SBoudrias/Inquirer.js#1357]
Even after installing the `npm i @types/inquirer -D` and the `module: "es6|esnext"`  is set in `tsconfig.json`, the intellisense or auto-completion is broken for `Inquirer v9`. 

![image](https://github.com/SBoudrias/Inquirer.js/assets/8446145/3782a910-f758-41d9-8748-e266597f2322)

### package.json

```json
{
  "dependencies": {
    "inquirer": "^9.2.13",
  },
  "devDependencies": {
    "@types/inquirer": "^9.0.7",
    "typescript": "^5.3.3"
  }
}
```

### tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "es6", 
    "outDir": "./bin",  
    "removeComments": true,   
    "esModuleInterop": true,   
    "forceConsistentCasingInFileNames": true, 
    "strict": true,
    "skipLibCheck": true  
  }
}
```

But upon testing to set `module: commonjs`, the auto-completion is working fine with Typescript

![image](https://github.com/SBoudrias/Inquirer.js/assets/8446145/72d17021-fd6a-49c2-8d65-b90ed5fc0e07)

### In tsconfig.json - we cannot set the module to commonjs since Inquirer v9 are already using esm modules

**Comment by lightzane** [comment]
I used this workaround...

### tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs", // for development, but build will use 'es6', see package.json > scripts > build
    "outDir": "./bin",
    "removeComments": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

### package.json
```json
{
    "scripts": {
        "build": "tsc --module es6",
    }
}
```

**Comment by SBoudrias** [comment]
Hi, we're not maintaining types for the `inquirer` packages (those are maintained by the DefinitivelyType community.) This is because this package is depreciated in favour of our new lighter weight implementation (but a breaking change, not a drop-in.)

If you're just getting started, or not calling `inquirer.prompt` often, I really encourage you to look into the new Inquirer - #1214.
