### ISSUE TITLE
Do not show the selected option again / closes automatically

### ISSUE THREAD

**Issue by Bes-js** [SBoudrias/Inquirer.js#1359]
I use list and it works in a function called mainMenu. I run this function at startup. After selecting an action from it, it sends it to another list section and produces a list to return. After returning from here, I run the mainMenu function again, but when I select the same option, it closes for no reason. The solution to this is are there?

**Comment by SBoudrias** [comment]
Hi, this is unlikely an issue coming from inquirer. Do you have code example?

**Comment by Bes-js** [comment]
```js
async function mainMenu(){

    child_process.execSync('cls');

    await db.prepare('CREATE TABLE IF NOT EXISTS lang (value TEXT)').run();
   
    var langData = await db.prepare('SELECT * FROM lang').get();
    if(langData)lang.setLang(langData.value);
    if(!langData){
    var newLang = await setNewLanguage();
    await db.prepare('INSERT INTO lang (value) VALUES (?) ').run(newLang);
    lang.setLang(newLang);
    };

    var mainMenu = await select({
    message: lang.getText('main_menu'),
    theme:{ icon: { cursor: '=>' }},
    loop: false,
    choices: getChoices(arr)
    });

    import(`./events/${mainMenu}.mjs`);
   // arr.push(mainMenu);
    
};

```

```js
import { returnMainMenu, lang, setNewLanguage } from '../cli.js';
import db from '../services/database.js';
import child_process from 'child_process';


const select_new_lang = async () => {
var newLang = await setNewLanguage();
await db.prepare('UPDATE lang SET value = ? ').run(newLang);
lang.setLang(newLang);
child_process.execSync('cls');
return returnMainMenu();
};
select_new_lang();
```

**Comment by Bes-js** [comment]
https://github.com/SBoudrias/Inquirer.js/assets/89789101/78b76f18-3918-44cd-9c4e-015eb8ae10b2

**Comment by Bes-js** [comment]
@SBoudrias

**Comment by SBoudrias** [comment]
Hi @Bes-js, there's a lot going on there.

What might help you is to simplify the case. Only make a recursive prompt with inquirer - see it works. Then add pieces by pieces and you'll likely find out where it breaks.

**Comment by Bes-js** [comment]
When I opened a new project and tried just select from scratch, the same problem occurred again.

**Comment by Bes-js** [comment]
It looks like a problem with the package, but when I tried such things in other languages it didn't cause any problems.

**Comment by SBoudrias** [comment]
Can you share your new project reproduction so I can run it?
