### ISSUE TITLE
Don't reject with standard error on exit signal 

### ISSUE THREAD

**Issue by mondeja** [SBoudrias/Inquirer.js#1368]
I'm trying to handle a SIGINT signal (tipically pressing `Ctrl^C`) on a script but this raises a standard error:

https://github.com/SBoudrias/Inquirer.js/blob/c91196e66689cfc05e9237763e6f95f3eb5342a1/packages/core/src/lib/create-prompt.mts#L39

I would like to catch a custom error instead. I know that I can use something like checking the error message, but that sounds like crazy to me, because it could lead to catch other errors or break if another released version changes this message.

Please, could you throw a [custom error](https://stackoverflow.com/questions/783818/how-do-i-create-a-custom-error-in-javascript) that I could be able to properly catch to exit when SIGINT is received?

**Comment by SBoudrias** [comment]
Hey, that's a good call out! Thanks for raising the issue.

I've made a first draft PR to address that issue. It'd be great if you could review the code and make sure that would work for you!

**Comment by SBoudrias** [comment]
Latest versions include the changes! Thanks again

**Comment by mondeja** [comment]
Great. Thank you!
