### ISSUE TITLE
Any way to cast the input?

### ISSUE THREAD

**Issue by ValYouW** [SBoudrias/Inquirer.js#1383]
In the old `inquirer` there was a Number input, Im trying to do something similar with the new `@inquirer/prompts` and wonder if there is a way to cast the value before it gets to the `validate` method. Any idea?
I know I can do the cast after calling `await input` but:
1) I think it is nicer to have all the input-related code in one place (the input options)
2) Currently the `validate` method gets a string and I need to "parse" it there as well.

Thx.

**Comment by SBoudrias** [comment]
Hey, I'm not against re-adding a good number prompt if you want to send a PR! I didn't reimplement as I found the previous UX bad, and didn't care much about it.

With the input prompt, for now I would do something:

```js
  const answer = parseInt(
    await input({
      message: 'Provide a number:',
      validate: (value) => !Number.isNaN(value) || 'You must provide a number',
    }),
    10,
  );
```

**Comment by ValYouW** [comment]
Yes, workarounds are possible but less nicer than the old number prompt.
My validate really needs a number to check it is within range etc. I know it's still doable but... 
I wonder whether a "cast"/"filter" method would be a better addition to the api, that way if someone wants a number he may cast the string to number, if someone wants a date she may cast the string to date, all before the validate stage, and the result would also be the result of the "cast".

**Comment by ValYouW** [comment]
I didn't find the time to get to it so I don't want to leave this issue open...

**Comment by SBoudrias** [comment]
There's sometime other folks coming to the repo looking for ways to contribute and start with open source. This IMO is a good first issue for many - and worse case I might get to it someday. Let's keep it open.

**Comment by ValYouW** [comment]
Sure! I just didn't want to add noise for you... 
Honestly, I wanted to work on it but the repo is too complex, first it's quite huge (1gb) and clone was too slow, then "npm install" didn't work for some reason (eslint issue), also lerna and typescript , too much for a vanilla node.js guy like me :)
Maybe I'll give it a other try one day.

**Comment by SBoudrias** [comment]
Did you start with https://github.com/SBoudrias/Inquirer.js/blob/main/CONTRIBUTING.md ?

**Comment by ValYouW** [comment]
Yes, though I use npm and not yarn.

**Comment by ValYouW** [comment]
Gave it a try with PR #1448
