### ISSUE TITLE
stdout trim issue in tests

### ISSUE THREAD

**Issue by Bartheleway** [SBoudrias/Inquirer.js#1385]
Hi,

I'm trying to write a plugin for inquirer and while writing tests I found a weird issue.

All my tests are running fine on Github actions but fails when running on my computer (Windows).

It seems that long lines are truncated to 80 caracters and if ends with a space are truncated in Github actions but not in Windows Powershell.

New test in `input.test.mts`
```ts
it('handle long question', async () => {
  const { answer, events, getScreen } = await render(input, {
    message: 'This is a very_very_very_very_very_very_very_very_very_very_very_very_very long question',
  });

  expect(getScreen()).toMatchInlineSnapshot([
    '"? This is a very_very_very_very_very_very_very_very_very_very_very_very_very',
    'long question"'
  ].join('\n'));
});
```

How should I workaround that?

Best regards,
Barthélemy

**Comment by SBoudrias** [comment]
Ohhh interesting. My educated guess is that [`cli-width`](https://github.com/knownasilya/cli-width/blob/master/index.js) returns a different value between windows/linux in this context.

**Comment by SBoudrias** [comment]
I'm not sure how we could automatically make this consistent from `@inquirer/testing`. Mocks are unlikely to work since they're now test framework agnostic, and `CLI_WIDTH` env variable would need to be set from outside.

At the very least, will add a note to the documentation.

**Comment by Bartheleway** [comment]
I changed the issue after releasing it was just a trim issue more than a width issue.
