### ISSUE TITLE
Support unicode for Windows

### ISSUE THREAD

**Issue by jeffsee55** [SBoudrias/Inquirer.js#1386]
Windows supports unicode characters but the figures library that determines this is [outdated](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/select/package.json#L61). I suspect this is intentional because later versions of figures only support ESM.

It would be nice if Windows users got unicode, though I'm not sure what the best path forward would be if dropping CJS support is not an option.

**Comment by SBoudrias** [comment]
I'm not against dropping `figures` and/or inlining core content of the library.

**Comment by jeffsee55** [comment]
Great, I'm happy to take a stab at it. Would you prefer to inline it into it's own package within the monorepo or just put it into `@inquirer/core`?

**Comment by SBoudrias** [comment]
It's own package, like `@inquirer/figures` (basically a simple fork to support cjs), would be best.

If we didn't use figures in multiple packages, then I'd prefer to inline it in those packages. But that'd be a lot of noise today since it's used often.
