### ISSUE TITLE
NodeJS inquirer prompt showing question twice. Once normally and again after answering it

### ISSUE THREAD

**Issue by BENthedude425** [SBoudrias/Inquirer.js#1412]
![image](https://github.com/SBoudrias/Inquirer.js/assets/52467828/e0fe1254-a22c-4ec9-bef9-b205f2718ca4)
![image](https://github.com/SBoudrias/Inquirer.js/assets/52467828/ac6f60f3-f212-413a-8466-5ea3d9639b2a)

Above is the code i am using as well as the terminal output. As you can see the question in the prompt is printed again once more after answering it. I have searched everywhere and it seems only one person I could find had the same problem that was fixed by removing  some of the imports / requirements, to test this I created a new script "test.js" and ran with nodemon (nothing changed when doing this and i still have the issue).

Now I am very confused and stuck with an issue I cant find the answer for, any help / suggestions are appreciated!

**Comment by SBoudrias** [comment]
Do you have the same issue [...]

1. With a different terminal app?
2. Using `node` instead of `nodemon`?

**Comment by BENthedude425** [comment]
@SBoudrias it does happen in all consoles when using nodemon, however using node fixes the issue. Do you have a suggestion to get this fixed while using nodemon or is this something I might have to suck up and deal with?

**Comment by SBoudrias** [comment]
Given that information, I'd go ask folks over at nodemon. Maybe they'll have an idea or can fix the issue.

**Comment by BENthedude425** [comment]
@SBoudrias okay I will give that a try if another hour of trying doesn't fix anything Thanks for the help!
