### ISSUE TITLE
`.yarn/cache` is committed?

### ISSUE THREAD

**Issue by smeijer** [SBoudrias/Inquirer.js#1433]
Is there a reason why the yarn cache is committed to this repo? It makes this repo massive—it's currently ~ 1GB in size. You might want to remove it and even remove it from history entirely.

https://github.com/SBoudrias/Inquirer.js/tree/main/.yarn/cache

**Comment by SBoudrias** [comment]
Yeah, it makes CI much faster (0 install) and allows to switch WIP branches when not connected to the internet (which has been useful for me).

We can cleanup the history when/if this becomes an issue. But FYI, we're running this setup on a monorepo with 400+ engineers and didn't really ran into major issues regarding size or clone time.

**Comment by smeijer** [comment]
Given that it's intended, I'm closing this.

**Comment by OnkelTem** [comment]
First, let me say thanks for the great tool @SBoudrias!

To the issue. Pushing caches into git is a new strategy for me. In our company we optimize CI using tools provided by the platform, e.g. caches or artifacts (depending on the scope). 

The current size is 2.3GiB now and it's growing. Honestly, it took for me half an hour to just fetch the repo. Granted Github speed degrades constantly it can turn into a real issue soon for many people soon. So I'd say _it's already an issue_. Would be great to see it reduced down to code.

But that's just my few cents, I'm not insisting on anything as I'm not a contributor. Just was delayed in my job by 30 minutes.
