### ISSUE TITLE
Could you provide the capabilty to fuzzy filter a list of items to select?

### ISSUE THREAD

**Issue by AbigailDeng** [SBoudrias/Inquirer.js#1445]
If we use @inquirer/select we can't do filter. So we want the ability of filtering a list of items to select just like [inquirer-search-list](https://github.com/robin-rpr/inquirer-search-list)

**Comment by SBoudrias** [comment]
Hi, the select input will do search if you type alpha-numerical keys (just like the native select HTML element.)

For more complex search, we're leaving it to community prompts for now since it usually comes with more complex and different requirements.

**Comment by SBoudrias** [comment]
Also, of interest, proposal to add a search prompt to the core https://github.com/SBoudrias/Inquirer.js/pull/1479

**Comment by moltar** [comment]
> select input will do search if you type alpha-numerical keys (just like the native select HTML element.)

Which version is this added in? I am not seeing this behaviour on the latest version.
