### ISSUE TITLE
`@inquirer/select`: prompt closes after timeout on `CTRL+C` or `CTRL+D`

### ISSUE THREAD

**Issue by matteosacchetto** [SBoudrias/Inquirer.js#1454]
When terminating the `@inquirer/select` prompt with `CTRL+C` or `CTRL+D` it properly throws the Error `User force closed the prompt with 0 null`
Though, it does so after the timeout `searchTimeoutRef` is expired.

[Example reproduction](https://stackblitz.com/edit/stackblitz-starters-8duhpc?file=index.mjs)
In this reproduction, try running `node index.mjs` and stop it with `CTRL+C` or `CTRL+D`. To compare the behavior, I also added the `index2.mjs` which uses `@inquirer/input`

By debugging the behavior, I noticed that on `CTRL+C` or `CTRL+D`, the `useKeypress` callback is called, the timeout is cleared and then, since the key combination does not match any of the `if`/`else if` statements, it enters the `else` condition. Here the timeout is created again, and after that timeout expires the Error is thrown.

https://github.com/SBoudrias/Inquirer.js/blob/ac687691f6847816e89a80a589e82738bc4c13b0/packages/select/src/index.mts#L124-L142

To address it, the simplest solution would be to change the `else` statement to an `else if` checking that it does not match `CTRL+C` or `CTRL+D`. Though, other strategies may be used.

Once we agree on a strategy, I am willing to open a PR to address this. 

Tested version:
`@inquirer/select: 2.3.8`

**Comment by SBoudrias** [comment]
Interesting... I think a more universal solution would be to modify `useKeypress` inside the core itself to ignore `CTRL+C` and `CTRL+D` (and macOS/linux equivalent.) Otherwise that'll be a weird edge cases for any prompts forgetting to check for that code.

I wonder if you'd encounter the same issue with a prompt with an async validator? (where there's a timeout to animate the loading animation.)

**Comment by matteosacchetto** [comment]
While that can help, I do not think it fully addresses the problem

The reason being that, if the timeout is started and then `CTRL+C` or `D` is clicked, it still waits for the whole timeout before closing the prompt and throwing the error even if the `useKeypress` is not triggered by that key combination.

I think that a solution could be, on top of ignoring those key combinations, to also provide some kind of hook/callback which gets called when the prompt exit condition is triggered. This would allow for resource cleanup, like deleting the timeout.

**Comment by SBoudrias** [comment]
Ah you're right!

I think as of now cleanups from useEffect will trigger on force exit 🤔  - e.g `useEffect(() => () => cleanup(), []);`. I'm not 100% sure, so we'd need to validate this (and if not, I'm pretty sure it should!)

I think we can keep this as-is in the core, and only use this inside `select`. WDYT?

**Comment by matteosacchetto** [comment]
I tried with the `useEffect` method, and I can confirm that it gets called on exit. Though it seems that the exit handler only gets called after the timeout is expired
https://github.com/SBoudrias/Inquirer.js/blob/85a3d400014280c5cdae03f6de63d2256ea6b2df/packages/core/src/lib/create-prompt.mts#L38-L43

I am still investigating the behavior to understand why it's behaving in this way

**Comment by matteosacchetto** [comment]
I had some time to look into this, and I was able to create a [small reproduction](https://stackblitz.com/edit/stackblitz-starters-icbrum?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=close.mjs,no-close.mjs&title=node.new%20Starter) of what is happening under the hood.

In the provided example, I simply used the Node.js `readline` and the `signal-exit` package (which is currently used in `@inquirer/core`). You will find there two different examples:
- `no-close.mjs`: this uses a simple setup similar to `@inquirer/select`, where on `keypress` refreshes the timeout. If you run this (`npm run no-close`) and begin to type, you will see printed out the events. If you then press `CTRL+C`/`CMD+C` it will print the event, wait the timeout and then exit
- `close.mjs`: this adds an event listener on the `close` event of `readline`, which will call a callback function with `setImmediate`. This is done to make sure that it is called after the `keypress` event. In this case, when you run it (`npm run close`) type and press `CTRL+C`/`CMD+C` you can see that the timeout is correctly deleted by this event listener and the prompt then terminates immediately

I have not yet looked into the reasons why `onExit` is called only after the timeout expires, though. Anyway, I think a consistent solution to handle issues similar to the one shown here could be to provide some kind of hook which exposes a way to set a callback on the `close` event of `readline`. Or to provide a way to access the `readline`, to manually set the event handler, so that when `readline` is closed, we can process it correctly and clear any pending resource.

What do you think?

**Comment by SBoudrias** [comment]
I'm not against fixing the specific prompt by canceling the timeout with `useEffect` cleanup function.

**Comment by matteosacchetto** [comment]
Let me try to clarify the issue a bit better.
I tried to use the `useEffect` cleanup function to address this specific issue, though the thing is that it didn't work.

After investigating, I understood that the `useEffect` cleanup function is called by the `onExit` function, which is called inside the `onSignalExit` callback function. I report the code below for reference
https://github.com/SBoudrias/Inquirer.js/blob/85a3d400014280c5cdae03f6de63d2256ea6b2df/packages/core/src/lib/create-prompt.mts#L38-L43

The `onSignalExit` method is just the `onExit` method of the `signal-exit` package renamed. And as I was trying to show in reproduction linked in the previous message, this method only gets called after the timeout is expired.

So, what is happening is that, while it is true that the cleanup method of `useEffect` gets called once we reach the `onSignalExit` handler, this handler only gets called after the timeout inside the prompt is expired. This means that the cleanup function of the `useEffect` which should clear the timeout only gets called after the timeout is expired, thus having no effect.

I do understand your concerns regarding adding new utility functions, and I do agree on trying to keep things simple. So if you have any other idea on how we could address it, I am open to investigate them 😄

**Comment by SBoudrias** [comment]
Ah sorry, loosing context over time on this issue.

Did you look into signal-exit code. I wonder if the wait for the timers come from there 🤔

**Comment by matteosacchetto** [comment]
Ok, so I think I figured out what is happening.

When we press the key combination `CTRL+C` it will trigger two events: the `keypress` event of the `rl.input` object and the [`close` event](https://nodejs.org/api/readline.html#event-close) of the `rl` object. The `keypress` listener will be invoked and will recreate the timer. Instead, since on the `rl` we do not set any listener, it simply closes the instance and releases the terminal from reading from `stdin`

After such a thing happens, the `rl` instance is closed so `node` could potentially terminate, but since the is still a timeout pending, it will wait for it to expire before exiting. Once it expires, node is ready to exit and `onSignalExit` is triggered, as this is one of the cases they state in the documentation (I think that library does something like `process.on('exit', fn)`)

At this point the `onExit` function, which takes care of cleaning up hooks, will be invoked, but it won't have any effect on the timer as it will be called too late.

I think we could probably address this by not adding any additional utility function/hook, but by slightly changing the `createPrompt` function to clean up hooks when the `close` event is triggered (Note though that `close` is triggered before `keypress`).
This way we could in general rely on the effect cleanup function, as you suggested, to address similar issues.

What do you think?

**Comment by SBoudrias** [comment]
@matteosacchetto sounds promising to me, let's try it out 😄

**Comment by andrevmatos** [comment]
I'm still experiencing this issue on latest `@inquirer/prompts` and `@inquirer/select` from npmjs. Is there a way to get the fixed version in my CLI? Thank you for the amazing tool!

**Comment by SBoudrias** [comment]
Can you make sure you're on `@inquirer/prompts@5.3.6` or newer? That's the release that contained this fix.

**Comment by andrevmatos** [comment]
Just checked, the added code to `select` is present in the version I have here, but it seems it didn't fix the issue: inside a `select` prompt, if I press `Ctrl+C`, the console hangs, any keypress starts showing as escape characters, and error is only printed when timeout occurs, several seconds later.

Maybe worth noting I have a couple of unrelated class instances with listeners on the background, but I've set cleanup hooks to close the connections upon error bubble-up. If my async functions (including those which call inquirer) just errors or throws for any reason, the rejections bubble-up and cleanups are properly called, making node exit cleanly almost immediately. Maybe inquirer is trying to exit somehow else? If the `await select` call just cleanup after itself and reject, the app should quit cleanly.

**Comment by SBoudrias** [comment]
On ctrl-c Inquirer throws an error, cleanup it's readline instance and that's it.

Sounds like you have a fairly complex setup and given the delays you're seeing this is unlikely to be the select 2sec keypress timeout.

**Comment by andrevmatos** [comment]
My `minimal.mjs` repro: you should just need latest `@inquirer/prompts` and `ethers`;
If you select an option, the select promise resolves and everything exits cleanly; if you Ctrl+C in the prompt, the `ExitPromptError` does reject that promise, but just several seconds later, and the interface stays frozen in the meantime.

```js
import { select } from '@inquirer/prompts'
import { WebSocketProvider } from 'ethers'

const cleanup: (() => Promise<unknown> | void)[] = []

async function main() {
  const provider = new WebSocketProvider('wss://ethereum-sepolia-rpc.publicnode.com')
  cleanup.push(() => provider.destroy())
  const answer = await select({
    message: 'Which is the best number?',
    choices: [
      { value: 1, name: 'One' },
      { value: 2, name: 'Two' },
      { value: 3, name: 'Three' },
    ]
  })
  console.log('Your choice:', answer)
}

main().finally(async () => {
  for (const c of cleanup.reverse()) {
    await c()
  }
})
```
