### ISSUE TITLE
Bump `yoctocolors-cjs` to `2.1.2` for Deno compatibility

### ISSUE THREAD

**Issue by bombillazo** [SBoudrias/Inquirer.js#1459]
Due to the lack of implementation of the tty library in yoctocolors, a patch was pushed to allow graceful error handling for the library with Deno. This package uses the yoctocolors package with the old version that causes inquerer to crash in Deno when using the latest version (since the move to yoctocolors)

**Comment by bombillazo** [comment]
Alos, using `yoctocolors` will effectively make colors unusable in Deno until [this issue](https://github.com/denoland/deno/issues/24407) in the Deno repo is resolved. The previous color library worked for Deno.

**Comment by SBoudrias** [comment]
Do you also have a ticket on yoctocolor repo?

**Comment by bombillazo** [comment]
I'm sorry for not getting back to you sooner!

I'm using `@inquirer/prompts,` and it's worked great so far. I haven't had any issues, but now the colors in the terminal don't work when running with Deno since `yoctocolors` uses a color implementation that Deno does not currently support. It used to work when you were using `chalk` though.

**Comment by bombillazo** [comment]
Hey, @SBoudrias, sorry for not getting back to you sooner!

I'm using `@inquirer/prompts,` and it's worked great so far. I haven't had any issues, but now the colors in the terminal don't work when running with Deno since `yoctocolors` uses a color implementation that Deno does not currently support. It used to work when you were using `chalk` though.

**Comment by SBoudrias** [comment]
That's unfortunate, but given the population of Node vs Deno users, I think the decision to switch our color library does bring more value to more users. And we see Deno's working on filling the gap with the `tty` module, so sounds like it's a matter of months maybe? I think that's fair enough from the point of view of this library.
