### ISSUE TITLE
High Severity ReDoS vulnerability in ansi-regex

### ISSUE THREAD

**Issue by tonypapousek** [SBoudrias/Inquirer.js#1467]
When running this through Snyk OSS, it reports:

[Regular Expression Denial of Service (ReDoS) [High Severity]](https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908) in ansi-regex@5.0.0
    introduced by @inquirer/prompts@5.1.2 > @inquirer/checkbox@2.3.10 > @inquirer/core@9.0.2 > wrap-ansi@6.2.0 > string-width@4.2.0 > strip-ansi@6.0.0 > ansi-regex@5.0.0
  This issue was fixed in versions: 3.0.1, 4.1.1, 5.0.1, 6.0.1
  
Bumping `wrap-ansi` should fix this, though it looks like that package converted to pure ESM in v8.0.0, if that matters.

**Comment by SBoudrias** [comment]
Hi, Inquirer doesn't force versions of transitive dependencies. You need to update them in your own lock files. I see a fix is already shipped under a compatible version.
