### ISSUE TITLE
Date prompt

### ISSUE THREAD

**Issue by aminnairi** [SBoudrias/Inquirer.js#1470]
It would be awesome to be able to select a date with some keyboard shortcuts to go from month to month, year, & dates.

Is there any plan on supporting it? 

If not, are there any resource I could use to have or implement this?

**Comment by SBoudrias** [comment]
Hi, I don't know of any such prompts as of now. You could consider [writing your own](https://github.com/SBoudrias/Inquirer.js#create-your-own-prompts)!

**Comment by aminnairi** [comment]
Thank you for your quick response.

Are pull request welcomed?

**Comment by SBoudrias** [comment]
Usually yes, but I'm not sure we need a date prompt in the default list. However I'd be happy to link to your prompt from the package Readme!
