### ISSUE TITLE
New set implementation errors when overriding a boolean with an object

### ISSUE THREAD

**Issue by andrewmcgivery** [SBoudrias/Inquirer.js#1473]
# Problem Description
In `9.3.1`, lodash's `_set` method was replaced with a direct implementation. However, this did cause a breaking change.

Consider this example:

```
{
    type: "confirm",
    name: "foo",
    message: "foo?",
    default: true,
  },
  {
    type: "list",
    name: "foo.bar",
    message: "bar?",
    default: 'hello',
    choices: ['hello', 'world'],
    when: (currentAnswers) => currentAnswers.foo,
  },
```

In previous versions, the first question would result in `{foo: true}` and then the second question would override this to be `{foo: { bar: 'hello}}` because it would override the boolean with an object.

In `9.3.1` and later versions, this now throws an error:

```
Cannot create property 'bar' on boolean 'true'
```

# Expected versus Actual

Expected: Boolean answers should be replaced with an object when setting subproperties
Actual: An error is thrown

# Suggested fix

I use this in my local `set` function:

```
if (i !== pathArray.length - 1 && typeof acc[key] === "boolean") {
  acc[key] = {};
}
```

# Alternatives

Because `confirm` does not have a `filter` function where I could override the answer from a boolean to a object myself, this doesn't leave a lot of options other than completely rewriting the entire program to do one prompt at a time instead of passing an array of prompts.

Would prefer to have this small fix to return it back to the original functionality if possible. :)

**Comment by SBoudrias** [comment]
Hey, happy to review a PR fixing this on latest. And I'll backport it on a v9 release if it helps.

**Comment by andrewmcgivery** [comment]
Awesome. I'll take a look at this probably later this week!

**Comment by SBoudrias** [comment]
`inquirer@9.3.6` is out
