### ISSUE TITLE
Program cannot be killed on powershell using Ctrl+c

### ISSUE THREAD

**Issue by txtyash** [SBoudrias/Inquirer.js#1478]
# Program cannot be killed on powershell using Ctrl+C

## Steps to recreate

1. Create a js file (index.js):
```js
import { input } from '@inquirer/prompts';

const branchName = await input({ message: `Enter your name: `, transformer: (input) => input.trim() });
console.log(branchName);
```

2. Run the file using bun js:
`> bun run index.js`

3. Attempt to kill the program by pressing `Ctrl+C`
    **Outcome:** Program does not terminate

**Comment by SBoudrias** [comment]
Does that only happens with Bun?

If so, there's not much I can do for you.

**Comment by mohas** [comment]
this is indeed an issue with bun, in the meantime, you can do this:

before using the inquirer setup a special listen for ctrl-c in windows:

```js
// put this somewhere in your code prior to use all inquirer prompts
if (process.platform === 'win32') {
    require('node:readline').createInterface({
        input: process.stdin,
        output: process.stdout,
    }).on('SIGINT', () => {
        process.emit('SIGINT')
    })
}
```
