### ISSUE TITLE
prompt list returns undefined

### ISSUE THREAD

**Issue by rafipiccolo** [SBoudrias/Inquirer.js#1482]
```
import inquirer from 'inquirer';

const allfiles = [
    {name: 'a', content: 'a'},
    {name: 'b', content: 'b'},
    {name: 'c', content: 'c'},
];
const answers = await inquirer.prompt([
    {
        type: 'list',
        name: 'answer',
        message: 'merge files ? (select source)',
        choices: allfiles,
    },
]);

console.log(answers);
// { answer: undefined }
```

**Comment by rafipiccolo** [comment]
worked with 9.3.5 but not since 10.0.0
is there a new way ? i didnt see anything in release comments

**Comment by SBoudrias** [comment]
The issue is the choice list doesn't provide a value attribute.

I'll document it, I wasn't aware of that previous behavior. (And I think I'll add a validation step so it's the easy to spot)

**Comment by rafipiccolo** [comment]
thx for your clarification, feel free to close as i have quit using the object form.
