### ISSUE TITLE
Using a separator makes the pointer change position

### ISSUE THREAD

**Issue by sindresorhus** [SBoudrias/Inquirer.js#149]
Not sure whether it's intended or not, but looks wrong.

![2014-08-15 22_48_55](https://cloud.githubusercontent.com/assets/170270/3938750/9b9d26ec-24bd-11e4-9d00-45aa4cf0b158.gif)

Relevant code:
https://github.com/yeoman/yo/blob/ec829c3126fdc192a61833f0e2041799c4713a23/yoyo.js#L380-L384

**Comment by sindresorhus** [comment]
@SBoudrias

**Comment by SBoudrias** [comment]
This is effectively not intended.

**Comment by dantman** [comment]
This is a severe problem for some users of inquirer like [npm-check](https://github.com/dylang/npm-check). When multiple separators are used this bug can stack resulting in the cursor completely leaving the visible area.

![aug 18 2015 11 56](https://cloud.githubusercontent.com/assets/53399/9339680/485b7b46-45a0-11e5-8d81-905cbdb58309.gif)

**Comment by dantman** [comment]
This bug is probably related to this line:

> https://github.com/SBoudrias/Inquirer.js/blob/master/lib/prompts/list.js#L97
> ```js
> message += "\n" + this.paginator.paginate(choicesStr, this.selected);
> ```

The lines of choicesStr includes the separators. But the active integer `this.selected` does not account for separators.

**Comment by Froren** [comment]
Doesn't seem like this is an issue anymore.

**Comment by LouiseBC** [comment]
It's still an issue for me in both iTerm and Terminal
