### ISSUE TITLE
How to get "Choice" type?

### ISSUE THREAD

**Issue by paul-uz** [SBoudrias/Inquirer.js#1491]
I need to tell a select prompt that my array for the `choices` option is an array of `Choices`, but its not working.

I need this type

```
type Choice<Value> = {
    value: Value;
    name?: string;
    description?: string;
    short?: string;
    disabled?: boolean | string;
    type?: never;
};
```

But using `Choice<Value>[]` isn't valid, as `Value` isn't exported? If I just use `Choice[]` then all the properties are required

**Comment by paul-uz** [comment]
I'm not wanting to type it manually, I want to use the types defined in the library.

eg I have this code

```ts
const users = await cognito.getUsers(userPoolID as string);

const username = await select({
  message: 'User',
  choices: users,
});
```

`const users` should be an array of type `Choice<Value>` ie `Choice<Value>[]` but thats not valid.

**Comment by SBoudrias** [comment]
Can you post the typescript error you get?

**Comment by paul-uz** [comment]
First, trying to use `Choice[]`, then trying to use `Choice<Value>[]`

<img width="852" alt="Screenshot 2024-07-31 at 09 29 41" src="https://github.com/user-attachments/assets/e93da519-3688-4a57-a64b-6508b1b409c0">

<img width="872" alt="Screenshot 2024-07-31 at 09 30 02" src="https://github.com/user-attachments/assets/e7916c78-b65a-4a89-a353-0ddf97184c9f">

**Comment by medallyon** [comment]
Could it be helpful to export the `Choice` type so that devs have access to it, similar to how we can do:

```typescript
import type { Separator } from "@inquirer/prompts";
```

**Comment by SBoudrias** [comment]
@medallyon I don't really want to do that because then we tie type interfaces to our public APIs and to breaking changes. I don't believe the problem Paul is running into here is linked to the lack of exported `Choice`.

@paul-uz Can you remove the casting completely. I want to understand why the types aren't inferred properly - you shouldn't need to type it manually. I think you have more of an issue with the return type of `cognito.getUsers` than with inquirer - but with the types you added, we'd burying this problem.

**Comment by powerfulech0** [comment]
I'm new to TypeScript, so apologies if I am missing some glaring obvious answer, but I am running into a similar issue.

```
import fs from 'fs';
import { google } from 'googleapis';
import { JWT } from 'google-auth-library';
import { select } from '@inquirer/prompts';

const SCOPE = ['https://www.googleapis.com/auth/drive'];

async function authorize() {
  const data = JSON.parse(fs.readFileSync('apikey.json', 'utf8'));

  const jwtClient = new google.auth.JWT(
    data.client_email,
    undefined,
    data.private_key,
    SCOPE,
  );

  try {
    await jwtClient.authorize();

    return jwtClient;
  } catch (err) {
    console.error('Something went wrong with Google auth: ', err);
  }
}

async function getFolders(auth: JWT) {
  const drive = google.drive({ version: 'v3', auth });

  try {
    const result = await drive.files.list({
      q: "mimeType='application/vnd.google-apps.folder'",
    });

    if (result.data.files) {
      return result.data.files.map((file) => ({
        name: file.name,
        value: file.id,
      }));
    }
  } catch (err) {
    console.error('Something went wrong with Google Drive: ', err);
  }
}

const auth = await authorize();

if (auth) {
  const choices = await getFolders(auth);
  if (choices) {
    const folderChoice = await select({
      message: 'Select a Google Drive folder to upload to: ',
      choices,
    });
    console.log(folderChoice);
  }
}
```

which then gives this error: 
```
src/index.ts:53:7 - error TS2322: Type '{ name: string | null | undefined; value: string | null | undefined; }[]' is not assignable to type 'readonly (Separator | Choice<string | null | undefined>)[]'.
  Type '{ name: string | null | undefined; value: string | null | undefined; }' is not assignable to type 'Separator | Choice<string | null | undefined>'.
    Type '{ name: string | null | undefined; value: string | null | undefined; }' is not assignable to type 'Choice<string | null | undefined>'.
      Types of property 'name' are incompatible.
        Type 'string | null | undefined' is not assignable to type 'string | undefined'.
          Type 'null' is not assignable to type 'string | undefined'.

53       choices,
         ~~~~~~~

  node_modules/@inquirer/select/dist/esm/types/index.d.mts:23:5
    23     choices: readonly (Separator | Choice<Value>)[];
           ~~~~~~~
    The expected type comes from property 'choices' which is declared here on type '{ message: string; choices: readonly (Separator | Choice<string | null | undefined>)[]; pageSize?: number | undefined; loop?: boolean | undefined; default?: unknown; theme?: { icon?: { ...; } | undefined; style?: { ...; } | undefined; helpMode?: "always" | ... 2 more ... | undefined; prefix?: string | undefined; spi...'


Found 1 error in src/index.ts:53
```

**Comment by paul-uz** [comment]
So I managed to get closer, ensuring I made my function return a type of `(Separator | Choice<any>)[]` but now get the error of `Type '(Separator | Choice<any>)[]' is not assignable to type 'readonly (Separator | Choice<any>)[]'.` so I guess I'm now blocked unless the types in the library are changed.

**Comment by SBoudrias** [comment]
@paul-uz can you send a minimal reproduction case? I'd be very happy to help, but it's really hard for me to provide help and direction without access to the exact code, and without being able to reproduce your issue.

**Comment by alex-kinokon** [comment]
```ts
import { type Separator, select } from "@inquirer/prompts";

type Choice<T> = Exclude<
  Parameters<typeof select<T>>[0]["choices"][number],
  string | Separator
>;
```
