### ISSUE TITLE
Which version of @inquirer/prompts supports Node.js v16?

### ISSUE THREAD

**Issue by jimguos** [SBoudrias/Inquirer.js#1494]
I have a project that has been maintained for a long time, and some features in it prevent it from supporting Node.js v18. I want to know which version can support Node.js v16. Now the @inquirer/type/1.5.1 version requires Node.js v18 or above.

**Comment by SBoudrias** [comment]
Up to `3.3.2` from git blame on the engine field of `package.json` https://github.com/SBoudrias/Inquirer.js/blame/b35b6bb529969be3ca0bb07808b7960896c9850d/packages/prompts/package.json

But I can't fully guarantee it.
