### ISSUE TITLE
A way to fix flickering

### ISSUE THREAD

**Issue by cAttte** [SBoudrias/Inquirer.js#1497]
hey! i've been getting an annoying flicker on every screen update (am i the only one?) and i remembered how i fixed it back when i implemented CLI screen updates myself some time ago. basically, write the clear character _along_ with the output rather than in separate writes. this seems to solve the flickering:

https://github.com/user-attachments/assets/6eda7062-f6c0-4928-a17c-71329dab622d

https://github.com/user-attachments/assets/83771552-9696-4556-9b85-35031d7bf05a

don't really have time for a proper PR + it's a little ugly (was just a quick [`patch-package`](https://www.npmjs.com/package/patch-package)) + there may be edge cases? but if you want i can open a PR. here's a diff:

```diff
--- a/node_modules/@inquirer/core/dist/esm/lib/screen-manager.mjs
+++ b/node_modules/@inquirer/core/dist/esm/lib/screen-manager.mjs
@@ -52,14 +52,14 @@ export default class ScreenManager {
             output += ansiEscapes.cursorUp(bottomContentHeight);
         // Return cursor to the initial left offset.
         output += ansiEscapes.cursorTo(this.cursorPos.cols);
-        this.clean();
         this.rl.output.unmute();
         /**
          * Set up state for next re-rendering
          */
+        const clean = this.getClean();
         this.extraLinesUnderPrompt = bottomContentHeight;
         this.height = height(output);
-        this.rl.output.write(output);
+        this.rl.output.write(clean + output);
         this.rl.output.mute();
     }
     checkCursorPos() {
@@ -71,14 +71,17 @@ export default class ScreenManager {
             this.cursorPos = cursorPos;
         }
     }
-    clean() {
-        this.rl.output.unmute();
-        this.rl.output.write([
+    getClean() {
+        return [
             this.extraLinesUnderPrompt > 0
                 ? ansiEscapes.cursorDown(this.extraLinesUnderPrompt)
                 : '',
             ansiEscapes.eraseLines(this.height),
-        ].join(''));
+        ].join('');
+    }
+    clean() {
+        this.rl.output.unmute();
+        this.rl.output.write(this.getClean());
         this.extraLinesUnderPrompt = 0;
         this.rl.output.mute();
     }
```

**Comment by SBoudrias** [comment]
Thanks for the deep-dive @cAttte! I went ahead and roughly implemented that change (with a bit more cleanup of the previous code.)

I'm kind of confuse because I was sure we had made a similar fix 😂... But now I wonder if that was maybe on `inquirer` and we never ported if to `@inquirer/core` - anyhow, thanks that was the nudge required to get this fixed!

**Comment by cAttte** [comment]
great, thank you for implementing it! (and for all your work)
