### ISSUE TITLE
Reuse prompt?

### ISSUE THREAD

**Issue by paul-uz** [SBoudrias/Inquirer.js#1501]
Is there a way to reuse a previous prompt?

EG I present a list of choices, and after executing some code for that choice, I want to re-prompt the list of choices

**Comment by SBoudrias** [comment]
You'd do that with a recursive function. You can see a real example over here https://github.com/SBoudrias/Inquirer.js/blob/main/packages/demo/index.mjs#L63

**Comment by paul-uz** [comment]
This is a great place to start, thank you.

I'm not looking to add the ability to go back to previous lists multiple times, but i'm struggling to get it working.

Do you have any examples of multiple select prompts with a "back" option to go back to previous prompts.

eg

1. display users
2. select user
3. display actions
4. pick "get user info"
5. display user info
6. reshow actions
7. select back
8. reshow user list

**Comment by paul-uz** [comment]
I figured it out, needed to tidy up my code and use a while loop
