### ISSUE TITLE
Handle ctrl+c gracefully

### ISSUE THREAD

**Issue by paul-uz** [SBoudrias/Inquirer.js#1502]
When I use control + c to close my CLI app (created using Commander), I get this error:

```
file:///Users/Programming/Work/CLI/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:30
                    reject(new ExitPromptError(`User force closed the prompt with ${code} ${signal}`));
                           ^

ExitPromptError: User force closed the prompt with 0 null
    at file:///Users/Programming/Work/CLI/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:30:28
    at Emitter.emit (file:///Users/Programming/Work/CLI/node_modules/@inquirer/core/node_modules/signal-exit/dist/mjs/index.js:67:19)
    at #processEmit (file:///Users/Programming/Work/CLI/node_modules/@inquirer/core/node_modules/signal-exit/dist/mjs/index.js:236:27)
    at #process.emit (file:///Users/Programming/Work/CLI/node_modules/@inquirer/core/node_modules/signal-exit/dist/mjs/index.js:187:37)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

How do I stop this from happening?

**Comment by SBoudrias** [comment]
You need to handle the error, otherwise it throws when you `await`. That's just how promises work.

```js
input().catch(() => ...)
```

**Comment by paul-uz** [comment]
Ah, silly me, I have now wrapped my prompts in a try/catch and handling the error accordingly. Thanks!

**Comment by SBoudrias** [comment]
Just note `try/catch` will swallow all errors - even those not related to inquirer. So you might want to filter specifically for the exit one `if (error.name === 'ExitPromptError') ...`

**Comment by paul-uz** [comment]
Yea, I've only wrapped the prompts and used a check for the error type (although i spotted that you warned against `instanceof` so will fix that)

**Comment by SBoudrias** [comment]
@ArnaudBarre any rejected promises will throw when awaited. What would you want inquirer to do instead?

**Comment by ArnaudBarre** [comment]
Don't throw `ExitPromptError` on ctrl+c and execute with code 0 (opt-in obviously for back compatibility)

I can do my own wrapper, but just to voice that I have a lot of npm scripts, and it happens often taht in the middle of it running I notice I forgot something and press ctrc+c.
When this happen during a promt, the output gets really bad compare when stopping the prettier for ex.

**Comment by ArnaudBarre** [comment]
I'm using it to have small scripts to do things on our platform I don't want to build a back-office for. Here is an extract of the "Add a demo user" script (code is closed source)

```ts
import { input, select } from "@inquirer/prompts";

/* Init prisma */

const acmes = await prisma.asset.findMany({
  select: ["name"],
  where: { fake: true },
});

const assetName = await select<string>({
  message: "Company?",
  choices: acmes.map((it) => it.name),
}).catch(() => process.exit(0));

const username = await input({ message: "Username?" }).catch(() =>
  process.exit(0),
);

await prisma.user.create({
  data: {
    asset: { connect: { name: assetName } },
    username,
  },
});
```

In this kind of scripts, if I stop at any moment (for example I remember that I forgot to create a new company when seeing the list), then it's a bit annoying to have an error

I hope it helps!

**Comment by SBoudrias** [comment]
Isn't there any convenient place to add this snippet?

```ts
process.on('uncaughtException', (error) => {
  if (error instanceof Error && error.name === 'ExitPromptError') {
    // noop; silence this error
  } else {
    throw error;
  }
});
```

Or, [here's how we do it in our demos](https://github.com/SBoudrias/Inquirer.js/blob/main/packages/demo/src/index.ts#L89-L95). And where I work we implemented a similar pattern through Clipanio (overwriting the `async catch(error) {` method).

**Comment by ArnaudBarre** [comment]
yeah good point about the cleanup. I didn't think to register an uncaughtException listener, it will totally make the job!
I think this could be added to the Recipes section of the documentation
Thanks for you help!

**Comment by SBoudrias** [comment]
Thanks for your help!

I've added instructions at the beginning of the recipe section as handling the error feels pretty important to do for all CLI programs! https://github.com/SBoudrias/Inquirer.js/commit/b2bc639dfeb95634965a30e253374411d87be1fe Let me know if you think it's unclear or if you have suggestion to improve the doc 🤞🏻 Cheers

**Comment by ArnaudBarre** [comment]
Thanks very clear for me!
