### ISSUE TITLE
Proper text search in select?

### ISSUE THREAD

**Issue by paul-uz** [SBoudrias/Inquirer.js#1503]
Without built in pagination; could we at least get a proper text search for the select prompt?

**Comment by SBoudrias** [comment]
The select prompt copies the search behaviour of native ones, what more would you want that is not covered by the [search prompt](https://github.com/SBoudrias/Inquirer.js/tree/main/packages/search)?

I'm open to implement simple logic, but complicated search algorithms aren't a good fit for the default prompts who're aiming to be lean and small.

**Comment by paul-uz** [comment]
something like https://github.com/robin-rpr/inquirer-search-list, as the search functionality in select currently isn't very good and wont match more then like 2 letters before jumping to a new result.

I can't use the search prompt cos im getting all my data at once first

**Comment by SBoudrias** [comment]
That prompt is quite similar to the search prompt - what's different?

**Comment by paul-uz** [comment]
Nvm, figured it out. The example threw me off. Its working now, thank you

**Comment by paul-uz** [comment]
Oh, how can provide a way to "exit" the search listing?
