### ISSUE TITLE
Registering API - plugins, mocking 

### ISSUE THREAD

**Issue by SBoudrias** [SBoudrias/Inquirer.js#152]
I want to add a register API to inquirer so user can provide custom prompts.

This will allow to register plugin prompt - or simply providing mocks.

Example API:

``` js
inquirer.register('type', promptConstructor)
inquirer.restoreDefaultPrompts() // empty the prompts and re-register the default ones
```

That should be fairly simple to implement considering prompt are already matched by named to a constructor. This would only provide a public API on top of it.

Relevant actual file: https://github.com/SBoudrias/Inquirer.js/blob/master/lib/inquirer.js#L9-L21

**Comment by JimmyBoh** [comment]
@SBoudrias Is there any written documentation on this? I see how it works with the built in types, but wasn't sure if there was a wiki page or blog post with details and gotchyas.

**Comment by SBoudrias** [comment]
@JimmyBoh No documentation at the moment, help is welcome to add one.
