### ISSUE TITLE
Add AbortSignal to @inquirer/core.

### ISSUE THREAD

**Issue by mshima** [SBoudrias/Inquirer.js#1521]
Allow to programmatically cancel the prompt.

Timeout example.
```js
await input(
  { message: 'Enter your name' },
  { signal: AbortSignal.timeout(5000) },
});
```

In `yeoman-environment` conflicter, conflict check and commit is done in background while the conflict resolution question is prompted. AbortSignal support will make easy to cancel the prompt.

**Comment by SBoudrias** [comment]
Ah, I think that's a great idea.

I'm happy to review a PR, or I'll get to it in a few weeks.
