### ISSUE TITLE
TypeError: items.findLastIndex is not a function

### ISSUE THREAD

**Issue by HopperDai** [SBoudrias/Inquirer.js#1526]
- prompt：[Select](https://github.com/SBoudrias/Inquirer.js/tree/main/packages/select)
- data：use demo
- version：^5.3.8
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/6c008427-5224-4987-8887-d50a3255d0ba">

**Comment by SBoudrias** [comment]
Hi, the problem is you're using a non-LTS version of Node. If you update the version to a newer one, this native array function will be available.
