### ISSUE TITLE
I want to change prefix after answered.

### ISSUE THREAD

**Issue by jiheapark** [SBoudrias/Inquirer.js#1537]
Hi, I want to change prefix from ? to ✔ after answered.
like `create-next-app`

![스크린샷 2024-09-05 오후 7 31 09](https://github.com/user-attachments/assets/50b3087e-76c9-45db-b692-a56ed89aa0e5)

Is there any solution?

**Comment by SBoudrias** [comment]
Ah, this isn't implemented as of now. But I think it make sense to add this feature in.

If you want to give it a stab, we should modify [`usePrefix` here](https://github.com/SBoudrias/Inquirer.js/blob/main/packages/core/src/lib/use-prefix.mts). I'd replace `isLoading` with `state` and return different prefix values based on that.

**Comment by nicholas-tayag** [comment]
Hi, can i get assigned to this? I'd like to try it.

**Comment by SBoudrias** [comment]
@nicholas-tayag for sure! Let me know if you have questions

**Comment by nvlang** [comment]
In a similar vein, I think it could be really nice to be able to get an additional argument for the `style.message` function in theme objects; currently, it receives only the message string, but if it also received, e.g., a second argument `status: 'pending' | 'done'`, users could, e.g., dim questions that have already been answered, or make the currently pending question brighter.

**Comment by SBoudrias** [comment]
@nvlang Happy to review a PR adding this feature.

**Comment by nvlang** [comment]
@SBoudrias Just made a PR (#1544) implementing this and some changes to `usePrefix`. I'd love to hear what you think.

**Comment by nicholas-tayag** [comment]
hi @SBoudrias, I noticed that someone put up a PR already solving this issue. Is it still alright if I work on this? This is my first time doing open-source contributions so I'm not sure how this works...

**Comment by SBoudrias** [comment]
Hey @nicholas-tayag, this is a rare case where I think N. V. wanted this feature badly and sent a PR faster. And also, a rare case because you're following up! Most often people say they'll work on something, and never come back 😅 Because of this, PRs are truly about first person to send one.

Given we have a PR in a pretty close state to being merge, you should look into recent-ish issues and see if there's another feature you'd be interested to work on.
