### ISSUE TITLE
Is there any way to change style of default value?

### ISSUE THREAD

**Issue by jiheapark** [SBoudrias/Inquirer.js#1538]
Hi,
I want to change default value style.

During asking user, I make default primary color.
It's hard to know what color it is just by looking at the hexadecimal number.

![스크린샷 2024-09-05 오후 7 32 13](https://github.com/user-attachments/assets/89b402b3-2a1d-4bad-aa66-1525d8d901cf)

So I want to set style like chalk bgHex.
![스크린샷 2024-09-05 오후 7 34 46](https://github.com/user-attachments/assets/6a4bb243-a58c-47fa-b297-389dcf83c9a4)

Is there any way to express the color of default value?

**Comment by SBoudrias** [comment]
Yes, you'll want to [provide a theme](https://github.com/SBoudrias/Inquirer.js/tree/main/packages/input#theming)

`theme.style.defaultAnswer` is the function to customize it.
