### ISSUE TITLE
prompt / Separator will throw TypeError

### ISSUE THREAD

**Issue by aheissenberger** [SBoudrias/Inquirer.js#1539]
**Error:**
```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at file:///catasta/node_modules/.pnpm/@inquirer+expand@2.2.0/node_modules/@inquirer/expand/dist/esm/index.mjs:10:29
    at Array.map (<anonymous>)
    at normalizeChoices (file:///catasta/node_modules/.pnpm/@inquirer+expand@2.2.0/node_modules/@inquirer/expand/dist/esm/index.mjs:4:20)
```

The error comes from `new inquirer.Separator(),` not providing a key property.

**Setup to replicate problem:**
https://github.com/SBoudrias/Inquirer.js/blob/0c039599ef88fe9eb804fe083ee386ec906a856f/packages/inquirer/examples/expand.mjs#L5-L40

Problem exists with the official example file `packages/inquirer/examples/expand.mjs`

**System configuration:**
inquirer: 10.2.0
Operating System: MacOS 14.6.1
node: v22.8.0

**Comment by SBoudrias** [comment]
Ah, Separator wasn't implemented in the new underlying `@inquirer/expand` prompt. I've re-added support in `inquirer@10.2.1`.

**Comment by aheissenberger** [comment]
The error ist gone, but it renders `[object Object]` and not a line:
```
Conflict on "vite.config.js": 
  y) Overwrite
  a) Overwrite this one and all next
  n) Do not overwrite
  d) Show diff
 [object Object]
  x) Abort
```
