### ISSUE TITLE
Don't display anything if the question is not defined or if "waitForUseInput" is false

### ISSUE THREAD

**Issue by michael-ts** [SBoudrias/Inquirer.js#1550]
I'm providing an empty string for the "message" parameter and passing waitForUseInput:false, but I still see a spurious question marked printed as well as the prompt to hit enter.  While the message about hitting enter seems to be deleted when the editor exit, the question mark is not.

It seems like a bug or at least omission to be printing something when I didn't request it.

**Comment by SBoudrias** [comment]
The `when` options is provided to skip a prompt programatically.

If you just want to launch an editor, then don't use inquirer for this. [external-editor](https://github.com/mrkmg/node-external-editor) is the library we use under the hood.
