### ISSUE TITLE
[Ask]: What is the actual use of the `status` parameter in `theme.message`?

### ISSUE THREAD

**Issue by br14n-sol** [SBoudrias/Inquirer.js#1567]
In the latest version of `@inquirer/core` a new parameter has been added to `theme.message` called [status](https://github.com/SBoudrias/Inquirer.js/blob/main/packages/core/src/lib/theme.mts#L91C29-L91C31), but I don't see it used, at least in the default theme.

Is this expected or was it simply added by 'mistake'?

**Comment by SBoudrias** [comment]
It was added on request. Some people wanted to render the message with different colors based on the status of the prompt; mainly `idle` vs `done`.
