### ISSUE TITLE
Can we use inquirer.js synchronously?

### ISSUE THREAD

**Issue by akwangho** [SBoudrias/Inquirer.js#157]
Hi,

The "when", "validate", "message", "default" and "filter" in inquirer.js are really cool.
However the asynchronous callback is tough to write comprehensive code.
I'm curious is there any approach to use inquirer.js synchronously?
Because I intend to insert a lot of logics between questions and may also generate questions dynamically.

A synchronous call is something like:
var answer = inquirer.prompt([{
            type: "input",
            name: "last_name",
            message: "What's your last name"
}]);
console.log("the answer: " + answer);

Thanks

**Comment by KK-wang** [comment]
> I think this does what you want: https://github.com/abbr/deasync

thanks a lot!!
