### ISSUE TITLE
@inquirer/select affecting later default confirm

### ISSUE THREAD

**Issue by MarceloZapatta** [SBoudrias/Inquirer.js#1574]
Hey! I'm having an issue when using the @inquirer/select@3.0.1.

When I use the select prompt it is working normally, I can select an option and it's is prompted if I put a console right below. But if I use the default confirm, I need to press Enter two times to enter the answer and it's default behavior only requires one.

Check the example below:

[Screencast from 2024-10-05 23-49-18.webm](https://github.com/user-attachments/assets/6388aff2-1a6d-4da8-ae3b-674842782fd9)

```javascript
const answer = await select<string>({
  message: 'Which type of project?',
  choices: ['Docker', 'PHP', 'Laravel', 'Laravel Sail', 'Java', 'Python', 'React', 'Flutter', 'Custom'],
  theme: { style: { help: () => dim('(Use arrow keys or type to select)') } },
});

console.log(answer); // Docker

const shouldProceed = confirm("Do you want to proceed?"); // Here it ask double Enter to take the confirm answer
console.log("Should proceed?", shouldProceed);```

**Comment by SBoudrias** [comment]
Hi, I believe this issue resides in your code. The example you provided (once fixed to run), does not reproduce the issue - try it yourself in isolation.

**Comment by MarceloZapatta** [comment]
It's seems a Deno incompatibility, but as workaround is possible to use the confim from @inquirer. But now I'm going to migrate to CLIFFY  because is more compatible with Deno.js

**Comment by SBoudrias** [comment]
Did you report the issue to Deno? They're probably unaware of that bug in their new release.
