### ISSUE TITLE
override like prompt?

### ISSUE THREAD

**Issue by tonylukasavage** [SBoudrias/Inquirer.js#166]
One bit of functionality missing from `inquirer` that I found indispensable in [prompt](https://github.com/flatiron/prompt) is the ability to provide an `override` to the prompting process. So in the case of `inquirer`, if I have 2 questions I want to ask, but in previous code I've already determined the value of 1 of them, I'd love it if I could do something like this:

``` js
var questions = [
    {
        name: 'name',
        type: 'input',
        message: 'name:'
    },
    {
        name: 'value',
        type: 'input',
        message: 'value:'
    },
];
var override = {
    name: 'this is the name'
};
inquirer.prompt(questions, override, function(answers) {
    // process answers
});
```

In the above case, only the `value` question would be asked since `name` is already available in the override. The resulting `answers` object would include the input answer for `value` and the value from the override for `name`.

I didn't see this functionality in the docs nor did I see any means to do it in a very quick check of the source.

**Comment by pyramation** [comment]
can we reopen this?

I'll try to illustrate a good use case:

```js
var inquirer = require('inquirer');
inquirer.registerPrompt(
  'autocomplete',
  require('inquirer-autocomplete-prompt')
);
...
inquirer.prompt([{
  type: 'autocomplete',
  name: 'from',
  message: 'Select a state to travel from',
  source: function(answersSoFar, input) {
    return myApi.searchStates(input);
  }
}]).then(function(answers) {
  //etc
});
```

If we filter the questions, you will see that `answersSoFar` will be missing what could be useful for narrowing down a search result, for example. I understand there are hacks around it, but I agree with @tonylukasavage that this is an important missing feature.

**Comment by SBoudrias** [comment]
Okay, I'll reopen. That's been a feature asked many times.

**Comment by pyramation** [comment]
cool! I took a stab at it here: https://github.com/pyramation/Inquirer.js/pull/1/files

I think I have something that works, but 3 tests are broken.

My approach was to keep it in the flow, but just return an always resolving answer from the overrides after passing them into the `prompt` constructor:

```js
PromptUI.prototype.fetchAnswer = function (question) {
  if (question.name && _.has(this.overrides, question.name)) {
    return rx.Observable.defer(
      function () {
        return rx.Observable.fromPromise(
          new Promise(resolve => {
            resolve({
              name: question.name,
              answer: this.overrides[question.name]
            });
          })
        );
      }.bind(this)
    );
  }

  var Prompt = this.prompts[question.type];
  this.activePrompt = new Prompt(question, this.rl, this.answers);
  return rx.Observable.defer(function () {
    return rx.Observable.fromPromise(this.activePrompt.run().then(function (answer) {
      return {name: question.name, answer: answer};
    }));
  }.bind(this));
};
```

**Comment by pyramation** [comment]
finally got around to it - but ended up just making a wrapper. If anyone is interested in this https://github.com/pyramation/inquirerer

**Comment by GeorgeGkas** [comment]
What is the current state of this? @pyramation gave a solution by creating another package. Do we expect to implement this feature in this package as well? Should we close it?

@tonylukasavage you are the one who opened the issue. What is your opinion?

**Comment by PsyGik** [comment]
I believe this use case is covered with the following:
```js
const answers = require('./answers'); // This could be from a file, or from some business logic. 
const questions = require('./questions');

inquirer
    .prompt(questions, answers) // provide `answers` as an argument, and inquirer skips those questions
    .then((_answers) => {
      // Use user feedback for... whatever!!
      preFlightChecks(_answers);
    })
    .catch(handleError);
```
answers.js
```js
module.exports = {
  description: "Default answer, or something specific",
  .
  .
  .
}
```
Answers will contain objects whose answers are known. When this is passed as args into `Inquirer` it skips those questions. 

questions.js
```js
module.exports =  [
  {
    type: "input",
    name: "title",
    message: "Title",
    default: "Random Title",
  },
  {
    type: "input",
    name: "description",
    message: "Description",
    when: function (answers) {
      return answers.title;
    },
  }
```
