### ISSUE TITLE
multi-line validate messages screw up prompt rendering

### ISSUE THREAD

**Issue by tonylukasavage** [SBoudrias/Inquirer.js#167]
### problem

Whenever I add `validate` to a question and it returns an error with more than one line of text (either explicitly defined as multi-line in the code, or overrun in the terminal), the subsequent rendering of the prompts gets all muddled up. It appears as though the prompts assume that the error will only be one line.

### test case
```js
var inquirer = require('inquirer');

inquirer.prompt([
	{
		name: 'name',
		type: 'input',
		message: 'name:',
		validate: function(input) {
			if (input !== 'test') {
				return 'this is a multi-line\n' +
					'error message that is going to\n' +
					'really screw up how inquirer.js\n' +
					're-renders the prompts.'
			} else {
				return true;
			}
		}
	}
], function(answers) {
	console.log(answers);
});
```

### results
```
? name: ThisNameFailsValidate
>> this is a multi-line
error message that is going to
? name: 
re-renders the prompts.
```

**Comment by flovan** [comment]
I think I found another bug that overlaps with the behaviour reported above.  
When the default value of a prompt spans across a new line, the error message gets cut off by the amount of characters already present on that line.

Example result with response "this is an error message":
````
? This is a question? (and this is a very long
default answer) WrongAnswer
? This is a question? (and this is a very long
default answer) essage
````

**Comment by SBoudrias** [comment]
Fixed on master. Please test and let me know how it goes.
