### ISSUE TITLE
InquirerJS in sync mode

### ISSUE THREAD

**Issue by fuechter** [SBoudrias/Inquirer.js#168]
Can run InquirerJS in sync mode?

Example:

```
var answers = inquirer.prompt([...]);
```

**Comment by AdrienHorgnies** [comment]
@SBoudrias Why is that ? I don't quite get it, ask user input synchronously is what I'd do in many languages. The case where you wait for user input and cannot do anything without it is pretty common.

**Comment by SBoudrias** [comment]
@AdrienHorgnies Yeah, common in a lot of languages, but Node.js doesn't have a synchronous Readline module https://nodejs.org/api/readline.html - so unfortunately, this isn't possible.

**Comment by GopherJ** [comment]
https://github.com/heapwolf/prompt-sync is what you are searching
