### ISSUE TITLE
Validation message of rawlist does not show up correctly in Mac OS 

### ISSUE THREAD

**Issue by akwangho** [SBoudrias/Inquirer.js#173]
Mac OS version: 10.9.4.
```js
node examples/rawlist.js 
? What do you want to do? 
  1) Order a pizza
  2) Make a reservation
   ──────────────
  3) Ask opening hours
  4) Talk to the receptionnist
  Answer: abc
```
After press <*Enter*> and result in
```js
node examples/rawlist.js 
? What do you want to do? 
? What do you want to do? 
  1) Order a pizza
  2) Make a reservation
   ──────────────
  3) Ask opening hours
  4) Talk to the receptionnist
  Answer:
```
That is, the question (? What do you want to do?) was in a newline and no validation message prompt.

BTW, I found we can simply comment out following line
`.write( clc.bol(0, true) )`
inside `Prompt.prototype.onError` in `rawlist.js` to workaround this issue.

So far I have not see any side effect both in Mac OS and terminal through serial port in CentOS.
But I'm not sure if it's still fine in other terminal/OS. And there must be a reason to have `clc.bol`.

**Comment by SBoudrias** [comment]
I've been fixing lots of similar issues with natural line returns on master. Please test and let me know how it goes.
