### ISSUE TITLE
Delete on prompt can cause the deletion of (non-related) lines

### ISSUE THREAD

**Issue by adibiton** [SBoudrias/Inquirer.js#176]
I'm testing with cmd (windows 7) - i created a simple example (with one input) -
var inquirer = require("inquirer");
inquirer.prompt([{
	name: "firstQuestion",
	message: "what is your name?"
}], function(answers) {

});

1. Enter more than one line as an input
2. Try to delete the input (pressing the delete button constantly) - you will notice that the delete action deletes some (not related) lines

**Comment by SBoudrias** [comment]
Fixed on master. Please test and let me know how it goes.
