### ISSUE TITLE
validate does not run for list

### ISSUE THREAD

**Issue by thaiat** [SBoudrias/Inquirer.js#179]
Looks like validate fn never runs when defining a list.

Here is a quick repro

``` js
var choices = _.range(3).map(function(index) {
   return {
      name: 'module' + index,
      value: 'module' + index
   };
});

var prompts = [{
   name: 'modulename',
   type: 'list',
   message: 'What is the name of your module ?',
   choices: choices,
   validate: function(value) {
      return 'Not valid';
   }
}];
```

**Comment by Amberlamps** [comment]
I would like to have a validate function on list types. Why would you purposely remove that feature?

**Comment by SBoudrias** [comment]
@Amberlamps if you want to do an action on the selection of a choice, no need to hack around. Just do it in the callback function.
