### ISSUE TITLE
don't hardcode pagination settings

### ISSUE THREAD

**Issue by dylang** [SBoudrias/Inquirer.js#180]
It would be nice if the number of entries that caused paging to be enabled was adjustable, or at least defaulted to something closer to [`process.stdout.rows`](http://nodejs.org/api/tty.html#tty_ws_rows).

```js
Choices.prototype.setRender = function( render ) {
  this.renderingMethod = (this.choices.length > 9) ? this.paginateOutput(render) : render;
};
```
https://github.com/SBoudrias/Inquirer.js/blob/master/lib/objects/choices.js#L143-145

```js
Choices.prototype.paginateOutput = function( render ) {
  var pageSize = 7;
```
https://github.com/SBoudrias/Inquirer.js/blob/master/lib/objects/choices.js#L155

**Comment by SBoudrias** [comment]
Fixed with #300
