### ISSUE TITLE
`when` to take current prompt as parameter

### ISSUE THREAD

**Issue by SBoudrias** [SBoudrias/Inquirer.js#186]
``` js
{
  name: 'foo',
  when: function (prompt) {
    assert.equal(prompt.name, 'foo');
  }
}
```

**Comment by GeorgeGkas** [comment]
The `when` key can receive the current user answers hash as its first parameter. Is that what the `prompt` in your example was referring to?

**Comment by SBoudrias** [comment]
Oh, it was to pass the recursive prompt configuration. But I'm actually not sure why I needed this at that time.

I'll close, I don't think it's very important.
