### ISSUE TITLE
Add reactive interface example

### ISSUE THREAD

**Issue by Swiip** [SBoudrias/Inquirer.js#190]
I use inquirer though a yeoman generator. I wanted to try to ask questions dependents from the first answers so I jump on the reactive interface feature. I updated yeoman-generator to 0.18 to have inquirer 0.8.

I'm totally new to RxJS and the doc from the readme is quite short. I was not able to make it work.

Can you provide a working example of using an observable list of questions? The must would be even to add questions dynamically.

**Comment by Freyert** [comment]
I attempted to pass in an Rx.Observables instance in a yeoman generator prompt and was slapped with this message:

`Error: You must provide a 'message' parameter`

This is how I use it.
```javascript
  prompting: function () {
    var prompts = Rx.Observable.create(function(obs) {
      obs.onNext({ type: 'input',
        name: 'howdy',
        message:'howdy'
        }
      }); 
      obs.onCompleted();
    }); 

    this.prompt(prompts);
  }, 
```
I must be missing something.

**Comment by SBoudrias** [comment]
Maybe your yeoman-generator inquirer version is not up to date. Run `npm update`

**Comment by GeorgeGkas** [comment]
@Freyert I know it's a bit late, but you can check the [rx-observable-create.js](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/examples/rx-observable-array.js) example. The API was updated since the time you post your answer.
