### ISSUE TITLE
Error-first Callbacks

### ISSUE THREAD

**Issue by shellscape** [SBoudrias/Inquirer.js#196]
I'm working in ES6 land and using a lot of thunks and yields. While I have Inquirer wrapped in order to provide the error-first callback that thunks expect, it'd be nice to have that directly available. I'm not suggesting the change outright, but rather would like to start a dialogue about it. I'm curious to know the reasons behind using a data-only callback to return answers versus the relatively standard error-first callback style.

Would switching up the callbacks to use error-first be something the project would consider?

**Comment by tkellen** [comment]
That's a bad reason. The lack of adherence to this node standard breaks an entire ecosystem of control flow libraries that compose callback-taking methods. Would you consider bumping major to fix this?

**Comment by PaperElectron** [comment]
I just stumbled on this issue myself, I have a pretty complicated setup composed of a bunch of reusable prompts. I figured I would just use bluebirds Promise.promisifyAll() to compose them into the order I wanted. No dice, my promises all get resolved on the .catch or .error handler though...

**Comment by jergason** [comment]
I have the exact same issue as PaperElectron. Conforming to the node api makes a lot of sense and makes it easier to interoperate with other tools, even if the error will never be present.

**Comment by shellscape** [comment]
@SBoudrias doesn't look like I'm alone in this situation, several good points made. Reconsideration?

**Comment by SBoudrias** [comment]
Oh, it'll be done, but this will require a major version bump. I'm just not quite ready for this bump as there other thing I'd like to fix first.

**Comment by PaperElectron** [comment]
@SBoudrias @shellscape I figured this would be the case, as it is going to break for everyone that already wrapped it.

**Comment by callumlocke** [comment]
Has there been any progress on this?

**Comment by guillaumervls** [comment]
:+1:
