### ISSUE TITLE
default is a reserved word

### ISSUE THREAD

**Issue by tkellen** [SBoudrias/Inquirer.js#201]
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-keywords

Would you consider bumping major to change it to defaultsTo or something similar?

**Comment by SBoudrias** [comment]
Default could be used as an object key in es5 - has it changed for es6?

**Comment by tkellen** [comment]
Now I am doubting myself... I may be conflating reserved words and identifiers. @rwaldron, could you weigh in here?

**Comment by rwaldron** [comment]
tld;dr: reserved words are ok to use as property names.

IdentifierName can be any word, including ReservedWord (which itself includes Keyword,  FutureReservedWord, `null`, `true` and `false`). PropertyName is always an IdentifierName, so indeed any ReservedWord is allowed as a PropertyName (as of ES5 and forever). Identifier can be any IdentifierName, but not ReservedWord (those are: FunctionDeclaration, VariableDeclaration, and as of ES6: GeneratorDeclaration, LexicalDeclaration, ClassDeclaration).

**Comment by tkellen** [comment]
Thanks @rwaldron.  Ignore me @SBoudrias.

/cc @carldanley, I was wrong!

**Comment by rwaldron** [comment]
No problem :)
