### ISSUE TITLE
Errors on windows and centos about dev/tty

### ISSUE THREAD

**Issue by adriengibrat** [SBoudrias/Inquirer.js#205]
Errors showed up in v0.8.1 this morning
see [comment on commit](https://github.com/SBoudrias/Inquirer.js/commit/b666d2a2f0d42b8f1987b9b9efd3476d96517598#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R31)

**Comment by SBoudrias** [comment]
FYI I unpublished inquirer 0.8.1

To fix further issue for now:

```js
npm install inquirer@0.8.0
```
