### ISSUE TITLE
[Feature Request]: list cycle option

### ISSUE THREAD

**Issue by knownasilya** [SBoudrias/Inquirer.js#206]
Currently the list keeps cycling if you hit arrow up or down, there should be an option: `cycle: false`.

**Comment by SBoudrias** [comment]
What would this option do?

**Comment by knownasilya** [comment]
Basically if you reach the end of the list, clicking down  will not do anything. Same thing when going up.

**Comment by jlukic** [comment]
:+1:

**Comment by marcelogft** [comment]
+1

**Comment by sindresorhus** [comment]
> An alternative would be to put a separator after reaching the end.

I think this is a better solution than an option.

**Comment by SBoudrias** [comment]
Going over old issues ATM. I agree with:

> I think this is a better solution than an option.

So I'm going to close this issue.

**Comment by knownasilya** [comment]
Is there another issue to look at, or is this already possible (a link/example would be appreciated if so)?

**Comment by SBoudrias** [comment]
@knownasilya https://github.com/SBoudrias/Inquirer.js#separator

**Comment by knownasilya** [comment]
Guess this is an alright solution, definitely not the best. Easy to think that the separator is not separating the start and end of the list, but multiple groups in the list, especially if you have many items.

**Comment by sqren** [comment]
For anyone else coming across this issue, this feature was added in https://github.com/SBoudrias/Inquirer.js/pull/925

```
loop: false
```
