### ISSUE TITLE
Duplicate prompts on Rx usage

### ISSUE THREAD

**Issue by justin-calleja** [SBoudrias/Inquirer.js#209]
If you try running the following:

https://gist.github.com/justin-calleja/833718609ba78143a939#file-pizza-js

you should get duplicate prompts like I am. I am new to RxJS and this is probably due to my lack of experience. If so, how do I avoid this (and why is it happening?)?

Also, I have tried using Rx.Observable.create as given in an example in the README.md (as opposed to Rx.Observable.fromArray as in the gist), but with the same results.

Btw, I am trying to get processing done after giving the answer not before so 'when' is not what I'm looking for. (Even if there is a way around not using RxJS for this I am still interested in doing this using RxJS).

Thanks!

**Comment by Freyert** [comment]
I can't get any of these to work :(

**Comment by SBoudrias** [comment]
I could reproduce this issue, I'll investigate what on rx.js side is breaking.

**Comment by justin-calleja** [comment]
@Freyert and @SBoudrias - thanks for fixing!

Just saw the latest reply. Must have missed the other one..

Kudos
