### ISSUE TITLE
trying to hack in back button functionality, getting weird errors

### ISSUE THREAD

**Issue by yoshokatana** [SBoudrias/Inquirer.js#212]
I'm trying to allow users to go to a previous question while retaining the answers they've already given, but I can't seem to hack anything together. When I tried to simply recreate the prompt, I started getting duplicate data. Here's the relevant bits of code: https://github.com/yoshokatana/magfest-radios/blob/master/lib/main-screen.js#L105

Any ideas?

**Comment by SBoudrias** [comment]
You'll need to close an inquirer session (prompt) before you can open another one. There's only a single tty available, so here you duplicate the number of prompts listening for answers at the same time.

**Comment by yoshokatana** [comment]
Ahh, that makes sense.

**Comment by Pau1fitz** [comment]
@nelsonpecora did you manage to figure out how to do this?

**Comment by nelsonpecora** [comment]
Hmm, I don't think I ever did. [Here's the repo](https://github.com/nelsonpecora/magfest-radios) if you wanna poke around with my attempts
