### ISSUE TITLE
inputs repeating question when input wraps

### ISSUE THREAD

**Issue by callumacrae** [SBoudrias/Inquirer.js#214]
Sorry for the rubbish title, this is better explained by example.

![screen shot 2015-02-04 at 16 19 58](https://cloud.githubusercontent.com/assets/472830/6044188/b32b33b8-ac89-11e4-9c2c-c139ce26eba6.png)

If the input goes onto the next line, the question repeats for every character over the new line. It's a bit strange.

I'm using zprezto in iTerm2. Let me know if you need to know anything else.

**Comment by SBoudrias** [comment]
The prompt is re-rendered each time someone type a character, so my guess is once we have a line return the cleanup code for the previous line is not affecting a correct line.

A fix could be to compare the real line length to the terminal width and determine how many line we need to cleanup.

**Comment by callumacrae** [comment]
Does seem to be what's happening: when the prompt becomes three lines long, the first two aren't touched.

I don't know how to write a test for this, sorry. Can you replicate it?

**Comment by jonschlinkert** [comment]
I've had the same issue on both windows and mac, in the built-in terminal on mac and iTerm.

**Comment by jviotti** [comment]
Are there plans to fix this?

**Comment by callumacrae** [comment]
Heh, pasting tokens is the case I had, too

**Comment by jviotti** [comment]
I have a fix working locally. I'll submit a PR soon.

**Comment by callumacrae** [comment]
:+1: :confetti_ball:

**Comment by jonschlinkert** [comment]
that would be great @jviotti. this happens every time I use yeoman

**Comment by jviotti** [comment]
PR sent: https://github.com/SBoudrias/Inquirer.js/pull/239. I only tested on OS X, so if you run a different OS, your testing would be appreciated :)

**Comment by FremyCompany** [comment]
FYI, I have a one-line fix (tested on Windows). Feel free to try it and comment on whether it works for you or not.

**Comment by callumacrae** [comment]
Seems to be fixing the symptom of the problem and not the problem itself, though.

**Comment by FremyCompany** [comment]
Well if (like I assume) there's no reason to redraw the line on each keypress, then fixing the while-writing line-redrawing issue is a waste of time and adds more code to maintain than it should. In this case, it's easier to remove the behavior altogether. Also: it may work better when you resize your console than the previous fix (as the question & input text may or may not rewrap, making things hard to compute reliably).

But, you're right, the "redraw onEnd" is still buggy with this one-line fix. However, the amount of code required to fix that one bug would be much smaller than to fix both issues. Also, I don't care much about that remaining issue: what's important to me is that I can type more than one line without being disturbed ;-)

**Comment by FremyCompany** [comment]
Oh, by the way, this fixes another bug on Windows(cmder): the input cursor is now properly located at the insertion point, and not at the end of the input (#229). 

It was really annoying to edit your text because you had to remember in your head where the insertion point was, and how many times you had to press LEFT or RIGHT to move to the right location. When you don't rewrite the text while Windows isn't looking, you don't have this problem.

**Comment by SBoudrias** [comment]
What happens when you submit the input and the validation fail?

**Comment by pauldijou** [comment]
I just wanted to highlight the fact that there is also a problem is the message of the question wraps. It gets really ugly with `list` and `checkbox` types because the message will be printed again and again and again each time the user navigate the answers using arrow keys. I do hope the PR also fix that...

![screenshot from 2015-06-07 13 06 39](https://cloud.githubusercontent.com/assets/1275293/8023679/4e1df0b2-0d16-11e5-88de-cc32d2de2a25.png)

**Comment by adriancooney** [comment]
Also getting the same problem if a value in a `list` wraps.

**Comment by SBoudrias** [comment]
Fixed on master. Please test and let me know how it goes.

**Comment by jviotti** [comment]
@SBoudrias The repeating issue is fixed however:

- When pasting a long line, the text prompt eats a bunch of lines from above.
- When printing short new lines afterwards (console.log), there are parts of the token not being cleaned up at the right.

<img width="1280" alt="screenshot 2015-07-06 07 54 35" src="https://cloud.githubusercontent.com/assets/2192773/8521687/48dfcd1e-23b4-11e5-96b3-e740c9b6c4f2.png">

**Comment by SBoudrias** [comment]
@jviotti please open new issues for new issues :)

**Comment by allenGKC** [comment]
This problem happen when i npm install inquirer，anyone can help me？

**Comment by episodeyang** [comment]
I'm seeing this problem again with long lines in checklist.

**Comment by episodeyang** [comment]
will do thanks!

**Comment by KID-joker** [comment]
> I just wanted to highlight the fact that there is also a problem if the message of the question wraps. It gets really ugly with `list` and `checkbox` types because the message will be printed again and again and again each time the user navigate the answers using arrow keys. I do hope the PR also fix that...
> 
> ![screenshot from 2015-06-07 13 06 39](https://cloud.githubusercontent.com/assets/1275293/8023679/4e1df0b2-0d16-11e5-88de-cc32d2de2a25.png)

@pauldijou I have the same problem. Did you solve it?
