### ISSUE TITLE
multi entry input type

### ISSUE THREAD

**Issue by kylemac** [SBoudrias/Inquirer.js#217]
hey all, I find myself creating prompts that I split by spaces to make arrays quite a bit so I thought i'd propose a new `multi` input type. I've worked most of it out and I wanted to run it by you to see if you think it's even viable. I am mostly looking for feedback on the UX -- as it probably presents the hardest challenge.

![e8ybfdsvvr](https://cloud.githubusercontent.com/assets/49507/6337465/e4b70658-bb77-11e4-9414-33c3ec043d9d.gif)

**Comment by SBoudrias** [comment]
How about simply asking for a list of values separated by commas in an input prompt?

The issue with using `x` as an exit value is that it'll prevent using it as a valid value.

**Comment by knownasilya** [comment]
Looking for something similar for inputing environment variables, so keys and values. Maybe have a recursive input that allows to input one entry, then asks to if the user wants to input more, if so shows it again. This is probably possible with the existing types, but I'd need to experiment to see if it works. Also I'd take an example from @SBoudrias :wink:

**Comment by SBoudrias** [comment]
So I'll close this issue as the UX suggested is not possible. And there exist - or will exist - other solutions:

1. Ask for an input with comma separated value or whatever similar
2. Just do a recursive prompt asking the user if he wants to add new value each time
3. [eventually] handle this with a [multiline prompt](https://github.com/SBoudrias/Inquirer.js/issues/99)

**Comment by knownasilya** [comment]
@SBoudrias can you give a simple example of a recursive prompt?

**Comment by SBoudrias** [comment]
https://github.com/SBoudrias/Inquirer.js/blob/master/examples/recursive.js

**Comment by knownasilya** [comment]
@SBoudrias thanks!
