### ISSUE TITLE
bypass inquirer

### ISSUE THREAD

**Issue by przemyslawpluta** [SBoudrias/Inquirer.js#221]
Is there a way to pass answers to `inquirer` ... let's say when config file has been specified and all the questions required previously by manual entry are now available in the configuration file? Thanks.

**Comment by SBoudrias** [comment]
This is something you can handle in your code via a façade. You can check how Yeoman does it https://github.com/yeoman/generator/blob/master/lib/test/adapter.js#L47-L51

But it is not something that should be handle by Inquirer.

**Comment by przemyslawpluta** [comment]
Thanks for the tip @SBoudrias
