### ISSUE TITLE
Separator as a plain object

### ISSUE THREAD

**Issue by dakal-oleksandr** [SBoudrias/Inquirer.js#223]
Hi.
I propose to change listRender, and give possibility to specify separator as plain object:
```javascript
if ( choice.type === "separator" ) {
    separatorOffset++;
    output += "  " + choice + "\n"; => to => output += "  " + choice.line + "\n";
    return;
}
```
So it will be possible to add such choice:  
```javascript
{
    type: "separator",
    line: "-----"
}
```

**Comment by SBoudrias** [comment]
Why?

**Comment by dakal-oleksandr** [comment]
Then it can be used in Yeoman without additional require of Inquirer.js

**Comment by SBoudrias** [comment]
Pretty sure you can currently pass a raw object and it'll just work.

**Comment by dakal-oleksandr** [comment]
No) It's returns [object Object]

**Comment by dakal-oleksandr** [comment]
So can it done?

**Comment by SBoudrias** [comment]
If you send a PR, it can.
