### ISSUE TITLE
Mocha test example of Checkbox (and maybe others)

### ISSUE THREAD

**Issue by mistermark** [SBoudrias/Inquirer.js#224]
Could you guys provide an example of how I can use Mocha/Should combination testing on the checkbox functionality?

I've been trying to get this working, but I'm stuck at the moment on triggering keystrokes to select one or a few options and passing this value to the test results. Right now I can select an option and give an `[enter]`, but it fails on an apparent empty value retuned. See example below:

Testing with `npm test`.
Reference to `bin` file: https://github.com/mistermark/gentleman/blob/tests/bin/test_2

```
describe('gman', function() {
    it.only('test_2', function(done) {
        var steps = [];
        var exec = spawn('node', ['bin/test_2']);

        exec.stdout.on('data', function(chunk) {
            chunk = chunk.toString('utf8');
            chunk = readline.stripVTControlCharacters(chunk);
            steps.push(chunk);
        });

        exec.stdout.on('end', function(chunk) {
            console.log('STEPS: ', steps);
        });

        setTimeout(function () {
            exec.stdin.emit("keypress", " ", { name: "space" });
            exec.stdin.emit("keypress", null, { name: "enter" });
            exec.stdin.end();
        }, 1000);

    });
});
```

**Comment by SBoudrias** [comment]
Just mock `inquirer.prompt()` method. You don't need (or want) to send tty events for testing.
