### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by SBoudrias** [SBoudrias/Inquirer.js#227]
The action of `require`ing Inquirer is costing 100~150ms. Inquirer shouldn't bind the stdout until it is actually used.

**Comment by sindresorhus** [comment]
:+1:

**Comment by jonschlinkert** [comment]
I'd be happy to do this, would you be willing to take/review a pr? I was about to create this request, glad to see it's on your mind already :)

**Comment by SBoudrias** [comment]
Yes, PR welcomed :)

**Comment by jonschlinkert** [comment]
great, I'll put something together this week. thx!

**Comment by jonschlinkert** [comment]
@SBoudrias I'm working on this now. since I have to update require statements I noticed that some places have double quotes, some single. which do you prefer?

**Comment by SBoudrias** [comment]
Closing has this issue has been addressed a while ago when we moved to instantiable prompt modules.
