### ISSUE TITLE
Default should be hidden on prompt question for password type

### ISSUE THREAD

**Issue by adamzr** [SBoudrias/Inquirer.js#228]
Right now when you are asked a question the prompt shows the default answer in light gray. This is good for most questions, but not for password. Defaults are often used when we are remembering the user's last answer. In such a user case this will display the user's last entered password. Ideally it should just show a group of stars.

Current example:

What is your password? (password123)

Suggested fix:

What is your password? (*****)

Or

What is your password? <Hit enter to use the default>

**Comment by SBoudrias** [comment]
Does it even makes sense for password to allow a default?

**Comment by adamzr** [comment]
The only use case I can think of is persisting a password and offering the user the ability to use the saved password (the default) vs. entering a new one.

**Comment by SBoudrias** [comment]
But your user wouldn't know what the default actually is as it'll be hidden. It could be anything.

**Comment by adamzr** [comment]
He'll know that there is something saved and he can use that. Or we can put in text that says (Press enter to use the saved/default password) or something to that effect instead of the default text. The use case I was thinking of was using `store : true` in a yeoman generator.

**Comment by SBoudrias** [comment]
Setting storing to true will save the user password in clear in a public file. You shouldn't do this.

**Comment by SBoudrias** [comment]
I'll close as I think it makes sense to always display the default. Probably just shouldn't be defaults for password.

Anyway, I don't personally intend on fixing it. Feel free to send a PR if you feel strongly about it.
