### ISSUE TITLE
[feature] Answers switch callback

### ISSUE THREAD

**Issue by dakal-oleksandr** [SBoudrias/Inquirer.js#231]
It will be nice to give user ability to specify callback that will be invoked when user switch between answers (highlight another answer). Fist parameter of callback can be highlighted answer options.

Practical advantage - will be possible show different content (bottom bar for example) based on highlighted answer.

**Comment by SBoudrias** [comment]
That's already possible through the Reactive interface:

```js
inquirer.prompt(prompts).process.subscribe(
  onEachAnswer,
  onError,
  onComplete
);
```

**Comment by dakal-oleksandr** [comment]
Well I tested and I see that `process.subscribe` works when user submit answer but not traversing between answers in scope of 1 question.

**Comment by SBoudrias** [comment]
You mean a callback each time a user move through a list without submitting?

**Comment by dakal-oleksandr** [comment]
Yes.. It can give ability to create dynamic content under list (for example hint or item long description), but it cause problems with identifying correct cursor position.
