### ISSUE TITLE
Question: when using the name object is it case sensitive? & what is the advantage of the CopyTpl method?

### ISSUE THREAD

**Issue by xtianus79** [SBoudrias/Inquirer.js#232]
If I set the applicationName as the hash for a prompt I have... 
is the input case sensitive?  for me it works but I was wondering what the official answer was. 

    {
      "name": "ASPNET-F5-<%= applicationname %>",
      "description": "The most amazing Foundation template for Visual Studio Vnext",
      "version": "0.0.10",

Moreover, altering template data like this seems pretty straight forward... What would be the advantage of the copyTpl method shown on this page as an example? http://yeoman.io/authoring/file-system.html

Meaning say that I want the ' this portion here to be a template binded response... Why would I/do I need to use the copyTpl directive?

**Comment by SBoudrias** [comment]
It is case sensitive.

About `copyTpl` it's all about the clarity of intent and the traceability of the data source. Using `this.template` just create a huge mess where it's hard to find data sources and intent.

**Comment by xtianus79** [comment]
so does that mean the ['title:' 'message here'] title = 'name' in hash?

**Comment by SBoudrias** [comment]
In an Object literal.

**Comment by xtianus79** [comment]
ok and last question on this topic... 

Can you have multiple options set like this. 

    this.fs.copyTpl(
          this.templatePath('index.html'),
          this.destinationPath('public/index.html'),
          { title: 'Templating with Yeoman' },
          { h1: 'Your message here'},
          {h2: 'Some message here'}
        );

**Comment by SBoudrias** [comment]
Just one objects with multiples keys. That's explained in the documentation.

**Comment by xtianus79** [comment]
sorry... like so...

   this.fs.copyTpl(
      this.templatePath('index.html'),
      this.destinationPath('public/index.html'),
      [ 
       { title: 'Templating with Yeoman' },
       { h1: 'Your message here'},
       { h2: 'Some message here'}
      ]
    );

Can you do the same for the templatepath and destinationpath options?

**Comment by SBoudrias** [comment]
Please read the documentation and learn a bit of JavaScript, I can't continue answering all those questions.

See StackOverflow if you want to ask further questions.

**Comment by xtianus79** [comment]
the problem with frameworks and libraries is that they all do different things no?  so while I assume you can do as much sometimes you can't... for whatever reason.  However, with that said this would be a feature improvement no?  So why not just give the answer.

**Comment by xtianus79** [comment]
for example I am looking into refracting this code... but want to plan it out properly so it can all be updated to the latest yeoman generator version.  

    switch (this.type) {

            case 'empty':

                this.sourceRoot(path.join(__dirname, '../templates/projects/' + this.type));

                this.template(this.sourceRoot() + '/startup.cs', this.applicationName + '/Startup.cs',         this.templatedata);

                this.copy(this.sourceRoot() + '/project.json', this.applicationName + '/project.json');

                /// wwwroot
                this.directory(this.sourceRoot() + '/wwwroot', this.applicationName + '/wwwroot');

                break;
