### ISSUE TITLE
Deleting characters causes cursor to move up a line

### ISSUE THREAD

**Issue by jfraboni** [SBoudrias/Inquirer.js#234]
At least on Cloud9, when inputting at your prompt, if a user deletes characters using the delete key, the cursor jumps up a line per deletion, causing a very confusing user experience.  Thanks!

**Comment by emilyrose** [comment]
I'm experiencing the same thing. If anyone knows where to start looking for a fix, I'm happy to try & contribute a patch.

**Comment by emilyrose** [comment]
I've noticed that this won't happen with the first prompt, but happens reliably with subsequent prompts.

**Comment by SBoudrias** [comment]
@emilyrose do you have the same issue on Cloud9 or another editor?

This feels like an issue specific to Cloud9 terminal. I believe you might want to report the issue over there rather than here.

**Comment by emilyrose** [comment]
@SBoudrias nope! I'm using inquirer directly with a node CLI application I'm maintaining.

**Comment by emilyrose** [comment]
I will try to find steps to reproduce and if I'm able to I will post them along with a separate issue.

**Comment by SBoudrias** [comment]
Pushed some fixes for rendering edge cases on master. Please test and let me know how it goes.

Without more details on your issue, I won't be able to help further on this issue. Closing for now.
