### ISSUE TITLE
Replace already colored choices

### ISSUE THREAD

**Issue by kevva** [SBoudrias/Inquirer.js#236]
For some reason Inquirer doesn't seem to replace the color when highlighting choices in a list that already has a set color. See the highlighted choice in this screenshot. `screenfull.js` should have a cyan highlight color but it's still blue.

![](https://cloud.githubusercontent.com/assets/170270/7230139/424a089e-e795-11e4-8179-3cdb765b51ee.png)

**Comment by SBoudrias** [comment]
Yeah, this was on purpose. Might be worth revisiting.

**Comment by sindresorhus** [comment]
I think makes sense to override the color, but not the style. Eg. override the `blue`, but not the `bold`.
