### ISSUE TITLE
Confirm prints message several times

### ISSUE THREAD

**Issue by rosen-vladimirov** [SBoudrias/Inquirer.js#240]
Hi,

I'm trying to use inquirer's confirm and when the message is shown on several lines, and I try to input  my answer (`y` in my case), the message is shown on the next line. For **any keystroke** the message is printed on new line. I've tried this in cmd and git bash on Windows (it is important to see the message on more than one line) and in my Ubuntu's terminal - the issue is reproducible with Node 0.10.x, 0.12.x.
Here's my test script:
```JavaScript
var inquirer = require("inquirer");

inquirer.prompt([{type: "confirm",
				name: "prompt",
				default: true,
				message: "This is some long text that must be shown on several lines in cmd or any other terminal."}], function(answers) {
		console.log("Selected text.");
});
```

And the output on Linux:
![inquirerconfirmissue](https://cloud.githubusercontent.com/assets/8351653/7514770/3b80104e-f4c9-11e4-948c-900753102547.png)

Am I doing something wrong here? The backspace key is also causing new line printing...

**Comment by SBoudrias** [comment]
Yup, known issue: https://github.com/SBoudrias/Inquirer.js/issues/6

You can manually line wrap your questions to prevent this.

**Comment by SBoudrias** [comment]
Also https://github.com/SBoudrias/Inquirer.js/issues/214
