### ISSUE TITLE
Trailing Parenthesis on "input" Type

### ISSUE THREAD

**Issue by shellscape** [SBoudrias/Inquirer.js#244]
If I create a prompt with type "input" and the "message" property of that prompt ends with a closing paren ")" then inquirer never places the colon at the end of the message when it's rendered to the console. 

Example below reproduces the bug.

```
    inquirer.prompt([
      {
        type: 'input',
        name: 'name',
        message: 'Please enter a name (or press return for none)'
      }
    ], function(){});
```

**Comment by SBoudrias** [comment]
You can add it manually.

I plan on removing auto prefix/suffix soon enough.
