### ISSUE TITLE
Request: Line Prefix Option

### ISSUE THREAD

**Issue by shellscape** [SBoudrias/Inquirer.js#245]
I'd like to request the ability to pass an option to either the UI or the Prompt to prepend a line prefix. In my particular use-case, I'd want to prepend two spaces. If there's a way to easily hack this, I'm all for that as well.

**Comment by Skywalker13** [comment]
Hello,

An example in order to remove `? `.

```js
/* HACK inquirer prefix */
Object.keys (inquirer.prompt.prompts).forEach (function (prompt) {
  inquirer.prompt.prompts[prompt].prototype.prefix = function (str) {
    return str;
  };
});
```

**Comment by GeorgeGkas** [comment]
@shellscape you can provide a `prefix` key in question objects and set manually the prefix you want. See the [documentation](https://github.com/SBoudrias/Inquirer.js#question) for more details. If this was what you wanted, then we can close this issue.
