### ISSUE TITLE
When choices is an array of objects, result's value should be an object

### ISSUE THREAD

**Issue by adam-lynch** [SBoudrias/Inquirer.js#247]
The readme says that an answers object's value (for a `list`) is:

> Selected choice value (or name if no value specified) (String)

This is a little confusing. Sure, the chosen string value is given but to me the chosen value is the object from the choices array whose `name` property matched the string I chose in the prompt. It would be better if it returned the object instead of just the `name` property (when an object was passed obviously). Someone could use `result[questionName].name` anyway if they wanted. 

---

For example, this is what I have (sorry if you don't like CoffeeScript):

```coffeescript
options = [
            type: 'patch'
        ,
            type: 'minor'
        ,
            type: 'major'
        ,
            type: 'prerelease'
        ,
            type: 'prepatch'
        ,
            type: 'preminor'
        ,
            type: 'premajor'
    ]

    options.forEach (option) ->
        option.outcome = semver.inc currentVersion, option.type, 'rc'
        option.name = "#{option.type}#{Array(20 - option.type.length).join(' ')}(#{currentVersion} -> #{option.outcome})"

    inquirer.prompt
        type: 'list'
        name: 'bump'
        message: 'What type of bump would you like to do?'
        choices: [{name: "don't bump"}].concat options
    , (result) ->
        console.log result
```

If I select `patch`, this prints `{bump: "patch                (1.2.3 -> 1.2.4)"}`. I need it to give me the object from the choices array (so I can do something with its `outcome` property.

This means I have to do `options.filter((option) -> option.name is result.bump)[0].outcome` to get the `outcome`.

**Comment by SBoudrias** [comment]
Why don't you generate the outcome after from the result? I have a hard time to see what's your issue.

**Comment by adam-lynch** [comment]
The outcome is used in the `name` of each choice;

```coffeescript
option.name = "#{option.type}#{Array(20 - option.type.length).join(' ')}(#{currentVersion} -> #{option.outcome})"
```

**Comment by adam-lynch** [comment]
The only reason why I can see that you might pass an array of objects instead of an array of strings is so you can acess the chosen object.

**Comment by pauldijou** [comment]
@adam-lynch Actually, array of objects should contain objects with 2 keys: `name` and `value` where `name` is the message to display and `value` the object that will be selected.

Just add this `value`, something like:

```coffeescript
options.forEach (option) ->
        option.value = semver.inc currentVersion, option.type, 'rc'
        option.name = "#{option.type}#{Array(20 - option.type.length).join(' ')}(#{currentVersion} -> #{option.outcome})"

    inquirer.prompt
        type: 'list'
        name: 'bump'
        message: 'What type of bump would you like to do?'
        choices: [{name: "don't bump", value: false}].concat options
    , (result) ->
        # will be the incremented version or false
        console.log result
```

**Comment by adam-lynch** [comment]
@pauldijou Thanks! That's better. 

Note for anyone reading this issue looking to do something similar: it should be `result.bump`.

I'm going to close this because I'm happy with that. Not sure this is obvious in the readme but I'll leave that up to the maintainers.
