### ISSUE TITLE
Curious behavior on Windows commande line

### ISSUE THREAD

**Issue by korvus** [SBoudrias/Inquirer.js#249]
I don't think it's specific to inquirer, 
But I'm on windows 7, with node v0.10.21 ;
When I use a too long line in choices or input or whatever, then, when I trigger direction arrows, that duplicate the label; That really strange behavior ;
As this behavior happen only when the sentence get the edge of the consol, the "fix" I found is just to enlarge the command view (right click > properties > configuration > width for window size) ; But obviously, that's not a perennial solution...

Here a very simple exemple:

When not "touching" the edge, each time I press any key, that's work perfectly fine.  
![Good behavior](https://cldup.com/ncl6DZlzNk-1200x1200.png)  

If I change the cmd size...  
![Change size cmd](https://cldup.com/gYV-loEU6Y-1200x1200.png)

Then, each time I press directions arrows, that duplicate the label as below:  
![Bad behavior](https://cldup.com/LGI-5ftW65-3000x3000.png)
```
/**
 * issue example
 */

"use strict";
var inquirer = require("inquirer");


inquirer.prompt([
  {
    type: "checkbox",
    message: "Select toppings",
    name: "toppings",
    choices: [
      {
        name: "test-test-test-test-test-test-test-test-test-test-test-test-test-test-test-test-test-test-test-test-test-"
      },
    ]
  }
], function( answers ) {
  console.log( JSON.stringify(answers, null, "  ") );
});
```

**Comment by jonschlinkert** [comment]
also related https://github.com/SBoudrias/Inquirer.js/issues/214

**Comment by SBoudrias** [comment]
Fixed on master. Please test and let me know how it goes.

**Comment by korvus** [comment]
Will do it asap ; 
Thx for your work.

**Comment by jonschlinkert** [comment]
Great! thanks. I'll also report back after I have a chance to review. Thank you so much for the hard work!
