### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by wraithan** [SBoudrias/Inquirer.js#256]
I'm about to build with this module and notice it has 100k downloads a day but is not 1.0. This seems suspect. With that many users you have a stable, relied upon API and should probably 1.0 then move forward from there using semver to manage changes. If you disagree then closing this issue is valid, otherwise I'd love to see a 1.0 cut so I can semver match against that and be able to trust new updates.

**Comment by SBoudrias** [comment]
There's still a lot to figure out to the internal API and extensibility that should be fixed before I consider 1.0

FWIW I'm actively working towards that goal.

**Comment by wraithan** [comment]
You literally have over 100k downloads a day. If you are going to change anything in the API it will be backwards incompatible for all 100k/day users. They are already locked into your API, calling it 0.x is just making them not be able to pick up backwards compatible updates automatically... Seems like you should just cut a 1.x then, if you find yourself needing an API change, cut a 2.x.
