### ISSUE TITLE
Is it possible to adjust menu list height?

### ISSUE THREAD

**Issue by kokujin** [SBoudrias/Inquirer.js#257]
I am using a prompt type "list" with several items, it starts to "scroll-wrap" after 6 items and below is a notice, "Move up and down to reveal more choices".

Is there a way to stop the wrapping or adjust the number of items displayed? I would like to display all choices at the same time, for example. 

Thanks

**Comment by SBoudrias** [comment]
There's no option for this currently, and no plan to add it.

We might in the future be smarter and use the terminal height to determine the number of choice we display.

**Comment by ihorskyi** [comment]
Any updates on this?

**Comment by oleander** [comment]
+1. This is how my console looks right now. Would be nice if the height could adjust to the console.

![skarmavbild 2016-11-11 kl 18 33 24](https://cloud.githubusercontent.com/assets/220827/20224166/6fac0732-a83d-11e6-82dc-9441b1cf638e.png)

**Comment by SBoudrias** [comment]
PR welcomed to auto adjust the height.

**Comment by raisen** [comment]
It looks like this is possible by changing the pageSize parameter for the paginate prototype on utils/paginator.js - is that right?
