### ISSUE TITLE
Impossible to get fs paths from input prompt

### ISSUE THREAD

**Issue by petersandor** [SBoudrias/Inquirer.js#258]
Hi, I wonder if there is any way to retrieve filesystem paths from users, I tried using `input` prompts, but with no luck. 

After many attempts I realized that it won't go through if the string contains slashes. This is what I get: 

`>> Please enter a valid value`

I've tried to use `validate` function as a means to override internal validation, but that didn't help.

Does anybody have experience with something like this? Any help greatly appreciated!

Thanks!

**Comment by SBoudrias** [comment]
I can pass slashes to raw input field without any issue. My guess is you're using a validation function that doesn't allow them.

Inquirer does nothing at this level.

**Comment by petersandor** [comment]
You're right, I didn't `return true` properly in my validation function. Lesson learned, Thanks!
