### ISSUE TITLE
Is there a way to configure the page size of a list?

### ISSUE THREAD

**Issue by rodrigosendin** [SBoudrias/Inquirer.js#260]
Hello,

I am using the list prompt option, and I notice that the page size (of the visible items) is limited on 7 items. Is there a way to configure a higher page size?

Thanks!

**Comment by SBoudrias** [comment]
There is not.

We might parametrize the size to be the terminal window size eventually, but that's not in the next near future.

**Comment by timkelty** [comment]
Looking for this option as well.
