### ISSUE TITLE
async usage issue

### ISSUE THREAD

**Issue by lazabogdan** [SBoudrias/Inquirer.js#263]
Hey guys,

I have this simple use case where I'd like to use inquirer to recursively prompt the user for bower package names and validate the packages via the bower API using this.async. However, it's not working.

Could anyone please point me into the right direction? What am I doing wrong. I would appreciate any thought.

Here's the full code that I think it should work but doesn't:

``` javascript
var inquirer = require('inquirer');
var bower = require('bower');
var dependencies = [];

function ask() {

    var prompts = [{
        name: 'package',
        message: 'Please provide a bower package name (or press ENTER to exit)',
        default: false,
        validate: function(answer) {

            var done = this.async();

            if ( ! answer) {
                return done(true);
            }

            var error = "You must provide a valid bower package name. E.g. package, package#version, name=package#version, name=github/shorthand#version, etc";

            bower.commands.info(answer)
                .on('end', function(info) {

                    if (typeof info == 'undefined') {
                        return done(error);
                    }

                    done(true);
                })
                .on('error', function(e) {
                    done(error);
                });

        }
    }];

    inquirer.prompt(prompts, function(props) {

        if (props.package) {
            dependencies.push(props.package);
            ask();
        }

    });
}

ask();
```

Thank you.

**Comment by lazabogdan** [comment]
Still trying to make some sense of the weird behaviour I'm getting from this.

Tried the same thing using process.subscribe and the code is more similar now to the examples/recursive.

```javascript
var inquirer = require('inquirer');
var bower = require('bower');
var dependencies = [];

var prompts = [{
    type: 'input',
    name: 'package',
    message: 'Please provide a bower package name (or press ENTER to exit)',
    validate: function(answer) {

        var done = this.async();

        if ( ! answer) {
            return done(true);
        }

        bower.commands.info(answer)
            .on('end', function(info) {
                done(true);
            })
            .on('error', function(e) {
                done("You must provide a valid bower package name. E.g. package, package#version, name=package#version, name=github/shorthand#version, etc");
            });
    }
}];

function onEachAnswer(prop) {
    if (prop.name == 'package' && prop.answer) {
        dependencies.push(prop.answer);
        ask();
    }
}

function onError(error) {
    console.log(error);
}

function onComplete() {
    console.log(dependencies);
}

function ask() {
    inquirer.prompt(prompts).process.subscribe(
        onEachAnswer,
        onError,
        onComplete
    );
}

ask();
```

So, when I run this:
1. the prompt always shows up, asking for package names .. all good!
2. I type a package name (valid or invalid) .. all good!
3. Here's the weird part .. sometimes the validation works, for instance if I entered an invalid bower package name it displays the error message from validate immediately, but sometimes it gets stuck doing something, and it just doesn't display the error message until I press any keys repeatedly for a few times (any key, for example an arrow key)
4. Other times it works for a couple of loops, but then gets stuck again on what seems to be random intervals (sometimes after entering a valid package name, sometimes after entering an invalid package name, it just seems totally random).

Am I missing something obvious here?

**Comment by lazabogdan** [comment]
Ok, it's starting to look like a serious bug. I striped out bower from the equation and simply used a timeout like in the official examples.

I've got the same behaviour. Sometimes it displays the error message from validate, sometimes it doesn't until I press some keys.

```javascript
var inquirer = require('inquirer');
var dependencies = [];

var prompts = [{
    type: 'input',
    name: 'package',
    message: 'Please provide a bower package name (or press ENTER to exit)',
    validate: function(answer) {

        var done = this.async();

        if ( ! answer) {
            return done(true);
        }

        setTimeout(function() {
            done("false");
        }, 1000);
    }
}];

function onEachAnswer(prop) {
    if (prop.name == 'package' && prop.answer) {
        ask();
    }
}

function onError(error) { console.log(error); }
function onComplete() {}

function ask() {
    inquirer.prompt(prompts).process.subscribe(
        onEachAnswer,
        onError,
        onComplete
    );
}

ask();
```

I think it might have something to do either with my terminal (tried both iTerm2 and default terminal) or my OS (Mac OS X Yosemite 10.10.4). Just tried on a Linux machine and it works just fine, so definitely a bug!

Just spent the last 20h trying to solve this.

I'm using: 
- inquirer#0.9.0
- Mac OS X Yosemite 10.10.4
- node v0.12.2
- npm 2.13.2

It's also worth mentioning I initially began experiencing this as part of a yeoman generator using the latest yeoman-generator#0.20.0 which I can see is using inquirer#0.8.5.

**Comment by lazabogdan** [comment]
After updating to node v0.12.7 the issue seems to be solved.

**Comment by revelt** [comment]
@lazabogdan if it's solved, would you mind _closing this issue_ please? Thank you.
