### ISSUE TITLE
Using 'list' as the first input to a prompt fails

### ISSUE THREAD

**Issue by LPGhatguy** [SBoudrias/Inquirer.js#266]
Using Inquirer.js 0.9.0 and io.js 2.5.0 or Node 0.12.7 on Windows 10:

```js
var inquirer = require("inquirer");

inquirer.prompt([
	{
		type: "list",
		name: "exampleInput",
		message: "Does this work for you?",
		choices: [
			"Yes",
			"No",
			"I can't tell!"
		]
	}
], function(answers) {
	console.log("Done!");
});
```

The arrow keys won't move the menu, allowing selection of only the first choice.

**Comment by SBoudrias** [comment]
Which version of inquirer?

**Comment by LPGhatguy** [comment]
Woops, sorry, 0.9.0 from `npm`

**Comment by LPGhatguy** [comment]
Have you been able to reproduce the issue or look into it? I've confirmed that it still occurs on io.js `3.0.0`, and I'll be checking it out on Mac OS X this Monday when I stop into work since we're using Inqurier for our new generator system.

What's curious to me is that `yo` from the `yeoman` project, which uses Inquirer 0.9.0, doesn't seem to have the same issue despite having the first prompt as a list input.

**Comment by SBoudrias** [comment]
@LPGhatguy does it work with inquirer 0.8.0?

**Comment by LPGhatguy** [comment]
It does not.

**Comment by LPGhatguy** [comment]
This bug does not occur on OS X as far as I can tell, so it's probably something Windows specific.

**Comment by JCMais** [comment]
Same issue, it works on node 0.10.40

**Comment by leerlemoniii** [comment]
This is still an issue with windows 12 node 4.0.0..... in both command prompt and in powershell

**Comment by LPGhatguy** [comment]
Now that node 4.0 is the mainline release, this issue might affect more users.

**Comment by SBoudrias** [comment]
@LPGhatguy I don't have easy access to a windows machine. This seems to be a big issue for you, it'd be nice if you investigate and send a fix as a PR.

**Comment by artem-malko** [comment]
Is there any news?) I have the same problem in Windows 8.1 cmd and git bash.

**Comment by SBoudrias** [comment]
@artem-malko did you try with cmd.exe?

**Comment by artem-malko** [comment]
@SBoudrias yeap. And it doesn't work in cmd.exe. I have 3 lists, so, the first one doesn't work, but other are fine.
There is interesting behaviour with firtst list. When I press any button, I see a char from with button in console. It seems, that cmd just output all what I've entered.

**Comment by SBoudrias** [comment]
@artem-malko Looks like windows is not entering in the readline or tty mode...

**Comment by artem-malko** [comment]
@SBoudrias so, what can I do or it is a bug of Inquirer?

**Comment by SBoudrias** [comment]
Looks like a Node.js bug. I'd like to have more details to give them to repro, but I don't really have the time to dig this one further.

You should probably investigate the issue on your own (no need to use inquirer, just reproduce it using a Node readline) and report a bug on node.

**Comment by maxdow** [comment]
Yes it's a nodejs bug. I'm able to reproduce it only with readline. It is related to the keypress event that is not triggered correctly

**Comment by artem-malko** [comment]
@maxdow so, what can I do with that?

**Comment by maxdow** [comment]
I tried to solve the issue but without success :/ I don't have the time to investigate more before next week. I think the best is to report an issue to node linked to this issue ( the same exist for angular formly and probably somewhere else ) and with a simple reproductible example.

**Comment by SBoudrias** [comment]
@maxdow can you post the steps you took to reproduce here?

**Comment by maxdow** [comment]
I can't have access to my windows machine until Monday. I will post you my test code. 
The idea was to detect the keypress event using only readline and nodejs. I had the same result than  Inquirer : new line ( press enter ) was Ok but nothing on keydown .
Next i used the keypress module (https://www.npmjs.com/package/keypress)  and i was able to make it working. 
I'm pretty sure it's a bug from nodejs. Maybe you can try to use keypress in Inquirer.js as a fix but the best it's to find the real problem.

**Comment by SBoudrias** [comment]
I wonder if maybe Node is not detecting the windows cli as a TTY on the first run. We could try to force it in TTY and then try if it still fails for you.

**Comment by peterblazejewicz** [comment]
@SBoudrias 
We got an input about the issue that maybe somehow will help to trace the problem:
https://github.com/OmniSharp/generator-aspnet/issues/351#issuecomment-141696695
```
on the "yo -v" select list, arrows works fine
```
I'll try to help somehow as that is a core component of `generator-aspnet` (and probably many others).
Thanks!

**Comment by leerlemoniii** [comment]
my very hacky fix for this was to have a regular Y/N question that asked the user if they were ready to run my config.... this then allowed me to make the drop down be the second question.  mean user has to hit enter (defaults to yes), but it works after that.  I also wrapped this inside a check of if I was on windows so I only add this question if I need to.

**Comment by artem-malko** [comment]
@leerlemoniii I did the same thing, but it is not good way)

**Comment by peterblazejewicz** [comment]
@SBoudrias 
I'm not able to run these examples on my machine at work:
https://github.com/SBoudrias/Inquirer.js/blob/master/examples/checkbox.js
https://github.com/SBoudrias/Inquirer.js/blob/master/examples/list.js
https://github.com/SBoudrias/Inquirer.js/blob/master/examples/long-list.js
https://github.com/SBoudrias/Inquirer.js/blob/master/examples/nested-call.js
```
node -v: v4.1.0
npm -v: 2.14.3
Inquirer.js: v0.10.0
Windows OS:: 8.1
Tried CMD, Bash and PowerShell terminals.
Let me know where too start with code to debug issue.

**Comment by peterblazejewicz** [comment]
The tests pass OK on the same machine:
https://gist.github.com/peterblazejewicz/162289a5f2ef93554293

**Comment by SBoudrias** [comment]
I've open an issue on Node side. https://github.com/nodejs/node/issues/2996

Any help from someone here (able to consistently reproduce the bug) would be very useful. A step by step test case to reproduce the issue with a raw readline would be awesome.

(also ping @maxdow)

**Comment by maxdow** [comment]
I do a minimal example and i run this on win8 and  win xp  : 
```
var readline = require("readline");


var rl = readline.createInterface(process.stdin, process.stdout);

rl.on("line",function(){
  console.log("line event");
});

process.stdin.on("keypress",function(){
  console.log("keypress");
});
```
On the win8 computer, i don't have the keypress event triggered at first. I have to press enter to "trig" the keypress event. On win xp there is no problem, i got keypress and line events separatly.
I suppose it works on linux too

Inquirer.js list works fine on win xp that's why I suppose it's related to node

**Comment by mzgol** [comment]
@maxdow Could you repost that at https://github.com/nodejs/node/issues/2996 so that core Node folks have a test case to try?

**Comment by maxdow** [comment]
done ;)

**Comment by artem-malko** [comment]
@maxdow @mzgol @SBoudrias @peterblazejewicz so, we have to wait for new Node release?

**Comment by maxdow** [comment]
Probably, or use a patch with [keypress](https://github.com/TooTallNate/keypress ) on Inquirer.js ..

**Comment by peterblazejewicz** [comment]
@maxdow 
just observation: I've got the same problem with `keypress` - as you described I had to hit Return (Enter) key first to get listener broadcasting keypresses.

**Comment by philkunz** [comment]
any update here?

**Comment by SBoudrias** [comment]
Anyone tried on the latest node? If it's not fixed yet, you should ping them on their bug thread.

**Comment by peterblazejewicz** [comment]
@SBoudrias I'll do this with LTS version. Thanks!

**Comment by peterblazejewicz** [comment]
@SBoudrias 
Tested on Win8.1: it seems that Node 5.1.1 Stable comes with fix.:
```
PS C:\Users\pibl> node --version
v5.1.1
```
The 5.1.1 works with CMD and PowerShell terminals. I was not able to get it worked with Bash terminal.
The LTS 4.2.3 version does not contain a fix I think.
Thanks!

**Comment by SBoudrias** [comment]
Bash (like git bash and cie) terminals don't support readlines on Windows. They're very bad emulator.

**Comment by peterblazejewicz** [comment]
> Bash (like git bash and cie) terminals don't support readlines on Windows. They're very bad emulator.
Understand. Just posting facts for the records. Thanks for the comments!

**Comment by peterblazejewicz** [comment]
@LPGhatguy  
It seems to be fixed in Node:
https://github.com/nodejs/node/issues/2996

**Comment by LPGhatguy** [comment]
It appears to work in 5.3.0 for me -- thanks for pointing that out!

**Comment by peterblazejewicz** [comment]
@SBoudrias Thanks for the patience :bow:

**Comment by AlexGustafsson** [comment]
Still not working for me. I thought this was solved by the Node JS team?

Windows 10,
CMD & Babun(Cygwin),
Node v5.6.0.

**Comment by SBoudrias** [comment]
There's a regression on the node side. The team is investigating.

**Comment by AlexGustafsson** [comment]
@SBoudrias is there any related issue I can follow?

**Comment by SBoudrias** [comment]
https://github.com/nodejs/node/issues/5384

**Comment by jokeyrhyme** [comment]
I have a module that helps identify broken versions of Node:

- https://github.com/jokeyrhyme/is-node-interactive-tty-broken

Do you think it might be worth integrating a similar check into this library? So that a warning or something could be displayed? Or perhaps modifying the "engines" part of package.json to help avoid broken Node versions at installation time?

**Comment by SmasherCoder** [comment]
Still broken in inquirer 8.2.0 node 16.13.1 on Windows 11 in a Terminal in VS Code
