### ISSUE TITLE
Support fancy characters on Windows 10

### ISSUE THREAD

**Issue by LPGhatguy** [SBoudrias/Inquirer.js#267]
Windows 10's command prompt now has a nice monospace font with Unicode support by default in the console. Right now, controls like the checkbox look kind of awful on Windows, unlike *nix: http://i.imgur.com/TNvSgRz.png

Would it be possible to support Windows 10 as a first-class character system in Inquirer?

**Comment by SBoudrias** [comment]
The symbols inquirer is using are provided by: https://github.com/sindresorhus/figures

You should open an issue over there! (please link to this issue so we have a trace)

**Comment by LPGhatguy** [comment]
@SBoudrias: I opened an issue on the repository and submitted a fix for `io.js` to make this all work out.

I have doubts that this will land in figures all that soon, would you be open to using a fork of inquirer until functionality like that would be merged? I'm not familiar with npm etiquette on that subject.
