### ISSUE TITLE
Password default should be masked

### ISSUE THREAD

**Issue by jo** [SBoudrias/Inquirer.js#270]
When using a default for the password it should be masked.

Eg:
```sh
? What is your npm password? (**************)
```

My use case is that I want to store the password with [keytar](https://github.com/atom/node-keytar) and want to allow the user to change it.

**Comment by SBoudrias** [comment]
I believe you can implement to logic to mask the previous password in your own code. The `default` value is used as is and is provided directly by the user. It is then totally possible for you to mask it without Inquirer doing anything.

As so, I'll close this issue as I prefer this logic to be kept on the user side.

```js
inquirer.prompt({
  default: mask(previousPassword),
  // etc...
});
```

**Comment by jo** [comment]
That way the answer would include the masked password.

**Comment by smeijer** [comment]
would indeed be useful to me: 

```js
const { password } = prompt({
  name: 'password',
  type: 'password',
  mask: '*',
  default: process.env.PASSWORD,
});
```

**Comment by wanthering** [comment]
> would indeed be useful to me:
> 
> ```js
> const { password } = prompt({
>   name: 'password',
>   type: 'password',
>   mask: '*',
>   default: process.env.PASSWORD,
> });
> ```

that solve my problem
