### ISSUE TITLE
Use lodash modules

### ISSUE THREAD

**Issue by Downchuck** [SBoudrias/Inquirer.js#275]
Lodash comes in modular forms, which may be more appropriate for the light use in this library:
https://www.npmjs.com/browse/keyword/lodash-modularized

Currently lodash is 2.1M of the total 2.9M that inquirer.js distributes as when unpacked.

**Comment by SBoudrias** [comment]
Feel free to send a PR

**Comment by sindresorhus** [comment]
:+1:

**Comment by seethemhigh** [comment]
Allow me to chime in. I've got the PR ready for the submission. Shall I send it out? @Downchuck does not mind?

**Comment by Downchuck** [comment]
That's fine with me. We did find in another project, that if you include many lodash modules, the aggregate size of the license files is unreasonable.

**Comment by seethemhigh** [comment]
Thanks!

That's amusing. Same thing happens here. That's only increased the size of the package. Not worth it. I think the issue can be closed.

**Comment by dthree** [comment]
@SBoudrias this is a really big deal for me. 

As you know [Vorpal](https://github.com/dthree) is a big user of Inquirer. 

I have been trying to make Vorpal as slim as possible:

- Like Inquirer, it's a user-downloaded module. That means someone types `npm install` stares at terminal waiting for the library depending on Inquirer / Vorpal to download. Speed is of the essence.

- The slimmer the module, the more willing someone will be do include it as a dependency. 

Right now, the latest lodash version is taking 61% of Inquirer's total size. Vorpal has the same problem, also depending on lodash.

I've been thinking long and hard about how to handle this, and so I'm proposing a solution I hope you're okay with.

---

[I published a repo](https://www.npmjs.com/package/mindash) that mirrors the latest build of lodash and matches its semver. It's simplied the minified build of the core library. 

- That means it's `68KB` unzipped, instead of `1.07MB`. **Thats a big difference.**

- This reduces Inquirer's size from `1.71MB` unziped to `727KB`.

As you may have a concern on depending on something unofficial, know I've already published it in Vorpal and so have a vested interest in keeping it up to date. *I've also given you publishing rights to the module, so you don't have to depend on me if you need it updated right away.*

---

I've submitted a Pull Request that uses the minified module instead of lodash, with passing tests:

https://github.com/SBoudrias/Inquirer.js/pull/335

---

Does this sound okay to you? Thanks.

**Comment by jdalton** [comment]
I don't think an unofficial [mindash](https://www.npmjs.com/package/mindash) is necessary for the case of `npm i`. The lodash v4.5.0 package is is 245kb over the wire to `npm i` it.
If I'm not mistaken npm installs should be cached by npm too so it's a one time cost per version.
See @othiym23 comments:

> When packages are in the cache, the initial metadata request sends the cached etag for the package, and in the vast majority of cases, the registry will return a 304 and the package tarball won't need to be downloaded again.
...
> it's always going to fire off a request to see if it has the latest version of a resource. Having an "offline" or "use the cache only" mode would prevent those network checks, and, barring what changes would come from making the cache content-addressable / read-through by fetching tarballs from the cache by their shasums, not the default mode for the cache, now or in the planned future. Discussion about how StrongLoop uses optionalDependencies belongs over there, and is not a part of this discussion.

**Comment by jdalton** [comment]
So by using `mindash` you're actually increasing the cost for most folks.

**Comment by Downchuck** [comment]
This issue pops up for quite a few projects; it's possible the lodash upstream project may have opinions on it.

I do see a benefit.

**Comment by jdalton** [comment]
If the cache isn't working, and there's a real issue, then yep lodash core is interested in helping. However, if the npm cache is working, then it's just about getting that knowledge spread. I see this comes up from time to time from those super interested in file size but without the background knowledge of how npm works or know how of bundlers/minifiers.

**Comment by dthree** [comment]
@jdalton thanks.

I do understand how NPM caching works, and have been over this before. However, for first-time installs, it is still taxing. For example, I'm about to [release an app](https://github.com/vorpaljs/cash) that's going to have a ton of first-time installs as it reaches to a different public.

I get that gzipped, you'll get lodash at 245kb over the wire. That's good, but if you gzip lodash minified, that's 21kb over the wire - 8% of the cost.

I guess my main question is this: would it really be so terrible for lodash core to support an official, automated minified version over NPM that would publish with zero thought or effort, [like the individual modules](https://www.npmjs.com/package/lodash.uniq)? It would very rapidly adopt a ton of dependencies and so pick up on cache saves, thought at 21kb that's almost no problem anyways.

I have no desire to publish mindash and will remove it any day for an official module, and I'd willingly do all the work to help you guys build an official bundler. I guess my question is, can we possibly look at this?

Thanks.

**Comment by jdalton** [comment]
>  However, for first-time installs, it is still taxing. 

If lodash has already been installed on their system then it should be cached regardless of your package release.

> That's good, but if you gzip lodash minified, that's 21kb over the wire - 8% of the cost.

Again, it's a one time cost. A cost that's likely already been paid.

**Comment by jdalton** [comment]
So what you're doing is adding extra download time to your app because changes are `mindash` is uncached and will require a download.

**Comment by jdalton** [comment]
Let's put it another way. 46,977 packages depend on `lodash` in some way. That's 46,977 opportunities of it to be cached. None currently published depend on `mindash`

**Comment by jdalton** [comment]
If you want a greater chance of it being cached use `lodash@^3.0.0` as it has a greater number of package dependents.

**Comment by dthree** [comment]
Totally got it on your points. I'm completely all for official builds with a ton of dependents. With in mind, could you please let me know your thoughts on the latter half of my last, concerning why there can't be an official minified module?

> I guess my main question is this: would it really be so terrible for lodash core to support an official, automated minified version over NPM that would publish with zero thought or effort, like the individual modules? It would very rapidly adopt a ton of dependencies and so pick up on cache saves, thought at 21kb that's almost no problem anyways.

> I have no desire to publish mindash and will remove it any day for an official module, and I'd willingly do all the work to help you guys build an official bundler. I guess my question is, can we possibly look at this?

**Comment by jdalton** [comment]
I think your micro-optimizing and obsessing to the point of actually adding a cost to your users. On 3g lodash as is takes maybe 1 second to download on a fresh non-cached install. I've put in to have `mindash` removed from the registry I'll let the npm admins take it from there.

**Comment by jdalton** [comment]
> I guess my main question is this: would it really be so terrible for lodash core to support an official, automated minified version over NPM that would publish with zero thought or effort, like the individual modules?

The individual modules take a considerable amount of effort. Every additional build has a cost to maintain.  I don't see this as adding value and worse it promotes misinformation about size, caching, & priorities. I don't want devs falling into this trap I'm not going to help push them in.

**Comment by SBoudrias** [comment]
After reconsidering and going through @jdalton answer. I think we should drop this issue. We're using lodash a lot inside of Inquirer, there's really no reason to start using only specific modules until we rely less on lodash.

**Comment by dthree** [comment]
I'm okay with this.
