### ISSUE TITLE
Using `.process.subscribe()` messes up the display.

### ISSUE THREAD

**Issue by yaru22** [SBoudrias/Inquirer.js#276]
If I use the following code, questions are displayed properly (see the screenshot below):

```js
var _ = require('lodash');
var inquirer = require('inquirer');

inquirer.prompt([
  {
    type: 'list',
    name: 'questionA',
    message: 'Question A?',
    choices: ['Yes', 'No'],
  },
  {
    type: 'list',
    name: 'questionB',
    message: 'Question B?',
    choices: ['Yes', 'No'],
  },
])
```
![screen shot 2015-08-25 at 8 39 24 pm](https://cloud.githubusercontent.com/assets/49256/9483071/68d915b2-4b69-11e5-9b18-ccaafd46358f.png)

However, if I use `.process.subscribe()`, it messes up the display a bit.

```js
var _ = require('lodash');
var inquirer = require('inquirer');

inquirer.prompt([
  {
    type: 'list',
    name: 'questionA',
    message: 'Question A?',
    choices: ['Yes', 'No'],
  },
  {
    type: 'list',
    name: 'questionB',
    message: 'Question B?',
    choices: ['Yes', 'No'],
  },
])
.process.subscribe(_.noop, _.noop, function () {
  console.log('Completed.');
});
```
![screen shot 2015-08-25 at 8 40 56 pm](https://cloud.githubusercontent.com/assets/49256/9483079/a3d05482-4b69-11e5-9689-a388e78cafdc.png)

I'm using version 0.9.0 with Node 0.12.7 on Mac.

Thanks.

**Comment by rtsao** [comment]
I'm getting the same issue

**Comment by SBoudrias** [comment]
Ok, I could reproduce this bug. Not sure what on rx.js side is breaking that flow. I'll investigate.

**Comment by SBoudrias** [comment]
Well, the bug is pretty simple to find.

Basically when you add an extra listeners, each items in the array get processed again (this here is going to get called twice https://github.com/SBoudrias/Inquirer.js/blob/master/lib/ui/prompt.js#L61).

Gonna have to read RX documentation to see how to not rerun the whole process for each listeners... Pr welcomed.
