### ISSUE TITLE
Keypress: `{ control: true }` does not register on `[control] + [backspace]`

### ISSUE THREAD

**Issue by dthree** [SBoudrias/Inquirer.js#277]
On listening for a keypress, `control` reads `false` when I do a `[control] + [backspace]`, however `control` reads `true` on other characters, like `control + s`.

I looked through all of the inquirer code and it doesn't seem to be dealth with - it could be a readline problem, or whatever is actually triggering the events.

**Comment by SBoudrias** [comment]
Can you explain which part of inquirer you're using?

**Comment by dthree** [comment]
@SBoudrias It's not a public API feature per say. This can be found in overwriting your `onKeyPress` event:

```js
    inquirer.prompt.prompts.input.prototype.onKeypress = function(e) {
      // This reproduces the keypress event I am talking about.
      // Right this event does not capture [control] + [backspace].
      console.log(e);
      // Your default functionality for handling keypress.
      this.render();
    };
```

T'hanks!

**Comment by dthree** [comment]
Btw, I'd love to get in touch with you, if you'd like. I've been putting a lot of work into [Vorpal](https://github.com/dthree/vorpal) / [Vantage](https://github.com/dthree/vorpal) and these are totally based on `inquirer` (I credit you). I'm trying to build Vorpal into a pretty robust framework for CLI apps, and `inquirer` is no small part in this. If you're interested, i'd love to throw ideas back and forth with you.

**Comment by SBoudrias** [comment]
Feel free to contact me if you'd like.

For your issue, it's because we drop the ctrl key on the utility transforming keypress events into rx streams. https://github.com/SBoudrias/Inquirer.js/blob/master/lib/utils/events.js It'd be trivial to add the any extra details to the events being send around. PR welcomed.

**Comment by dthree** [comment]
Thanks.

Hmm: Didn't see any code there that explicitly drops it. Also, I tried this:

```js
process.stdin.on('keypress', function(value, key){
  console.log(key);
});
/*
{ sequence: ',
  name: 'backspace',
  ctrl: false,
  meta: false,
  shift: false }
*/
```
Unless you're somehow magically manipulating `process.stdin`, this doesn't look like your problem, does it?

**Comment by SBoudrias** [comment]
Oh yes, if you don't see it on a raw keypress event on stdin, then I don't know what your issue is.

Also, you're correct, I wrongly assume we were deleting the ctrl key data, but it's kept through the stream.

I'll close this issue as it doesn't seem related to inquirer.

**Comment by dthree** [comment]
K no problem. Do you happen to know what lib the keypress event comes from?

**Comment by SBoudrias** [comment]
Oh yes, we're mirroring the event on the readline here: https://github.com/SBoudrias/Inquirer.js/blob/master/lib/ui/baseUI.js#L67

That should be removed. I'll reopen to take note.

**Comment by dthree** [comment]
K thanks.

But looking at `readline`, it doesn't emit `keypress` events! Only a `line` event from any docs I can see. I'm trying to see where the keypress event comes from. Odd.

**Comment by SBoudrias** [comment]
Oh, readline is an EventEmitter. Inquirer is manually triggering keypress on the readline when they occurs on the input stream.

**Comment by dthree** [comment]
You're right. I verified this as a node bug and filed.

https://github.com/nodejs/node/issues/2890

**Comment by SBoudrias** [comment]
I removed the hack triggering the keypress on the readline today.

**Comment by dthree** [comment]
Thanks!
