### ISSUE TITLE
Inquirer 0.9.0 displayed list is too small!

### ISSUE THREAD

**Issue by dubeej** [SBoudrias/Inquirer.js#278]
It appears that prompts of type checkbox, and list display only seven items at a time, and the user has to scroll through the list to see more items. Is there a configurable setting to display more items, or is a length of seven hardcoded into the module?

**Comment by SBoudrias** [comment]
There's a lot of other issue about this subject on the bug tracker. Please research your issue before opening a new one.

**Comment by dubeej** [comment]
Thanks for all the help!
