### ISSUE TITLE
Allow setting input and output

### ISSUE THREAD

**Issue by ruyadorno** [SBoudrias/Inquirer.js#279]
Resurrecting the ideas from #188 #197 

I just stumbled upon a use case where having the `ttys` module support that @naholyr added would have saved the day (basically reading from stdin and prompting user with info taken from there).

By reading through the history of these PRs it seems to me that `ttys` turned out to be a very unreliable module that unfortunately only worked on some terminals and eventually all the changes got reverted :disappointed: 

@SBoudrias would you be open to implement back the possibility of setting input/output but defaulting to `process.stdin`/`process.stdout` instead? That would at least allow use cases like the one I have to deal with now, to opt-in for `ttys` or to use some other better solution in the future.

**Comment by SBoudrias** [comment]
Yes, I totally want to allow a user to set input/output stream manually.

It just requires a bit of a refactor.

**Comment by ruyadorno** [comment]
would it be the same refactor from #197 ? (excluding adding `ttys` again of course)

**Comment by SBoudrias** [comment]
Similar to it yes, but I'm pretty sure there's place where we're calling `process.stdout` directly. I remove them as I fall on them, but there might be some still around.

**Comment by ruyadorno** [comment]
got it, I might give it a try and send a PR in the next few days :blush: thanks!

**Comment by naholyr** [comment]
Well done :)
