### ISSUE TITLE
stdin/stdout cli-width issue

### ISSUE THREAD

**Issue by ruyadorno** [SBoudrias/Inquirer.js#285]
One small issue I found while playing with the possibility of setting an `stdin`/`stdout` introduced on #280 is that the [cli-width](https://github.com/knownasilya/cli-width) dependency is still using `process.stdout` directly.

In my specific case I could get a workaround by using its `defaultWidth` property but it's definitely going to be problematic for people wanting to define their own input/output streams.

**Comment by SBoudrias** [comment]
You should probably open an issue on cli-width package.
