### ISSUE TITLE
Cannot press space to select

### ISSUE THREAD

**Issue by tienloc1** [SBoudrias/Inquirer.js#288]
I used windows 8.1 and generator-webapp but I cannot press space to select my choice. Please check my screenshot.

![Image of webapp] (https://cloud.githubusercontent.com/assets/3436941/10119401/3fec0a64-64bf-11e5-8370-83cdca6fdc64.jpg)

Maybe is bug? Or there away to fix it? Thank so much for help!

p/s: I tried to report my issue in generator-webapp issue, but they assign me to here.

**Comment by SBoudrias** [comment]
This is a node issue, we're tracking it on https://github.com/SBoudrias/Inquirer.js/issues/266

**Comment by navehazan** [comment]
did u resolve this problem ? i have the same issue
