### ISSUE TITLE
Default value callback not called when used in recursion

### ISSUE THREAD

**Issue by cravecode** [SBoudrias/Inquirer.js#292]
If I'm recursively prompting a set of questions, the default value of a question is the generated value from the first iteration. It appears that a default value callback is not called on successive prompts of the same question.

**Comment by kokujin** [comment]
Does anyone have a solution for this issue? Thanks

**Comment by SBoudrias** [comment]
Inquirer re-process every input everytime it's called. There's no cache.

I'll need some code to see what you're doing that might break.

**Comment by SBoudrias** [comment]
Closing as inactive. Feel free to reopen if you provide reproduction steps.
