### ISSUE TITLE
Duplicated prompt on Windows

### ISSUE THREAD

**Issue by iamakulov** [SBoudrias/Inquirer.js#294]
Hi,

I’m working on a Yeoman generator. The following code makes a prompt to a user:

```js
this.prompt({
    message: 'How would you like to name the control?',
    type: 'input',
    name: 'controlName',
    default: currentDir
}, answer => {
    this.controlName = answer.controlName;
    done();
});
```
The produced prompt is duplicated after the user answers the question:

![Demo](http://i.imgur.com/kYn0QLn.gif)

This is reproducible both in PowerShell and in `cmd.exe`.

Is there a way to fix this behavior or work around it?

**Comment by gxoptg** [comment]
Whoops, sorry, I was wrong about `cmd.exe` working properly. Removed that line.

**Comment by EladBezalel** [comment]
+1

**Comment by hrbu** [comment]
+1 The same in git-bash on Windows.

**Comment by karol-f** [comment]
Same is on OSX iTerm2

**Comment by SBoudrias** [comment]
This should work fine on the latest release now.

**Comment by iamakulov** [comment]
Amazing, thanks!

Could you please point to the commit that fixes it? Just interested what was the reason.

**Comment by SBoudrias** [comment]
@iamakulov not sure anymore, it's been fixed for a while.
