### ISSUE TITLE
Better error message when running inquirer in a context where cliWidth equals zero

### ISSUE THREAD

**Issue by jviotti** [SBoudrias/Inquirer.js#296]
Running an inquirer widget inside a script called with [windosu](https://www.npmjs.com/package/windosu) for example, where `cliWidth()` equals `0`, throws the following error:

```
Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
```

Which comes from https://github.com/SBoudrias/Inquirer.js/blob/master/lib/utils/screen-manager.js#L108.

Assuming there is no reliable way to get a meaningful `cliWidth` number out of contexts like this, I suggest checking it's return value and if zero, show a more descriptive message like:

> inquirer cannot run in this context

Or something like that. What do you think?

**Comment by SBoudrias** [comment]
Duplicate of https://github.com/SBoudrias/Inquirer.js/issues/290

**Comment by jviotti** [comment]
@SBoudrias The two issues, while similar in the surface, mention different problems. With `windosu`, if I just mock the return value of `cliWidth` inquirer *does* run (`stdio` is inherited).

**Comment by SBoudrias** [comment]
The context is different, the issue is the same. Inquirer should handle a cli width of 0 by setting a baseline default value.

**Comment by jviotti** [comment]
Yeah sorry, I deleted the message before you posted that one. I believe you updated the link since it was pointing to another issue before.
