### ISSUE TITLE
Terminal breaks when input is too wide

### ISSUE THREAD

**Issue by dthree** [SBoudrias/Inquirer.js#299]
Minimally on the standard OSX Yosemite 10.10.4 terminal, the prompt goes whack when text extends beyond the end of the line.

See this link for more details:

https://github.com/dthree/vorpal/issues/23

**Comment by scotthovestadt** [comment]
Confirmed this happens in raw Inquirer.js as well as Vorpal. In screen-manager.js, if I console.log every time input is detected, I can go to 2 lines (and on the third line this happens). Seems related to screen-manager.js.

![blankthoughtfulhyracotherium](https://cloud.githubusercontent.com/assets/1831484/10547577/2cd124ac-73ea-11e5-8642-279622d5b4e7.gif)

**Comment by scotthovestadt** [comment]
Note that the attached behavior only happens until it reaches the top of the screen and then it behaves somewhat normally.

**Comment by scotthovestadt** [comment]
Using require('cli-clear')() will reset terminal input and everything works correctly from that state. If terminal input is pushed to bottom again this resumes happening.

**Comment by SBoudrias** [comment]
This is the same bug as #261 - I'll close this one in favor of this other one who contains lot more details as to why this behavior is happening.

**Comment by dthree** [comment]
kk
