### ISSUE TITLE
Use Rx.Subject?

### ISSUE THREAD

**Issue by djskinner** [SBoudrias/Inquirer.js#302]
Using `Rx.Observable` works for me but `Rx.Subject` does not.

For example the following works:

```
var prompts = Rx.Observable.fromArray([questions.a, questions.b, questions.c]);
inquirer.prompt(prompts).process.subscribe(function onEachAnswer(answer) { ... }
```

But the following does not:

```
var prompts = new Rx.Subject();
prompts.onNext(questions.a);
prompts.onNext(questions.b);
prompts.onNext(questions.c);
inquirer.prompt(prompts).process.subscribe(function onEachAnswer(answer) { ... }
```

I want to use a Subject so that I can add further questions to the stream depending on answers to previous questions.

Any idea why the prompt just doesn't display when using `Rx.Subject`?

**Comment by SBoudrias** [comment]
Is there a chance the RX versions just mismatch?

**Comment by djskinner** [comment]
I just tried using "rx-lite": "^3.1.2" and it has the same issue.

**Comment by SBoudrias** [comment]
So, I think Rx.Subject is a hot observable. That means it won't replay event who've already been dispatched. You'd use it as so:

```js
var prompts = new Rx.Subject();
inquirer.prompt(prompts).process.subscribe(function onEachAnswer(answer) { ... }
prompts.onNext(questions.a);
prompts.onNext(questions.b);
prompts.onNext(questions.c);
```

See the `onNext` calls happens after inquirer binded the Observable object.

**Comment by djskinner** [comment]
Ah I see. Perhaps a `ReplaySubject` was what I was looking for.
