### ISSUE TITLE
Possible to select all or none?

### ISSUE THREAD

**Issue by loveencounterflow** [SBoudrias/Inquirer.js#308]
When presenting a long checkbox list, it would be great if one could select all options, no options or invert choices with a single keystroke (such as `a`, `n`, `i`). Is something like that possible or can it be implemented using the current API?

**Comment by BlueHotDog** [comment]
:+1:

**Comment by senshuu** [comment]
I've submitted a Pull Request to implement the features proposed in this request. Options to select all, none, or the inverse have been implemented. Additionally, I implemented a "random" function as well, just for scenarios that may call for random choice selection. Please feel free to remove the 'random' option though, if it's not desired.

**Comment by SBoudrias** [comment]
Done on master.
