### ISSUE TITLE
Unicode checkbox

### ISSUE THREAD

**Issue by sindresorhus** [SBoudrias/Inquirer.js#31]
Not sure if it would be feasible, but might consider using unicode symbols:

☐☑☒ though I fear these might be too small.

or just a checkmark on the chosen one and nothing on the others: ✔

or same as above, but an other symbol: ❯ ➤ ➔

Could also consider using unicode combinators:
http://unicodinator.com/#20E3 combined with ✔ makes ✔⃣   or    ✖⃣

or this http://unicodinator.com/#20DD combined with ✔ makes ✔⃝    or   ✖⃝

**Comment by mikedevita** [comment]
Is there a way to force inquirer to use checkboxes and not unicode characters?

**Comment by SBoudrias** [comment]
@mikedevita no, that's not a feature at the moment. Are you running somewhere where unicode is not supported?

**Comment by mikedevita** [comment]
Were a shop which runs windows and uses putty to connect to RHEL servers and can't reliably set putty to use fonts which support unicode...

Rather than fixing all our machines to use a unicode font I'd rather just use plaintext and bypass the issue.
