### ISSUE TITLE
this.async() not compatible with ES6's arrow function.

### ISSUE THREAD

**Issue by Amberlamps** [SBoudrias/Inquirer.js#310]
With the uprise of ES6 people will intuitively write:

```
validate: (input) => {
  let done = this.async();
  done(true);
}
```

But this obviously throws an error as `this` is now pointing to the `questions` array itself rather than to whatever Inquirer elects as `this`.

`TypeError: this.async is not a function`

Ideally I would like to change the function's signature to `validate: (input, done) => {}`, but that is not at all backwards compatible and would break a lot of code.

I will use good old anonymous functions for now, but I thought this issue is worth mentioning.

**Comment by SBoudrias** [comment]
You can return a promise.

Also, ES6 didn't deprecate `function () {}`

**Comment by keithamus** [comment]
Hey @SBoudrias you mention that I could return a Promise instead of using this.async.

I had assumed this to be the case for `when` - but it seems not to be. (Using inquirer 0.11.0).

Here you can see I'm trying it in the Node repl:

```js
$ node
> var inquirer = require('inquirer');
> var q = {
...  name: 'test',
...  message: 'This shouldn't come up because `when` resolves to false',
...  when: function () {
...    return Promise.resolve(false);
...  }
...};
> inquirer.prompt(q, console.log.bind(console));

? This shouldn't come up because `when` resolves to false
```

It looks like the problem is that `run-async` is [only version 0.1.0](https://github.com/SBoudrias/Inquirer.js/blob/master/package.json#L32) in Inquirer's package.json. Would you like me to PR an update to 2.0.0?

**Comment by SBoudrias** [comment]
@keithamus oh yes, PR welcomed. It might be blocked a while though as master is broken on windows and I haven't really got the time to investigate that further.

**Comment by keithamus** [comment]
Is there an issue for Windows breaking? Do you know the commit that caused it?

**Comment by SBoudrias** [comment]
@keithamus no ticket, it's just part of refactor/fixes to issue with implicit line returns https://github.com/SBoudrias/Inquirer.js/commit/6e269f05ebc49383398b8504dc65a5c7cd0806c0

If you feel like investigating, windows add an extra empty line between each line. I feel like it automatically send the cursor to the next line after writing a line (maybe).
