### ISSUE TITLE
if both checkbox select, return value

### ISSUE THREAD

**Issue by yashilanka** [SBoudrias/Inquirer.js#314]
how to get return value form if both checkbox select, i hope this is a simple one. i tried several methods but none of them working.

**Comment by SBoudrias** [comment]
What do you mean?

**Comment by yashilanka** [comment]
ok here is the example

 i'm asking what do you want to backup, and there are two answers(checkbox) one is src folder another one is build folder, when someone check both option then both are created, i have try length, check, truthy, equal things but none of them working. but when someone choose one of answers then it build backup according to what he choose. i need to check if both are checked. that is what i want to do.. thanks if you can help me.. i know this is simple thing. but this simple thing won't work. can someone suggest a simple solution

**Comment by SBoudrias** [comment]
Well, the checkbox will return the choices in an array value. So just check what this array contains.

This is not an issue with the project, and it looks like a basic JS question. Please refers to StackOverflow with a reduced test case if you need further help.

**Comment by yashilanka** [comment]
i figure it out.. thanks
