### ISSUE TITLE
Display default value?

### ISSUE THREAD

**Issue by gsklee** [SBoudrias/Inquirer.js#315]
Can we have default values displayed somehow?

**Comment by SBoudrias** [comment]
What do you mean?

**Comment by mxstbr** [comment]
Like a placeholder, giving the users an example of what the answer to the input might look like. I've had this request a few times, and think it'd be really useful!

**Comment by SBoudrias** [comment]
@mxstbr doesn't the `default` option enough?

Also, if you need specific formatting or answers, then other prompts like lists might be more appropriated. Or using a filtering/validator function.

**Comment by mxstbr** [comment]
The problem is that you don't show the `default` afaik. So as a user, I have no idea what I should put in the input.

An example would be a question after a twitter username, should I include the `@`, should I not include it,...?

**Comment by SBoudrias** [comment]
@mxstbr the default is displayed. Maybe you don't see it because or your terminal color theme?

**Comment by mxstbr** [comment]
Oooh nice, this issue can be closed then I guess. Thanks!

**Comment by sakulstra** [comment]
Stumbled over this a real `placeholder` would be nice and `default` is not exactly the same.

With default you will always have a value, even on optional fields - i imagine a placeholder to work more like a `hint` on how to type.
