### ISSUE TITLE
Access previous answers in current answer

### ISSUE THREAD

**Issue by eurochriskelly** [SBoudrias/Inquirer.js#318]
I'd like question X+1 to know the answer from question X.
In the following example I use validate to get the desired effect. 

Is there a way to get access to the answers object before it's been passed to the callback?

                
    var min = 0;
    var prompts = [
            {
                type: 'input',
                name : 'min',
                message : 'min?',
                validate : function (m) {
                    min = m;
                    return true;
                }
            },
            {
                type : 'input',
                name: 'max',
                message : function () { return 'max greater than ' + min; },
                validate : function (m) {
                    return (m > min);
                }
            }
    ];
    inquirer.prompt(prompts, function (answers) {
        // do stuff with answers
    });

**Comment by SBoudrias** [comment]
Nest the prompts - Inquirer is only javascript.

**Comment by eurochriskelly** [comment]
Thanks for the quick response. I prefer my own hack to nesting though. I was thinking it would be nice to make answers accessible as another parameter to the validate callback or perhaps to a ```before``` hook.

**Comment by SBoudrias** [comment]
Most inquirer functions get an answer object as parameter. Pretty sure validate have it too.

**Comment by eurochriskelly** [comment]
Ok, that's great. thanks. I can ditch the closure now:

    var prompts = [
            {
                type: 'input',
                name : 'min',
                message : 'min?'
            },
            {
                type : 'input',
                name: 'max',
                message : function (answers) {
                    return "max: must be greater than " + answers.min;
                },
                validate : function (m, answers) {
                    return (m > answers.min);
                }
            }
    ];
    inquirer.prompt(prompts, function (answers) {
        // do stuff with answers
    });
