### ISSUE TITLE
Feature: List choice config for arbitrary value option

### ISSUE THREAD

**Issue by atomantic** [SBoudrias/Inquirer.js#319]
would be great to allow a list to be configured with an 'arbitrary' boolean option.
```
var inquirer = require("inquirer");
inquirer.prompt([{
  type: 'list',
  arbitrary: true,
  message: 'what do you want to do?',
  choices: ['suggestion 1', 'suggestion 2'],
  name: 'choicename'
}], function( answers ) {
  // evaluate options
});
```
which would output:

```
[?] what do you want to do?
 > suggestion 1
    suggestion 2
    ...
```
and if the user selects the 3rd option ('...'), a new `input` prompt appears to capture an arbitrary value.

As it is, it looks like I have to ask a set of questions then evaluate all the answers to see if any of the values are "new..." to re-ask the questions as `input` types, which is sub-optimal :)

**Comment by SBoudrias** [comment]
Doing it manually is not cluttering the API with specific needs and is not that hard. I'll close the request.
