### ISSUE TITLE
Inactive list select items?

### ISSUE THREAD

**Issue by kmgilbert100** [SBoudrias/Inquirer.js#321]
Is it possible to make a select list item inactive so it cannot be selected or at least if it is it doesn't do anything...

Thanks.

**Comment by SBoudrias** [comment]
Why not just exclude the choice from the list?

**Comment by kmgilbert100** [comment]
I have a terminal menu for a full block terminal application... Multi level menu etc... Some items are disabled temporarily therefore they should show.

I found this - https://github.com/SBoudrias/Inquirer.js/issues/92 

But i tried it and it seems it doesn't work so well.

**Comment by kmgilbert100** [comment]
It seems if you add that disabled you can still select the list item... if you do it returns the response for the next item in the list.

**Comment by SBoudrias** [comment]
Hum, that might be a bug. Feel free to investigate and send a PR.

**Comment by kmgilbert100** [comment]
Sure - Always glad to contribute when the project is actually monitored.. haha

**Comment by kmgilbert100** [comment]
Hmm.... I tried setting up a new env and pulled from master and the disabled state seems to work... ill have to do some more investigating but can maybe mark this as resolved here in a bit.
