### ISSUE TITLE
Resizable Header.

### ISSUE THREAD

**Issue by martinheidegger** [SBoudrias/Inquirer.js#325]
In [nodeschool-admin](https://github.com/nodeschool/admin) I used Inquirer to do all the dialogs. In front of the first dialog I wanted to render some ascii art because it makes you feel special. However: the ascii art turns out to be [not resizable](https://github.com/nodeschool/admin/issues/25) and I am not quite sure how I would implement resizability with an active inquirer wizard running. Do you know how this could be done?

**Comment by SBoudrias** [comment]
You could check the `cli-width` size prior to prompting and change the ASCII art being displayed (maybe show a smaller one on smaller screen).

There's definitively no way to resize text programmatically in the terminal to make your art fit.

**Comment by SBoudrias** [comment]
Also rule of thumb, keeping the art under 80char width will match pretty much any screens.

**Comment by martinheidegger** [comment]
@SBoudrias There is a way of resizing text programmatically in the terminal to make art fit (its how & why `vim` and `emacs` works). Here is [terminal-layout](https://github.com/Comedalte/terminal-layout), a library that does resizing. Technically - as far as I understand - it works by deleting formerly rendered content and rendering it again. I thought it could be best if Inquirer could have something like.

```
  header: function () {
    return '...'
  }
```

which is called everytime the [screen resizes](https://nodejs.org/api/tty.html#tty_event_resize).

**Comment by SBoudrias** [comment]
It doesn't resize. Like I said, it change the content when the screen size change. You can listen to all those things with Node API. That's not something that Inquirer is handling or is Inquirer specific.

**Comment by martinheidegger** [comment]
While being presented a question the inquirer renders the string output and changes it upon selection. On Screen-resize I would need to clear the inquire content AND the header.
