### ISSUE TITLE
.hide() and .show() active prompt

### ISSUE THREAD

**Issue by kpapadatos** [SBoudrias/Inquirer.js#329]
The output of my program constantly logs various events but also waits for input from a prompt. If one starts typing a command and something needs to be logged, the text will break. I would like to wrap console log with something like this:

``` js
var log = msg => {

  prompt.hide(); // Hides as many lines as the UI of the active prompt takes
  console.log(msg); // Log whatever
  prompt.show(); // Pushes it in again

}
```

Is this possible right now?
Thanks.

**Comment by SBoudrias** [comment]
That's not possible ATM. And to be fair that's not really a priority, I'm not sure how we'd handle a similar use case.

**Comment by SBoudrias** [comment]
Well we'd probably want to do something like the BottomBar module where we'd probably want to split our screen in two stream and make inquirer write to the bottom stream while the log is piped to the top stream.
