### ISSUE TITLE
Enforce idiomatic style guide with JSCS?

### ISSUE THREAD

**Issue by hzoo** [SBoudrias/Inquirer.js#331]
If you want, you can enforce a style with JSCS' idiomatic.js preset http://jscs.info/overview

```js
// create .jscsrc config like jshint
{
  "preset": "idiomatic",
  "rules-that-are-not-wanted": false // you can disable rules that you don't like as well or enable more
}
```

```bash
npm install jscs --save-dev
./node_modules/.bin/jscs lib examples test
./node_modules/.bin/jscs lib examples test --fix # to automatically fix style issues
```

**Comment by SBoudrias** [comment]
If you're willing, I'd be happy to accept a PR adding eslint following xo style.

**Comment by hzoo** [comment]
Sure - and removing JSHint/changing the readme to say it's following xo style?

**Comment by SBoudrias** [comment]
Exactly :)

**Comment by SBoudrias** [comment]
@hzoo any chance you're still up for the task?

**Comment by hzoo** [comment]
Sorry, was busy - if you are going to do it soon anyways then go ahead

**Comment by SBoudrias** [comment]
Done.
