### ISSUE TITLE
cli-width can return 0 in STDIN-less terminals.

### ISSUE THREAD

**Issue by hansl** [SBoudrias/Inquirer.js#337]
Emacs notably has a terminal mode where `cli-width` return 0. Seems that in this case the default width is also ignored.

This results in this line [here](https://github.com/SBoudrias/Inquirer.js/blob/master/lib/utils/screen-manager.js#L116) to construct an invalid regex (`(?:(?:\\033\[[0-9;]*m)*.?){1,0}`).

Solution: [this line](https://github.com/SBoudrias/Inquirer.js/blob/master/lib/utils/screen-manager.js#L109) should be `return width || 80;`.

**Comment by SBoudrias** [comment]
You should open an issue on the cli-width package.
