### ISSUE TITLE
"Pizza" & "checkbox" examples answers are null

### ISSUE THREAD

**Issue by valgaze** [SBoudrias/Inquirer.js#341]
From a fresh clone of the master branch, the answers from the pizza & checkbox examples are null when logged in the terminal (see screenshots below)

It appears the cause for the issue is that the examples use a callback to access the answers rather than a promise. I will submit a PR with a working version of the examples using promises in order to help get some extra insight/eyeballs on this. My dev environment is as boring and unremarkable as it gets.

<img width="746" alt="screen shot 2016-03-14 at 4 34 17 pm" src="https://cloud.githubusercontent.com/assets/1396559/13763349/b36b58a0-ea02-11e5-9f36-a1c053dcf121.png">

<img width="774" alt="screen shot 2016-03-14 at 4 44 47 pm" src="https://cloud.githubusercontent.com/assets/1396559/13763535/1839f786-ea04-11e5-8e3c-a7cab406d8c4.png">

**Comment by SBoudrias** [comment]
Yeah, that was broken on master since a pretty major push to add Promises for 1.0 release. It's fixed now.

Note that 1.0 is not yet released and promise API won't be working on the 0.x branches.
