### ISSUE TITLE
'err' contains the awnsers

### ISSUE THREAD

**Issue by Realtin** [SBoudrias/Inquirer.js#345]
Hey,

I tied some of your examples (list and input) and wrote this super simple code based on the input example:

```
'use strict'

var inquirer = require('inquirer')

var questions = [
  {
    type: 'input',
    name: 'words',
    message: 'Type the list of words'
  },
  {
    type: 'input',
    name: 'pattern',
    message: 'Type the pattern'
  }
]

inquirer.prompt(questions, function (err, answers) {
  console.log(err)
  console.log(JSON.stringify(answers, null, '  '))
})
```
logging the `answers` would give me `undefined` but logging the `err` gives me the answers! 
Maybe there is a mixup in the code? 

I have Node 4.1.1 and Inquirer v0.12.0

**Comment by SBoudrias** [comment]
Please refer to the 0.12.0 documentation here https://github.com/SBoudrias/Inquirer.js/tree/v0.12.0
