### ISSUE TITLE
async validate/filter/when

### ISSUE THREAD

**Issue by endquote** [SBoudrias/Inquirer.js#353]
I have some logic that requires reaching out to a service on the network to validate input. If `question.validate` accepted a callback and waited for me to call it before going on to the next question, I could do that. Adding this to `filter` and `when` would open some interesting options as well.

Or maybe this is possible already using the reactive interface?

**Comment by SBoudrias** [comment]
You can use `var cb = this.async()`

**Comment by SBoudrias** [comment]
https://github.com/SBoudrias/Inquirer.js#question

**Comment by endquote** [comment]
Found it... thanks! Interesting how that works.
