### ISSUE TITLE
`Press <space> to select` hint disappears and users get stuck

### ISSUE THREAD

**Issue by drobertduke** [SBoudrias/Inquirer.js#354]
I'm trying to popularize Yeoman generators with the hundreds of Java developers I work with. Every time I've had people use it, invariably someone gets stuck on a checkbox-style prompt because they hit the arrow keys to move around, which deletes the selection instructions.  They then start hitting enter, or hitting numbers, or asking for help because they don't know how to select options.

I never had this issue myself but it's the most common complaint I've gotten after 50 or so developers have used it.

**Comment by SBoudrias** [comment]
What's your suggestion?

**Comment by drobertduke** [comment]
Don't erase the `Press <space> to select` hint.

**Comment by sindresorhus** [comment]
Or better, remove the hint on `select` instead of arrow keys.
