### ISSUE TITLE
examples do not work with shelljs

### ISSUE THREAD

**Issue by shanshanyang** [SBoudrias/Inquirer.js#355]
`shjs.exec('node examples/checkbox.js')
`

![screen shot 2016-04-05 at 10 32 05 pm](https://cloud.githubusercontent.com/assets/4010256/14304154/6e3dd04a-fb7e-11e5-9296-d5c1e2cc2897.png)

all the examples are not responsive when used with shelljs exec method, is this a bug?

**Comment by SBoudrias** [comment]
No, you need to pipe the stdin/out to the process or it won't receive key inputs.

**Comment by SBoudrias** [comment]
That being said, I don't know about shelljs specifically. It might be that `exec` don't allow to pipe the stdio. You might actually want to use node native `child_process.spawn` instead.

But the main point remain, you need to pipe the stdio for it to work.

**Comment by shanshanyang** [comment]
great, thanks, i'll give it a try

**Comment by yorkie** [comment]
@SBoudrias `child_process.spawn` doesn't work with me, the weird part is not just the stdin, when I pipe the spawned inquirer program to `process.stdout`, the color gets removed.

**Comment by SBoudrias** [comment]
@yorkie that means when you spawn the process, it is not a `tty`. This is really not an issue with Inquirer itself, you need to make sure you can spawn tty process that'll have the current tty as input/output. I don't know exactly how you'd do that with node.

**Comment by SBoudrias** [comment]
Added a working example in the repo: https://github.com/SBoudrias/Inquirer.js/blob/master/examples/spawn.js

Like I said, you need to inherit the current tty

```js
var spawn = require('child_process').spawn;

spawn('node', ['input.js'], {
  cwd: __dirname,
  stdio: 'inherit'
});
```

**Comment by yorkie** [comment]
Yea @SBoudrias you are right, I didn't inherit processes.
