### ISSUE TITLE
Callback never called when passed an object, not array

### ISSUE THREAD

**Issue by grabbou** [SBoudrias/Inquirer.js#356]
I do realise this is definitely a developer mistake, but I've been wondering if we shouldn't call a callback with an error in this case. Otherwise it hangs indefinitely, which might not be helpful to debug.

See https://github.com/rnpm/rnpm/issues/138#issuecomment-206672048

**Comment by SBoudrias** [comment]
Can you explain what happened? It's not clear from the issue you linked and the related fix.

**Comment by grabbou** [comment]
We basically passed an empty object to `inquirer.prompt()` instead of an empty array and that caused the callback to never being called.

**Comment by SBoudrias** [comment]
Oh yes. Since 1.0, inquirer returns a promise. So the callback is not used anymore. That was noted in the release notes breaking changes: https://github.com/SBoudrias/Inquirer.js/releases/tag/v1.0.0

**Comment by grabbou** [comment]
Oh thank you!
