### ISSUE TITLE
Is it possible to change the color of the input beyond certain length?

### ISSUE THREAD

**Issue by sarbbottam** [SBoudrias/Inquirer.js#359]
Is it possible to change the color of the input beyond certain length? 

Somthing like
<img width="563" alt="screen shot 2016-04-04 at 11 57 11 am" src="https://cloud.githubusercontent.com/assets/949380/14259591/713b5740-fa5c-11e5-9a20-e483b9dcb790.png">

<img width="883" alt="git-cz" src="https://cloud.githubusercontent.com/assets/949380/14259695/eb64ee96-fa5c-11e5-9f7a-f174f9a5f2c4.png">

---

May be something like:

``` diff
...
}, {
    type: 'input',
    name: 'subject',
-    message: 'Write a short, imperative tense description of the change:\n'
+    message: 'Write a short, imperative tense description of the change:\n',
+    transformer: function(line) {
+        return line.substring(0, 99) + chalk.red(line.substring(100))
+   }
}, {
....
```

and

[Inquirer.js/lib/prompts/input.js#L55-L70](https://github.com/SBoudrias/Inquirer.js/blob/master/lib/prompts/input.js#L55-L70) can invoke this `transformer function`

``` diff
Prompt.prototype.render = function (error) {
  var bottomContent = '';
  var message = this.getQuestion();

  if (this.status === 'answered') {
    message += chalk.cyan(this.answer);
  } else {
-   message += this.rl.line;
+   message += reference.to.the.transformer(this.rl.line);
  }

  if (error) {
    bottomContent = chalk.red('>> ') + error;
  }

  this.screen.render(message, bottomContent);
};
```

Thanks!

**Comment by sarbbottam** [comment]
Hi @SBoudrias, does this sound feasible? If yes, I can work on a PR, with little guidance.

**Comment by SBoudrias** [comment]
Everything is possible, the question is more what would be the API exposed to the user?

**Comment by sarbbottam** [comment]
I guess the API remains the same, if optional `transformer` function is passed, `this.rl.line` is transformed before it gets added to the message.

May be I am over-simplifying, you could suggest better.

**Comment by SBoudrias** [comment]
I think that makes sense. PR welcomed

**Comment by pudgereyem** [comment]
@sarbbottam, @SBoudrias, any progress on this?

If not, I might look into it.

**Comment by travi** [comment]
@pudgereyem i've been meaning to make a contribution around this for a while, but have never found time to start looking into it. it would be hugely helpful to me if you end up getting it working. if any help testing it out would be helpful, i may be able to find some time for that.

**Comment by travi** [comment]
@SBoudrias i know this is a pretty dated issue at this point, but i tried to take a stab as this a couple of nights ago and had some trouble figuring out how the tests are intended to run.

https://github.com/SBoudrias/Inquirer.js/blob/master/test/specs/prompts/input.js looks like an appropriate place to try to test drive this behavior, but the changes that i've made there don't appear to be executed when i run `npm test`. am i missing something obvious, or is this file somehow excluded from the tests that are intended to run? are there any tricks or tips you could share about how to test a new feature like this?

**Comment by SBoudrias** [comment]
@travi no magic around tests, the `npm test` command should have this file tests running... Any chance there's an error when parsing/importing the file and that somehow makes the runner skip the whole file?

**Comment by travi** [comment]
> no magic around tests, the npm test command should have this file tests running

i didnt think it looked like anything more than a simple config for the tests. however, even with my changes stashed, any `console.log`s that i add to the `beforeEach` or test blocks (`it`) dont show up in the mocha output when running `npm test`. if it's helpful, mocha reports `93 passing`. does that number align with what you would expect if that file is being included?

i saw the `engines` defininition of using node 6:
```
"engines": {
    "node": ">=6.0.0"
  },
```
so after switching with `nvm` to v6 with `nvm use 6`, i end up on `v6.9.1`. thats the context i'm running `npm test` in

**Comment by SBoudrias** [comment]
@travi just checked it out myself, and you're right some tests weren't running. I think a version update changed how mocha treated the glob pattern and drop all test in nested folders (but kept travis green, so it went unnoticed.)

It's fixed on latest master.

**Comment by travi** [comment]
Glad to hear I'm not crazy at least. Thanks for taking a look and getting it taken care of. 

Hopefully that clears the way to getting this feature knocked out. With any luck I'll get a PR to you within the week so we can finalize implementation details.
