### ISSUE TITLE
Add a table display

### ISSUE THREAD

**Issue by MaffooBristol** [SBoudrias/Inquirer.js#360]
I can create a table using [text table](https://www.npmjs.com/package/text-table), but I would quite like it to be interactive and move the cursor up and down rows like in Inquirer.js.

Are there any plans to add a table display to this module, so that rather than passing an array of strings into `choices`, you pass an array of arrays and it will display it as such?

Thanks
Matt

**Comment by SBoudrias** [comment]
Hey, there's no plan to add new default prompts, but you can create an Inquirer plugin for it.

**Comment by MaffooBristol** [comment]
Ah okay, thanks- I hadn't noticed the plugin API!
