### ISSUE TITLE
When using a function for default, value is calculated only once

### ISSUE THREAD

**Issue by booooh** [SBoudrias/Inquirer.js#361]
When passing a default value to a prompt, one of the options is to pass it a function which receives the current answers as the argument.

When prompting the same question more than once (like in the recursive example), the default value gets overridden with a plain string result from the first time.

it seems like this is because the library overrides the property with the value of the function (e.g. it's the expected behavior), but this is non-trivial and not well documented.

[edit: reference to relevant code]
fetchAsyncQuestionProperty in utils.js 

It would be great if this behavior could be optional.

**Comment by SBoudrias** [comment]
Can you post a code example?

It's possible we should clone the option object before operating on it.

**Comment by booooh** [comment]
This is just a very slightly modified version of the recursive example provided in the repository (added a default section):

```javascript
/**
 * Recursive prompt example
 * Allows user to choose when to exit prompt
 */

'use strict';
var inquirer = require('inquirer');
var output = [];

var questions = [
  {
    type: 'input',
    name: 'tvShow',
    message: 'What\'s your favorite TV show?',
    default: function(answers) {
      return 'The simpsons ' + output.length;
    }
  },
  {
    type: 'confirm',
    name: 'askAgain',
    message: 'Want to enter another TV show favorite (just hit enter for YES)?',
    default: true
  }
];

function ask() {
  inquirer.prompt(questions).then(function (answers) {
    output.push(answers.tvShow);
    if (answers.askAgain) {
      ask();
    } else {
      console.log('Your favorite TV Shows:', output.join(', '));
    }
  });
}

ask();
```
