### ISSUE TITLE
"expand" prompt type results broken

### ISSUE THREAD

**Issue by Turbo87** [SBoudrias/Inquirer.js#362]
Behavior in v0.12.0:

```
$ node examples/expand.js
? Conflict on `file.js`:  Overwrite this one and all next
{
  "overwrite": "overwrite_all"
}
```

Behavior in v1.0.1:

```
$ node examples/expand.js
? Conflict on `file.js`:  Overwrite this one and all next
{
  "overwrite": "Overwrite this one and all next"
}
```

It seems that the `value` property of the choices is ignored and not returned at all.

**Comment by SBoudrias** [comment]
Thanks for the report, I'll look into it as soon as possible.

**Comment by Turbo87** [comment]
awesome, thanks for the quick fix!

**Comment by oveddan** [comment]
This changed caused a confusing error for me which I had to dig into source code to troubleshoot:

TypeError: Cannot read property 'short' of undefined
    at Prompt.onSubmit (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/expand.js:164:23)

It would be better if there was a more descriptive error message
