### ISSUE TITLE
Less surprizing validation API

### ISSUE THREAD

**Issue by tomekwi** [SBoudrias/Inquirer.js#367]
Hello,

first of all, thank you for the great piece of software! I’ve only discovered Inquirer the other day – and I’m totally in love with it!

I’ve got one suggestion from a newcomer’s perspective. A hallway usability test for free. 😄

The relationship between async validation and promises was a bit suprizing for me:

```js
$ cat <<——— > greetMe.js
require('inquirer').prompt([{
  name: '_',
  message: 'Say “hello”:',
  validate: (answer) => new Promise((resolve, reject) => {
    if (answer === 'hello') resolve(true);
    else reject('Please greet me! Just say “hello”.');
  }),
}]);
———

$ node greetMe.js
? Say “hello”: hello
>> [object Object]

$ node greetMe.js
? Say “hello”: NO! I don’t want to say hello!
>> [object Object]
```

Here’s my full story. Validation via `return true` and `return 'Error message'` worked okay with sync validation for me. Then I needed to validate some input with async actions. Since your library makes heavy use of Promises (and that’s a great thing!), a Promise was my first weapon of choice.

Perhaps you have good reasons for doing async validation via callbacks and `this.async()`. But if it’s just historical reasons, you might consider adding idiomatic, first-class support for promises. In my humble newcomer opinion:
* `resolve()` and `reject('Error message')` is easier to understand than `return true` and `return 'Error message'` without reading the docs – even with synchronous stuff. 
* When doing async validation, the elegance of promises really shines over callback spaghetti.
* For us it’s less complexity and less docs – and for users it’s less overhead to have one promise-based API to rule them all – synchronous and asynchronous validation.
* Perhaps we could apply the same API to `default`, `filter` and `when` as well.

**Comment by tomekwi** [comment]
Closely related: #310.

**Comment by SBoudrias** [comment]
I believe the issue is that you need to resolve the promise with the error message. Rejecting the promise is currently handled as a code error.

**Comment by tomekwi** [comment]
Tried that as well – that still leads to an instant `[object Object]` error message.

**Comment by tomekwi** [comment]
You can see that here, by the way (promise resolved to `true` shouldn’t be an error):

```js
$ node greetMe.js
? Say “hello”: hello
>> [object Object]
```

**Comment by mrkmg** [comment]
I am unable to replicate this bug. I used the following as a test:

    {
      type: 'input',
      name: '_',
      message: 'Say hello',
      validate: function (value) {
        return new Promise(function (resolve, reject) {
          if (value == 'hello') resolve(true);
          else resolve('Bad user, say hello');
        })
      }
    }

Everything seems to be working correctly here.

**Comment by tomekwi** [comment]
Hey, thanks for looking at this! To be honest, I no longer have access to the project I used Inquirer for. It might have been fixed “by accident” in the meantime – or it might have been a glitch in the matrix 😉

Since I can’t reproduce this either, let’s consider this wrapped up 🙂
