### ISSUE TITLE
First prompt on Windows is duplicating

### ISSUE THREAD

**Issue by Vasyl-Kobyletskiy** [SBoudrias/Inquirer.js#369]
Good afternoon,

There is one issue. When we use inquirer latest version 1.1.2, user entrance of first prompt is duplicating.
Let me show you a simple example to demostrate it

var inquirer = require('inquirer');
inquirer.prompt([
	{
		name: 'name',
		type: 'input',
		'message': 'Name:'
	},
	{
		name: 'surname',
		type: 'input',
		'message': 'Surname:'
	},
	{
		name: 'password',
		type: 'password',
		message: 'Password:'
	}
]).then(function(credentials){
	console.log(credentials);
});

![prnt_scr](https://cloud.githubusercontent.com/assets/869623/15217359/dcd9fb4e-1863-11e6-803c-80c2478ddfd2.png)

Issue is that firsr prompt is duplicating. It was tested on Windows 8.1 x64, node v 5.0.0.
The same issue was detected when using older version of inquirer - 0.12.0.

**Comment by deep9** [comment]
I am using https://github.com/dylang/grunt-prompt, which uses inquirer@0.11.4, and the issue is the same.

When having just one prompt with pasword, it is only masked in the second line, so you can see what are you typing (password), then after pressing enter you see the line repeated, but with masked input.

**Comment by dprothero** [comment]
Same issue on Windows 10 with Powershell

**Comment by dprothero** [comment]
I should say, I have both issues... first line is duplicated and if the first prompt is type password, you can see the input that is typed.

**Comment by nshtg** [comment]
I can confirm both issues!

**Comment by fabiorogeriosj** [comment]
+1

**Comment by SBoudrias** [comment]
Some node version ship with a totally broken readline.

See https://github.com/nodejs/node/issues/5384 for more details. You'll want to try again on latest stable Node.js version.

**Comment by Vasyl-Kobyletskiy** [comment]
Thank you SBoudrias for your answer.

**Comment by dprothero** [comment]
Awesome SBoudrias, thanks so much.
