### ISSUE TITLE
Confusing exception when using expand, if the value does not match up with the key.

### ISSUE THREAD

**Issue by oveddan** [SBoudrias/Inquirer.js#373]
I had an existing prompt config:

```code
{
        name: 'isTeamGame',
        message: 'Does the game have teams?',
        type: 'expand',
        choices:  [
          {
            key: 'y',
            name: 'yes, the game has teams',
            value: true
          },
          {
            key: 'n',
            name: 'no, the game does not have teams',
            value: false
          }
        ]
 }
```

This worked fine, until I upgrade to the latest version of Inquirer.  When "n" was selected, I get the confusing error:

TypeError: Cannot read property 'short' of undefined
    at Prompt.onSubmit (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/expand.js:164:23)

It's due to this line of code:
```javascript
  var choice = this.opt.choices.where({value: state.value})[0];
```

There should be a more descriptive error message, like:
"Error: value 'n' does not exist in list of choices (true, false)"

**Comment by akatsukle** [comment]
I am not really sure what should be the behaviour here. The API is not really specific on what types are allowed for `value`.
My first commit paches getCurrentValues. If the value was faulty (ie the boolean false) then the function would return the name. 
My second one add a verification on the field `value`, that will allow only Strings, Integers and Booleans.
I think doing both is a good idea, however supporting objects should probably also be done for the second fix.

**Comment by oveddan** [comment]
Thank you!
