### ISSUE TITLE
Option to not clear the prompt when validation false

### ISSUE THREAD

**Issue by mhkeller** [SBoudrias/Inquirer.js#374]
Currently when an answer false validation, the answer the user has given is also cleared. An option to have the user input remain so that it could be edited would be helpful.

My use case is that I'm asking the user to fill out text for a sample tweet with validation that the text is less than 140 characters. If the string is over 140, I give an error message with the current character count. For the user, it would be nice if they could edit the text string and resubmit instead of having their entry get cleared and have to start again.

**Comment by rohmanhm** [comment]
I agreed with @mhkeller .
Are there any options to clear the screen after user submit an answer?

**Comment by SBoudrias** [comment]
PR welcomed. I think the default behavior should be updated to not clear the initial answer.

**Comment by rebgrasshopper** [comment]
I get the opposite behavior - the input does not clear upon validation error. Was there a change that made this the default behavior?

**Comment by SBoudrias** [comment]
It's possible different prompts have different behaviors; or the stable version (`inquirer`) VS the beta ones (`@inquirer/input`).

Any of this would explain the different behavior?

Also anyone has strong opinion the input should be cleared? If so, we could consider adding as a configuration option

**Comment by brendaHuang-2023** [comment]
I'd like to have the input cleared. Otherwise when user enters an invalid input, we have to ask the user to clear the input and retype, which is not the best user experience.

**Comment by SBoudrias** [comment]
Alright! To summarize the need if someone wants to send a PR:

1. Expose an option on `@inquirer/input` to control the behavior on validation failure. (2 cents: `validationError: 'clear' | 'keep'`, default on keep. - Feel free to suggest a better naming for the options!)
2. Implement both a clear, and keep content option.
