### ISSUE TITLE
Max listeners reached.

### ISSUE THREAD

**Issue by frankdiox** [SBoudrias/Inquirer.js#375]
@SBoudrias  Hello! First of all, thanks a lot for this tool!
I have forked this repo to implement a small feature for a project. Basically, I wanted to cancel list prompts to be able to go back to the previous question. While doing this I noticed that if I cancel prompt and open it again several times it was throwing an error related to reaching maximum listeners for the same event (10 by default). I believe this also happens if you chain several prompts without canceling anyone.

Therefore, this is not a real bug report but a "possible bug" report. I don't know too much about rx lib but I made a `dispose` function to remove listeners when the prompt is resolved and it fixed this issue. You can [check it here](https://github.com/frankdiox/Inquirer.js/commit/6589cd325a09d5422dda624b29188fce7bac9abf).

If that's not a problem then just ignore this issue. Also, if you know a better way to implement this kind of feature or you notice any possible error, I'd appreciate if you let me know :)

Thanks!

**Comment by SBoudrias** [comment]
Inquirer correctly clears its listeners using events constraints. (see the `takeUntil` https://github.com/SBoudrias/Inquirer.js/blob/master/lib/prompts/input.js#L42)

So the event listener issue really is only in your own code.

**Comment by frankdiox** [comment]
Thanks for checking!
