### ISSUE TITLE
Setting BottomBar message in validate causes duplicated line

### ISSUE THREAD

**Issue by jsonmaur** [SBoudrias/Inquirer.js#380]
When I set a "pending" message for the bottom bar during an input validation, it will duplicate the line/answer when the validation completes. Is this expected behavior? See the example below to reproduce (running this in an empty project).

![out](https://cloud.githubusercontent.com/assets/911274/15720909/cd2ce5ae-27f3-11e6-9bed-ef64de70d487.gif)

``` javascript
var inquirer = require('inquirer')

var ui = new inquirer.ui.BottomBar()

inquirer.prompt([{
  type: 'input',
  name: 'test',
  message: 'Test Input:',
  validate: function () {
    ui.updateBottomBar('Waiting...')

    var done = this.async()
    setTimeout(function() {
       done(null, true)
    }, 2000)
  },
}]).then(function (answers) {
  console.log(answers)
})
```

**Comment by souravray** [comment]
I am facing the same issue.

**Comment by revelt** [comment]
Confirmed, this line alone will cause duplicated rows:

```js
const ui = new inquirer.ui.BottomBar()
```

![repeated_lines](https://user-images.githubusercontent.com/8344688/34652079-6de4c110-f3d1-11e7-8f3a-3817ace97b4c.gif)

When I remove it, there's no duplication, as intended.
