### ISSUE TITLE
Default not activated when !when

### ISSUE THREAD

**Issue by TimothyGu** [SBoudrias/Inquirer.js#381]
```js
require('inquirer').prompt([
  {
    type: 'input',
    name: '_',
    message: 'msg',
    default: 'sfd',
    when: false
  }
]).then(a => console.log(a._));
```

```
$ node -v
v6.2.1
$ node a
undefined
```

Is this a bug? If not, the behavior is certainly surprising as I would expect the output to be `sfd`.

**Comment by SBoudrias** [comment]
I don't see why it is confusing. If a prompt is skipped, there's no result in the answer array.

`'_' in a` will return false in your case.

**Comment by TimothyGu** [comment]
But the point is that there's a default for this specific member, and the documentation says that it is the "default value(s) to use if nothing is entered." If `when` is false, indeed nothing is entered, and I was surprised to find that the default is not used.

**Comment by Robinfr** [comment]
I also ran into this and find it confusing that it doesn't take the default when `when` is false.
