### ISSUE TITLE
Prompt value without prompting the question

### ISSUE THREAD

**Issue by bastuijnman** [SBoudrias/Inquirer.js#382]
Hi,

I have a certain use-case where I don't want a question (a list) displayed when only 1 value is available, so I use the `when` property to skip the question in that case, but I do want the value (of that 1 item) to be passed along. For now I'm setting the value in the values object which is passed to the when function.

```
when: function (values) {
    values.question = value;
    return false;
}
```

I do this because the `default` function doesn't get executed when the `when` function returns false. Is there a way currently to do this in Inquirer. If not, would you be willing to accept a PR which adds this functionality.

Cheers,

Bas

**Comment by SBoudrias** [comment]
I'm not sure, I really feel if a prompt doesn't run, it shouldn't provide a value as answer.

Receiving an answer object without the answer allows you to know the question was actually skipped.

**Comment by bastuijnman** [comment]
That's true, haven't thought about that one yet. Thanks!
