### ISSUE TITLE
Can list and input work together

### ISSUE THREAD

**Issue by jaredleechn** [SBoudrias/Inquirer.js#391]
Awesome project！

I want to write a translation program, for a few words, it request google(add other machine translate service) to fetch translation for each word，and let user choose which one is the best

But the condition is those translations are generally not good enough, so i want to add a feature to modify the the most close one and save as result

So i wonder can input be one selection of list with specified translation as default value? Or when using list, if i press some button, it turn to input?

thx

**Comment by SBoudrias** [comment]
@jaredleechn Inquirer is only JavaScript, feel free to make it call itself recursively or nesting the calls or whatever other things you can do with the programming language.
