### ISSUE TITLE
Examples not available upon `npm install inquirer`

### ISSUE THREAD

**Issue by tishma** [SBoudrias/Inquirer.js#393]
I understand if `examples` dir was not meant to be available upon merely running `npm install inquirer` (and I've found my way to github repo),  but documentation actually suggests it would be.

**Comment by SBoudrias** [comment]
I don't see how the documentation suggest it would be? Can you explain what let you believe that?

**Comment by tishma** [comment]
Sry. You're right. I've missed the point I'm trying to make. The issue doesn't belong to github, but I guess that was the only place where I could get in touch. Simply reading the page at https://www.npmjs.com/package/inquirer doesn't suggest one should do anything else but `npm install...` 
<img width="494" alt="screen shot 2016-07-04 at 11 43 20 pm" src="https://cloud.githubusercontent.com/assets/4130604/16570199/5d2a5a26-4241-11e6-920a-f022013da207.png">

**Comment by gentunian** [comment]
I've tried to run examples this way:

```
npm install -g inquirer
git clone https://github.com/SBoudrias/Inquirer.js
cd Inquirer.js
node examples/pizza.js
```

results in:

```
$ node examples/pizza.js 
module.js:327
    throw err;
    ^

Error: Cannot find module 'external-editor'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/seba/code/node/Inquirer.js/lib/prompts/editor.js:7:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

Do we need an extra package to test examples? I'm using inquirer in code and works well. Only examples are not working.

**Comment by SBoudrias** [comment]
You want to npm install the project dependencies first. No need to globally install inquirer.

```
git clone https://github.com/SBoudrias/Inquirer.js
cd Inquirer.js
npm install
node examples/pizza.js
```
