### ISSUE TITLE
Checkbox Input

### ISSUE THREAD

**Issue by chrisroselli** [SBoudrias/Inquirer.js#394]
I'm building a checkbox list and am trying to get it to output a snippet of php into a template with `<%= example %>` when selected. I can only get it to output the `name:` object which does work well in the command line. Is there a way to add a `value:` object of sorts to output the snippet? I guess I'm saying I want to select one or more checkboxes and have it output the php snippet to the template using EJS tags.

**Comment by SBoudrias** [comment]
Please refer support question to StackOverflow. This doesn't seems related to Inquirer, you're just wondering how to piece your program together.

**Comment by chrisroselli** [comment]
Alright makes sense, sorry. I actually figured it out from another closed Issue, ironically.   "Improve title for checkbox like list #384"
