### ISSUE TITLE
v1.1.1 causes re-display of the answers of list-type prompts after each new prompt is accepted

### ISSUE THREAD

**Issue by digiwano** [SBoudrias/Inquirer.js#395]
code to reproduce:

```javascript
'use strict';

const inquirer = require('inquirer');

const questions = [
  {
    type: 'list',
    name: 'q1',
    message: 'question-1',
    choices: ['one', 'seven', 'twelve'],
  },
  {
    type: 'input',
    name: 'q2',
    message: 'question-2',
    default: () => 'two',
  },
  {
    type: 'input',
    name: 'q3',
    message: 'question-3',
    default: () => 'three',
  },
];

inquirer.prompt(questions).then(console.log);
```

Under v1.1.0:
![inquirer-v1 1 0](https://cloud.githubusercontent.com/assets/767011/16638675/f992b0f4-439d-11e6-9cc2-be418912615c.png)

Under v1.1.1:
![inquirer-v1 1 1](https://cloud.githubusercontent.com/assets/767011/16638677/fd2f681a-439d-11e6-8d6a-617e0444a09c.png)

The flow goes something like this:
1. List-type question is displayed. After selecting the user's choice, the `? question-1 one` is rendered.
2. Next question is asked. At this point, on-screen, you have the Q1 line above, and the Q2 prompt. As soon as you hit 'enter' to accept your Q2 choice, it re-renders  `? question-1 one` followed by  `? question-2 two`, and it is only at this point that the  `? question-1 one` line has been duplicated.
3. Again, at the point that Q3 is asked, you see `? question-1 one`, then `? question-1 one`, then `? question-2 two`, then the active prompt-line for Q3. Once Q3 has been answered, it will then re-render again `? question-1 one` followed by `? question-3 three`, resulting in the state seen in the above screenshot.

**Comment by SBoudrias** [comment]
Woooo, not good! Fixed :)

Thanks for the report!

**Comment by olso** [comment]
Publish to npm please 👍
