### ISSUE TITLE
Obfuscate default password in prompt.

### ISSUE THREAD

**Issue by tishma** [SBoudrias/Inquirer.js#396]
Using Inquirer to create a wizard that generates a config file. Seems strange that default value for a password (pre-loaded from existing configuration) shows in plain text. If you have no time to do it, a hint what to hack in order to obfuscate default is very much appreciated.

**Comment by tishma** [comment]
Btw, here's my hack: 
`inquirer.prompt.prompts.password.prototype.getQuestion = function () {
    var message = chalk.green('?') + ' ' + chalk.bold(this.opt.message) + ' ';
    // Append the default if available, and if question isn't answered
    if (this.opt.default != null && this.status !== 'answered') {
        message += chalk.dim('(*******) ');
    }
    return message;
};`

**Comment by SBoudrias** [comment]
Well, it would be worse in my opinion to provide a default which is hidden; then the user don't even know the default being provided.

Furthermore, if you can preload a password as text from anywhere, then you have a security leak. Don't ever store people passwords.

Worth reading: https://nakedsecurity.sophos.com/2013/11/20/serious-security-how-to-store-your-users-passwords-safely/

**Comment by tishma** [comment]
Thanks @SBoudrias ,

Good point is to mention in the question message that pressing Enter will keep the old password.

And nobody said it's a 'people password' ;) For example, I've never seen a DB config file that uses anything but plain text password (or equivalent which might be somewhat obscure and more painful to manage, but never more secure) in order to be able to establish a connection.

Best
v.
