### ISSUE TITLE
Answer typings out of date

### ISSUE THREAD

**Issue by JimmyBoh** [SBoudrias/Inquirer.js#398]
I'm using TypeScript and the typings appear out of date for the `Answers` interface. Example (from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/inquirer):

```ts
interface Answers {
  [key: string]: string|boolean;
}
```

The problem lies with using the `checkbox` question type. Since the interface will only allow `string` or `boolean` you cannot access an array of selected items. For example:

```ts
inquirer
.prompt([{
  type: 'checkbox',
  name: 'ports',
  message: 'Which ports would you like to track?'
  choices: [
    {name: 'SSH', value: 22},
    {name: 'HTTP', value: 80},
    {name: 'HTTPS', value: 443}
  ]
}])
.then((answers: Answers) => {
  return <number[]>answers['ports'] // This cast breaks!
});
```

Is my understanding correct? Should it be updated to the following:

```ts
interface Answers {
  [key: string]: any;
}
```

I am happy to make the PR to DefinitelyTyped, but I wanted to check here first before doing so.

(also, if there are any other typings that must be updated, please let me know and I can do them all at once!)

**Comment by JimmyBoh** [comment]
@SBoudrias Any insight on this? In the meantime I will make the change and send a PR out. Please let me know if there is any other definitions that needs updating.

**Comment by SBoudrias** [comment]
Hey, I don't personally use TypeScript. But feel free to send a PR to deftyped if you found a bug. I'll close here as I don't support the typed interfaces provided by other projects.

**Comment by JimmyBoh** [comment]
Will do, thank you!
