### ISSUE TITLE
How to fail validation with Promise? (or Where is my failed validation message?)

### ISSUE THREAD

**Issue by tishma** [SBoudrias/Inquirer.js#399]
I'm sorry if I'm failing to see the obvious, but I really miss an example of `validate` code that returns a Promise and shows how to fail validation and display the message before showing the question again. Hence it's unclear if we should `reject` or `resolve(false)` in such case.

Calling `reject` appears to interrupt the prompt, while I would like to display the message and show the prompt `message` again.

Writing to console before doing `resolve(false)` appears to have no effect (tried console.log, console.error etc.), and question is just  re-stated below the first line of the same question shown previously. Like this:

```
? Question line 1
? Question line 1
Question line 2
Question line 3: 
```

What I would expect to see is:

```
? Question line 1
Question line 2
Question line 3:  <answer that just failed validation in chalk.red>
<Failed validation message in chalk.red or bold>
? Question line 1
Question line 2
Question line 3:  
```

It appears that script scrolls the stdout up to some point, and overwrite its contents (including failed validation message). 

Note: I have much more than 3 lines, as I need to write instructions for an external operation that results with a string to be input as answer, and the number of lines inquirer scrolls up is not the same depending on terminal window size. Using iTerm 2 on Mac, btw.

**Comment by SBoudrias** [comment]
You need to `resolve(false)` or `resolve('error message')`.

I think you're just missing your log message because by calling `console.log` you change the input height which will mess up the next clean/write phase.

**Comment by tishma** [comment]
so, are you suggesting not to use `console.log`, and use `resolve('error message')` instead? whatever gets messed up, I don't think it's too much to ask that a message remains on screen.

**Comment by SBoudrias** [comment]
@tishma add `\n` around your `console.log` if you want to see the message.

Given Inquirer needs to cleanup the console content to make dynamic prompting possible, I'm sure you can understand why pushing lines on the prompt doesn't play well.
