### ISSUE TITLE
Multi-line question (or choices)

### ISSUE THREAD

**Issue by SBoudrias** [SBoudrias/Inquirer.js#4]
Right now there's no support for using line return inside questions or choices.

**Comment by mchlltt** [comment]
Apologies for reviving an extraordinarily old issue, but I wanted to check whether multi-line choices ever became possible. I'd like my user to be able to view pretty-printed JSON objects and choose between them, but the fact that they're ~5 lines each means that the interface is bugging out pretty badly. I've tried upping pageSize to no avail. I'm sure I could find a workaround for my specific case, but I thought I'd ask.

**Comment by SBoudrias** [comment]
@mchlltt Multiline support in choices should work fine https://github.com/SBoudrias/Inquirer.js/blob/master/examples/long-list.js#L11

But there's a good chance having bigger than ~2 lines choices can trip the UI badly. The pagination is pretty dumb ATM. You can see this PR trying to making it better #492

**Comment by mchlltt** [comment]
@SBoudrias - Ah, thanks :) I'll keep an eye on that PR in case I'm able to help out.
