### ISSUE TITLE
Returning 'undefined' when choosing 'false' with 'when:'

### ISSUE THREAD

**Issue by chrisroselli** [SBoudrias/Inquirer.js#400]
Returning 'undefined' when choosing 'false' with 'when:'. Causing error when skipping questions then processing answers with EJS into a template.

**Comment by SBoudrias** [comment]
Can you explain your issue clearly and provide minimal code reproducing the issue?

**Comment by chrisroselli** [comment]
When user answers "Yes" to `Do you want to add primary colors?` , the question is displayed in the command line, the user provides an answer, and EJS enters that answer into the template with `<%- primaryBrightColor %>`. When the user answers "No" that question is skipped, as desired, but automatically returns a value of `undefined ` causing an error when EJS runs `<%- primaryBrightColor %>` because there is no value for EJS to input into `<%- primaryBrightColor %>`. Unless I'm missing something, there doesn't seem to be a way to add a default value of maybe an empty string when false is chosen as a value for `when:`?
```
gulp.task('default', function (done) {
      var prompts = [
        {
           name: 'colorOption',
           message: 'Do you want to add primary colors?',
           type: 'list',
           choices: ['Yes', 'No']
        }, {
           name: 'primaryBrightColor',
           message: 'Paste primary bright color (ex. #XXXXXX)',
           when: function(answers){
             return answers.colorOption === 'Yes';
           }
        }, 
```

**Comment by SBoudrias** [comment]
No, just do it in your JavaScript code.

`answer.primaryBrightColor || ''`
