### ISSUE TITLE
Refresh prompt questions

### ISSUE THREAD

**Issue by guigrpa** [SBoudrias/Inquirer.js#401]
Is there a way to refresh a prompt during the user input session, possibly with updated `choice` items? I have looked for that in the documentation, and even dived into the code, but can't find a simple or not-so-simple way...

**Comment by SBoudrias** [comment]
No, that's not possible at the moment.

**Comment by trueicecold** [comment]
8 years later, is it possible now? :/

**Comment by SBoudrias** [comment]
With `@inquirer/prompts` and the new prompts it is possible to implement with custom code relying on `promise.cancel()`. https://github.com/SBoudrias/Inquirer.js#canceling-prompt

Let me know how that goes!
