### ISSUE TITLE
Input prompt flickering. 

### ISSUE THREAD

**Issue by ghost** [SBoudrias/Inquirer.js#408]
The input prompt flickers pretty badly when typing - using the following code: 

```
var inquirer = require("inquirer");
inquirer.prompt([
 {
    type: 'input',
      name: 'message',
        message: 'Message > '
         },]).then(function (result) {
     console.log("result.message")
 }
```

**Comment by SBoudrias** [comment]
Platform? command line? Node and system versions? etc etc

**Comment by ozzie1998** [comment]
I am using JXCore but tested it with the default version of Nodejs: v4.4.7
 I am running on Mac OSX El capitan.

**Comment by SBoudrias** [comment]
@ozzie1998 what's your terminal app?

**Comment by ozzie1998** [comment]
terminal.app, the default terminal that comes with a Apple Macintosh.

**Comment by colophonemes** [comment]
Having similar issues

**Comment by ozzie1998** [comment]
I take it you don't want to accept that there's an issue?

**Comment by SBoudrias** [comment]
@ozzie1998 I take it you don't understand OSS maintainers are busy sometime?

**Comment by ozzie1998** [comment]
You must be very busy...

**Comment by colophonemes** [comment]
I think I've solved my issue — the issue seems to happen when running Inquirer in a child process (e.g. via [Supervisor](https://github.com/petruisfan/node-supervisor)). Running the script standalone is fine

**Comment by mbenson025** [comment]
Same issue while using vs code with node(windows 10). I'm also running the script standalone-

![readmegen](https://user-images.githubusercontent.com/35643709/172062913-02232ee7-8565-41c2-9fd9-ceef350bf7d7.gif)

**Comment by SBoudrias** [comment]
Inquirer v10, and `@inquirer/prompts` included major perf fixes. Feel free to reopen specific issues if you run into problems with the new versions. Cheers!
