### ISSUE TITLE
cursor tabbed forward when using JXCore with the prompt.

### ISSUE THREAD

**Issue by ghost** [SBoudrias/Inquirer.js#409]
Using this standard code.

```
 var inquirer = require('inquirer')
     inquirer.prompt([{
        type: 'prompt',
          name: 'message',
            message: ' ->',
          }]).then(function (answers) {

  //do stuff with the data.
   }
```

The prompt looks like so in JXCore. 
I am not using node.js due to some weird memory leak and key press listener memory leaks. The application also runs and behaves better in JXCore. 

![screen shot 2016-08-14 at 16 46 00](https://cloud.githubusercontent.com/assets/6974773/17650160/abed0c5e-623e-11e6-9136-dfbccc3f046f.png)

**Comment by ozzie1998** [comment]
Some input on fixing this issue would be useful.
