### ISSUE TITLE
Inquirer exits CLI when prompt is answered

### ISSUE THREAD

**Issue by jordan-simonovski** [SBoudrias/Inquirer.js#410]
I'm running into a very interesting issue with inquirer at the moment which only affects users that globally install a CLI that I'm writing.

I'm running commander for a basic arg parsing mechanism.

What happens is that I run the command 'superaws stack', which then prompts the user for an action (create, delete). Once that is entered, the program exits without proceeding further.
However, if I run 'node index.js stack' the CLI runs without an issue and proceeds to prompt the user for more input.

I'm not sure where to start debugging this really. I'm not even getting anything on the prompt callback which leads me to believe that it exits during the input.

Has anyone else run into this issue before?

**Comment by SBoudrias** [comment]
Any chance a promise somewhere is failing and the error is just swallowed?

**Comment by jordan-simonovski** [comment]
I think I've worked it out. I had written some stuff using callbacks. Switched to promises and it's working perfectly fine! :D
