### ISSUE TITLE
Type Checkbox doesn't work as expected

### ISSUE THREAD

**Issue by renan-quirino** [SBoudrias/Inquirer.js#412]
Good evening,
I was trying to add some choices. The choices have shown in the prompt, but i can't select anyone. The arrow doesn't move and the spacebar doesn't work, conclusion, nothing happens. I'm using Command Prompt from Windows. Do you know how to fix it?

model used below:

[
	{
		"type": "checkbox",
		"name": "competences",
		"message": "Input the competences you would like to extract",
		"choices": [
			"2011",
			"2012",
			"2013",
			"2014",
			"2015"
		]
	}
]

**Comment by sdotson** [comment]
The model you've included seems to work fine on mac. What version of Windows are you running?

**Comment by aaronbrowder** [comment]
Checkbox doesn't work for me either, as described by @renan-quirino. I'm on Windows 10.

**Comment by SBoudrias** [comment]
Some node version ship with a totally broken readline.

See https://github.com/nodejs/node/issues/5384 for more details. You'll want to try again on latest stable Node.js version.
