### ISSUE TITLE
Unable to paste content with newlines

### ISSUE THREAD

**Issue by ericuldall** [SBoudrias/Inquirer.js#416]
Is there any way to paste in content that has newlines during the prompt?

For instance:

? What is your favorite foo?

paste: bar
bar
bar
bar
bar

Currently when I paste multiline it takes the first line then goes to the next question. Any help is much appreciated.

**Comment by SBoudrias** [comment]
Only the [`editor` prompt](https://github.com/SBoudrias/Inquirer.js#editor---type-editor) support multiline input.

**Comment by ericuldall** [comment]
Cool. Thank you.
