### ISSUE TITLE
`editor` prompt disables all Node timers

### ISSUE THREAD

**Issue by guigrpa** [SBoudrias/Inquirer.js#418]
Launching an external editor with the `editor` prompt type causes all Node timers (both periodic and one-off) to be suspended. Consider the following example:

```js
const inquirer = require('inquirer');

setInterval(() => console.log(new Date()), 1000);

inquirer.prompt([{
  name: 'name',
  type: 'editor',
  message: 'What is your name?',
}])
.then(() => console.log('Done!'));
```

Output:

```
? What is your name? Press <enter> to launch your preferred editor.2016-09-26T10:08:48.621Z
2016-09-26T10:08:49.626Z
2016-09-26T10:08:50.627Z
2016-09-26T10:08:51.628Z
2016-09-26T10:08:52.629Z
? What is your name? Received
2016-09-26T10:08:59.669Z
Done!
2016-09-26T10:09:00.669Z
2016-09-26T10:09:01.669Z
2016-09-26T10:09:02.669Z
2016-09-26T10:09:03.671Z
```

Note the gap between 10:08:52 and 10:08:59. Periodic messages are not printed during the time the external editor remains open. This happens in Linux and Windows.

This **does not happen with other prompt types (e.g. `input`)**.

Is this intended behaviour? If so, maybe it should be mentioned in the docs.

**Comment by SBoudrias** [comment]
It might just be the side effect of switching process. Did you try logging to a file rather than the stdout?

**Comment by guigrpa** [comment]
My example above was very contrived. In our application, we periodically sent a UDP packet, and the packet doesn't get sent as long as the external editor is open.

**Comment by SBoudrias** [comment]
@guigrpa so the plugins we use for the editor is spawning the editor synchronously, so it'll keep the thread busy prevent any async operartions https://github.com/mrkmg/node-external-editor/blob/master/src/index.coffee#L73

You might want to bring this issue up with this package author.

**Comment by mrkmg** [comment]
I have just added the ability to use external-editor in an async manner. I am now working on implementing this into Inquirer.js

**Comment by mrkmg** [comment]
@SBoudrias Rx.js takes some learning! Awesome library but man I had no idea what I was doing at first...

**Comment by guigrpa** [comment]
Works like a charm, thanks!

**Comment by guigrpa** [comment]
And thanks to @mrkmg as well!
