### ISSUE TITLE
checkbox input unresponsive on windows git bash

### ISSUE THREAD

**Issue by akalman** [SBoudrias/Inquirer.js#422]
#### expected behavior

checkbox questions display a list that can be interacted with and selected

#### observed behavior

check questions display a list but arrow keys (nor any key that I can find) do not navigate between options and spacebar does not select options.  Enter does proceed to the next question with no options selected.

#### version information

inquirer@1.2.1
windows git bash @ 2.10.0.windows.1
windows @ Windows Server 2012 R2 Standard

**Comment by SBoudrias** [comment]
Some node version ship with a totally broken readline.

See https://github.com/nodejs/node/issues/5384 for more details. You'll want to try again on latest stable Node.js version.
