### ISSUE TITLE
pass current inquirer session answers hash to filter and validate methods as second parameters

### ISSUE THREAD

**Issue by demircancelebi** [SBoudrias/Inquirer.js#428]
I think adding answers hash as the second parameter to `filter` and `validate` would make inquirer a more powerful tool. This kind of feature might be necessary (at least I needed it) when working with a long set of prompts that should be tied to each other somehow. It would also feel natural since `message`, `default`,  `choices`, and `when` methods already take answers as their first parameter.

**Comment by dickeylth** [comment]
Need it as well.

**Comment by SBoudrias** [comment]
`validate` does take the answer hash as second parameter. I think only `filter` doesn't.

If you want to send a PR, you just have to add it on this line https://github.com/SBoudrias/Inquirer.js/blob/287d437ae505764acbe6d2ecdb5a5c841811e487/lib/prompts/base.js#L88
