### ISSUE TITLE
nodemon and inquirer don't get along

### ISSUE THREAD

**Issue by charliecalvert** [SBoudrias/Inquirer.js#429]
I clone the Inquirer repo. Go to the examples directory. Type the following, and all works as expected:

```
node list.js
```

Now Install nodemon, if you haven't already (npm install -g nodemon) and try again:

```
nodemon list.js
```

When I try to move the arrow keys on the menu I get random characters:

```
Talk to the receptionist ^[[B^[[B^[[Aq^C
```

I understand that this might be a nodemon issue, as designed, or something else altogether, but I'm not sure where to begin tracking this down.

**Comment by SBoudrias** [comment]
Any chance nodemon doesn't spawn the subprocess as a tty? If it only reports logs from the process, then it won't work.

Anyway, this is on nodemon side. You should open an issue over there if you want this fixed.

**Comment by boxpositron** [comment]
I found a solution to this. 
You can tell nodemon to stop listening its restart command.
You can find more information about this in faq link below

https://github.com/remy/nodemon/blob/master/faq.md#nodemon-doesnt-work-with-my-repl

**Comment by Ronald-0001** [comment]
using
nodemon --exec "node" path/to/your/app.js
seems to also work
