### ISSUE TITLE
Handle callback finish

### ISSUE THREAD

**Issue by Ridermansb** [SBoudrias/Inquirer.js#431]
After answer questions.. how to handle callbacks ?

```javascript
inquirer.prompt([ ... ]).then(answers => {
    // Call function, should wait the callback to finish
    callFn({  ...  }, function callback() {
        // this never call
    })
})
```

**Comment by SBoudrias** [comment]
Please refer coding question to StackOverflow. Specifically, in this case you're asking about how promise are working.

You should give this documentation a read: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

**Comment by Ridermansb** [comment]
@SBoudrias I know how promise works.

My question is about handle callback with Inquirer.

Inquirer return to terminal after promise are resolved. But in my case , I execute another code with callback, that are called but the terminal not show anything because already receive return code from Imquirer.

See my code , after Imquirer promise are resolved, I call callFn function with callback.
Callback is never called.

**Comment by SBoudrias** [comment]
That's not about Inquirer. Inquirer doesn't shut the process after it ran. Your code will run as any other code.
