### ISSUE TITLE
ReferenceError after every question input.

### ISSUE THREAD

**Issue by nerdybeast** [SBoudrias/Inquirer.js#434]
I'm getting a `ReferenceError` after every question input and just seeing weird behavior in the console. 

Here is my stack:
Windows 10
node v4.6.1
inquirer v1.2.2

Here is my basic script:
![script](https://cloud.githubusercontent.com/assets/15707802/19623155/0af4956e-987c-11e6-90ca-2815720f0a69.PNG)

And here is what the command prompt looks like using that script:
![command prompt](https://cloud.githubusercontent.com/assets/15707802/19623157/1d86afe6-987c-11e6-8edd-d2265c94863a.PNG)

Thoughts?

**Comment by nickolasclarke** [comment]
I am seeing the same thing with an extremely simple use case. However, I'm rather noob, so perhaps I'm missing something here.  I nearly commented on #410 , but found this to be more accurate. Not only am I getting `ReferenceError` for non-numbers, it is also exiting on completion, even if I just give it numbers. 
```javascript
"use strict"
var inquirer = require('inquirer');

var prompt = inquirer.createPromptModule();
var promptQuestions = [{
  type: 'input',
  name: 'do_api_token',
  message: 'Digital Ocean token:'
}, {
  type: 'input',
  name: 'ssh_key_location',
  message: 'Path of SSH key used to connect to Streisand droplet:'
}]

function getSessionInfo() {
  prompt(promptQuestions).then(answers => {
    console.log(answers);
    
  })
}
```

return with values that I would actually want for my questions:

``` 
 getSessionInfo()
? Digital Ocean token: undefined
? Digital Ocean token: bb4543f0e
ReferenceError: bb4543f0e is not defined
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
? Digital Ocean token: bb4543f0e
? Path of SSH key used to connect to Streisand droplet: ~/.ssh/priv_key
~/.ssh/priv_key
 ^
SyntaxError: Invalid regular expression flags

? Path of SSH key used to connect to Streisand droplet: ~/.ssh/priv_key
{ do_api_token: 'bb4543f0e',
  ssh_key_location: '~/.ssh/priv_key' }
```

another run, this time just spamming with something.

```getSessionInfo()
? Digital Ocean token: undefined
? Digital Ocean token: 123
123
? Digital Ocean token: 123
? Path of SSH key used to connect to Streisand droplet: hi
ReferenceError: hi is not defined
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
? Path of SSH key used to connect to Streisand droplet: hi
{ do_api_token: '123', ssh_key_location: 'hi' }
```

lastly, running with only numbers. Returns successfully, but still exits. adding a .catch() after the .then() block returns the same. 
```
getSessionInfo()
? Digital Ocean token: undefined
? Digital Ocean token: 123
123
? Digital Ocean token: 123
? Path of SSH key used to connect to Streisand droplet: 1232
1232
? Path of SSH key used to connect to Streisand droplet: 1232
{ do_api_token: '123', ssh_key_location: '1232' }
```

*Windows 10 (but running node under Bash on Windows. Havent tried on native node yet)
node: v6.9.1
inquirer@1.2.3*

**Comment by SBoudrias** [comment]
@nickolasclarke how did you run this program? Right now all your input is being parsed as JS - just as if you were in the `node` repl.

This is most probably not a bug with Inquirer.

**Comment by nerdybeast** [comment]
I eventually figured this out, thanks for the follow up @SBoudrias!
