### ISSUE TITLE
Feature or Documentation for complex menu depth.

### ISSUE THREAD

**Issue by cbuteau** [SBoudrias/Inquirer.js#435]
This is a request for feature documentation.
I use this library to build myself menus that result in a series of complex commands at the command line.

It is extremely easy to build menu lists and it functions fine in Cmder.net (a ComEmu packaging that is nice)
Whoever has coded this did a nice job in making the API simple to understand.
It has been very useful to me in chaining commands that I could forget the parameters.

My initial script had nested calls to the main menu script everywhere.
To modularize the code I had to pass the mainMenu function everywhere.

It would be nice if you documented (or exampled) a very complex depth of menus.
Either using a Promise helper library or wrapping calls so the menus and their work can be handle synchronously in a series of objects.

Your current hierarchy example assumes a single script with global functions.
Most coders write OO and modules for Node and JS.

I tried to use Bluebird to wrap the prompt object that came back but Promise.all() did not wait for the result and passed back execution.

Either suggest a strategy or provide a mechanism to chain complex menu selection.

Do not misinterpret this ... it is simple feedback which I feel would make the library even better.
It is an EXCELLENT library.

Thank you for your time.

**Comment by SBoudrias** [comment]
You can check how yo handles it by abstracting menus away in routes https://github.com/yeoman/yo/blob/master/lib/cli.js#L146

**Comment by cbuteau** [comment]
Yeah that is similar to the strategy I came with.  
It just didn't feel that clean because I was calling back into the initial app pointer.

Thanks for responding.

**Comment by SBoudrias** [comment]
No problem, this is really more a problem of how you use the library than a concern the library should address. The library provide the a base tool, but then it's really up to each developer to architect their app as best they can/know.

I'll close the issue as there's no actionable item here.

**Comment by cbuteau** [comment]
Thats fine this issue can serve as the documentation I asked for.
