### ISSUE TITLE
Move up and down to reveal more choices

### ISSUE THREAD

**Issue by ldeluca** [SBoudrias/Inquirer.js#439]
I have 9 choices in a inquirer list prompt and I get the message "Move up and down to reveal more choices). I find it confusing. I'd rather the system show all 9 items in the list OR be configurable so that I could specify when I wanted the "move" guide to appear.

**Comment by SBoudrias** [comment]
We decided the height of the list based on common terminal size setup. We also don't want to make it configurable for this reason.

That being said, we've been talking for a while to make the height relative to the current size of the terminal window. PR is welcomed to add this feature :)

**Comment by ldeluca** [comment]
looks like the code has some logic for "pageSize || 7".  Seems like it could be an option that developers could specify.  What is the reasoning behind them not being able to? wouldn't they still be able to scroll up and down if it's not in view?  or is it more of a concern about the help "move up and down" not being displayed if it's off the terminal height?

**Comment by SBoudrias** [comment]
Letting the developer specify the height they want don't fix the UX/UI issue for end users.

**Comment by ldeluca** [comment]
That's my question. What are/were your ux/ui issues? Just the arrow interaction help comment in gray? Or is there something else as well?

**Comment by SBoudrias** [comment]
Oh, the UI issue is making the prompt too big and then it'll break if it don't fit the terminal.

**Comment by diegohaz** [comment]
Does not it work? (I'm currently using this `pageSize` to control the height of a checkbox)
```js
{
      type: 'list',
      pageSize: 9,
}
```

**Comment by ldeluca** [comment]
pageSize doesn't affect anything for me @diegohaz ... maybe it only works on Windows?  I'm running on a mac.  My pageSize value is set to 10 and it only shows 7 options before asking me to use the arrow keys.

**Comment by diegohaz** [comment]
I'm on Mac. Maybe Yeoman has something to do with it?
![image](https://cloud.githubusercontent.com/assets/3068563/20684081/a888f140-b595-11e6-9d04-9846fd992088.png)

**Comment by ldeluca** [comment]
![image](https://cloud.githubusercontent.com/assets/4448698/20684212/ed994a78-b57c-11e6-8dce-58cac0d78981.png)

Here's my code:

    inquirer.prompt([{
		type: "list",
		name: "template",
		message: welcomePromptMsg,
		pageSize: 10,
		choices: WELCOMEOPTIONS
	  }], function( answers ) {

**Comment by SBoudrias** [comment]
@ldeluca looks like you're using an old version. `inquirer` doesn't uses callback function anymore.

**Comment by ldeluca** [comment]
Thanks @SBoudrias, odd that the callback function still works with version 1.2.3 of inquirer. But I was working off of an older version. Changed the code to use .then and now I see the pagesize properly. Thank you!
