### ISSUE TITLE
Can't seem to select different item

### ISSUE THREAD

**Issue by ORESoftware** [SBoudrias/Inquirer.js#440]
Using this library, and the up and down arrow keys, I cannot select a different checkbox option

```
{
        type: "checkbox",
        message: "Servicios Publicos",
        name: "servicios",
        choices: [
            {
                name: "Agua"
            },
            {
                name: "Luz",
                checked: true
            },
            {
                name: "Internet"
            },
        ],
    }
```

because "Luz" is checked, that option will always be chosen - the UI does not allow me to check a different option. How can I choose Agua or Internet?

**Comment by ORESoftware** [comment]
nevermind, it says to use the spacebar to select checkbox items!

**Comment by SBoudrias** [comment]
Spacebar (that's the standard, it's how it works in UI apps and web browsers). We also support `a` for all and `i` to inverse.

**Comment by ORESoftware** [comment]
Ok cool. I am going to file another issue.
