### ISSUE TITLE
tab completion (for name prompts)

### ISSUE THREAD

**Issue by ORESoftware** [SBoudrias/Inquirer.js#441]
I am looking to get tab-completion, so that the user can select a path from the current working directory.

Is tab-completion possible with this library?

**Comment by SBoudrias** [comment]
There's a few plugins for that:

https://www.npmjs.com/package/inquirer-path
https://www.npmjs.com/package/inquirer-directory

**Comment by ORESoftware** [comment]
I tried inquirer-directory, seems to have a bug, will try inquirer-path

**Comment by ORESoftware** [comment]
I'd recommend that you adopt inquirer-directory and make that core to your lib, plugins have always been dumb, they never work

**Comment by diegohaz** [comment]
I think we should work on this. `inquirer-path` doesn't work with inquirer's last versions (not even v1).

`inquirer-directory` works, but it's not a "tab completion".

**Comment by SBoudrias** [comment]
[cleaning up old issues]

We have a demo available doing mostly this with the `search` prompt. [See here](https://github.com/SBoudrias/Inquirer.js/blob/main/packages/demo/demos/search.mjs#L48-L82)
