### ISSUE TITLE
Make Inquirer.prompt an Observable method

### ISSUE THREAD

**Issue by ev1stensberg** [SBoudrias/Inquirer.js#443]
Would be great if we made `inqurirer.prompt(promise)` an observable method/class by default. This means that we could make logic a lot simpler and we could avoid using `inquirer.promt` on every new logic. Seems now, that in order to have dynamic interfaces, you would need to exit the current prompt and create a new one. 

I imagine the syntax would look like this: 

```js
const questions = {...}
const inquirer = Rx.Observable.inquirer(questions)
inquirer.fromPromise(questions).map( (answer) => {
// application logic
// onNext(questions.next) || generator of some sort
}
```
Please illuminate me if there's any likewise way to do this 👍

**Comment by SBoudrias** [comment]
Well, the prompt method takes an observable as argument no? So if you keep your observable alive, you can just push more prompts as you go.

**Comment by ev1stensberg** [comment]
Got an example of how to do this? It seems like there's only 1 way to validate questions, and that is all at once via the  `inquirer.prompt(obs).then( ans => ...)` promise

**Comment by SBoudrias** [comment]
`inquirer.prompt().ui.process` is an observable if you want to get the answers as an observable.

**Comment by ev1stensberg** [comment]
Great. Thanks for the tip. Closing this now, got enough context to proceed.
