### ISSUE TITLE
create alias for choices

### ISSUE THREAD

**Issue by ORESoftware** [SBoudrias/Inquirer.js#446]
So I have this code:

```js
const secondSetOfQuestions = [
  {
    type: 'list',
    name: 'action',
    message: 'What would you like to do?',
    default: 'Run single test',
    choices: [
      'Run single test',
      'Run multiple tests',
      'Run tests with test coverage (Istanbul)',
    ]
  }
];

inquirer.prompt(firstSetOfQuestions).then(function (respuestas) {

  console.log('Respuestas => ', respuestas);

  if (respuestas.action === 'Generate a valid Suman terminal command') {
    return inquirer.prompt(secondSetOfQuestions).then(function (answers) {
            // do something
    })
  }

}).catch(function (err) {
  console.error(err.stack || err);
});
```

*but* is there a way to do something like this:

```js
const secondSetOfQuestions = [
  {
    type: 'list',
    name: 'action',
    message: 'What would you like to do?',
    default: 'Run single test',
    choices: [
      {  
        value:   'Run single test',
       alias: 'a'
      },
     {  
        value:   'Run multiple tests',
       alias: 'b'
      },
      {  
        value:    'Run tests with test coverage (Istanbul)',
       alias: 'c'
      }
    ]

  }
];
```

....if I can use aliases, then I can do more convenient things, like below:

```js
inquirer.prompt(firstSetOfQuestions).then(function (respuestas) {

  console.log('Respuestas => ', respuestas);

  if (respuestas.action === 'Some value') {
    return inquirer.prompt(secondSetOfQuestions).then(function (answers) {
                return require('./subdir/' + answers.action);   // action = a,b, or c
    })
  }

}).catch(function (err) {
  console.error(err.stack || err);
});
```

as you can see, I am using directory names, and requiring directories to branch my code logic, but it will be less convenient to name a directory:

 'Run tests with test coverage (Istanbul)'

I would prefer to name the directory:

'a'

Let me know! thanks

**Comment by ORESoftware** [comment]
there is a way to do this, I had to go through the code, it is like this, where alias is "name" and the actual value that gets passed back is value.

 choices: [
    {
      value: './node_modules/.bin/suman',
      name: 'Locally installed ($ ./node_modules/.bin/suman foo bar baz)',
    },
    {
      value: 'suman',
      name: 'Globally installed ($ suman foo bar baz)',
    }
  ],

**Comment by ORESoftware** [comment]
this seems like a common need, should this be in the docs?

**Comment by SBoudrias** [comment]
It is documented here with the `choice` key https://github.com/SBoudrias/Inquirer.js#question

**Comment by ORESoftware** [comment]
yeah, a code sample would help there, though
