### ISSUE TITLE
Windows 10 / Node 7 UnhandledPromiseRejectionWarning on prompt

### ISSUE THREAD

**Issue by macdonaldr93** [SBoudrias/Inquirer.js#447]
When running inquirer on Windows 10, Node 7.x, I'm getting this breaking error. The CLI just hangs afterwards:

```
(node:5764) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: write EINVAL
(node:5764) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
not handled will terminate the Node.js process with a non-zero exit code.
```

This is more or less the code that we're running:

```js
async function(name) {
  let dirName = name;

  if (!dirName) {
    const answers = await prompt({
      type: 'input',
      name: 'dirName',
      message: 'What do you want to name the directory?',
      default: 'theme',
    });

    dirName = answers.dirName;
  }
}
```

Also tried without async/await, but still getting the error.

**Comment by mischah** [comment]
Should be fixed with the current Node Release from today:

Qoute from https://github.com/yeoman/yo/issues/485#issuecomment-262441418
> Closing this since Node 7.2 fixes this issue:
> https://nodejs.org/en/blog/release/v7.2.0/
