### ISSUE TITLE
End prompt midway

### ISSUE THREAD

**Issue by 0x62** [SBoudrias/Inquirer.js#448]
I've been looking for a way to end a set of prompts midway.

I have an input, and then a list. The input is used to generate the options for the list:

```
[{
    type: 'input',
    name: 'query',
    message: 'Find user by any field: ',
    validate: val => {
      return /\S/.test(val) ? true : 'Please enter a search query'
    }
  }, {
    type: 'list',
    name: 'user',
    message: 'Select user: ',
    choices: res => {
      return new Promise(resolve => {
        let query = { $text: { $search: res.query } }
        User.find(query).exec((err, users) => {
          resolve(users.map(user => ({ name: `${user.email} (${user.profile.name || 'no name' })`, value: user })));
        });
      })
    }
  }, { ... }]
```

My issue is when no users are found. `users` is an empty array, so `map` returns an empty array, which is then passed to the list of choices, which causes a list to be drawn with no options (possible bug?). 

Following the list prompt, I have several more which rely on the value returned by the list (they are all operations which can be done on the user object). If no user is found, I need to exit the prompt automatically (or return to the input query).

I'm aware I could validate by performing a DB call within `validate`, however I'd prefer to only make one query. I could also store the returned users from validate in a global, then check it again from within select user, but this is a little messy.

Is there a way to programmatically exit the sequence?

**Comment by SBoudrias** [comment]
Can you use `when` to skip your empty prompt?

**Comment by 0x62** [comment]
That would require all subsequent prompts (of which there are quite a few) to check that the users array isn't zero-length, which is a bit messy.

**Comment by SBoudrias** [comment]
Well it is just JavaScript, split your prompt array in two and only run the second group only if the results from the first session warrant it.
