### ISSUE TITLE
Enhancement/discussion: change in flow based on answers.

### ISSUE THREAD

**Issue by CDHDeveloper** [SBoudrias/Inquirer.js#45]
As pizza.js shows things work fine as long as question flow is in a strictly linear fashion. But consider where the answer to one question affects the flow of another question. For example                      lets say that Node Pizza also offers calzones and subs and salads. Then a user would need to be asked what type of thing they want to order and based on that they would have a subset of questions to answer (perhaps coming back to the original series of questions to finish up/continue).

Could that be handled with some alterations to the inquirier module without adversely affecting the linear/serial flow of questions?

**Comment by dgrcode** [comment]
I think this should be in the documentation. I've also found a separate issue opened for this purpose https://github.com/SBoudrias/Inquirer.js/issues/1081
