### ISSUE TITLE
Callback method does not work after 0.12.0

### ISSUE THREAD

**Issue by shesmu** [SBoudrias/Inquirer.js#452]
Not sure if this was intentional but
`inquirer.prompt([
	  {
	    type      : "list",
	    name      : "foo",
	    message   : "Result",
	    choices   : choices,
	  }
	], function(answer) {
		console.log(answer);
	});`
no longer works post 0.12.0, the callback function is never called.

**Comment by SBoudrias** [comment]
This is intentional. It now returns a promise.
