### ISSUE TITLE
Allow cancelling input with Esc key

### ISSUE THREAD

**Issue by laggingreflex** [SBoudrias/Inquirer.js#454]
I want the user to be able to escape out of the input by hitting <kbd>Esc</kbd> key. 

There should be an option which if turned on tells Inquirer to reject the promise of the prompt when user hits <kbd>Esc</kbd>, and let the program handle that rejection. 

It's kind of similar to #148 but it shouldn't exit, just reject. 

Was this almost implemented in #427 but only for list input? I haven't looked into it in detail but if it's what I think it is, that's exactly what I wanted but for all kinds of input - answer, checkbox etc. 

And would it also solve #291? It asks for a similar feature but using <kbd>Ctrl</kbd><kbd>c</kbd>. I think <kbd>Esc</kbd> would be much better. 

Thoughts?

**Comment by episodeyang** [comment]
this is such an important issue. I hope this is merged.

**Comment by sidharthv96** [comment]
It is not possible to cancel List input either using `Ctrl + C` or `Esc`

**Comment by SBoudrias** [comment]
With the new API, you can now cancel a prompt cleanly. [More on this in the README](https://github.com/SBoudrias/Inquirer.js#canceling-prompt)

So for this use case, you'd set an event listener for the escape key, and cancel the prompt (in user code, so there's a bit of plumbing to do.) You can take inspiration from this recipe here [doing the same thing, but with a timeout](https://github.com/SBoudrias/Inquirer.js#get-default-value-after-timeout).

If you need something more precise, consider building a custom prompt. This should also be simpler than before with [the new core](https://github.com/SBoudrias/Inquirer.js#create-your-own-prompts).
