### ISSUE TITLE
'expand' - make help default

### ISSUE THREAD

**Issue by ihorskyi** [SBoudrias/Inquirer.js#456]
What is a correct syntax to make `expand`'s `help` item to be default instead ot the very first `Item A`?

```javascript
const QUESTION = {
  type    : 'expand',
  name    : 'root',
  message : 'Choose an item',
  default : 'help',    // <------------ kind of like this
  choices : [
    { key:'a', value:'item_a',  name:'Item A'  },
    { key:'b', value:'item_b',  name:'Item B'  }
  ]
}
```

**Comment by SBoudrias** [comment]
Just use a `rawlist` for a very similar UI. Expand prompts cannot be expanded by default.

**Comment by ihorskyi** [comment]
@SBoudrias but `rawlist` won't accept any other shortcut keys, except item's index?

**Comment by SBoudrias** [comment]
Yes, that's correct.

If you just want to present a list of options, then we consider indexes to be a better UX for the end user.

**Comment by ihorskyi** [comment]
This is a workflow I'm trying to achieve:

1. User launches a cli app and sees lot of options (let's say 15)
2. User forgot which key corresponds to item so he just press `Enter`
3. Help shows items and their short-cut keys (**same as used in CLI version**)
4. User clicks that key and action is triggered

Thus having same shortcut keys is very important, b/c in most cases user will remember most used ones in CLI and will easily use same in inquirer
