### ISSUE TITLE
Use strict dependency version numbers - Security vulnerability

### ISSUE THREAD

**Issue by jondubois** [SBoudrias/Inquirer.js#460]
It looks like inquirer uses a lot of small dependencies with version numbers in the format `^x.x.x` - Is it possible to just drop the `^` and update manually as needed? https://github.com/SBoudrias/Inquirer.js/blob/master/package.json#L22-L56

Each dependency is a potential security vulnerability; if the the author of any of those has malicious intent (or gets hacked); they can easily push out a virus on the machines of all `inquirer` users and no one will notice initially.

It's hard to control sub-dependencies, but I think it would be nice if every module did its part.
I don't see the benefit of auto-updating such trivial modules.

**Comment by wtgtybhertgeghgtwtg** [comment]
> I don't see the benefit of auto-updating such trivial modules..

Even if you use Greenkeeper, it is extremely easy to let dependencies get stale, and makes deduping very difficult.

**Comment by jondubois** [comment]
I guess it depends on preference. Personally I prefer to have stale dependencies and update them only when needed than to run the risk of an arbitrary sub-module owner sneaking in malicious or unwanted code into my module.

It's always safer to trust 1 person you know than 100 people you don't know.

What if the dependency module owner decides to add a patch which is good for 95% of all projects that depend on it, but YOUR project just happens to be in the 5% where it's not suitable (in fact it actually breaks your project).

You're just giving trust and control to the dependency owners (which is only as truthworthy as the least trustworthy among them) and making it so that every user who installs your module ends up with different permutations of dependency versions (often making issues within your own module difficult to reproduce).

And as demonstrated by the `left-pad` [drama](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/), relationships/trust between people does disintegrate over time.

**Comment by wtgtybhertgeghgtwtg** [comment]
> You're just giving trust and control to the dependency owners (which is only as truthworthy as the least trustworthy among them)

You're already trusting them by using their package.  And it is in their best interest to make sure that non-major releases do not break.  If they do, you can raise an issue and work with them to fix it.  It's a mutually beneficial relationship.

**Comment by jondubois** [comment]
@wtgtybhertgeghgtwtg I trusted the code itself (as it was at a specific point in time); I don't necessarily trust all of the sub-project owners on an ongoing basis (especially since there are a lot of them involved). This is mostly an issue when it comes to code auditing.

I just raised this issue because some companies are really strict regarding dependencies.

It's low priority. Just something to think about. Feel free to close, anyone.

Thanks for your feedback @wtgtybhertgeghgtwtg - I'm still trying to decide how to approach that other dependency issue you raised in SC - I think having a separate CLI module as you recommended might be the best solution - There are a few issues I have to think about before doing this though.

**Comment by SBoudrias** [comment]
@jondubois the responsibility of pining dependencies relies on the end users with the Node ecosystem. For this you want to use either npm shrinkwrap or Yarn.

Even if I were to ping the dependencies, each of inquirer dependencies are still not pining their dependencies, and they'd get update. So this wouldn't fix any security issue.
