### ISSUE TITLE
Dropped node 0.12 support in minor version update

### ISSUE THREAD

**Issue by ThomWright** [SBoudrias/Inquirer.js#461]
The most recent release (v1.3.0 07c0683) has broken support for node 0.12.

I see you dropped support for node 0.12 in your tests here 4a44e94 - I assume because `string-width` and `figures` did so in their *major* version bumps here 3943f35.

This should be a **major** version bump.

**Comment by SBoudrias** [comment]
Unpublished 1.3 and released 2.0

**Comment by ThomWright** [comment]
Thank you :smile:
