### ISSUE TITLE
This just broke all my builds

### ISSUE THREAD

**Issue by ronkorving** [SBoudrias/Inquirer.js#462]
Sorry for the cynical title, but here we go...

Just a quick notice regarding what happened yesterday. Because 1.3.0 got unpublished and I just started using Inquirer.js (and thus used ^1.3.0) all my builds starting breaking today.

Please [read](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy) up on unpublishing if you haven't yet. I'm sure and I understand you had your reasons. I just wanna make sure you know there's a real impact on users. Thanks for your consideration.

**Comment by SBoudrias** [comment]
See #461

I'm sorry it causes you troubles, but sometime there's no perfect solutions.
