### ISSUE TITLE
Password field not masked when run in nodemon?

### ISSUE THREAD

**Issue by alancwoo** [SBoudrias/Inquirer.js#467]
Not sure if this should be directed at nodemon, or perhaps it's even considered a debugging feature, but the password field is not masked when running inside nodemon.

Actually had the same problem with [flatiron/prompt](https://github.com/flatiron/prompt/issues/98) so maybe the issue is related?

**Comment by SBoudrias** [comment]
I would assume nodemon is wrapping the module in some way that might prevent us from correctly handling the node readline.

**Comment by artus9033** [comment]
Looks like the issue is still reproducible while using nodemon.

**Comment by SBoudrias** [comment]
To run with nodemon:

```sh
npx nodemon ./packages/demo/demos/password.mjs --no-stdin
```

It requires the `--no-stdin` flag otherwise it'll print everything types. This is not specific to `inquirer`.

This has been document a while over at https://github.com/SBoudrias/Inquirer.js/tree/main/packages/inquirer#known-issues
