### ISSUE TITLE
Configurable getAnswers: () => Answers parameter

### ISSUE THREAD

**Issue by colelawrence** [SBoudrias/Inquirer.js#469]
It would be nice to have a way to listen to answers being set, and passing in answers to active prompts. This would be especially useful for closer control over `question.default` behavior.

I struggled to get this working incredibly well, until I ended up assigning `default` to a function which had the answers which inquirer was tracking, and I injected my answers before passing it down.

**Comment by SBoudrias** [comment]
@ZombieHippie I'm not sure I understand your request? What's wrong with using the answer object passed as argument?

**Comment by ZombieHippie** [comment]
How do you pass the answers as an argument?

**Comment by SBoudrias** [comment]
It's automatic, the functions just receive them.

```js
{
    default: function (answers) {
        return 'default value';
    }
}
```

If this is not working, then make sure you're using the latest Inquirer.

**Comment by ZombieHippie** [comment]
No, I understand this, thank you for the attention to my question.

I mean when you call inquirer.prompt(questions, answers)

Or, my original thought for complete control,

inquirer.prompt(qs, {
  onUpdate: (question, value, answers) => do something, return new answers.
})

Etc.
