### ISSUE TITLE
There is an way to cancel/update the current prompt? 

### ISSUE THREAD

**Issue by calebebrim** [SBoudrias/Inquirer.js#474]
The scenario is: 
I Have a lot of back processing. Based on realtime process I want to change the current prompt. 

There is an way to cancel the old question or to update the current one?

**Comment by whitecolor** [comment]
```js
var prompt = inquirer.prompt(...);
prompt.ui.close();
```

**Comment by SBoudrias** [comment]
The new API now exposes a clean & documented way to do this. [More on the README](https://github.com/SBoudrias/Inquirer.js#canceling-prompt)
