### ISSUE TITLE
Is there any way to remove the keyup related events?

### ISSUE THREAD

**Issue by Aaaaaashu** [SBoudrias/Inquirer.js#477]
When I use the Inquirer.js with blessed-contrib, keyup event will be conflict, so I hope after using the  Inquirer.js, remove the keyup relate event.

**Comment by SBoudrias** [comment]
How would we detect keys press if we can't listen to keyup?

**Comment by Aaaaaashu** [comment]
@SBoudrias 
What I mean is that when using Inquirer.js ended, remove the keyboard related events.

**Comment by SBoudrias** [comment]
I do believe we're properly cleaning inquirer keypress listeners when the prompt is answered.

Can you provide a specific code example with which I can reproduce this bug?

I'm going to close this issue for now, but I'll reopen if you can add helpful details to help me debug your issue.
