### ISSUE TITLE
rawlist: "Move up and down to reveal more choices" 

### ISSUE THREAD

**Issue by jbdemonte** [SBoudrias/Inquirer.js#481]
As describe on #199

rawlist prompt "Move up and down to reveal more choices" while up & down arrows are not usable

**Comment by RonWang** [comment]
Is there any correction for that?
Also when I input the number of answer, the first line of the list will go up to the line of the question. Any solution to that?

**Comment by stop2stare** [comment]
I've updated Inquirer to the newest version and it seems to be unsolved still.
Do I have to set `type` to `list` to scroll the choices with keyboard UP and DOWN? Any workaround? THX.
