### ISSUE TITLE
initialize with answers?

### ISSUE THREAD

**Issue by ianwremmel** [SBoudrias/Inquirer.js#483]
I've got a config file that may be partially populated before I use inquirer. Is there a way to pass the values of that config file into inquirer so that my `when` functions can treat the config as answers?

right now, my `when` blocks are shaping up to look like

```
when(answers) {
  return (!has(answers, `key-a`) && !has(config, `key-a`) 
}
```

**Comment by SBoudrias** [comment]
Inquirer is only javascript, so yeah:

```js
var config = getMyConf();

inquirer.prompt([{
  ...
  when: function() {
    console.log(config); // it's available here due to variable scoping
  }
}])
```

**Comment by ianwremmel** [comment]
right, but that means i have to check both the config object and the answers passed to `when`. 

Rather than

```javascript
var config = getMyConf();

inquirer.prompt([{
  ...
  when: function(answers) {
    return (!has(answers, `key-a`) && !has(config, `key-a`) 
  }
}])
```

something more like

```javascript
var initialAnswers = getMyConf();

inquirer.prompt(initialAnswers, [{
  ...
  when: function(answers) {
    return !has(answers, `key-a`);
  }
}])
```

would make things a bit easier.

**Comment by SBoudrias** [comment]
I don't think it's making the code clearer or easier to understand. Also, depending on each person use case, you would probably want slightly different logic; example, someone want to pass `null` value as answer, but someone else wants to ignore it, etc.

I don't think that's something that would make Inquirer better and benefit most users.

**Comment by fogine** [comment]
@SBoudrias I disagree. It would simplify users' code a lot.

> Also, depending on each person use case, you would probably want slightly different logic; example, someone want to pass null value as answer, but someone else wants to ignore it, etc.

I don't think I understand your argument. The proposal is simply about the ability to set the initial `answers` instance property value of `PromptUI` which should always be a hash map.

> I don't think that's something that would make Inquirer better and benefit most users.
Because I don't understand your argument (explained above), the quoted statement doesn't make sense to me either. Please, could you elaborate?

```diff
diff --git a/lib/ui/prompt.js b/lib/ui/prompt.js
 util.inherits(PromptUI, Base);
 
-PromptUI.prototype.run = function (questions) {
+PromptUI.prototype.run = function (questions, answers) {
   // Keep global reference to the answers
-  this.answers = {};
+  this.answers = _.isPlainObject(answers) ? answers : {};
 
   // Make sure questions is an array.
   if (_.isPlainObject(questions)) {

```
