### ISSUE TITLE
Need pinkie-promise in your package.json

### ISSUE THREAD

**Issue by sbonnet** [SBoudrias/Inquirer.js#487]
Cannot find module 'pinkie-promise' on /lib/ui/prompt.js.

I think you just miss to add to your package.json.

**Comment by insin** [comment]
The import should be removed if the intention was to drop support for Node.js v0.12.

pinkie-promise is also still present in `yarn.lock`.

**Comment by SBoudrias** [comment]
Thanks for reporting. It's now fixed.
