### ISSUE TITLE
How to extend Key events - (Urgent help required)

### ISSUE THREAD

**Issue by souravray** [SBoudrias/Inquirer.js#490]
I have an application wich displays a lsit like bello

> text 1
> text 2
> text 3

Say we selected "text 2"
Now on pressing Enter it shows
> text 2 description

I want to have another key functionlity like, when  "c" key is pressed then it will show
> "text 2"  is copyied 
and application will terminate.

I cannot figure out a way to bind custom keyboard events to my prompt callback method. Please let me know if there is a way to extend the default event hander of prompmt object.

P.S.  I am not a regular Node developer, so possibilly my question is ,may sounds stupid to you. Sorry for that, but please reply to my query.

**Comment by SBoudrias** [comment]
This is not a feature supported by Inquirer. You'd have to create a custom prompt yourself to allow for that behavior.

**Comment by souravray** [comment]
Thanks SBoudrias, but couldn't find any documentation on creating a custom prompt.
Do you think there is any existing custom prompt that I can refer to?
