### ISSUE TITLE
Timeout/cancel current prompt?

### ISSUE THREAD

**Issue by christav** [SBoudrias/Inquirer.js#491]
I have a scenario where I need to prompt for some input (in my case a yes/no confirm call). However, if I don't get an answer within 30 seconds I need to assume yes and move on.

I can do this by creating a second promise that just completes after 30 seconds and using Promise.race so that I'm sure to complete within my timeout. However, at that point the original prompt is still open and waiting for keyboard input.

This is resulting in annoying extra text being output after the timeout, and messed up keyboard input. In particular, in my simplified test even though the process is done, it's still waiting for keyboard input. Is there a better way to do this timeout?

Sample code:
```javascript
const inquirer = require('inquirer');

let p1 = inquirer.prompt([
  {
    type: 'confirm',
    name: 'result',
    message: 'Do it?',
    default: true
  }
]);

let p2 = new Promise((resolve, reject) => {
  setTimeout(resolve, 30000);
}).then(() => {
  console.log('Timed out');
  return { result: true };
});

Promise.race([p1, p2]).then(v => { console.log(`And done with result ${v.result}`)})
  .catch(ex => { console.log(`Error: ${ex.message}`)});
```

**Comment by SBoudrias** [comment]
You could maybe trigger a `SIGINT` event on the readline?

Otherwise, a clean way could be to implement a custom prompt "confirm-with-timeout" that'd handle an answer timeout.

**Comment by christav** [comment]
@SBoudrias Any pointers, documentation or examples I can look at to figure out how to write a custom prompt?

**Comment by souravray** [comment]
@christav I figure out that the original prompts are reference for writing your own prompt.
https://github.com/SBoudrias/Inquirer.js/tree/master/lib/prompts

You can use the custom prompt in your code just by registaring the prompt

```
var inquirer = require('inquirer');
var timeoutPrompt = require('./prompts/my-shiny-new-timeout-prompt')

inquirer.registerPrompt(' timeout',  timeoutPrompt );

var pmt = inquirer.prompt([{
		type: 'timeout',
		name: 'url',
		message: ' some random message',
		choices: choices,
		input: stdin,
	}], function (answers) {
		console.log ( answers.name + " Got selected")
	});
```

**Comment by SBoudrias** [comment]
Thanks for helping out @souravray :)

**Comment by SBoudrias** [comment]
Also, realize we were doing this here https://github.com/yeoman/insight/pull/51/files

```js
var prompt = inquirer.prompt(...);
prompt.ui.close(); // will cancel the current prompt
```

**Comment by kvz** [comment]
I’m trying prompt.ui.close(), and it works 🎉

however I do get the warning that the method “is protected and only accessible within class ‘UI’ and its subclasses”

Any chance we can get a public interface for this? It’s quite useful for my UI

**Comment by SBoudrias** [comment]
@kvz this might come from definitely-typed if you use Typescript. There's no protected method on the class in inquirer's own codebase.

**Comment by kvz** [comment]
that must be it yes 👌

**Comment by kvz** [comment]
I hope the method can remain publicly accessible also in future majors, and then i will just add an ignore, thank you!

**Comment by JesusDR01** [comment]
Same problem here
I had to use:
```ts
type ui = { ui: any };
let prompt: Promise<Answers> & ui;
```

Because 
```ts
type ui = { ui: inquirer.ui.Prompt<Answers> };
let prompt: Promise<Answers> & ui;
```


prompt.ui.close(); was causing  “is protected and only accessible within class ‘UI’ and its subclasses”

Coming from /node_modules/@types/inquirer/lib/ui 

<img width="623" alt="image" src="https://user-images.githubusercontent.com/15522791/204787595-dab62ec6-5c08-4175-bf82-7768519b686f.png">
