### ISSUE TITLE
issue with getting call-back from custom prompt

### ISSUE THREAD

**Issue by souravray** [SBoudrias/Inquirer.js#493]
I have implemeted the _run method in my custop prompt -

```
Prompt.prototype._run = function (cb) {
  this.done = cb;
  // some code
  //  --------
  this.render();
  return this;
}
```
 and then called the callback method -
```
 Prompt.prototype.onSubmit = function (value) {
  \\ custom logic
  this.done(value);
};
```
The call back method is passed, like - 
```
var pmt = inquirer.prompt([{
	type: 'mypromt',
	name: 'xxx',
	message: ' some random message',
	choices: choices,
	input: stdin,
}]).then(function (answers) {
	// My custom call back method (not getting called)
})
```
The annonimus function in  .then() is not getting called 

I am not sure whether is it a bug or I am missing something in the custom prompt implementation.

**Comment by SBoudrias** [comment]
Well, are you sure onSubmit is getting called?

**Comment by souravray** [comment]
yes on submit is getting called. I am re-render the sceen in onSubmit, and that logic is working fine.

**Comment by souravray** [comment]
I printed a console.error in the base class and it looks likes `resolve(value)` is also get called.

**Comment by souravray** [comment]
Looks like some peculiar JSissue. This code is working fine -

```
var pmt = inquirer.prompt([{
	type: 'mypromt',
	name: 'xxx',
	message: ' some random message',
	choices: choices,
	input: stdin,
}]);
pmt.then(function (answers) {
	// My custom call back method (it'st getting called)
})
```
