### ISSUE TITLE
[WARNING] prompt

### ISSUE THREAD

**Issue by Necmttn** [SBoudrias/Inquirer.js#498]
is there any way we can create warning with Inquirer
which will show after previous prompt true.
react-boilerplate/react-boilerplate/pull/1523

**Comment by SBoudrias** [comment]
Can you explain a bit more about your use case? If you just want to display a prompt line, then you can call `console.log()`.

**Comment by Necmttn** [comment]
We are using Plop for generate components. which depends on this repo. 
![image](https://cloud.githubusercontent.com/assets/5212808/23153741/1e6c8c4a-f845-11e6-9d33-cf6ef4992c22.png)
Currently best solution we did able to is like this. 
we show line of prompt with no argument. 

```
 {
    type: 'confirm',
    name: 'wantActionsAndReducer',
    default: true,
    message: 'Do you want an actions/constants/selectors/reducer tuple for this container?',
  }, {
    when: (response) => response.wantActionsAndReducer,
    name: 'actionsAndReducerWarning',
    message: chalk.yellow('️⚠️ Not loading in a route?, Add to app/reducers.js: combineReducers. Ref #1407. [ENTER]'),
  },
```
but it's still require us to press ``enter`` for go next prompt. 

what we want is just show the warning message in new line show next prompt.

for reference
https://github.com/Necmttn/react-boilerplate/blob/f2a971b5e24af0e59e18aee0ed471dc218f09fde/internals/generators/container/index.js

**Comment by SBoudrias** [comment]
Not sure I understand why you can't use `console.log('my message')`. Inquirer is still only javascript. If you log in between 2 prompts, it won't mess up with Inquirer layout.
