### ISSUE TITLE
Communicating answers to inquirer.js through stdin

### ISSUE THREAD

**Issue by brianvoe** [SBoudrias/Inquirer.js#502]
I was trying to test some code that i was working on and wanted to spawn or exec a script that runs inquirer. The problem was i wasn't able to send enter key or up/down arrows to stdin to answer the questions. Any idea how to achieve this?

Thanks and good job!

**Comment by SBoudrias** [comment]
That's the file handling events https://github.com/SBoudrias/Inquirer.js/blob/master/lib/utils/events.js

It's listening for `keypress` events on the `Readline.input` stream. If you send your events on that stream, Inquirer will catch them.
