### ISSUE TITLE
Can I clear the prompt when I finish input ?

### ISSUE THREAD

**Issue by foisonocean** [SBoudrias/Inquirer.js#504]
For example, I used a "type: list" prompt, and when I select one of choices, it still show the message and the choice I choose there, I want to clear them, how can I do?
Sorry for my English.

**Comment by SBoudrias** [comment]
This is not an option currently. What's your use case?

**Comment by foisonocean** [comment]
@SBoudrias 
I have a list of questions, and before ask questions, I will print some info in the screen. If each question leave a message, the screen will scroll, so people can't see the info before the question.

**Comment by SBoudrias** [comment]
You can add the information in the prompt `message`

Like:

```js
message: [
  'Some information',
  'And more info',
  'And my question:'
].join('\n')
```

**Comment by foisonocean** [comment]
@SBoudrias 
The information is generated by other codes, put the information to prompt `message` will make it too coupled. Also, put the information to prompt `message` means the information will be printed many times, which is not what I want.
So could you please make a option to clear the prompt ? Thanks a lot.

**Comment by fogine** [comment]
@foisonocean , on Linux systems, when you print "\033c" sequence. it will clear user's console.
