### ISSUE TITLE
typeahead for lists

### ISSUE THREAD

**Issue by jpnelson** [SBoudrias/Inquirer.js#505]
if the selection was

> apple
> banana
> cranberry

typing `c` would highlight that option.

Would a PR to do this be accepted?

**Comment by jpnelson** [comment]
I've got something mostly working, but I have a dilemma now – j and k navigation will compete with the typeahead.

So for this list:

> a
> b
> c
> jjk
> d

typing `jj` will no longer select c, it will select `jj`.

So my options are:

1) detect when in "j / k nav mode"
2) make the autocomplete behaviour optional

which would you prefer?

**Comment by SBoudrias** [comment]
There's a few plugins already doing that - you might want to have a look https://github.com/mokkabonna/inquirer-autocomplete-prompt

The base prompt in Inquirer at the moment are in my opinion final. I prefer to see extra prompts published as plugin.
