### ISSUE TITLE
checkbox: accepting default choices still displays instructions after selection

### ISSUE THREAD

**Issue by mysticflute** [SBoudrias/Inquirer.js#507]
I have a checkbox prompt with some of the choices with checked:true.

When you accept these defaults without toggling any of them (space, a, i) it prints the line of the selected choices as expected but that line still contains the instruction text:
(Press <space> to select, <a> to toggle all, <i> to inverse selection)

![screen shot 2017-02-23 at 3 50 30 pm](https://cloud.githubusercontent.com/assets/327116/23278531/dcb08184-f9df-11e6-8d0b-8a96dfb24c09.png)

**Comment by mysticflute** [comment]
actually this also happens if you use the <a> and <i> shortcuts too. So the only way to get rid of that is to use <space> on a specific choice

**Comment by SBoudrias** [comment]
Good catch, that's a bug.

**Comment by andyford** [comment]
I ended up here because I was trying to figure out why the keyboard hints disappeared as soon as you pressed space, a, or i (before pressing Enter to continue). It's actually very confusing to remove hints while a user is still trying to use the prompt.
