### ISSUE TITLE
checkbox formatting issue

### ISSUE THREAD

**Issue by mysticflute** [SBoudrias/Inquirer.js#508]
I'm using the checkbox and it doesn't look much like the example in the readme:

![screen shot 2017-02-23 at 3 57 09 pm](https://cloud.githubusercontent.com/assets/327116/23278972/753dcc3a-f9e1-11e6-9aea-8e7a9c4c5b9b.png)

specifically it's missing a space after the checkmark/circle (and the circle itself looks different too).

I'm using OS X Sierra 10.12.3, Terminal app, node 7.6.0.

**Comment by SBoudrias** [comment]
These are fonts related. Different fonts will render glyphs differently.
