### ISSUE TITLE
Not clearing properly

### ISSUE THREAD

**Issue by mokkabonna** [SBoudrias/Inquirer.js#510]
Hi, after this change https://github.com/SBoudrias/Inquirer.js/commit/51ea8e44df31858c61955ce9cc4498028cf3c602

I get the following output:
![image](https://cloud.githubusercontent.com/assets/230877/23399909/55fd344a-fda2-11e6-8ba7-ce9e2a4de867.png)

With the done call I get 
![image](https://cloud.githubusercontent.com/assets/230877/23399929/6e694af0-fda2-11e6-824f-7db19ff73698.png)

I am aware of the other issue https://github.com/SBoudrias/Inquirer.js/issues/506 that was the cause for that change.

Do you get the same behaviour as me or do you get a blank line on interrupt? Could we have some platform issues? I have node LTS 6.9.5 and ubuntu 14.04.

I get the same problem with all prompts I tested, input, list, autocomplete.

**Comment by SBoudrias** [comment]
What I see is like your second screenshot. When user `ctrl-c`, the prompt goes directly under all the content (including the help text)

Node 7.6 on osX

**Comment by SBoudrias** [comment]
Okay, release version with the PR fix.
