### ISSUE TITLE
Documentation Images

### ISSUE THREAD

**Issue by calebebrim** [SBoudrias/Inquirer.js#515]
Hello, the documentation images are missing. 
This is affecting github and npm page.

**Comment by SBoudrias** [comment]
Looks like dropbox close down the public images... What do people use to host images in readme nowaday?

**Comment by mokkabonna** [comment]
You can host them in the repo itself with a relative url from the readme.

**Comment by SBoudrias** [comment]
And it's back! Thanks for the report
