### ISSUE TITLE
Running under a git hook auto answers 

### ISSUE THREAD

**Issue by bapti** [SBoudrias/Inquirer.js#518]
I'm using inquirer to build a little CLI tool, great library!

I have a script that's my pre-push hook for git below

```sh
#!/bin/bash
node ~/my-script.js || exit
```

When running under git it auto-populates the answer in inquirer, when I run the script manually it works and asks me the question. I've been reading through the issues but I can't figure out why this might happen.

**Comment by SBoudrias** [comment]
Inquirer won't run in non-tty environment. The git hook is probably called in a sub process or a process without access to the prompt tty.

**Comment by bapti** [comment]
Thanks @SBoudrias  for the quick response, more googling required from me then! Thanks for the hint

**Comment by bapti** [comment]
Thanks again @SBoudrias - this was the hint I needed

Adding the following command to my pre-hook has made my tool work as expected

```sh
exec < /dev/tty #allow interactive shell commands
```

**Comment by eitah** [comment]
@bapti Brilliant!!! this thread saved the day.

Since my team uses Husky to manage githooks it was as simple as:

>         "postcommit": "my-script < /dev/tty"

thanks again!!

**Comment by quasivivo** [comment]
On our Windows (git bash) development machines, having"< /dev/tty" inside the package.json Husky command failed with:  "The system cannot find the path specified."

This alternate approach worked:

**package.json**:
"pre-push": "sh hooks/prepush.sh"

**prepush.sh**:
#!/bin/sh
exec < /dev/tty

node ./hooks/prepush/script.js

**Comment by pcicho** [comment]
@bapti @SBoudrias @eitah it took me hours to solve this problem, thanks guys you are my heroes!

**Comment by SBoudrias** [comment]
I raised this up to the README https://github.com/SBoudrias/Inquirer.js#using-as-pre-commitgit-hooks-or-scripts

**Comment by monolithed** [comment]
It seems like Husky isn't running the script on Mac

```json
{
   "precommit": "node .husky/dump.mjs < /dev/tty"
}
```
