### ISSUE TITLE
Redirect Output

### ISSUE THREAD

**Issue by brianantonelli** [SBoudrias/Inquirer.js#519]
Would love to see a configuration option to redirect output to `stderr` instead of `stdout`. That way programs could support functionality like:
```
eval $(myapp dosomething)
```
Then we could then display the prompt through `stderr` so that only the response will be evaluated.

**Comment by jrylan** [comment]
@brianantonelli I needed this too and just discovered it's already available.

```js
const inquirer = require('inquirer')

const prompt = inquirer.createPromptModule({ output: process.stderr })

prompt(/* question array/object here */)
```

**Comment by SBoudrias** [comment]
@jrylan thanks for following up with the proper way to handle it <3

**Comment by brianantonelli** [comment]
Thx!

**Comment by brianantonelli** [comment]
So I'm still seeing some issues with this. I followed @jrylan 's instructions and my prompts are now directed to `stderr` which is perfect. However, I'm still seeing some rogue control characters being sent to `stdout`.. Thoughts?

```
^[[?25l^[[?25hexport AWS_ACCESS_KEY_ID=aaa && export AWS_SECRET_ACCESS_KEY=bbb && export AWS_SESSION_TOKEN=ccc
^[[?25h
```

**Comment by jrylan** [comment]
@brianantonelli That's strange, is that on AWS? I'm using iTerm2 as my terminal on macOS and all the output is identical when using `process.stderr` -- everything works perfectly fine.

**Comment by brianantonelli** [comment]
No, running this on OSX in Terminal. As soon as I make the call to inquirer I get those control chars. The one at the end really throws me because its printing that many function calls later.

**Comment by SBoudrias** [comment]
@brianantonelli weird, but that doesn't seem relate to Inquirer. As you might guess, we're not snooping in on your AWS creds.

**Comment by brianantonelli** [comment]
That's just an example output from an application that leverages this library. In my application if I pipe all data to stderr using the above solution and only do a single output to stdout (the AWS keys export command in this case) I see these control characters. If I remove the call to inquirer the control chars disappear.

**Comment by SBoudrias** [comment]
@brianantonelli I'm not super familiar with that, but any chance some ANSI control chars can't be use on stderr?

**Comment by brianantonelli** [comment]
This only occurs if you use the list prompt. If I do a standard input prompt the characters aren't there. Here's a snippet to reproduce this:

```
var inquirer = require('inquirer'),
    prompt   = inquirer.createPromptModule({ output: process.stderr });

console.error('start');

if(process.argv[2] === 'inq'){
    prompt([ { type: 'list', name: 'test', message: 'Test', choices: ['a', 'b', 'c'] }]).then(function(answers){
        console.error(answers);
    });
}

console.log('test');
console.error('stop');
```

- Running `node test.js > out.txt && vi out.txt` shows no control characters:
```
test
```
- Running `node test.js inq > out.txt && vi out.txt` shows control characters:
```
^[[?25ltest
^[[?25h^[[?25h
```

**Comment by brianantonelli** [comment]
Any ideas?

**Comment by popey456963** [comment]
@brianantonelli Those control codes are for colours.  This is something inquirer uses.  Vi doesn't support those control code colours, so displays the base codes.  Hence you're running into an issue.

**Comment by brianantonelli** [comment]
Can't those be disabled?

**Comment by popey456963** [comment]
@brianantonelli You can use something like [strip-ansi](https://www.npmjs.com/package/strip-ansi) to remove ansi from a string, I've opened an issue to be able to use it with streams https://github.com/jlord/sheetsee.js/issues/26.  However, it would probably be pretty simple to allow it to support streams yourself.

**Comment by SBoudrias** [comment]
Simpler yet, I believe chalk doesn't print colors when `--no-color` is in the process argv.

**Comment by bkry7581** [comment]
Support ny trade

**Comment by CasanovaDoo** [comment]
Doodee
