### ISSUE TITLE
Request: message optional

### ISSUE THREAD

**Issue by PierBover** [SBoudrias/Inquirer.js#521]
I'd like to be able to style my questions with chalk on any number of lines.

For this I'd like `message` to be optional.

Would you accept a PR for that?

**Comment by SBoudrias** [comment]
Could you explain in more details what you have in mind? And what you're trying to do

**Comment by PierBover** [comment]
I'd like to style the question in any way I wish. For example without the `>` as first character, having multiple lines, multiple text styles, etc.

I understand this is out of scope for this package, so a simple solution would be to be able to omit the `message` an simply present the options to the user.

**Comment by SBoudrias** [comment]
Well the message property can be anything. It can be multi-line and contains color. The only missing part is the question prefix who's hard-coded.

There's been a few discussion about the best way to change that. Search the issue tracker. I'm happy to merge a PR fixing this issue properly

**Comment by PierBover** [comment]
But the message property is always styled as bold, no?

I'll check what can be done about the prefix.

**Comment by patrick-motard** [comment]
@PierBover You can style text using chalk and you can do multiple lines using the new line character. Here's an example where i do both using chalk and string interpolation.

```
var inquirer = require('inquirer'),
    chalk = require('chalk');
var questions = [
    {
        name: "name",
        type: "input",
        message: `${chalk.red("what's your name?")}\n${chalk.blue("i'm a chicken")}`
    },
    {
        name: "phone",
        type: "input",
        message: "what's your phone?",
        when: answers => {
            return answers.name;
        }
    }
];

var prompt = inquirer.prompt(questions);

```

**Comment by PierBover** [comment]
Thanks @patrick-motard for the suggestion.

I'm guessing this should be closed then.
