### ISSUE TITLE
Retrieve Value From User

### ISSUE THREAD

**Issue by dhaniboy09** [SBoudrias/Inquirer.js#523]
`var question1 = {
    type: "input",
    message: "Enter Name: ",
    name: "my_name"
}

 inquirer.prompt([question1]).then(function (answers) {
    console.log(answers);
});
`
With the code above. Say i enter the value "James" as input in the CLI prompt. How can i access the value "James" for re-use. I've tried things like answers.name , answers.name.value but i get undefined. How do i get the actual value?
Thanks.

**Comment by mokkabonna** [comment]
In the example above you will get the value with answers.my_name

**Comment by dhaniboy09** [comment]
It return undefined. It says my_name is not defined.

**Comment by SBoudrias** [comment]
Which terminal are you using?

**Comment by SBoudrias** [comment]
I'll close as inactive.
