### ISSUE TITLE
If no value provided, Default value will not pass validation

### ISSUE THREAD

**Issue by alexandervalencia** [SBoudrias/Inquirer.js#525]
I'm prompting the user to input a year in YYYY format. If the user inputs four digits everything works as expected. If the user inputs anything else it works as expected, it returns them to the prompt and tells them, "Please return a valid year (YYYY)." However, if the user simply presses ENTER to accept the default value of 2017 a TypeError returns: `>> TypeError: value.match is not a function`

Here is the code snippet of what I'm calling:
````
{
  default: 2017,
  message: 'What year was the issue open during? (YYYY) Default:',
  name: 'issueDate',
  type: 'input',
  validate: function(value) {
    var pass = value.match(/^(\d{4})$/);

    if (pass) {
      return true;
    }

    return 'Please enter a valid year (YYYY).'
  },
  when: function(answers) {
    return answers.searchByDate === true;
  }
}
````

**Comment by SBoudrias** [comment]
If no value is entered, then you receive a `null` or `undefined` value. So you need to handle that type properly. FWIW, we do not only send string as values - like in the case of list and checkboxes inputs. So passing null if no value is provided doesn't break types expectations.

IMO this seems to be working as expected. I'll close the issue.
