### ISSUE TITLE
Inquirer usage inside a custom REPL

### ISSUE THREAD

**Issue by maheshj567** [SBoudrias/Inquirer.js#529]
Hello Simon,

Loving this module. I've been trying to incorporate it into a custom REPL that I'm building for my application. Here's the code...

    const repl = require('repl');
    const inquirer = require('inquirer');

    let isInquiring = false;

    repl.start({
        prompt: '> ',
        eval: myEval
    });

    function myEval(cmd, context, fileName, callback) {
        var commands = ["login"];
        if (isInquiring) {
            return callback();
        }

        if (commands.indexOf(cmd.trim()) == -1) {
            return callback(chalk.red("Unknown command"));
        }

        isInquiring = true;
        getLoginCreds(function () {
            callback(undefined, arguments);
            isInquiring = false;
        });
    }

    function getLoginCreds(callback) {
        var questions = [
        {
            name: 'email',
            type: 'input',
            message: 'Enter your e-mail address:',
            validate: function (value) {
                if (value.length) {
                    return true;
                } else {
                    return 'Please enter your e-mail address';
                }
            }
        },
        {
            name: 'password',
            type: 'password',
            message: 'Enter a new password for your account:',
            validate: function (value) {
                if (value.length) {
                    return true;
                } else {
                    return 'Please enter a new password for your account';
                }
            }
        }];

        inquirer.prompt(questions).then(callback);
    }

The problem is that when I'm invoking the prompt inside the REPL, the asked question and answer is printed after I enter the answer. The output of the above code is shown below...

    > login
    ? Enter your e-mail address: abc@xyz.com
    ? Enter your e-mail address: abc@xyz.com // printed after I entered the email address and hit ENTER
    ? Enter a new password for your account: ******
    ? Enter a new password for your account: ****** // printed after I entered the password and hit ENTER
    { '0': { email: 'abc@xyz.com', password: 'mahesh' } }

I don't see this behaviour in a normal setup. Any way that this can avoided?

Thank you,
Mahesh.

**Comment by SBoudrias** [comment]
Any chance the repl code handle the enter keys when it's used to confirm an inquirer answer?

**Comment by maheshj567** [comment]
Yes, that worked. Thanks Simon. I added the line `process.stdout.write(ansiEscapes.eraseLines(2));` in the `isInquiring` check and it removed the line I used to input the data.

It would be great if the library could do this instead the developer handling it, because it is able to do it outside REPL.

**Comment by SBoudrias** [comment]
The library does do it. It just seems like the code you wrote or the modules you used are injecting an extra line break. Inquirer can't know or control that.

**Comment by maheshj567** [comment]
Ok. As written in the code, I'm using just the two modules - `repl` and `inquirer`. I also have checks to make sure I'm not handling anything extra or printing anything else to the console. So I thought Inquirer's implementation missed this.

To me, it seems like the `repl` module is adding the extra line break. I tried to understand the code to see if I can tweak it to handle this case, but haven't spent enough time on it yet.
