### ISSUE TITLE
When using async validate function, user can continue typing, submit new values

### ISSUE THREAD

**Issue by kevinschaul** [SBoudrias/Inquirer.js#538]
When a prompt has a asynchronous validate function, the user can submit a value, delete/type a new value, submit that value, etc. for the same prompt. The validate function can be called multiple times before it resolves whether the initial value was valid or not.

I think Inquirer could be improved by waiting until the validate function resolves before considering further input. Furthermore, if there were a way to show visually that a validate function were processing the input, that could help the UX of the prompt.

**This code ...**

```js
var inquirer = require('inquirer');
var ui = new inquirer.ui.BottomBar();

inquirer.prompt(
  [{
    type: 'input',
    name: 'name',
    message: 'What is your name?',
    validate: function(input) {
      return new Promise(function(resolve, reject) {
        ui.log.write('\nvalidating name: ' + input + '\n');
        setTimeout(function() {
          resolve(true);
        }, 5000);
      });
    }
  }]
).then(function(answers) {
  ui.log.write('Name: ' + answers.name);
});
```

**... can produce this output**

```
? What is your name? Kevin

validating name: Kevin

validating name: Sally

validating name: George
? What is your name? Kevin
Name: Kevin
```

I can start working on a PR but please let me know if anyone has feedback.

**Comment by SBoudrias** [comment]
Yeah that's a bug, PR is welcomed :)

**Comment by kbrandwijk** [comment]
@kevinschaul Regarding the visual indication, I have just created #631 and #632 for this.

**Comment by ujenjt** [comment]
Thanks for this PR, I really need this bugfix. How can I help to get a pull request merged?

**Comment by SBoudrias** [comment]
@ujenjt we'd need test and documentation. (You can build on top of the opened PR by cloning PR itself) Or collaborate with the initial author if he still has some time to get this PR moving to a mergeable state :)

Thanks for offering help!

**Comment by kbrandwijk** [comment]
@SBoudrias I would have liked that feedback on the PR right away. Right now, I'm very limited in time, so I can't add to it...

**Comment by SBoudrias** [comment]
@kbrandwijk sorry, I didn't reply as I saw you left a list of todos.
