### ISSUE TITLE
Integrating Inquirer.js with a web app?

### ISSUE THREAD

**Issue by mmikitka** [SBoudrias/Inquirer.js#543]
Hello - Is it possible to integrate Inquirer.js with a web app? If so, can you please guide me to the relevant documentation? If not, would you consider adding this to the roadmap?

I am not looking for a terminal-like interface in a browser, rather I'm looking for the core of Inquirer.js (types of inquiries, validation, etc.) and pluggable outputting functions, so that my app can be used in a terminal environment and a web app environment with minimal code.

**Comment by SBoudrias** [comment]
That's not something I've ever tried. Maybe you could register custom prompt types?

**Comment by mmikitka** [comment]
Do you know of a library, not including a tightly-coupled MVC,etc. framework, that provides Web UI prompts? In the meantime, I'll play around with Inquirer.js, trying to separate the presentation layer (console, web UI) from the data-processing layer.

**Comment by SBoudrias** [comment]
I don't know of any sorry.

I'll close this issue as that's not something I consider in the scope of Inquirer.

**Comment by Kreijstal** [comment]
https://dev.to/shalvah/i-was-bored-so-i-made-my-website-into-a-node-package-heres-how-2id3
I found this article, @mmikitka this might help you

**Comment by MarketingPip** [comment]
@SBoudrias I know this is old! But if you are interested in possibly implementing this "in the browser".

Can I suggest you take a look at this library? [Termino.js](https://github.com/MarketingPipeline/Termino.js). 

I would be more than happy to work together on adding support needed to make things work with your library! And assume the open-source community would be more than happy to pull it together!

ps; @mmikitka - if you are still looking for a command parser in web UI! (not connected to a SSH instance etc / but you could easily do this too) check it out!
