### ISSUE TITLE
inputs repeating question when input wraps and install way is npm install

### ISSUE THREAD

**Issue by allenGKC** [SBoudrias/Inquirer.js#552]
The problem is happen when I npm install inquirer, can anyone help me to solve it?
check the issue [https://github.com/SBoudrias/Inquirer.js/issues/214](https://github.com/SBoudrias/Inquirer.js/issues/214)

**Comment by SBoudrias** [comment]
Can you give context on your OS, terminal, node version? etc etc

We can't help you if you don't provide debugging information

**Comment by allenGKC** [comment]
![image](https://user-images.githubusercontent.com/6214258/27065218-845fa5aa-502e-11e7-9060-cc3241314512.png)
![image](https://user-images.githubusercontent.com/6214258/27065229-939a7108-502e-11e7-87a7-4a8420c5baf1.png)
environment：macOS，and ITerm2

**Comment by allenGKC** [comment]
I install the Inquirer.js with npm install Inquirer

**Comment by allenGKC** [comment]
I have solve the problem because i use readline module, I remove it and become nomal, I guess it is the module's problem. 
@SBoudrias  thank buddy any way
