### ISSUE TITLE
Questions with type: 'list' don't work with Git Bash

### ISSUE THREAD

**Issue by dafo** [SBoudrias/Inquirer.js#557]
**Steps to reproduce:** 
1.
```
var inquirer = require('inquirer');

var questions = [
    {
    type: 'list',
    name: 'destinations',
    message: 'Select destination!',
    choices: [ "London", new inquirer.Separator(), "New York", new inquirer.Separator(), "Madrid" ],
    default: 'London'
  }
];
```
2. Open with Git Bash

**Actual result**: 
Navigating with the keyboard arrow keys is not changing the selection but is moving the cursor through the console. Selecting a destination is not possible. 

**Expected result:** 
Navigating through the list of available answers should be possible.

**Comment by SBoudrias** [comment]
Sorry about that, git bash isn't a TTY terminal and as such cannot support the interactive features.

I'd recommend using a proper command line tool.

**Comment by dafo** [comment]
Thank you for your response.
