### ISSUE TITLE
Prompt Text Color Matches Terminal Background

### ISSUE THREAD

**Issue by joshvickerson** [SBoudrias/Inquirer.js#560]
In my terminal profile (a slightly modified version of macOS's "Pro" theme), Inquirer seems unable to detect the correct text color to use for prompts, resulting in unreadable text (e.g. black text on a black background). 

I experienced this issue initially in using [Sonar](https://github.com/sonarwhal/sonar), where I reported this issue [here](https://github.com/sonarwhal/sonar/issues/302). At their suggestion, I'm opening an issue here hoping this can be resolved.

At least one Sonar contributor was able to reproduce the issue, but it seemed to depend on when the window was active, what color the window under the active terminal is, and some other factors. I'm unsure which setting in my terminal profile is making it difficult to detect which text color to use.

I've attached my current terminal profile that I hope will be of some use.

[Pro (Modified).zip](https://github.com/SBoudrias/Inquirer.js/files/1109019/Pro.Modified.zip)

**Comment by revelt** [comment]
Hi Josh!
I tested your theme on my Terminal and if not my previously left transparency setting, it would have been black on black.

![screen shot 2018-01-07 at 17 45 25](https://user-images.githubusercontent.com/8344688/34652179-acff2d94-f3d2-11e7-8145-74e564d5750d.png)

However, it doesn't look like it's Inquirer's problem but rather terminal theme issue. May I kindly suggest exploring different themes on [Hyper](https://hyper.is/) or [iTerm2](https://www.iterm2.com/).

My concern is that while we _might_ explore solutions for this, the community would probably benefit more if we worked on Inquirer's own features and bugs, the ones within its code scope.

If you can, please try out different themes and report back how it went.

**Comment by joshvickerson** [comment]
@revelt Thanks for the thoughtful response! I definitely understand that this is a matter of priority - just thought I'd bring it to someone's attention to see if this was worth resolving.

Just to clarify your comment:
> if not my previously left transparency setting, it would have been black on black.

Does this mean that it's the transparency setting that's causing the color to be black on black? i.e. my theme has reduced opacity (65%), and I'm guessing your opacity was still at 100% (or something closer to it)?

Since filing this bug I've changed jobs (and thus, work computers) and don't currently have Sonar / anything I know to use Inquirer installed so I can't readily test this at the moment. If you are going to prioritize other more relevant issues over this I'm happy to edit my terminal theme should I run into this issue in the future - just want to make sure I know what to edit.

Again, thanks for the response!

**Comment by revelt** [comment]
Hi Josh, 

No it's not transparency setting causing problem. Anyway, to me it looks like it's terminal theme issue, it's got nothing to do with Inquirer.

Let's close this issue, what do you say?

**Comment by joshvickerson** [comment]
Sure thing. Thanks for taking a look!
