### ISSUE TITLE
Git Bash support on Windows

### ISSUE THREAD

**Issue by ccorcos** [SBoudrias/Inquirer.js#570]
I use Git Bash on Windows as a Bash emulator. It would be nice if there was better support for Inquirer. :)

**Comment by SBoudrias** [comment]
The issue isn't that I don't want to support it. The issue is that git bash is not an interactive/TTY terminal. So it just cannot work :(

I though windows shipped with bash built in now?

**Comment by ccorcos** [comment]
Did it? How can I open it?

**Comment by SBoudrias** [comment]
Maybe this can help? https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by ccorcos** [comment]
Amazing! Thanks!

**Comment by mustafaskyer** [comment]
any updates !!,
not working with git bash in windows 10 64bit

i had a list of options,
the issue is, can't move between options,
and can't show which option i am on to select,
any help would be appreciated,
regards

**Comment by coder-mike** [comment]
Is there a way to detect whether the terminal is interactive so we can fail gracefully?
