### ISSUE TITLE
Feature request: automatically choose an option after X seconds

### ISSUE THREAD

**Issue by StevePotter** [SBoudrias/Inquirer.js#572]
Feature request here:
I have a few circumstances where a CLI command is started by a dev then they go onto something else.  Typically they enter the default answers so I'd like the ability for it to automatically choose a default after a few seconds of inactivity.   This would require a few things:
1) a timeout property, ideally in seconds
2) a countdown timer shown in the prompt's title
3) timer reset after the user presses up or down

I could approach the problem a different way, like not prompting them and providing a command to change the defaults.  But I think this could be a useful feature and have seen it in various places in my practice.  Anyway, thanks for the great library.

**Comment by SBoudrias** [comment]
See recipe for this https://github.com/SBoudrias/Inquirer.js#get-default-value-after-timeout
