### ISSUE TITLE
Question as a function

### ISSUE THREAD

**Issue by LestaD** [SBoudrias/Inquirer.js#576]
I want to modify question bases on a previous answers:

```js
inquirer.prompt([
  { type: 'input', name: 'name', message: 'Enter name of a component:' },
  (answers) => ({
	type: 'confirm',
    name: 'accept',
    message: `You should accept license to create component ${answers.name}:`,
  }),
  (answers) => ({
  	type: 'list',
    name: 'anotherName',
    answers: getAvailableList().filter(name => name !== answers.name),
    message: `Select another name for ${answers.name}`,
  }),
  {
  	type: 'list',
    name: 'type',
    message: 'Select type of your component',
    answers: ['atom', 'molecule', 'organism'],
  },
  (answers) => ({
  	type: 'input',
    name: 'path',
    message: 'Enter path for your component:',
    default: `src/ui/${answers.type}/${answers.name}.js`,
  }),
])
```

What about add that API with Promise support?

**Comment by SBoudrias** [comment]
You can already do that with pure JS by nesting your calls or chaining promises. There's an example here: https://github.com/SBoudrias/Inquirer.js/blob/master/examples/hierarchical.js and https://github.com/SBoudrias/Inquirer.js/blob/master/examples/nested-call.js and https://github.com/SBoudrias/Inquirer.js/blob/master/examples/recursive.js

As I don't think adding an extra API would make the use case clearer or make Inquirer easier to use; I'll close this issue. Let us know if you need further help.
