### ISSUE TITLE
'list' accepts a value default, 'expand' only accepts a numeric default

### ISSUE THREAD

**Issue by sbj42** [SBoudrias/Inquirer.js#581]
The `README.md` says that for both `list ` and `expand`:

> default must be the choice index in the array

But in `list.js:40`, if the default is not a number and not null then it looks through the `value`s of the options to find a match.   `expand` does not do that, so there is some inconsistency between the two.  I did not check other prompt types but according to the README `checkbox` and `confirm` expect the default to match a value.

Even thought `list`'s behavior differs from the README spec, I prefer it.  Setting the default by value instead of by index is more convenient in my opinion.  I would prefer that the by-value behavior be implemented by all prompt types.

To see this in action, edit `examples/list.js` to add:
```
  default: 'Make a reservation',
```
And edit `examples/expand.js` to add:
```
  default: 'diff',
```

**Comment by Froren** [comment]
Created [PR 609](https://github.com/SBoudrias/Inquirer.js/pull/609) to experiment with this functionality.

**Comment by kbrandwijk** [comment]
Seems fixed as of 4.0.0
