### ISSUE TITLE
Second prompt does not respond to keypresses

### ISSUE THREAD

**Issue by sbj42** [SBoudrias/Inquirer.js#582]
In my tests, a second call to `prompt()` doesn't work very well: it displays the first question, but does not accept any input and locks up the application.  Here are steps to reproduce the problem:

OS: Windows 10
Node: 8.1.0
Inquirer: 3.2.2
Terminal: Powershell, cmd.exe, and Powershell terminal in Visual Studio Code

```js
inquirer.prompt([{
  type: 'confirm',
  name: 'a',
  message: 'A?'
}]).then(function() {
  return inquirer.prompt([{
    type: 'confirm',
    name: 'b',
    message: `B?`,
  }]);
}).then(function() {
  console.log('done');
});
```

That program accepts the answer to `'A?'`, and then displays the question:
~~~
? B? (Y/n)
~~~
but no keypress is registered after that.

**Comment by SBoudrias** [comment]
Can you try on latest node? https://nodejs.org/en/

There was some bugs in the earlier 8.x release breaking the readline module.

**Comment by sbj42** [comment]
Looks like that was it.  I upgraded to node 8.4.0 and the issue is resolved.  Thanks!
