### ISSUE TITLE
List Selected Highlight not changing on arrow key press

### ISSUE THREAD

**Issue by dsc03** [SBoudrias/Inquirer.js#586]
I'm having an issue with running Inquirer in the Mac terminal where when using the 'list' type, the highlighted selection arrow/font style will not move up and down with arrow key presses.

![screen shot 2017-09-14 at 3 17 07 pm](https://user-images.githubusercontent.com/25214199/30458376-190e571c-9960-11e7-9864-da8526c6dc3a.png)

In this screenshot, I have pressed the down arrow key twice, and thus the selection choice is actually on 'other', but that selection is not being displayed properly in the UI.

**Comment by SBoudrias** [comment]
Which node version? Did you try updating it?

**Comment by dsc03** [comment]
I'm currently on v6.10.3. Will try updating now.

**Comment by dsc03** [comment]
I just saw that the recommended version for node is v6.11...not sure if you still think i should try updating.

**Comment by SBoudrias** [comment]
Yes, try updating to the latest node v6.x

**Comment by dsc03** [comment]
Experiencing the same issues on v6.11...additionally had a friend try on v8.4 and didn't work.

**Comment by SBoudrias** [comment]
Can you post your code?

**Comment by dsc03** [comment]
`/** VERIFY INITIAL COMMAND PROMPT QUESTION INFO **/

var inquirer = require('inquirer');
var prompt = inquirer.createPromptModule();

let commandPromptQuestions = {
  type: 'list',
  name: 'command',
  message: 'What operation do you want to perform next?',
  choices: ['this', 'that', 'other', 'next']
};

/** TAKE IN USER INPUTTED COMMAND AND PASS THROUGH SWITCH STATEMENT **/
let commandPrompt = () => {
  prompt(commandPromptQuestions)
    .then(answers => {
      commandRunner(answers.command);
    })

    .catch(error => {
      console.log('There was an error with this command! Try again');
      commandPrompt();
    })
};`

**Comment by dsc03** [comment]
hey! Wanted to see if you had any updates on this issue?? Let me know.

**Comment by SBoudrias** [comment]
Looking at the code yes, but it's not a complete example. So there could be other modules touching the TTY that are conflicting with inquirer.

It'll be hard to really help without a full example I can run and reproduce.

**Comment by dsc03** [comment]
I was testing it out as a tool so I actually just have a basic server set up with that command you have above (commandRunner was just console logging). I will create a repo for it, push it up and send you the link so you could see everything.

**Comment by dsc03** [comment]
https://github.com/dsc03/clitool

**Comment by dsc03** [comment]
^^ that was the playground i was testing this inquire with and getting issues...the only additional module I'm using in this case is express.

**Comment by saikatharryc** [comment]
this is because of terminal plugins like i use `zsh` it doesn't works here, but when i shifted to bash it works fine

**Comment by nelsonomuto** [comment]
same issue and I'm on node v10.9.0

**Comment by MichaelWilkens** [comment]
I solved this problem by removing a node_modules directory that was accidentally installed in my root directory. Look that you don't have inquirer installed in a higher directory, as it seems they clash somehow.

**Comment by jedmao** [comment]
I was having the same issue on Windows 10, Node 11, but I just upgrade to Node 12.2.0 / npm 6.9.0 and the problem went away. Hope this helps someone!

**Comment by knaut** [comment]
Running nodemon in the npm start script caused this issue for me.
I had this:
`
"scripts": {
    "start": "nodemon --exec babel-node index.js"
  }
`
Changed it to this. Now my keypresses work as expected:
`
"scripts": {
    "start": "babel-node index.js"
  }
`

**Comment by gpoitch** [comment]
This recently started happening to me.  It works initially but after about 3 seconds you get the key code output instead of the list selection moving.

Inquirer: 7.0.0
node: 12.9.1
OS: macOS 10.14.6 - stock bash terminal

**Comment by AgkTF** [comment]
> Running nodemon in the npm start script caused this issue for me.
> I had this:
> `"scripts": { "start": "nodemon --exec babel-node index.js" }`
> Changed it to this. Now my keypresses work as expected:
> `"scripts": { "start": "babel-node index.js" }`

Same issue here, nodemon was the culprit as soon as I changed it to 
> `"scripts": { "start": "node index.js" }`
it worked as expected.

**Comment by kuakman** [comment]
@AgkTF @knaut Try the ```-I``` option from nodemon:

```-I, --no-stdin ........... nodemon passes stdin directly to child process```

```"scripts": { "start": "nodemon -I --exec babel-node index.js" }```

That is working for me.

**Comment by sorengrey** [comment]
> > Running nodemon in the npm start script caused this issue for me.
> > I had this:
> > `"scripts": { "start": "nodemon --exec babel-node index.js" }`
> > Changed it to this. Now my keypresses work as expected:
> > `"scripts": { "start": "babel-node index.js" }`
> 
> Same issue here, nodemon was the culprit as soon as I changed it to
> 
> > `"scripts": { "start": "node index.js" }`
> 
> it worked as expected.

This fixed it for me, too! Nodemon doesn't like it.

**Comment by shiva2021** [comment]
> @AgkTF @knaut Try the `-I` option from nodemon:
> 
> `-I, --no-stdin ........... nodemon passes stdin directly to child process`
> 
> `"scripts": { "start": "nodemon -I --exec babel-node index.js" }`
> 
> That is working for me.

Awesome.. worked like charm

**Comment by metellusa** [comment]
Nodemon seems to have been the culprit for me. Once I removed nodemon, it worked!

I had this before:
`"scripts": {
         "start": "nodemon --watch 'src/**/*.ts' --exec \"npx ts-node\" index.ts"
   }`

Changed to this and it worked:
`"scripts": {
        "start": "ts-node index.ts"
    }`
