### ISSUE TITLE
type: 'editor' in vim with empty input crashes inquirer

### ISSUE THREAD

**Issue by mhchen** [SBoudrias/Inquirer.js#587]
First off, thank you for this terrific library. I've written many tools that have made my life easier using it.

I'm having trouble with the type: 'editor' option and vim. When I enter the editor and :wq without entering any input, my script stops abruptly and exits to the command line.

```
const inquirer = require('inquirer');

inquirer.prompt([{
  name: 'test',
  type: 'editor',
  message: 'Enter test input'
}]).then((answers) => {
  console.log(answers);
});
```

I'd expect to have the test input be an empty string, but instead it looks like the script throws a `ExternalEditor.ReadFileError` here: https://github.com/SBoudrias/Inquirer.js/blob/master/lib/prompts/editor.js#L92

So it seems like vim doesn't write the temporary file if you don't enter any text, which means we get this ReadFileError.

Any thoughts on how to solve would be appreciated! If you have an idea of how you might want to handle this and would welcome a PR, I'd also be happy to try and make a code contribution. Thanks!

**Comment by SBoudrias** [comment]
cc @mrkmg looks like something you could fix upstream no?

**Comment by mrkmg** [comment]
@SBoudrias Checking this out now

**Comment by mrkmg** [comment]
@mhchen Could you do me a favor. While vim is open, can you check to see if the temporary file it is trying to edit exists on the filesystem?

ExternalEditor should create the file itself. So if vim does not write to the file, it should still exist.

**Comment by mhchen** [comment]
Thanks @SBoudrias and @mrkmg for the quick replies!

@mrkmg I did some investigation and ended up opening a PR here: https://github.com/mrkmg/node-external-editor/pull/10

What seems to be happening is that https://github.com/mrkmg/node-external-editor/blob/develop/src/index.coffee#L91 has an encoding of `null` when the buffer is empty, which causes `IConvLite` to crap out, throwing a `ReadFileError`. I did check your suggestion: vim does in fact create the temp file, but because it doesn't insert a newline, the buffer will be empty, which doesn't seem to happen at least with nano. Btw this is all on Mac OS X.

Didn't see a Contributing.md so I hope the PR format is good, but the fix seems easy enough to replicate if you want to incorporate my changes. Thanks!

**Comment by mrkmg** [comment]
I have accepted @mhchen pull request and published the new version.

Thanks @mhchen!

**Comment by SBoudrias** [comment]
You guys are awesome, thanks a lot!

**Comment by mhchen** [comment]
Everything's working well now. Thank you both for the quick response!
