### ISSUE TITLE
Input field along with options?

### ISSUE THREAD

**Issue by reznord** [SBoudrias/Inquirer.js#588]
Just want to get some thoughts on the following:

So right now, we can either get a value from the user by giving some options to the user or by providing an input field. Is there any way where we can combine both?

Something like: We can have a set of options and then to the end of that, we can provide an option like `Enter a value`, then we can prompt the user to enter a value.

**Comment by SBoudrias** [comment]
You can:

1. display a list
2. If user select "Custom value", then display an input field.

And you use the `when` option to skip the input field when the user selected a value.

**Comment by reznord** [comment]
Thanks for the explanation. It would be great if you can give me an example.

**Comment by raphaelokon** [comment]
An example would be great @SBoudrias
