### ISSUE TITLE
Create better unit test for testing nested prompts

### ISSUE THREAD

**Issue by SBoudrias** [SBoudrias/Inquirer.js#59]
`0.3.0` presented a regression in the nested prompts support (events where duplicated). It really needs a better unit test so this don't happens again.

**Comment by GeorgeGkas** [comment]
The current version of Inquirer (master branch) address nest calls (see https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/examples/nested-call.js). We should close this issue.
