### ISSUE TITLE
Feature request: Initial input values

### ISSUE THREAD

**Issue by renarsvilnis** [SBoudrias/Inquirer.js#590]
I'd like to make a feature request for the ability to have editable default values (maybe call it "initial value"?).

### Usage example
In the example gif below instead of copy-pasting the "default" value, that is auto-generated from the given link, I'd like the user to be able to edit the generated value easier.

![out](https://user-images.githubusercontent.com/3515099/30602468-4ef33896-9d6d-11e7-99fb-27ce3c3d1b7f.gif)

Maybe there is some hackish way of achieving it now? I tried mutably modifying the given Answers hash within the filter method of the first question, but no luck.

**Comment by renarsvilnis** [comment]
Any feedback?

If so, I'm interested in contributing the feature.

**Comment by czebe** [comment]
This would be useful. At the moment it's hard to get default value in the input prompt and edit/modify it (eg. rename  file.xxx to file2.xxx etc). To me it'd feel natural if I press TAB, the default value gets written in the input so I can edit it (I'm not sure if you can detect this in the console).

**Comment by SBoudrias** [comment]
@czebe yeah, any keypress can be detected.

I think using tab to put the default value in is a great idea actually. Would you be interested in preparing a PR?

**Comment by renarsvilnis** [comment]
@SBoudrias I'll give it a shot

**Comment by jonathancochran** [comment]
Any luck with this @renarsvilnis?

**Comment by renarsvilnis** [comment]
@jonathancochran No, I needed a quick fix, so I just added a prefix `+,` in my app, that when present prepends inputted tabs with the "initial values"

**Comment by hi2u** [comment]
This would be really useful.  My use case is entering dates in a CLI (paper documents) scanning interface.  

My default value is today's date, such as `2018-06-07` - but when I need to enter a different date, it's usually around the same time, so would be handy being able to just edit the default answer rather than having to fully type it out (or copy and paste).  

I know there's datepicker plugins, but text is a bit easier for me.

The file renaming example above is really good too.

The tab completion idea is nice, but as a basic start without much more work it would be handy just as an option we can specify.

**Comment by NoriSte** [comment]
I'm very interested in this feature, I'd like to use it in my [nprr](https://github.com/NoriSte/nprr) (a sort of *npm run + autocomplete*) package 😊

**Comment by TianyiShi2001** [comment]
the [`prompts`](https://www.npmjs.com/package/prompts) package already has [this feature](https://github.com/enquirer/enquirer#input-prompt)

**Comment by swordensen** [comment]
I ended up solving this a little bit differently. For situations where I want to be able to edit the default value of an `input` type question I push the default value to the inquirer read stream. 

This is my code:

 ```ts
 import inquirer from 'inquirer';

(async ()=>{
    const question = {
        type: 'input',
        name: 'answer',
        default: "idk, give it a try",
        message: "can you edit the default value?"
    }
    const prompt = inquirer.prompt([
        question
    ])

    const readStream = (prompt.ui as any).rl.input;
    readStream.push(question.default);
    const {answer} = await prompt;
    console.log({answer});
})()
```

note that it this only works if you are asking one question at a time.

**Comment by SBoudrias** [comment]
Hi all, the new [@inquirer/input](https://github.com/SBoudrias/Inquirer.js/tree/master/packages/input) allow editing the default value when pressing `tab`.

I'll close this ticket as we don't intend to backport features to the maintenance version. [See new release announcement](https://github.com/SBoudrias/Inquirer.js/discussions/1214)
