### ISSUE TITLE
Validation doesn't work on list

### ISSUE THREAD

**Issue by cotts** [SBoudrias/Inquirer.js#593]
I found some issues about the no sense about the validation inside list, but I have a example where I need to validate before continue the flow of my function.

```
const checkDir = path =>  (!fs.exists(path)) ? false : (fs.lstatSync(path).isDirectory()) ? true : false;

const choices = options =>

  inquirer.prompt([
    {
      type: 'list',
      name: 'repo',
      message: 'Select one repository to clone',
      choices: options,
    },
    {
      type: 'input',
      name: 'new_name',
    message: 'Do you wanna change the name? Default = no',
    validate : function(val) {
      const done = this.async();
      if(checkDir(val)){
        done('Choose another name: Already Exists ');
        return;
      }
      done(null, true);
    }
  }
  ])
```

I have a scenario where I choose one repository from github to clone, after that choice if I type some text later, it will change the cloning name, but If the directory already exsists I can't handle with that, because there is no validate inside list.

#383

**Comment by mokkabonna** [comment]
Couldn't you just get all directories in the folder and if directory exists for the selected repo name and default folder name, just require that new_name actually needs to be something? That you would do in the validate function of new_name.
