### ISSUE TITLE
When inquirer answers the first question, the latter question can not be answered, and the command line is stuck directly

### ISSUE THREAD

**Issue by RodeyManager** [SBoudrias/Inquirer.js#603]
When inquirer answers the first question, the latter question can not be answered, and the command line is stuck directly。
![qq 20171024155849](https://user-images.githubusercontent.com/1145316/31931013-58140838-b8d4-11e7-8da2-ba83d722b74d.png)

**Comment by RodeyManager** [comment]
By the time `Project Description` is not entered, the command line is jammed

**Comment by SBoudrias** [comment]
Did you try with latest node?

**Comment by RodeyManager** [comment]
I current use node version 8.1.0
![qq 20171024165627](https://user-images.githubusercontent.com/1145316/31933671-54044552-b8dc-11e7-824f-fdda51ccd3af.png)

**Comment by SBoudrias** [comment]
Okay, I'd suggest trying with latest. Node had a lot of issues around their Readline module a few months ago. And I can't really fix inquirer when the core has major bugs.

**Comment by RodeyManager** [comment]
OK, I'll try

**Comment by revelt** [comment]
@RodeyManager how did it go, did you solve this since?

**Comment by SBoudrias** [comment]
I'll close this issue and will reopen if need be. But this was a known issue with old Node.js versions.

**Comment by MLoughry** [comment]
@SBoudrias, I and some on my team are running into this issue on Node v11.1.0.

**Comment by MLoughry** [comment]
Ah, nevermind, false alarm. Seems we had an older version of inquirer, and this doesn't repro with latest (6.2.0)
