### ISSUE TITLE
how to interrupt when i answer the first confirm question

### ISSUE THREAD

**Issue by alankell** [SBoudrias/Inquirer.js#604]
```javascript
inquirer.prompt([{
      type: 'confirm',
      message: 'can i close directly'
      name: 'cm'
    }, {
      type: 'input',
      message: 'please input MSG?',
      default: 'auto by xbox',
      name: 'msg'
    }]).then(function (answers) {
      ...
    })
```

when i answer the first question as yes, i want to interrupt program directly, how to do?

**Comment by SBoudrias** [comment]
You can split your prompts in 2 functions. Then only call the second function if the first answer is "no".

This is just JavaScript code, no special feature on Inquirer to do this.

Note, you could also use the `when` option if it's more convenient for you.
