### ISSUE TITLE
type: 'password' being shown

### ISSUE THREAD

**Issue by sathomps** [SBoudrias/Inquirer.js#605]
Running this in a DOS prompt with latest version of inquirer

```
npm 5.4.2
node 8.8.1

{
        type: 'password',
        message: 'User Password:',
        name: 'creds_pwd',
        validate: function (answer) {
            if (!answer) {
                return 'User Password required!';
            }
            return true;
        }
}
``` 
Output is the following

`User Password: [input is hidden] aassffaaddssffaassdd`

While each char is duplicated on the screen, it's stored/passed correctly.

**Comment by sathomps** [comment]
Appears this is a documentation issue.  The password type needs to be supplied a mask option.  It would be nice if it defaulted to one if the user didn't supply it.

**Comment by SBoudrias** [comment]
Oh yeah, that is a weird behavior. Do you want to send a PR? I think it'd be simple to fix :)

**Comment by sathomps** [comment]
Sure I'll create one this weekend.

**Comment by sathomps** [comment]
Guess that weekend was a long one :)

Pull request here #751
