### ISSUE TITLE
inquirer.prompt(...).then is not a function

### ISSUE THREAD

**Issue by ksmithut** [SBoudrias/Inquirer.js#606]
With the following example, I get an error saying that the value returned from `.prompt()` is not a function.

<details>
<summary>Example:</summary>

Input:

```js
'use strict'

const inquirer = require('inquirer')

inquirer
  .prompt([
    {
      type: 'confirm',
      name: 'confirm',
      message: 'confirm?'
    }
  ])
  .then(console.log)
```
</details>
<details>
<summary>Error:</summary>

```
TypeError: inquirer.prompt(...).then is not a function
    at Object.<anonymous> ({redacted}/index.js:11:4)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
</details>

Am I completely off my rocker in missing something super obvious?

**Comment by ksmithut** [comment]
Nevermind, I hadn't actually installed inquirer in the project, must have been using some older version from another dependency

**Comment by unofficialdxnny** [comment]
I get same problem however i have installed it properly any help will be agreatly appreciated

**Comment by wrenjohnson** [comment]
> I get same problem however i have installed it properly any help will be agreatly appreciated

did you ever find a solution to this problem?

**Comment by SBoudrias** [comment]
@wrenjohnson any more details you can provide for us to help? Can you provide reproduction steps? Or a repo with minimal reproduction?

**Comment by wrenjohnson** [comment]
i have installed everything correctly and it still give me an error im not sure what to do.  heres the repo 
https://github.com/wrenjohnson/readme-generator

**Comment by ksmithut** [comment]
@wrenjohnson It looks like you're probably getting an error that looks like this:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module [...]/node_modules/inquirer/lib/inquirer.js from [...]/index.js not supported.
Instead change the require of inquirer.js in [...]/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/ksmithut/Code/github.com/wrenjohnson/readme-generator/index.js:2:18) {
  code: 'ERR_REQUIRE_ESM'
}
```

In order to use inquirer, you need to switch your project to ESM (by setting the "type" property in your package.json to "module" and changing your `require` statements to `import` statements) or you need to use the dynamic import module (in your code changing it to use `import('inquirer').then((inquirer) => inquirer.prompt(questions)).then((responses) => {`. Here's some documentation on how to use ESM in your project: https://nodejs.org/dist/latest-v20.x/docs/api/esm.html

**Comment by SBoudrias** [comment]
You can also:

1. Use Inquirer v8 which is still CJS compatible (latest v9 is not)
2. Use the new packages who are CJS compatible too (See #1214)

**Comment by wrenjohnson** [comment]
> You can also:
> 
> 1. Use Inquirer v8 which is still CJS compatible (latest v9 is not)
> 2. Use the new packages who are CJS compatible too (See [Say Allo' to the new Inquirer (release of the rewrite) #1214](https://github.com/SBoudrias/Inquirer.js/discussions/1214))

this fixed the issue thank you so much!

**Comment by Tanujch03** [comment]
use this `import inquirer from "inquirer";` instead of `const inquirer = require('inquirer');`
