### ISSUE TITLE
Long inputs wrap weirdly in interactive node session

### ISSUE THREAD

**Issue by willclarktech** [SBoudrias/Inquirer.js#611]
Seems related to https://github.com/SBoudrias/Inquirer.js/issues/214

![inquirer_wrap_issue](https://user-images.githubusercontent.com/11036220/32943962-29a4fb70-cb8e-11e7-8445-d394f3b23f20.gif)

If I run [this script](https://raw.githubusercontent.com/SBoudrias/Inquirer.js/master/examples/pizza.js) non-interactively with `node pizza.js`, requiring from my npm-installed Inquirer (`var inquirer = require('inquirer')`), everything is fine.

- OSX 10.12.6
- Node 8.9.0
- iTerm 3.1.5 (but I also tried with Mac Terminal)
- zsh 5.2 (but I also tried starting from bash)
- Inquirer 4.0.0 installed via `npm install inquirer`

**Comment by SBoudrias** [comment]
@willclarktech I don't think this can ever work in the node interactive prompt as each line returns is also handled by the node interactive process.

**Comment by SBoudrias** [comment]
Never followed up, but long lines of answers (and choices in list) have been fixed for a while.
