### ISSUE TITLE
Any way to handle async default value

### ISSUE THREAD

**Issue by clemtrek** [SBoudrias/Inquirer.js#615]
I am using the package `git-username` to determine the user's Github username from his/her email address.

While I am able to do so, this process takes some time and while the username loads, I can press the `enter` key on the command line and it keeps moving to the next line.

Is there any way I can stop this ___enter___ thing.

```js
{
			name: 'github-user',
			message: 'Github Username',
			default: async() => {
				const username = await githubUsername(email);
				return username;
			}
		}
```

**Comment by SBoudrias** [comment]
Is it purely visual?

**Comment by clemtrek** [comment]
Yes, when I type anything it is visible on the console

**Comment by clemtrek** [comment]
Figured It myself. Thank you.

Took Help from the ___generator-node___ project
