### ISSUE TITLE
Inquirer does not honor cursor position

### ISSUE THREAD

**Issue by TimoStaudinger** [SBoudrias/Inquirer.js#617]
When I **set the cursor position manually**, e.g. via `readline.cursorTo(process.stdout, 0, 5)`, an inquirer prompt initially renders correctly. However, when the user moves through options, the **prompt is re-rendered several lines higher** along the Y axis compared to the cursor position. This is the case in both PowerShell and Windows Command Prompt.

---

My use case is the following: I am rendering a table with fixed height that is refreshed in a 500ms interval to respond to new data. Below this table, I would like to render an inquirer prompt to offer menu options to the user, e.g. to quit the application.

My current solution is to re-render the table on a specific `setInterval`, where I move the cursor to the top of the table, clear `n` lines, `n` being the table height, rendering the new table at the previous table's top, and moving the cursor back below the table where the inquirer prompt should be rendered.

This however results in the issue described above, whenever the user moves between options with the arrow keys, the prompt is re-rendered a few lines too high, overwriting the bottom of my table.

---

**My questions are:**
1. Can this be considered a bug, or is this expected behavior?
2. Is this a case that has been solved before, and if so how? Any suggestions on how to cover this use case differently?

---

This is an **MVCE** of the issue, executed in PowerShell with node 8.9.1 and inquirer 4.0.0:

```
const setInterval = require('timers').setInterval
const readline = require('readline')
const inquirer = require('inquirer')

readline.cursorTo(process.stdout, 0, 5)
setInterval(() => readline.cursorTo(process.stdout, 0, 5), 100)

inquirer.prompt([{
  type: 'list',
  name: 'foo',
  message: 'Please select',
  choices: ['abc', 'def', 'ghi']
}])
```

The prompt should consistently be rendered on line 6. This is the case on the initial render, however when moving between options, the prompt is re-rendered on line 3:

![Execution](https://i.imgur.com/49Qshkw.gif)

**Comment by ycmjason** [comment]
Same issue for me too...

**Comment by xusai2014** [comment]
Do  you have  a solution for the problem? I want the prompt is fixed bottom.

**Comment by SBoudrias** [comment]
Hi, I'm pretty sure this works properly with the new Inquirer. Do let me know if not. See #1214
