### ISSUE TITLE
Putty on windows cannot show the figures characters correctly.

### ISSUE THREAD

**Issue by kishoregv** [SBoudrias/Inquirer.js#620]
When using putty to connect a linux shell checkbox is not shown correctly.
![image](https://user-images.githubusercontent.com/1823272/33934990-1784fa7e-e003-11e7-8304-59dc8b91a870.png)

**Comment by stupkad** [comment]
Any news on this issue? I am experiencing the same issue. It works well if connecting to the linux shell via command line or git bash. How to contribute?

**Comment by SBoudrias** [comment]
Looks like putty should be detected as Windows but isn't.

Inquirer relies on https://github.com/sindresorhus/figures for this. You could make a PR to that project to properly detect Windows + Putty.

**Comment by SBoudrias** [comment]
Following-up, I see this was raised up in the past on Figures. Sounds like it's a matter of configuration for Putty. https://github.com/sindresorhus/figures/issues/6

I'll close as there'll be no action on Inquirer itself.
