### ISSUE TITLE
Getting prompts and errors using the reactive interface.

### ISSUE THREAD

**Issue by sramam** [SBoudrias/Inquirer.js#623]
First off, I barely understand RxJs. And this is more a support request than a bug. 

However, it seems that using the reactive interface it should be possible to create a driver
for a set of questions, to enable testing. The idea is that given a set of expected inputs, 
one can drive the interface from the onEachAnswer/onError subscription, by testing for appropriate answers or error messages. 

For the happy path, this works well. It's when errors are triggered that I can't seem to 
figure how to trap them.

Even the example https://github.com/SBoudrias/Inquirer.js/blob/master/examples/rx-observable-array.js can't seem to print the error message when I enter an erroneous phone number.

Am I missing something or is this just not a possibility?

The simplest example I could come with to illustrate my intent:

```
  var inquirer = require('inquirer');
  const questions = [{
    type: 'input',
    name: 'q1',
    message: 'message',
    default: 'bar',
    validate: q1 => q1 === 'foo' ? 'cannot accept foo as an answer' : true
  }, {
    type: 'text',
    name: 'q2',
    message: 'q2',
    default: 'q2'
  }];
  var prompt = inquirer.createPromptModule();
  var promise = prompt(questions);
  promise.ui.process.subscribe(
    (answers, ...rest) => {
      console.log(`onEachAnswer: ${JSON.stringify({answers, rest})}`);
      setTimeout(() =>  promise.ui.rl.emit('line', 'q3'), 5);
    },
    (errors) => {
      console.log(`onError: ${JSON.stringify(errors)}`);
      setTimeout(() =>  promise.ui.rl.emit('line', 'jack'), 5);
    },
    (complete) => { console.log(`onComplete: ${JSON.stringify(complete)}`)}
  );

  promise.ui.rl.emit('line', 'foo');
```
If one removes `q1.validate` in the questions array above, this works. How do I trap the error message to ensure it's what I expect?

I'd also like to get the prompt string - to lock down my testing. Is that even possible?

**Comment by SBoudrias** [comment]
When failing validation, the error event isn't triggered. The error events would only get triggered in case of an exception thrown from code (`throw new Error();` or just broken code).

When the validation fail, inquirer handles it an display the error message automatically to the user, so you would see a re-rendering on the readline. I don't think you could get this from the reactive interface.

**Comment by sramam** [comment]
dang! makes sense.
Though it would be nice to be able to get the errors messages on some kind of a subscription.
And the same for the output messages. Would make testing a sequence of prompts a breeze. 

Thanks for quick turn-around.
