### ISSUE TITLE
Is it possible to use type = `editor` with pre-filled contents?

### ISSUE THREAD

**Issue by damianmr** [SBoudrias/Inquirer.js#627]
As per the docs:

> Editor - {type: 'editor'}: Launches an instance of the users preferred editor on a temporary file.

I would like to add contents to that temporary file, so that users can modify these contents and write new ones. Is this possible somehow?

**Comment by damianmr** [comment]
Sorry, I answer myself. Basically when you create the answer object you just pass a `default` option. :)

**Comment by jeremy-j-ackso** [comment]
@damianmr You should do a PR on the README that adds this.
