### ISSUE TITLE
not working in VSCode and Ubuntu terminal

### ISSUE THREAD

**Issue by tx4x** [SBoudrias/Inquirer.js#628]
all examples with choices print ^[[A or similar when using arrow keys. any idea ? 

using nodejs 8 & latest version.

**Comment by SBoudrias** [comment]
Which ubuntu terminal? the latest one?

And how do you run the examples? (just `node examples/list.js`?)

**Comment by tx4x** [comment]
ubuntu, yes! (17.10) pretty much all terminals have the same. tried stdin.setRawMode and what also listening to data & keypress but always the same. maybe this is just a glitch of my OS.

**Comment by tx4x** [comment]
examples: yes, tried many, not difference

**Comment by SBoudrias** [comment]
Yeah the weird thing is that if you see the raw code rather than arrow keys, it means the terminal isn't registering the keyboard events and is printing everything directly... Not sure where to go from now as I'm no ubuntu expert.

**Comment by tx4x** [comment]
ok, will close this; thanks again

**Comment by sagargondaliya** [comment]
I am also facing same issue.
