### ISSUE TITLE
FR: Show progress indicator on async validate

### ISSUE THREAD

**Issue by kbrandwijk** [SBoudrias/Inquirer.js#631]
I have an async validation that takes a while. When the user presses enter, nothing seems to happen, until the validation completes. Is it possible to add some visual indication (for example, changing the question mark into a progress spinner), while the validation is running. The UI feels unresponsive now.

Unfortunately, I can't console.log something like that myself, because if the validation fails, any logging will cause the question to repeat, which is not what I want.

**Comment by SBoudrias** [comment]
This would be a great improvement I believe.

Anyone wants to work on a PR?

**Comment by kbrandwijk** [comment]
With some guidance, I might. It seems that functionality would wrap this call: https://github.com/SBoudrias/Inquirer.js/blob/master/lib/prompts/base.js#L87 with something like `startSpinner -> call validate -> resetSpinner`. Would that be the right place to put this?

**Comment by kbrandwijk** [comment]
This is the implementation I have now. I added another option `validatingText` to a question for it too.
![spinner](https://user-images.githubusercontent.com/852069/34754598-10cd9e58-f5bf-11e7-8e7a-08b42cf17d4c.gif)

This can also be extended to filtering, which is also async:
![spinnerfiltervalidate](https://user-images.githubusercontent.com/852069/34755551-feac04ac-f5c4-11e7-962b-cce1136f3fd7.gif)
In the filtering case, I also added updating the display with the filtered answer after filtering is complete.

**Comment by kbrandwijk** [comment]
@SBoudrias Please see my PR for implementation details.

**Comment by benmonro** [comment]
any update on this @kbrandwijk ?  I would love to have this!

**Comment by kbrandwijk** [comment]
The PR apparently needs something (test case?) but I don't have any time to do it...

**Comment by kbrandwijk** [comment]
@benmonro Feel free to contribute if you'd like to 'have this'...

**Comment by ihack2712** [comment]
Check out the ora module by Sindre Sorhus.
