### ISSUE TITLE
Show information between prompts?

### ISSUE THREAD

**Issue by truckingsim** [SBoudrias/Inquirer.js#633]
So I'm writing a tool to pull files from s3 based on information given it filters differently.  One of the prompts ( a list) is like:

```
? Found X results.  What do you want to do with them?
> View File Names
> View Files
> Download
```

If they choose view file names I want to print out the names and then ask that question again.  However if I console log and then prompt the process exists without letting them choose. Basically it would look something like:

```
? Found X results.  What do you want to do with them?
> View File Names
> View Files
> Download
[file.json, file2.json, file3.json]
? Found X results.  What do you want to do with them?
> View File Names
> View Files
> Download
```

Is this possible?

**Comment by SBoudrias** [comment]
I don't think you need a change to inquirer to handle that. Just make a recursive function or chain 2 functions calling inquirer together. Some JavaScript code scheduling your events should work just fine.

**Comment by truckingsim** [comment]
@SBoudrias its not about making javascript that can call inquirer twice, I already do that.  The problem is node is exiting after doing the second prompt before I can answer.   As soon as I show the second prompt the process exits with a 0 exit code.  

The process should still be open because I haven't selected an option on the second prompt, but its not and that's why I created this.

You're saying it should work, can you think of any reason why it would exit without me selecting an answer?

**Comment by truckingsim** [comment]
@SBoudrias found a way around this by spawning an instance of `less` (the gnu program, not the css preprocessor) and using that to show data.

**Comment by SBoudrias** [comment]
If the process just exit, my guess would be that there's a lock on the process (like no callback keeping the process alive)
