### ISSUE TITLE
Mark questions as complete

### ISSUE THREAD

**Issue by kbrandwijk** [SBoudrias/Inquirer.js#634]
Would you be open to a PR that marks questions as complete after answering? Also, I noticed there's no 'global' options object anywhere. Maybe that could be introduced to set this behavior (and the progress spinner) for every question?

![spinnermarkcomplete](https://user-images.githubusercontent.com/852069/34810357-1888cadc-f69b-11e7-8f62-fc03f8f3112f.gif)

**Comment by SBoudrias** [comment]
[Cleaning up old issues]

This is now the default behaviour of inquirer on all recent release. There's also some `theme` options to customize this behaviour.
