### ISSUE TITLE
Use Rxjs complete to terminate prompt

### ISSUE THREAD

**Issue by geyang** [SBoudrias/Inquirer.js#639]
@SBoudrias I have the following pattern that I'm expecting to terminate the prompt:

```javascript
const prompt$ = new Subject();
inquirer.prompt(propt$).then(({key})=>console.log(key));
process.stdin.on('keypress', (ch, key) => {
    prompt$.complete();
});
```

I know the right way is to do `prompt.ui.close()`. Would it make sense to hand that control to the upstream `prompt$` object? After all `complete` events should be propagated down the chain.

I would love to hear your thought on this!

And thanks for this great library.

**Comment by SBoudrias** [comment]
Yeah, I think it'd make sense for us to handle that properly. Want to send a PR?

I think you'd need to modify this file https://github.com/SBoudrias/Inquirer.js/blob/master/lib/ui/prompt.js
