### ISSUE TITLE
Prompt finish exits repl instance

### ISSUE THREAD

**Issue by E314c** [SBoudrias/Inquirer.js#646]
inquirer@5.1.0
node v8.9.0

---

I'm trying to write a custom CLI and i'm using the inbuilt node REPL with a custom eval function.
Unfortunately, whenever an enquirer prompt finishes, it closes the current REPL instance.

## Code to replicate:
```javascript
const inquirer = require('inquirer');
const repl = require('repl');

const cliInstance = repl.start({
    prompt: '$ ',
    eval: (cmdStr, context, filename, callback) => {
        cmdStr = cmdStr.trim();
        inquirer.prompt([
            {
                type: 'input',
                name: 'name',
                message: 'What is your name? '
            }
        ]).then((res)=>{
            console.log('Prompt finished with', res);
            callback(null, res);
        });
    }
});
```

## Expected behaviour:
- enter something into repl (in real app it would be a command, but for this simple example any string will work)
- custom eval starts `inquirer` to ask a question
- answer question
- answer returned to repl
- _repl prompts for next input_

## Actual:
- enter something into repl
- custom eval starts `inquirer` to ask a question
- answer question
- answer returned to repl
- __repl exits__
- __node session exits__

## Notes
I'm guessing this probably has something to do with inquirer hooking into the active terminal or readline instance, then closing it, but this appears to be closing the instance created and used by repl.

**Comment by E314c** [comment]
probably worth clarifying that REPL doesn't `exit` in the clean sense:
if you add an 'exit' event handler, it never gets called
```
cliInstance.on('exit', (...args)=>{
    console.log('REPL saw exit: ', args);
});
```
instead the repl instance appears to just terminate

**Comment by SBoudrias** [comment]
So this might be caused by having 2 readlines runs over each other. The repl is also using the readline, so there might be some conflicts.

If you want to dig into that issue, you'd probably want to modify this function: https://github.com/SBoudrias/Inquirer.js/blob/master/lib/ui/baseUI.js#L43

If you find a solution, please send a PR!

**Comment by ellis** [comment]
Just as a minor note, `baseUI.js` has been moved and can currently be found here:
https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/lib/ui/baseUI.js

**Comment by KnisterPeter** [comment]
I'm in the same situation. From a first search I think it would be possible to start inquirer with a flag to not close or pause after a 'line' event on the readline.
Like here: https://dev.to/michael/how-to-prevent-readline-in-node-from-exiting-on-line-event-42n0

**Comment by SBoudrias** [comment]
I think this is related/same issue as https://github.com/SBoudrias/Inquirer.js/issues/894#issuecomment-602145740

I've posted some thoughts there about what a fix could be.
