### ISSUE TITLE
ANSI escapes for list choices?

### ISSUE THREAD

**Issue by erichs** [SBoudrias/Inquirer.js#651]
Hi! I notice that Inquirer `message` fields may have ANSI escapes (like those output via [chalk](https://github.com/chalk/chalk)), but List `choices` may not: choice entries are stripped before being rendered. Is it possible to support colorized list choices?

**Comment by SBoudrias** [comment]
Want to send a PR?

I think this might've been done because ANSI code in string might mess up the size calculation (although I do believe this might've been fixed since then)

**Comment by erichs** [comment]
Sorry, this was user error. This code works just fine:

```
const choices = [
  chalk.red('red'),
  chalk.green('green'),
  chalk.yellow('yellow')
];

const question = {
  type: 'list',
  name: 'choosy',
  message: 'choose one',
  choices: choices
};

inquirer.prompt(question)
  .then(answers => {
    console.log(stripAnsi(answers.choosy));
    console.log('fin');
  });
```
