### ISSUE TITLE
Input for only numbers?

### ISSUE THREAD

**Issue by championshuttler** [SBoudrias/Inquirer.js#654]
is there any input type through that only we can input number?

**Comment by SBoudrias** [comment]
There's no such prompt at the moment. The closest would be the normal input prompt with a validation checking user only inputted numbers.

I'm not against adding such a prompt to the core if someone wants to send over a PR.

**Comment by karlhorky** [comment]
Can this be closed now that #663 was merged?

**Comment by dkirchhof** [comment]
Hello, i was looking for the number prompt feature and found this issue first. You should update the documentation and typings, that this feature was merged.

**Comment by SBoudrias** [comment]
Oh good point. Anyone want to send a PR to update the README?

**Comment by dkirchhof** [comment]
Just made a pull request (https://github.com/SBoudrias/Inquirer.js/pull/786).

**Comment by SBoudrias** [comment]
Thanks for the PR!

We can properly close this issue now :)
