### ISSUE TITLE
[Question] Select / Deselect items of checkbox by code ?

### ISSUE THREAD

**Issue by supersuraccoon** [SBoudrias/Inquirer.js#656]
I am having a problem when using the checkbox prompt.

Say I have 5 items : [A, B, C, D, E] and now I need some items to be marked as `selected` when one item is selected. 

For example, when `A` is selected by the user , `B` and `C` need to be marked as `selected` automatically. 

I found a function named `toggleChoice(index)` in `checkbox.js` but do not know how to use it along with the `inquirer.prompt` function.

Any suggestion will be appreciated, thanks :)

**Comment by SBoudrias** [comment]
This option is not opened as something that can be programmatically done now.

Not sure Inquirer provide a proper interface for this to be easily implemented/and usable for developers.

I'm open to API suggestions; but not totally sure I want to add this feature unless there's lots of community support.
