### ISSUE TITLE
Ask questions not passed in via arguments

### ISSUE THREAD

**Issue by antony** [SBoudrias/Inquirer.js#664]
First off - great module, I've basically wrapped most of our DevOps commands in inquirer, and it works wonderfully.

One thing another developer has raised however, is the ability to allow a series of the questions to be skipped, based on pre-existing answers (i.e. from cli args).

If I have three questions:

* How many hands?
* How many toes?
* How many feet?

I would like to be able to do something like:

```bash
my-cli --hands 3
```

and for that question to be skipped, and the value 3 used as the answer.

In my app this might involve parsing the args into an answers hash, which can be passed to the Inquirer constructor.

**Comment by SBoudrias** [comment]
I think you could achieve this with https://www.npmjs.com/package/yargs-interactive

There's a few other projects on NPM also handling the logic between args parsing and interactive prompts.

Hope this helps :)

**Comment by antony** [comment]
Interesting - thanks!
