### ISSUE TITLE
Question: how to handle custom arrow-up key event? 

### ISSUE THREAD

**Issue by chlab** [SBoudrias/Inquirer.js#666]
Hi

Sorry for asking this here but I was hoping to get some more qualified answers than on SO. I developed an interactive translation manager with commander.js and inquirer.js - [here](https://github.com/liip-amboss/locale-man).

You can enter a series of keys and translations until you're finished. I would really like to add the functionality that you could press `[arrow key up]` and the tool would prefill your last-entered translation key for you (since often times they will be similar, like `page.billing.title`, `page.billing.intro`, etc.).

I played around with this for a while, trying to use the inquirer.js event handlers and just a regular node key event handler but I can't seem get it to work, especially the pre-filling the user input.

Can someone point me in the right direction here or even better, give me an example? This is where the magic would have to happen: https://github.com/liip-amboss/locale-man/blob/master/src/commands/AddTranslation.js#L52. Something like (pseudo code):

```
process.stdin.on('keypress', (ch, key) => {
  if (key.name == 'up') {
    process.stdout.write(lastTranslationKey)
  }
})
```

Thanks!!

**Comment by jwulf** [comment]
Have you looked at this? 

https://github.com/SBoudrias/Inquirer.js/issues/306

**Comment by chlab** [comment]
No, haven't looked into this since last year. Thanks for the link, looks promising.
