### ISSUE TITLE
Unterminated Process (with repro)

### ISSUE THREAD

**Issue by dschnare** [SBoudrias/Inquirer.js#667]
There's an odd issue I've encountered where the Node process will not terminate if I call `inquirer#prompt` multiple times with all questions having a falsey `when` setting *and* there is a time consuming task occurring between calling `inquirer#prompt`.

**Result:** The Node process does not terminate and can only be terminated by pressing the `Enter` key or the `Ctrl+C` interupt

**Expected Result:** Node process should terminate after calling `inquirer#prompt` multiple times when all questions are to be skipped *and* there are time consuming tasks interspersed between the calls

**Repro:** See https://github.com/dschnare/inquirer-unterminated

**Comment by anchengjian** [comment]
It's worked

```js
 // some inquirer code ...

  const readline = require('readline')
  readline.emitKeypressEvents(process.stdin)
  process.stdin.setRawMode(true)
  process.stdin.resume()
  process.stdin.on('keypress', (str, key) => {
    if (str === '\u0003') {
      process.exit()
    }
  })
```
