### ISSUE TITLE
[Security] Update lodash

### ISSUE THREAD

**Issue by nothingismagick** [SBoudrias/Inquirer.js#675]
https://nodesecurity.io/advisories/577

> Versions of lodash before 4.17.5 are vulnerable to prototype pollution.

Inquirer.js uses => ` "lodash": "^4.3.0" `

**Comment by ehmicky** [comment]
This should not be an issue since they are using `^`. Removing your `package-lock.json` then running `npm install` should solve this problem?

**Comment by SBoudrias** [comment]
@ehmicky thanks for helping out.

That's indeed what should be done now that lodash published a fix.
