### ISSUE TITLE
Wrong position of caret when using ANSI escape commands or backspace in message

### ISSUE THREAD

**Issue by ghost** [SBoudrias/Inquirer.js#677]
The default behavior of `inquirer` is to insert an additional space between the `prefix` and the `message` of a `Question` which looks as follows:

![screen shot 2018-05-11 at 12 34 07](https://user-images.githubusercontent.com/32624319/39920828-c67c7310-5518-11e8-841d-7b4ef86a66a2.png)

In my case I am trying to remove that space since I am using background colors to indicate the different parts of the prompt (similar to Powerline). When I add `message: chalk.reset(chalk.bgGreen.black("\b $ "))` for example there is an annoying side effect which you can see here:

![screen shot 2018-05-11 at 12 34 33](https://user-images.githubusercontent.com/32624319/39920871-fedc7ec6-5518-11e8-9bf0-70386282fc63.png)

The dark caret at the end of the text is always one char off since the manual backspace does change the caret's position. Is there any reasonable way to fix this without manually altering these lines:

https://github.com/SBoudrias/Inquirer.js/blob/a4cfcd39bab203e979abb0174d504c4f4cefc375/lib/prompts/base.js#L117-L122

Furthermore usual ANSI escape codes do not change the visual caret position although the logical caret is moved correctly. That means replacing my `\b` with a `\u001b[1D` to move the caret left cause the same rendering issue.

**Comment by SBoudrias** [comment]
Hum, how about we change prefix the contain the space, so you can more easily overwrite it without relying on `\b`?

**Comment by NearAutomata** [comment]
Sorry, but I don't understand your suggestion - can you elaborate more?

**Comment by NearAutomata** [comment]
Although this change makes sense, you might break code from other people. Assume they have a custom prefix without a space at the end. Once you remove the hardcoded space as suggested prefix and message suddenly get together. Even though it is only a "cosmetic" change, it is a breaking change the nonetheless.

My suggestion is to add an option for the time being that, when turned on, does exactly what you describe; otherwise, it shall behave as before.

**Comment by SBoudrias** [comment]
@NearAutomata There's a PR open to bump rxjs to the latest version. That'll also be a breaking change, so now is actually a good time to get a breaking change in even if it's small.

**Comment by NearAutomata** [comment]
Alright, I am all for it anyways, since I don't need to maintain and update my forked version with customized changes in the meantime then 😄

**Comment by NearAutomata** [comment]
@SBoudrias When do you consider adding the discussed change? I guess there is no PR necessary since it's only a very minor change in code.

**Comment by SBoudrias** [comment]
@NearAutomata I'm away from home now, so not sure when I'll have time. I'll gladly merge a PR sooner though.

**Comment by hongaar** [comment]
@SBoudrias I'm bumping into this now. Is this still planned for or would you accept a PR for this? 

Don't know how it would fit in a release schedule as I guess this would still be a breaking change?

BTW: the relevant code has moved here: https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/lib/prompts/base.js#L126

**Comment by SBoudrias** [comment]
Tested this and it works fine in `@inquirer/prompts` and `inquirer` v10; not sure when it was fixed.
