### ISSUE TITLE
Input prompt with command substitution

### ISSUE THREAD

**Issue by kwkelly** [SBoudrias/Inquirer.js#681]
I'm trying to write a bash script using inquirer for input, but when using command substitution, inquirer does not show the prompt.

Test script `test.js`
```
var inquirer = require('inquirer');

inquirer.prompt([
 {
    type: 'input',
    name: 'comments',
    message: 'Any comments on your purchase experience?',
    default: 'Nope, all good!'
}
]).then(answers => {
    console.log(answers)
});
```

To see the problem, try assigning the output of the prompt to a variable.

In a bash shell (maybe others):
`ans=$(node test.js)`

And nothing shows up, event though simply 
`node test.js`
works just fine.

However, the `read` bash builtin seems to work fine with command substitution. The following will show a prompt:
`$(read -p "Enter input: " input)`

**Comment by kwkelly** [comment]
Interestingly, the bash builtin `read` uses stderr to display the prompt text. Redirecting stderr to stdout causes it to be captured in the variable.

**Comment by kwkelly** [comment]
Looks like this is probably solved by https://github.com/SBoudrias/Inquirer.js/issues/519

But is it possible to write to /dev/tty instead of stderr?

**Comment by SBoudrias** [comment]
I don't think you'll be able to write to `/dev/tty` directly. Node only supports stdout and stderr as far as I know.

**Comment by kwkelly** [comment]
`/dev/tty` is just a file, so it can be written to as you would a file:

```
var fs  = require('fs');
var tty = fs.createWriteStream('/dev/tty');

tty.write('testing\n');
```

However, this might not be a great idea since I have no idea what the equivalent would be on Windows.

**Comment by SBoudrias** [comment]
@kwkelly actually, you can pass any stream as `output`. So it should work fine with the result of `fs.createWriteStream`.
