### ISSUE TITLE
install size bloat for inquirer@5

### ISSUE THREAD

**Issue by bugzpodder** [SBoudrias/Inquirer.js#682]
Since Inquirer upgraded from rxjs-lite v4 to rxjs V5/6, the install size quadrupled from 7MB to 25MB.
Part of the reason is because of the way rxjs bundles (https://github.com/ReactiveX/rxjs/issues/3334) but even if we do not account for src/ it is is still a 17MB dependency.  

inquirer@5 is used by create-react-app@2 and eslint@5 and we are trying to see if there is anyway to reduce the install size and still use this dependency.
https://github.com/facebook/create-react-app/issues/3880
https://github.com/eslint/eslint/issues/10404

**Comment by SBoudrias** [comment]
Anyone has a suggestion on how to reduce rxjs size? We made the choice to use rxjs a long time ago, but it's been causing file size issues for a long time now...

**Comment by dwieeb** [comment]
Wait for https://tc39.github.io/proposal-observable? 😂 

On a more serious note, it'd be possible to do a massive refactor of Inquirer to have the "core" be event-based, and then have `inquirerjs-reactive` or something for those who wish to use the reactive interface. Just a _lot_ of work.

This library is depended upon by Facebook, ESLint, Vue, Ionic, Yeoman, and likely many more big names. Could we all come together and help? I'd be happy to give more hours of my time. I can't promise anything related to sponsorship, though.

**Comment by frangio** [comment]
Please reopen this issue.

**Comment by SBoudrias** [comment]
If anyone wants to help, there's an on-going effort to refactor the core without rxjs who's the very large dependency.

https://github.com/SBoudrias/Inquirer.js/issues/685
