### ISSUE TITLE
Unable to run the jest tests, if answer for the question is true

### ISSUE THREAD

**Issue by grv190** [SBoudrias/Inquirer.js#683]
I want to run the jest tests, if the user give the correct answer.How can i acheive that?

In the below code, in .then() i am calling the function.

`
const inquirer = require('inquirer')

inquirer
  .prompt({
    type: 'checkbox',
    message: 'Select the responsiveness, you want to take snapshot',
    name: 'responsiveness',
    choices: [
      new inquirer.Separator('select responsiveness'),
      {
        name: 'mobile_320x480'
      },
      {
        name: 'tab_768x1024'
      },
      {
        name: 'tab_1024x768'
      },
      {
        name: 'pc_1366x768'
      },
      {
        name: 'pc_1920x1080'
      }
    ]
  })
  .then(answers => {
    console.log('inside')
    console.log('answers:', answers)
    liveSnapshot(320, 480)
    console.log('after')
  })`

**Comment by hdorgeval** [comment]
Hi @grv190, @SBoudrias , maybe this kind of test is an answer to your problem: [inquirer unit testing on publish-please repo](https://github.com/hdorgeval/publish-please/blob/pr/audit/test/config.spec.js) 

and [inquirer unit testing](https://github.com/hdorgeval/publish-please/blob/pr/audit/test/inquires.spec.js)

**Comment by SBoudrias** [comment]
@hdorgeval thanks for taking the time to answer :)

In unit test you'll want to mock inquirer (like any other system input usually). `jest.mock` should work just fine for that.

**Comment by LetsMelon** [comment]
@hdorgeval your links are dead :,(
