### ISSUE TITLE
How can I execute a function according to the choice made in this example?

### ISSUE THREAD

**Issue by Odka33** [SBoudrias/Inquirer.js#689]
![capture d ecran 2018-06-04 a 00 33 42](https://user-images.githubusercontent.com/22498710/40891920-0d44e4f2-678f-11e8-9dd1-2c2fd07ae2de.png)

**Comment by SBoudrias** [comment]
If/else works just fine

```js
if (choices.choices === 'Get list of users') {
   getListOfUsers();
}
```

**Comment by Odka33** [comment]
Thanks for help !
