### ISSUE TITLE
Async prompting causes issues

### ISSUE THREAD

**Issue by jwinnie** [SBoudrias/Inquirer.js#690]
I fire off two `inquirer.prompt`s at the same time, and it gets all messed up.

![inquirerjs](https://user-images.githubusercontent.com/20506149/41128416-f5ea613e-6a62-11e8-96be-ccf2fd1841ec.png)

Is there a way to do one prompt first, then the other?

**Comment by SBoudrias** [comment]
Yeah, wait for the first one to complete before triggering the second one.

Pure async won't ever work as a user can't answer 2 prompts at the same time.

**Comment by jwinnie** [comment]
@SBoudrias Sorry, I'm not very good at JS. How would you do that? Using `async`/`await`?

**Comment by SBoudrias** [comment]
@jwinnie yes that would be a good approach. Here's example code:

```js
const options = await getOptions();
const { choice } = await inquirer.prompt([ ... ]);

const options2 = await getOptions2();
const { choice2 } = await inquirer.prompt([ ... ]);
```
