### ISSUE TITLE
Separating the generation of the message and the actual screen rendering

### ISSUE THREAD

**Issue by yll12** [SBoudrias/Inquirer.js#696]
We were trying to add a timeout feature to the ListPrompt by extending it, and we want to generate a message that countdowns before the program exits. The issue is we couldn't amend the message because the generation of the message and the actual screen rendering is coupled in the `render()` function. We ended up copying the logic of `render()` and the `listRender()` function:

```js
render(seconds) {
    // Render question
    var message = this.getQuestion();

    if (this.firstRender) {
      message += chalk.dim('(Use arrow keys)');
    }

    // Render choices or answer depending on the state
    if (this.status === 'answered') {
      message += chalk.cyan(this.opt.choices.getChoice(this.selected).short);
    } else {
      var choicesStr = listRender(this.opt.choices, this.selected);
      var indexPosition = this.opt.choices.indexOf(
        this.opt.choices.getChoice(this.selected)
      );
      message += '\n' + this.paginator.paginate(choicesStr, indexPosition, this.opt.pageSize);

      // WE ADDED THIS LINE :)
      if (seconds) {
        message += `\nExiting after ${seconds} seconds. (Press ${figures.arrowUp}/${figures.arrowDown} to continue...)`;
      }

    }

    this.firstRender = false;

    this.screen.render(message);
  }
```

Can we separate the logic of generating the message and screen rendering into two methods? So that we can just write something like:

```js
generateMessage(seconds){
  if (this.status === 'answered' || !seconds) return super.generateMessage();
  return super.generateMessage() + `\nExiting after ${seconds} seconds. (Press ${figures.arrowUp}/${figures.arrowDown} to continue...)`;
}
``` 

We're happy to submit a PR if you like this idea.

CC @ycmjason

**Comment by ycmjason** [comment]
I think this will make the prompt more extendable.

**Comment by SBoudrias** [comment]
You should check the refactor plan over here: https://github.com/SBoudrias/Inquirer.js/issues/692

The new core will make adding similar hook trivial.

**Comment by ycmjason** [comment]
@SBoudrias 
Nice. The ongoing refactor definitely looks like it will resolve these issues. However, I do feel that the completion of this may be quite a while away. This proposed change will make this library more extendable without affecting the API. This should be safe to implement so maybe it's worth doing in the meantime?

In the mean time, is it possible to quickly add this? it wouldn't change the API and should be safe to implement. 👍

**Comment by ycmjason** [comment]
@SBoudrias 
Nice. The ongoing refactor definitely looks like it will resolve these issues. However, I do feel that the completion of this may be quite a while away. This proposed change will make this library more extendable without affecting the API. This should be safe to implement so maybe it's worth doing in the meantime?
