### ISSUE TITLE
keyboard shortcut for list selection ?

### ISSUE THREAD

**Issue by benintech** [SBoudrias/Inquirer.js#699]
Hi,
It would be great to add the possibility to select a choice in a list through a keyboard shortcut, for example :
```
$ node list.js
? What do you want to do? (Use arrow keys)
❯ [O]rder a pizza 
  Make a [r]eservation 
  ──────────────
  Ask for opening [h]ours 
  - Contact support (Unavailable at this time)
  Talk to the receptionist 
```
Typing "o" would select the first choice (order a pizza), typing "r" the second choice (make a reservation), and so on.

Could be useful in the case of a long list, no need to use the arrow keys...

**Comment by banminkyoz** [comment]
Since there's 'j', 'k' mapping to move up and down like vim, i think mapping 'o' to select is really cool
