### ISSUE TITLE
Problems using reactive interface with typescript

### ISSUE THREAD

**Issue by adityaparab** [SBoudrias/Inquirer.js#702]
I created this simple cli app just to test out reactive interface of inquirer with typescript.
I was able to run the module with typescript without reactive interface and it works fine. However, I'm unable to get it working with typescript. Would be great if anyone can point me in a right direction.

This is my `questions.ts` file

```ts
import { Answers, InputStreamOption, Question, Questions } from 'inquirer';

const nameQuestion: Question<Answers> = {
    message: 'Enter Name',
    name: 'name',
    type: 'input',
};

export const CliQuestions: Question[] = [
    nameQuestion
];

```

And this is my index.ts file where I import the file from above.

```ts
import { Answers, prompt } from 'inquirer';
import { CliQuestions } from './questions';

class CliTool {
    private prompt: Promise<Answers> | undefined = undefined;
    constructor() {
        console.log('Constructing CliTool Instance');
    }

    public run() {
        console.log('CliTool Instance Started');
        this.prompt = prompt(CliQuestions);
        this.prompt.then((answers: Answers) => {
            console.log(answers);
        });

    }
}

const cliTool = new CliTool();

cliTool.run();
```

As I said earlier, this is working fine.

However, something goes haywire when I try to use reactive interface here.

```ts
import { Answers, prompt, Question } from 'inquirer';
import { Subject } from 'rxjs';

import { CliQuestions } from './questions';

class CliTool {
    private cliPrompt = new Subject<Question[]>();
    constructor() {
        console.log('Constructing CliTool Instance');
    }

    public run() {
        console.log('CliTool Instance Started');
        prompt(this.cliPrompt);

    }
}

const cliTool = new CliTool();

cliTool.run();
```

I end up getting this error

src/index.ts:14:16 - error TS2345: Argument of type 'Subject<Question<Answers>[]>' is not assignable to parameter of type 'Questions<{}>'.
  Type 'Subject<Question<Answers>[]>' is not assignable to type 'Observable<Question<{}>>'.
    Property 'observeOn' is missing in type 'Subject<Question<Answers>[]>'.

14         prompt(this.cliPrompt);

**Comment by SBoudrias** [comment]
Closing as this question was posted twice.
