### ISSUE TITLE
What does question.source mean?

### ISSUE THREAD

**Issue by NE-SmallTown** [SBoudrias/Inquirer.js#707]
There is a repo which use question.source option but I don't find it in the https://github.com/SBoudrias/Inquirer.js#question or issues, release list.

Could you explain for it? thanks.

**Comment by SBoudrias** [comment]
Hey, there's no such things as `option.source`. Maybe they use a custom wrapper on top of Inquirer or they use the key for their own reference. Either way, this is not an Inquirer option.

Hope this help a little :)

**Comment by NE-SmallTown** [comment]
Thanks for you reply, I think maybe it's not true.

You can check something like:
https://github.com/SBoudrias/Inquirer.js/issues/166#issuecomment-324805981
or
https://github.com/carloscuesta/gitmoji-cli/blob/master/src/prompts.js#L39

**Comment by SBoudrias** [comment]
> are you in beijing of China now?

Yes, that's where I live 😛 

The `source` parameter might be from an inquirer plugin too. You can see it's not used in Inquirer's own code base with search: https://github.com/SBoudrias/Inquirer.js/search?q=source&unscoped_q=source

**Comment by SBoudrias** [comment]
@NE-SmallTown Feel free to ping me on gitter, I can send you my wechat.

**Comment by NE-SmallTown** [comment]
Yea, ping you ~
