### ISSUE TITLE
Pre-defined answers

### ISSUE THREAD

**Issue by aleclarson** [SBoudrias/Inquirer.js#708]
I should be able to pass a hash of pre-defined answers to `prompt` that essentially auto-fills the associated prompts.

The pre-defined answers would still be passed to the `filter`, `transformer`, and `validate` functions. <s>Beforehand, they would be coerced to a string as if they were manually typed into the prompt.</s>

WDYT?

**Comment by rdpacheco** [comment]
This would be very valuable for testing

**Comment by aleclarson** [comment]
@rdpacheco See #709

**Comment by rdpacheco** [comment]
> @rdpacheco See #709

This is great, hope it gets merged soon. Thanks!

**Comment by aleclarson** [comment]
@rdpacheco Unlikely that it will, because it modifies the "old" codebase and has no unit tests.

**Comment by jeasonstudio** [comment]
what about pre-set 'environmental variable'  @aleclarson

**Comment by SBoudrias** [comment]
Not sure when that was added, but a PR was merged with that feature. [See documentation](https://github.com/SBoudrias/Inquirer.js/tree/main/packages/inquirer#inquirerpromptquestions-answers---promise).

(cleaning old issues)
