### ISSUE TITLE
Disable scrolling behind first/last element

### ISSUE THREAD

**Issue by apierzch** [SBoudrias/Inquirer.js#722]
By default paginator allows to scroll behind last element by "overflowing" to first element, and vice-versa. Is it possible to disable this behavior?

**Comment by SBoudrias** [comment]
Any specific reason you need to prevent this behavior?

**Comment by apierzch** [comment]
The list of choices that I want to display is ordered chronologically, it's very confusing when the last item appears before first.

**Comment by ycmjason** [comment]
+1 to this suggestion.

I would also want the pager to only scroll when the highlighted option hits the bottom.

**Comment by SurenAt93** [comment]
@SBoudrias There is at least should be an ability to change/control this behavior.

**Comment by SBoudrias** [comment]
Not sure when it ended up making it in core but all prompts have a `loop` option today (probably safe to say since at least v8) to turn off the looping behaviour in the list.
