### ISSUE TITLE
Verify inquirer prompt validate function unit testing

### ISSUE THREAD

**Issue by Shreyas-vgr** [SBoudrias/Inquirer.js#729]
Hi, is there a way to verify validate functionality in inquirer prompt while unit testing.
var questions = {
     type : 'input',
     message : 'Please enter username',
    validate : (value) => {
        if( !value || value.length == 0) return 'Error: invalid username'; 
       return true;
   };
};
inquirer.prompt([questions]).then((answer) => { console.log(answer)});

**Comment by SBoudrias** [comment]
You can find help on how to mock modules on StackOverflow. (you'd want to use something like `jest.mock()`, `proxyquire` or equivalent feature with other tools)

I hope this doesn't get around too rudely, but I cannot offer technical support to all the users of Inquirer. Let's keep the issues channel for bugs and feature requests.
