### ISSUE TITLE
Put a Prompt in the BottomBar?

### ISSUE THREAD

**Issue by linkjay** [SBoudrias/Inquirer.js#735]
I clearly seem to be missing something. Is there any way to dock an input prompt at the bottom so no text output goes over the prompt?

Maybe a way to put the prompt inside of a BottomBar?

**Comment by SBoudrias** [comment]
That was the initial goal, but the implementation didn't turn out as I had hope. Currently this is not possible.

The main issue is that combining 2 readlines (where one readline is a children of the first one) wasn't really working properly. If there's was always one write per prompt screen update - it might be possible. But right now there's no easy way to know when the prompt readline would need to be refreshed inside the bottom bar.

**Comment by kearfy** [comment]
would it be possible though to do it with just an input? that would use only one line, and the output would just go above...
