### ISSUE TITLE
User input list

### ISSUE THREAD

**Issue by redxtech** [SBoudrias/Inquirer.js#737]
I was wondering if there is any way to implement a way for users to input a list. I know that it is currently possible to allow users to select from a list, but if would be amazing to be able to ask for a list from the users.

For example, I would like to request a tracklist for an album and would like the answer value to be
```javascript
['Song 1', 'Song 2', 'Song3']
```
If this could be done I would greatly appreciate it.
Thanks :)

**Comment by ohjimijimijimi** [comment]
Hey, I just came across the same question. I solved it with an `input` question as follows:
```
const questions = [{
    type: 'input',
    name: 'list',
    message: 'What are you looking for?',
    suffix: ' Please, enter a comma separated list of items',
    filter: (versions) => {
      return versions.split(',').map(item => item.trim(item))
    }
  }
];
```

With the input `Song 1, Song 2 , Song 3` the output will be `['Song 1', 'Song 2', 'Song3']`.

Hope it could help

**Comment by redxtech** [comment]
That makes a lot of sense - thanks a ton.

**Comment by redxtech** [comment]
@ohjimijimijimi Just an FYI you can improve this and make it less code if you refactor the filter line to this:
```javascript
{
    filter: versions => versions.split(',').map(item => item.trim(item))
}
```
