### ISSUE TITLE
compatibility with Node 10.11

### ISSUE THREAD

**Issue by gustavomerini** [SBoudrias/Inquirer.js#739]
Hello, i'm not sure if this is a bug or something else but I tried to use this lib with the latest (not safe) version of node(10.11) and when I tried to use a question of type "editor" it did not work.

```
    const questions = [
        {
            name: "file",
            type: "editor",
            message: "Submit your file contents_:",
        },
    ];
    logger.verbose('questions ' + questions.toString());
    const answers = await inquirer.prompt(questions);
    logger.verbose('answers ' + answers);
```

the log answers do not display on my console, although the questions log does.

can anyone tell me if this lib is working on the latest (unsafe) version of nodeJS? 

p.s - it is working perfectly on the safe version of node(8.12), I just wanted to know about the 10.11 compatibility because it will soon be the actual version of node.

Thanks in advance and sorry if I created an unnecessary issue

**Comment by SBoudrias** [comment]
It should be compatible... I haven't heard of any upcoming breaking changes on Node part. You should open a ticket over there if it really stop working on the latest version.

**Comment by gustavomerini** [comment]
ok, thanks, i'll investigate better.
