### ISSUE TITLE
Waiting too long to require('inquirer') 

### ISSUE THREAD

**Issue by jinCN** [SBoudrias/Inquirer.js#744]
My command line app prompts immediately after start.
The problem is  require('inquirer')  takes about 0.2 ~ 0.4 seconds.
Really bad user experience.
Can it be optimized to under 0.05 seconds?

**Comment by SBoudrias** [comment]
Hi, we're running a refactor within which we hope to improve the startup performance considerably. All the help is welcomed over on https://github.com/SBoudrias/Inquirer.js/issues/692
