### ISSUE TITLE
Clear the questionnaire ?

### ISSUE THREAD

**Issue by udithv** [SBoudrias/Inquirer.js#746]
how do I clear the entire questionnaire after all of it is asked.

**Comment by udithv** [comment]
@SBoudrias yes but not the whole console. just the output. Something like logUpdate module where the output is replaced with another... only in my case it has to be replaced with nothing.

**Comment by tashpjak** [comment]
Any update?

**Comment by LitoMore** [comment]
Jump out of your question, I think [Ink](https://github.com/vadimdemedes/ink) is a better tool to implement your idea.

**Comment by raulfdm** [comment]
I've just implemented that by using `console.clear`:

![2022-08-30 at 16 23 17 - Blue Owl](https://user-images.githubusercontent.com/12464600/187462671-18e63900-5af3-4306-93de-daf41353a19a.gif)

In my case I have multiple prompts and before jump from one to another, I run a `console.clear` and then show my CLI title again.

**Comment by SBoudrias** [comment]
Hello, I've added this feature in our new prompts (the `@inquirer/*` modules.)

**Comment by raulfdm** [comment]
@SBoudrias, what do you mean exactly?

Is there documentation about this somewhere?

**Comment by SBoudrias** [comment]
There's types and documentation per prompts; but not a great consolidated doc yet. Here's an example code:

```js
import confirm from '@inquirer/confirm';

const answer = await confirm(
  { message: 'Enter your name' },
  { clearPromptOnDone: true }
);
```
