### ISSUE TITLE
Windows10 and Node v10, the second time of inquirer.prompt will hang

### ISSUE THREAD

**Issue by RonWang** [SBoudrias/Inquirer.js#752]
Platform: Windows10, Nodejs any version greater then v10.2.0

Issue: If the second time calling [readline.createInterface](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/lib/ui/baseUI.js#L15), input will hang. 

After some investigation, v10.1.0 is working but v10.2.0 starts to have this hanging problem. Then checking the [changelog of Nodejs](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.2.0) for v10.2.0, it seems this is because the lazy loading of readline https://github.com/nodejs/node/commit/3eb38debb4. Why is the lazy-loading change causing this?

**Comment by Nessworthy** [comment]
Running into the same issue in node `v10.13.0` and inquirier `v4.0.0`

**Comment by braydenc303** [comment]
I get the same thing with node v11.4.0 and inquiter v4.0.0.

**Comment by Nessworthy** [comment]
Just commenting back on this, upgraded to inquirer 6.2.0 and it has resolved my issue! Thanks devs :)

**Comment by braydenc303** [comment]
Rolling back to 6.2.0 fixed it for me.
