### ISSUE TITLE
When calling a node script with inquirer from bash, process immediately exits

### ISSUE THREAD

**Issue by jeffreyhshapiro** [SBoudrias/Inquirer.js#753]
I have a bash script where I call a node process containing inquirer. 

```
#!/bin/bash

#stuff happening here, and pass data into script

node /path/to/node/script/index.js
```

The node script has an inquirer prompt in it.  When called from the bash script, it displays the options and then immediately exits.  When I call the node script directly in the command line, it works as expected.

For reference, this is my Inquirer code

```
inquirer.prompt(
  [
    {
      type: "list",
      name: "proceed",
      message: 'Testing',
      choices: ['Yes', 'No']
    }
])
.then(answers => {
  console.log(answers);
})
.catch((e) => {
  console.log(e, "err")
})
```

Using MBP High Sierra, Node v8.12.0 FWIW

**Comment by SBoudrias** [comment]
The script needs to inherit the stdio stream to be able to listen and respond do keypress. If the stdio stream allocated isn't a TTY, node readline module will auto exit

**Comment by mickeypearce** [comment]
I similarly use `inquirer` in a spawn process. I inherited the stdin stream and It works quite well:
```js
child.spawn(process.execPath, params, {stdio: ["inherit"]})
```
But there is a minor glitch when using prompt inputs. It echoes the inputed string char by char:
```bash
? Your input: h
? Your input: he
? Your input: hel
? Your input: hell
? Your input: hello
```
Any idea on how to solve this issue? I tried inheriting the stdout  {stdio: ["inherit", "inherit"]} but it doesn't work.

**Comment by SBoudrias** [comment]
@mickeypearce looks like in your case it ignores the ANSI clear codes... I'm not sure why. But I'd assume somehow the terminal prevent this from spawned processes. Did you try with exec?

**Comment by mickeypearce** [comment]
Hey, I think exec is "synchronous" in a way that it waits for a child process to end and then returns all data at once. It waits on input in my case and doesn't respond.

**Comment by mickeypearce** [comment]
I figured it out. It is:
```js
child.spawn(process.execPath, params, {stdio: "inherit"})
```
which inherits whole stdio (including stdout and stderr) not only stdin as I had in my previous case. 🙄
sorry to bother you and thanks.

**Comment by jeffreyhshapiro** [comment]
I figured out my problem as well- really easy

```
#!/bin/bash

#stuff happening here, and pass data into script

exec < /dev/tty;

node /path/to/node/script/index.js
```

**Comment by SBoudrias** [comment]
Thanks for following up :)

I didn't know the `exec < /dev/tty;` trick, that's quite handy!

**Comment by Teebo** [comment]
@jeffreyhshapiro how exactly did you resolve this issue?

**Comment by yamsellem** [comment]
@jeffreyhshapiro @SBoudrias may you please explain how you've pass data to the script, bypassing inquirer limitation to run scripts?

Thanks a lot.

**Comment by c6fc** [comment]
The solution here works for directly executed scripts: `./myscript.sh`

To fix for `cat myscript.sh | bash`, you need to structure the line like this:

```#!/bin/bash

#stuff happening here, and pass data into script

exec node /path/to/node/script/index.js < /dev/tty;```
