### ISSUE TITLE
chore: better error message handling for `choices`

### ISSUE THREAD

**Issue by niftylettuce** [SBoudrias/Inquirer.js#765]
right now if `choices` contains a number, e.g. `choices: [ 100, 90, 80 ]` then the following error message appears (which isn't obvious to the user that `choices` can only be a String or Object (per the README)

```sh
(node:52503) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'value' in 100
    at new module.exports (/Users/me/.nvm/versions/node/v8.12.0/lib/node_modules/lass/node_modules/inquirer/lib/objects/choice.js:25:22)
```

**Comment by LitoMore** [comment]
> Which isn't obvious to the user that `choices` can only be a String or Object (per the README

@niftylettuce This issue has been explained in documentation. See https://github.com/SBoudrias/Inquirer.js#question

> Right now if choices contains a number, e.g. choices: [ 100, 90, 80 ] then the following error message appears

Good point, let's add support for it! I will be working on this issue.
