### ISSUE TITLE
In rawlist, the answers go in negative while moving up 

### ISSUE THREAD

**Issue by sarthology** [SBoudrias/Inquirer.js#769]
In the type `rawlist`, when the key is used to choose value the answers go in negative, if you up and more than the total choices if you go down.

Is this a bug or I'm missing something?

```
inquirer.prompt([{
            type: 'rawlist',
            name: 'title',
            message: 'Select the story 🤓',
            choices: ['👻','🤓','👩🏻‍💻','👨🏻‍💻','🦄','💻','👾','👽'],
            paginated: true
        }])
        .then(answers => {
            openLink(answers);
        });
```
![](https://media.giphy.com/media/24FMrDc1eOnQmW35de/giphy.gif)

**Comment by sarthology** [comment]
Ohk on it.

**Comment by LitoMore** [comment]
Hi @sarthology We could close this issue if it already solved.

**Comment by sarthology** [comment]
Yeah it's solved from my side.
