### ISSUE TITLE
Expand functionality for a list?

### ISSUE THREAD

**Issue by NickHeiner** [SBoudrias/Inquirer.js#77]
I would like to be able to use `hint` to give additional information for the currently selected list item. Is that currently possible? If not, I think it should be added. Would you be amenable to a PR?

**Comment by GeorgeGkas** [comment]
It seems that the issue was resolved. @SBoudrias can we close it for inactivity? If there is more discussion to be done, it's better to file a new issue. Many things have been improved from the last comment 5 years ago.

**Comment by NickHeiner** [comment]
I'm fine to close the issue.
