### ISSUE TITLE
Accommodate choices with multiple lines in `name`?

### ISSUE THREAD

**Issue by cheapsteak** [SBoudrias/Inquirer.js#781]
Adding `\n` to the name of a choice results in the curser going off-screen and the current selection going outside the viewport  

```js
inquirer.prompt([
  {
    type: 'list',
    choices: Object.entries(package.scripts).map(
      ([scriptName, scriptContents]) => ({
        name: `${scriptName} =>\n    ${scriptContents}`,
        value: scriptName,
      }),
    ),
  },
]);
```

![](https://camo.githubusercontent.com/415e6c9f0bd21bf27f3080aa794e4bcd378c08a1/68747470733a2f2f636c2e6c792f3062643836336463666364612f53637265656e2532305265636f7264696e67253230323031392d30322d3039253230617425323031302e3032253230414d2e676966)

It looks like the `topIndex` isn't correctly calculated for these

This works for me right now, but it's hardcoded to my situation of having exactly one `\n` per choice:
```diff
-var topIndex = Math.max(0, active + lines.length - this.pointer);
+var topIndex = Math.max(0, active * 2 + lines.length - this.pointer);
```

Not sure what a better solution would be

**Comment by SBoudrias** [comment]
I believe this works fine with the current releases; but let me know if not, I'll take a look.
