### ISSUE TITLE
Doesn't work properly with terminal-link

### ISSUE THREAD

**Issue by zxqfox** [SBoudrias/Inquirer.js#782]
When I trying to install and run this sample:
```sh
npm i inquirer@6.2.2 terminal-link@1.2.0
```
```js
const inquirer = require('inquirer');
const terminalLink = require('terminal-link');

inquirer.prompt({
    type: 'input',
    name: 'xxx',
    message: `TEXT (${terminalLink('CLICK', 'https://github.com')})`,
});
```

I saw cursor positioned far away from `(CLICK)`.
Looks like a bug because of link

**Comment by SBoudrias** [comment]
I don't think

**Comment by LitoMore** [comment]
It's a bug of the [strip-ansi](https://github.com/sindresorhus/strip-ansi). I created an issue to track this bug.

https://github.com/chalk/strip-ansi/issues/25
