### ISSUE TITLE
SIGINT captured

### ISSUE THREAD

**Issue by sumarlidason** [SBoudrias/Inquirer.js#789]
Possibly Related #293 

We experienced issues with promises + subprocesses inside the inquirer promise chain when sending SIGINT to the process. Removing the `prompt` from the process and hardcoded `answers` resolved the issue. We did some research into what could still be listening for SIGINT from `process` and found that `cli-cursor` uses `restore-cursor` which uses `signal-exit`. In testing I found that signal-exit's listeners were not being called while sending ctrl-c. Clearing the listeners manually(`process.removeAllListeners('SIGINT');`) after receiving `answers` from `prompt` resolved the issue. We also noticed the event listeners only lingered while using `list` question type. Here is a sandbox we were testing with:
```javascript
const i = require('inquirer');
const util = require('util');

const questions = [
  {
    type: 'list',
    name: 'version',
    message: 'Some important question?',
    choices: ["a", "b"],
  }
];

const ask = async () => {
    const answers = await i.prompt(questions);
    const listeners = process.listeners('SIGINT');
    if(listeners.length) {
        console.log(listeners[0].toString());
        console.log(util.inspect(process.listeners('SIGINT')));
    }
};

ask();
```

**Comment by SBoudrias** [comment]
Are you suggesting we change `cli-cursor` dependency as it captures the SIGINT?

**Comment by sumarlidason** [comment]
It's not so much `cli-cursor` as `signal-exit`. signal-exit ensures the cursor is always re-enabled upon process exit. A lot of code to do something so simple. I lack the bandwidth to dig deep -- will revisit. I need to build a sample that reproduces the actual problem.

**Comment by shirshak55** [comment]
@sumarlidason what is the issue? I also see ctrl+c don't work with inquirer any more. Is there any good solution?

**Comment by sumarlidason** [comment]
@shirshak55 I don't have access to the affected code any more and cannot remember anymore than what is in this issue. Do you have a concise code sample you can share with the problem?

**Comment by shirshak55** [comment]
used only 
```
async function getQuestions()=>{
	let questions = await inquirer.prompt({type="list" ...})
	return questions
}
```
now Ctrl + C is not working on other application lol. especially on express server SIGINT disappears somewhere. And when i remove the above code ctrl +c works.
