### ISSUE TITLE
Add inquirer-select-directory to plugin List

### ISSUE THREAD

**Issue by Joniras** [SBoudrias/Inquirer.js#800]
It makes selecting a directory easy as never before!

Add it to the Plugin list for easier access.

Here are the links:
[NPM](https://www.npmjs.com/package/inquirer-select-directory)
[Github](https://github.com/KamiKillertO/inquirer-select-directory)

**Comment by SBoudrias** [comment]
Please send a PR :)

As not an issue about Inquirer, I'll close this ticket.
