### ISSUE TITLE
Access previous answers from filter

### ISSUE THREAD

**Issue by pldg** [SBoudrias/Inquirer.js#804]
I know I can put each prompt inside a function and access a previous answer by passing it as argument:

```js
const { inputDir } = await ask_input();
const { outputDir } = await ask_output(inputDir);

async function ask_input() {
  return inquirer.prompt([{
    type: 'input',
    name: 'inputDir',
    message: 'Input directory',
  }]);
}

async function ask_output(inputDir) {
  return inquirer.prompt([{
    type: 'input',
    name: 'outputDir',
    message: 'Output directory',
    filter: outputDir => path.resolve(inputDir, outputDir)
  }]);
}
```

But I think adding this feature directly inside `filter` would make it simpler:

```js
inquirer.prompt([
  {
    type: 'input',
    name: 'inputDir',
    message: 'Input directory'
  },
  {
    type: 'input',
    name: 'outputDir',
    message: 'Output directory',
    
    // I'd like to access the previous answers here...
    filter: (outputDir, answers) => path.resolve(answers.input, outputDir)
  }
]);
```

**Comment by SBoudrias** [comment]
I don't see a reason why not given we're doing this for other functions (I'm actually kind of surprised this doesn't work out of the box already).

Want to send a PR?

**Comment by robertjk** [comment]
>``` 
>    // I'd like to access the previous answers here...
>     filter: (outputDir, answers) => path.resolve(answers.input, outputDir)
> ```
Currently filter accepts 2 arguments: answer to the current question and hash containing all answers, so that you can write exactly that.

Below's a code from `/packages/inquirer/lib/prompts/base.js`. It passes both `value` and `self.answers` to the filter. I tested it in my project, as I ran into exactly the same problem, and it works.

```
var asyncFilter = runAsync(this.opt.filter);
    var validation = submit.pipe(
      flatMap(value =>
        asyncFilter(value, self.answers).then(
```
