### ISSUE TITLE
the terminal crash

### ISSUE THREAD

**Issue by bWhirring** [SBoudrias/Inquirer.js#810]
I write a node command-cli tool when I used twice in a row, the first one is ok, but when the second time I input sth or choice sth, my terminal not working, just crashed. the strange thing is it works well when I use `npm link` or the other directory. 

Inquirer version is 6.4, but when I use 5.2, it works well. I don't know Which version brought some influence.

**Comment by danielo515** [comment]
Same as #811

**Comment by li-shuaishuai** [comment]
In the new version v6.4.0, I encountered the same problem

**Comment by SBoudrias** [comment]
`6.4.1` was just released.
