### ISSUE TITLE
Inquirer hangs on subsequent calls in newest v6.4.0 (works in 6.3.1)

### ISSUE THREAD

**Issue by edmundpf** [SBoudrias/Inquirer.js#812]
Can't show source since private code, but essentially I had a project built with v6.3.1, when I installed it on a new machine, it grabbed the newest v6.4.0. When the code got to an inquirer call after the first call, the terminal became unresponsive, I could not type, and you could not terminate the script with CTRL+C. I thought something was wrong with my code but alas when I downgraded inquirer back to v6.3.1 everything was working perfectly. I think some people in recent issues are experiencing similar issues.

**Comment by joeycozza** [comment]
Here is my code. Works on inquirer version 6.3.1, totally hangs (even CTRL-C) on 6.4.0
```javascript
async function promptForName(message, validateFunction) {
  const { name } = await inquirer.prompt({
    message,
    name: 'name',
    type: 'input',
  })

  return validateFunction(name) ? name : promptForName(message, validateFunction)
}
```

I'll do some quick testing to see if I can pair the code down even more.

**Comment by sean256** [comment]
Same issue here. In addition to subsequent prompts locking up, even a single prompt will freeze the app for a few good seconds before the process ends.

**Comment by joeycozza** [comment]
looks like this is a dupe of #811 and they already have the reproducing code there.

**Comment by edmundpf** [comment]
> Here is my code.
> 2 prompts works fine on inquirer version 6.3.1
> 
> On 6.4.0, the initial prompt works, but then any additional attempt has the hanging/blocking behavior.
> 
> ```js
> const inquirer = require('inquirer')
> 
> foo().then(res => {
>   console.log('res: ', res)
>   foo().then(res2 => {
>     console.log('res2: ', res2)
>   })
> })
> 
> async function foo() {
>   const { name } = await inquirer.prompt({
>     message: 'input your name',
>     name: 'name',
>     type: 'input',
>   })
> 
>   return name
> }
> ```
I don't doubt that works, but for whatever reason a lot of people are having this issue, could be type of prompt, etc.

Here's some minimal code:
''' javascript
async function getAction() {

	const choices = {
						configApp: 'Configure API/Web App',
						configSchema: 'Configure Database Schema',
						setSecret: 'Set up a secret key',
						createAdmin: 'Create an admin account',
						resetAdmin: 'Reset admin accounts and secret key',
						updatePassword: 'Update admin password',
					}
	const answer = await inquirer.prompt([
		{
			type: 'rawlist',
			name: 'action',
			message: 'What would you like to do?',
			choices: Object.values(choices)
		}
	])

	for (const choice of Object.keys(choices)) {
		if (choices[choice] == answer.action) {
			eval(`${choice}()`)
		}
	}
}
// Set Secret Key

async function setSecret() {

	print('This will set your secret key for admin signup. If you have an existing key, it will become obsolete.', 'success')

	try {

		if (REQUEST_CONFIG.token == '') {

			try {
				const req = await request({
					method: 'GET',
					uri: `http://localhost:${REQUEST_CONFIG.port}/secret_key/get_all`,
					json: true,
				})
				if (req.status == 'ok') {
					if (await secretKey()) { return }
					else { return await tryAgain(setSecret) }
				}
			}
			catch (err) {
				print('This API endpoint is protected since a secret key has already been set up. You must log in to change your secret key.')
			}

			if (await login()) {
				if (await secretKey()) { return }
				else { return await tryAgain(setSecret) }
			}
		}
		else if (REQUEST_CONFIG.token != '') {
			if (await secretKey()) { return }
			else { return await tryAgain(setSecret) }
		}
	}
	catch (err) {
		if (err.error.response != null &&
			err.error.response.message != null &&
			err.error.response.message == 'No token provided.') {
				protectedMessage()
		}
		else {
			print('Could not set secret key.', 'danger')
		}
		return await tryAgain(setSecret)
	}

}

// Set Secret Key Routine

async function secretKey() {

	var key_match = false
	var answer
	while (!key_match) {
		answer = await inquirer.prompt([
			{
				type: 'password',
				name: 'secret1',
				message: 'Enter your secret key (shh):',
				mask: true,
			},
			{
				type: 'password',
				name: 'secret2',
				message: 'Confirm your secret key:',
				mask: true,
			},
		])

		key_match = (answer.secret1 == answer.secret2)
		if (!key_match) {
			print('Keys do not match! Please try again.', 'danger')
		}
	}

	const req = await request({
		method: 'GET',
		uri: `http://localhost:${REQUEST_CONFIG.port}/secret_key/insert?key=${answer.secret1}`,
		headers: { 'authorization': REQUEST_CONFIG.token },
		json: true,
	})

	if (req.status == 'ok') {
		print('Set new secret key.', 'success')
		await exitPrompt()
		return true
	}
	else {
		print('Could not set secret key.', 'danger')
		return false
	}

}
'''

**Comment by edmundpf** [comment]
> looks like this is a dupe of #811 and they already have the reproducing code there.
I see, I'll go ahead and close this, thanks

**Comment by edmundpf** [comment]
Closing, see #811 for issue.
