### ISSUE TITLE
Style customization

### ISSUE THREAD

**Issue by medikoo** [SBoudrias/Inquirer.js#822]
It'll be nice to be able to _style_ the output, e.g. at [serverless](https://github.com/serverless/serverless/) we'd love to resemble style to which we already accustomed our users, as e.g.:

![Screenshot 2019-07-08 at 17 32 53](https://user-images.githubusercontent.com/122434/60837515-a416ce80-a1c8-11e9-8bbc-ace9c5563e1a.png)

Currently, it appears that without hacking of inquirer internals it's not possible to achieve.

**Comment by SBoudrias** [comment]
I'm open to extend the API to support something like this. Maybe you could suggest how the API could look like?

**Comment by medikoo** [comment]
> Maybe you could suggest how the API could look like?

As `inquirer` is singleton, it could work as:

```javascript
inquirer.registerStyle({
  // Assign on top of default style (not changed remain as default)
  question: chalk.bold.yellow,
  answer: chalk.bold,
   ..
})
// All further prompts rely on that
```

Internally, probably `@inquirer/style` should be introduced to serve as a style information source for all prompts.

What do you think?

**Comment by SBoudrias** [comment]
Yeah I think I like that. Then we'd need to update our prompts to use `styles.question(prefix + question)` instead of raw chalk.

I don't think an extra module is necessary? What would this module do? Encapsulate default styles and the way to extend it?

Might be good to also unify everything like:

```js
{
	colors: {
		question: chalk.bold.yellow,
		...
	},
	glyphs: {
		questionPrefix: { default: '? ', windows: '? ' },
	}
}
```

There's been request to update the way we modify glyphs quite often too, so this might be a good occasion to unify everything under a styling interface.

**Comment by medikoo** [comment]
> Yeah I think I like that. Then we'd need to update our prompts to use styles.question(prefix + question)

It might be more composable if  a _prefix_ (which may already have a custom styles applied by user) is kept out of enforced styling, e.g. in my case I want _prefix_ to be in different style than _question_ body, so if _question_ style would be applied to it, I would need to add hack so it doesn't really apply.

> I don't think an extra module is necessary? What would this module do? Encapsulate default styles and the way to extend it?

I thought it'll be good if given prompts can just access given styles setup (without a need of injecting them as argument for every prompt creation). So my first thought was that e.g. [here](https://github.com/SBoudrias/Inquirer.js/blob/5c9f9e05c7d938c5052298b4d1740ebab913fb7f/packages/confirm/index.js#L2) it can be:

```javascript
const style = require('@inquirer/style');
```
but technically we could also do:

```javascript
const { style } = require('@inquirer/core')
```

> There's been request to update the way we modify glyphs quite often too, so this might be a good occasion to unify everything under a styling interface.

Currently, if I see correctly `?` is a default value for a prefix, which is already fully customizable. 
I'm not sure if it really applies for that. Are there any other characters in other places you're referring to?

**Comment by SBoudrias** [comment]
All the requests were about the question prefix specifically. But we could extend to things like lists characters, etc.

**Comment by SBoudrias** [comment]
Closing this old issue, there's a `theme` today configuration supported by all prompts.
