### ISSUE TITLE
Confirm Filter?

### ISSUE THREAD

**Issue by jedmao** [SBoudrias/Inquirer.js#836]
The [confirm prompt type](https://github.com/SBoudrias/Inquirer.js#confirm---type-confirm) doesn't say anything about supporting a `filter` key; however, [the tests do](https://github.com/SBoudrias/Inquirer.js/blob/83e8727f910b64f9f8b53c4646db0e0bfdf84393/packages/inquirer/test/specs/api.js#L114-L117). Which one is right?

**Comment by SBoudrias** [comment]
Hey the code is right. That being said I'm toying with potentially removing the filter option all together in a future major version (in favor of transforming the data in your own JS code)

**Comment by jedmao** [comment]
Thanks! Just FYI. I finished converting the entire project into TypeScript and am currently just trying to work out any remaining kinks.
