### ISSUE TITLE
v6.5.1 deps and Node.js 6.x

### ISSUE THREAD

**Issue by XhmikosR** [SBoudrias/Inquirer.js#837]
@SBoudrias: it seems you did some major version updates in dependencies and those drop Node.js 6.x support, like:

- `figures@3.x`
- `cli-cursor@3.x`
- `ansi-escapes@4.x`
- `string-width@4.x`

And for devDependencies `eslint@6.x`

But the package was published as a patch version. This violates semver and will break things. I suggest that you downgrade to the previous versions that supported Node.js 6.x, release a 6.5.2 version and then, if you want to bump those deps, make it major version bump.

**Comment by XhmikosR** [comment]
Friendly bump @SBoudrias. This is quite a serious regression that affects the ecosystem.

BTW don't get me wrong, I'm all for dropping Node.js 6.x support, but should be done properly with a major version bump after a patch has been released to restore 6.x support.

**Comment by IvanGoncharov** [comment]
@SBoudrias I fully agree with @XhmikosR comment:
> BTW don't get me wrong, I'm all for dropping Node.js 6.x support, but should be done properly with a major version bump after a patch has been released to restore 6.x support.

I maintain [graphql-js](https://github.com/graphql/graphql-js) and we plan to drop Node.js 6.x but we plan to make major release next month so this situation creates a lot of inconveniences.
Can you please release `6.5.2` at supports Node v6?

**Comment by rwjblue** [comment]
FWIW, this is also causing a bit of issues in the Ember ecosystem. Many packages have already updated to drop Node 6 support (with major version bumps) but some are waiting for specific circumstances to do a major version bump (e.g. a new feature on the way).

**Comment by SBoudrias** [comment]
Thanks for the feedback everyone. I'll release a rollback on the 6.x series and bump latest to 7.x

Just give me a few days to have time to handle this.

**Comment by SBoudrias** [comment]
Actually I took some time right now to do this. Should be fine now:

New versions:

- `v7.x` is latest master, it drops supports for Node 6
- `v6.5.2` who's `v6.5.0` republished to replace `v6.5.1`

**Comment by XhmikosR** [comment]
Thanks!
