### ISSUE TITLE
checkbox delete prompt message

### ISSUE THREAD

**Issue by joeyZhouYicheng** [SBoudrias/Inquirer.js#838]
If I just press a to choose all, and enter to submit, the prompt message won't disappear. It's kinda ugly i think.
![image](https://user-images.githubusercontent.com/39218926/62909456-4836fb00-bdaf-11e9-9277-97b998f3739c.png)

maybe we could add a line in line 125 of checkbox.js

```js
onEnd(state) {
    this.status = 'answered';
    this.spaceKeyPressed = true;   // add this!

    // Rerender prompt (and clean subline error)
...
}
```
and the prompt message will disappear after the enter pressed

![image](https://user-images.githubusercontent.com/39218926/62909520-86341f00-bdaf-11e9-820d-1b91301c63d4.png)
isn't that has a much better look, and a clearer message display?

**Comment by SBoudrias** [comment]
Can you send a PR? Seems like it's just a feature we missed.
