### ISSUE TITLE
What is the relationship between Inquirer.js and enquirer?

### ISSUE THREAD

**Issue by Gaspacchio** [SBoudrias/Inquirer.js#839]
I'm writing simple CLI app to ease the integration of style guide in JS projects ([standardize-js](https://github.com/Gaspacchio/standardize-js)), and am currently using [Inquirer.js](https://github.com/SBoudrias/Inquirer.js/) to get an interactive experience. I discovered [enquirer](https://github.com/enquirer/enquirer) and was wondering if there are benefits to keep using Inquirer.js?

Since enquirer seem to be pretty sure to be faster enquirer/enquirer#22 do you have advantages that enquirer has not? Are there any other advantages of one over the other?

Furthermore, since both projects seems to pursue the same goal, I was wondering if you were aware of their existence and what was your relationship?

Thanks for your nice answer!

_Btw, I have asked the same question (enquirer/enquirer#205) to the enquirer team to get a fair comparison_

**Comment by SBoudrias** [comment]
I didn't explorer enquirer too deeply. It's basically a fork/reimplementation of Inquirer.

Inquirer uses rxjs and Reactive programming which is slower than using raw JS - so it's possible it's faster. On the other hand, Inquirer has been there for a long time and has a very large install base.

See https://www.npmtrends.com/enquirer-vs-inquirer-vs-prompt-vs-prompts for quantitative differences. If this will matter a lot for your project, then you should spend time to explore each APIs; if it doesn't matter a lot then picking any should work just fine.
