### ISSUE TITLE
Arrows are not working in cmd?

### ISSUE THREAD

**Issue by ouahibAbdou** [SBoudrias/Inquirer.js#844]

**Comment by ResourceHog** [comment]
This is happening for me as well.

**Comment by SBoudrias** [comment]
@ResourceHog @ouahibAbdou how are you running your app?

`node index.js` or something else? If it's something else you need to make sure the input events are piped in.

**Comment by ResourceHog** [comment]
That's exactly how aframe-typescript-toolkit runs.

**Comment by wztscau** [comment]
Nodemon has this problem. Use node instead of nodemon.

**Comment by accimeesterlin** [comment]
I can confirm that this is not an issue with inquirer itself. It's an issue with nodemon. Run the app using node instead

```
node index.js
```

**Comment by dhl** [comment]
This is definitely a problem I can reproduce with `rawlist`, even without nodemon involved. `list`, on the other hand, is fine.

I have two modules:
```
app.js           <= entry module, what gets launched with `node app.js`
menu.js        <= creates a menu with `inquirer`. This is where `inquirer` is loaded.
```

With this setup, arrow key doesn't work on rawlist. However, if I require `inquirer` in `app.js` and pass the module into `menu.js` and using the passed in module, arrow key would work.

**Comment by Rjrunner44** [comment]
it's actually not a bug in either inquirer or nodemon, pass stdin to nodemon with -I flag. See: https://github.com/remy/nodemon/blob/master/doc/cli/options.txt#L16

**Comment by gouroujo** [comment]
For anyone looking for the nodemon configuration : `{ stdin : false }` in the configuration file or --no-stdin flag

**Comment by felipenmoura** [comment]
And for those who are NOT using nodemon, what's fix?

It was working normally...I updated to node 20+ and updated the dependencies and now arrows won't navigate.

The way I am using it (and haven't changed a line) is this:

```js
const inquirer = (await import('inquirer')).default;

inquirer
  .prompt([])
  .then(...);
```

**Comment by SBoudrias** [comment]
Oh yeah, the `rawlist` doesn't support arrow navigation (AFAIK never has 🤔)
