### ISSUE TITLE
"Press Enter to continue" prompt

### ISSUE THREAD

**Issue by medikoo** [SBoudrias/Inquirer.js#846]
It'll be nice to have a prompt that pauses the action, until user says it's fine to continue.

On our side we have a use case, where we expect user to setup something externally and then get back to the process.

Currently we solve it with "input" prompt, but it's not perfectly clean, user can write anything and it'll remain printed in a log.

**Comment by SBoudrias** [comment]
Hey @medikoo, I do not think this is a common case we should add to the core library.

But feel free to write a custom prompt to handle this use case! You can refer to the code of the plugins to see how this can be implemented: https://github.com/SBoudrias/Inquirer.js#plugins

**Comment by medikoo** [comment]
Ok, thanks for clarification

**Comment by ycmjason** [comment]
late to the party, but for whoever found this post, here's a lazy version of this prompt:

```ts
import { select } from '@inquirer/prompts';

export const enterToContinue = async ({
  message
}: { message: string }): Promise<void> => {
  await select({
    message,
    choices: ['Enter to continue...']
  });
};
```
