### ISSUE TITLE
FR: Non-infinite scroll version of paginator

### ISSUE THREAD

**Issue by jmoore914** [SBoudrias/Inquirer.js#853]
I think it would be useful to allow the user to choose whether they would like to use the default paginator with infinite scroll or a non-infinite scroll option. I actually built this feature into an inquirer plugin I wrote that I could show/turn into a PR if there is interest.

**Comment by bdenham** [comment]
Hey @jmoore914, I’d be interested to see the plugin you created. I’m looking for this feature to add Tom my CLI. Thanks.

**Comment by jmoore914** [comment]
Hi @bdenham,

Here is the plugin: https://github.com/jmoore914/inquirer-file-selector-prompt
The file with this feature is here: https://github.com/jmoore914/inquirer-file-selector-prompt/blob/master/paginatorNonInfinite.js

**Comment by SBoudrias** [comment]
This is also exposed under the `loop` option of list type prompts. It's been for a while, so not sure anymore in which version it was released; maybe v8.
