### ISSUE TITLE
Add `message` hook

### ISSUE THREAD

**Issue by vvscode** [SBoudrias/Inquirer.js#854]
How about adding support for `message` as a function, with takes all previous responses and returns a string?

That allow to add messages, which depends on previous values. 

@SBoudrias  The question - is PR welcome?

**Comment by SBoudrias** [comment]
Is this not already working?

**Comment by vvscode** [comment]
```message: (String|Function) The question to print. If defined as a function, the first parameter will be the current inquirer session answers. Defaults to the value of name (followed by a colon).```

missed, thanks
