### ISSUE TITLE
Choices does not support a promise like the documentation suggests

### ISSUE THREAD

**Issue by kbirger** [SBoudrias/Inquirer.js#858]
According to the readme
> default, choices(if defined as functions), validate, filter and when functions can be called asynchronously. Either return a promise or use this.async() to get a callback you'll call with the final value.

However, when I try to do this, I get an error:
> TypeError: choices.forEach is not a function
    at listRender (.......\node_modules\inquirer\lib\prompts\list.js:157:11)

Looks like the line of code being called, and indeed, the whole file, assumes that choices will be an array.
https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/lib/prompts/list.js#L157

**Comment by SBoudrias** [comment]
The code changed a lot since 2019, I don't believe this bug still exists.
