### ISSUE TITLE
rawlist: move up and down do not work properly with multi rawlist

### ISSUE THREAD

**Issue by hk029** [SBoudrias/Inquirer.js#861]
When you use multiple rawlist, there will be a mess up in the second rawlist. As you can see in the gifs below, when you press `Down` key 3 times, and `Up` key 1 times, the current selection should be the third one, but it turn out to the first one.

Here is the gifs
![](https://p1.music.126.net/xqHm2FPX0SQjvWDCQ8IK7Q==/109951164500081208.gif)

![](https://p1.music.126.net/915lZkKCDBxbh9krCOszZA==/109951164500075471.gif)

Here is my code
```
const { prompt } = require('inquirer');

const questions = [
    {
        type: 'rawlist',
        name: 'application',
        message: 'first question',
        default: 'web',
        choices: ['a', 'b', 'c'],
    },
    {
        type: 'rawlist',
        name: 'prefix',
        message: 'second question',
        default: 'music-',
        choices: ['aa', 'bb', 'cc', 'dd'],
    },
];

async function main() {
    const params = await prompt(questions);
    console.log(params);
}
```

Environment | Info
-- | --
inqquirer | 7.0.0
System | Mac OS X 10.15.1

**Comment by ovidiu141** [comment]
Shouldn't this issue be closed?
