### ISSUE TITLE
inquirer js progress bar

### ISSUE THREAD

**Issue by kruzus** [SBoudrias/Inquirer.js#868]
Is there a way to integrate a progress bar with this?

**Comment by na57** [comment]
There should be.

**Comment by SBoudrias** [comment]
A progress bar or flow control could be created, but that to me is a different package.

I wouldn't mind integrating it under the `@inquirer/*` umbrella and officially supporting, but I have limited interest to develop a solution myself (it can change in the future, but not a personal priority now.) I'm happy to help brainstorming an API design, but first step is to properly understand the problem space.
