### ISSUE TITLE
Dots "." are not supported in question names

### ISSUE THREAD

**Issue by EvHaus** [SBoudrias/Inquirer.js#871]
It looks like dots are not supported in question names. The following code:

```js
const stuff = await inquirer.prompt([{
    name: "name.with.dots",
    message: "some message"
    type: 'password'
}]);
```

Results in garbage output:

```js
{
    name: [ null, null, null, "asd" ]
}
```

Where I would expect:

```js
{
    "name.with.dots": "asd"
}
```

**Comment by SBoudrias** [comment]
PR welcome to fix this issue

**Comment by xiaoxielnino** [comment]
@EvHaus @SBoudrias 
It seems not to be a bug here. Inquirer.js provides the feature that allows us to deal with nested name.  It will take it as a `'path'` to the question names.

With the following code:
```js
const stuff = await inquirer.prompt([{
    name: "name.with.dots",
    message: "some message"
    type: 'password'
}]);
```
 If the names contain dots, the result output:
```js
{
  name: {
    with: {
      dots: 'asd'
    }
  }
}
```
not  : 
```js
{
    "name.with.dots": "asd"
}
```
If you do not like this feature, please replace them with other symbols like `'-'`.

**Comment by radarsu** [comment]
When you use for example **chalk** library to color some strings in name property the problem arises and you get answer object like:
```ts
answer { '\u001b': { '34mts-node\u001b': { '39m \u001b': [Object] } } }
```
I believe inquirer should provide additional property "ignoreDots" that would ignore the feature of dealing with nested names.
