### ISSUE TITLE
adding/removing choices live

### ISSUE THREAD

**Issue by jedwards1211** [SBoudrias/Inquirer.js#872]
I just built some inquirer prompts to select a task from AWS ECS.  Because fetching the tasks is a somewhat slow, multi-step process, I'd like to be able to display a prompt as soon as possible add the choices as they come in.  I also show a recent items list immediately at first, and I'd like to remove items from that list as soon as I hear back from the SDK that they no longer exist.

I skimmed the list code, not long enough to completely grok it, but I didn't get the impression it supports reactive updates to the list of choices.  Or does it?  If so I'd be happy to PR a section to the readme documenting how to do this.

**Comment by SBoudrias** [comment]
Hey @jedwards1211, that's unlikely something I want to support within the library itself. It's quite a specific use case, and it'd be quite a lot of efforts to support in a reusable way.

I'd suggest you to implement a custom prompt to handle this special logic. I've been working on a new Inquirer core API over the last year, and you might be able to use this to implement a custom list that'll refresh its options when you're getting more data. You can take the new list prompt code as a starting point: https://github.com/SBoudrias/Inquirer.js/blob/master/packages/select/index.js

Good luck!

**Comment by jedwards1211** [comment]
Yeah it was just a thought.
I like how you cloned the React hooks API for this, it's great huh?
