### ISSUE TITLE
possibility to expand text for a list/rawlist choice

### ISSUE THREAD

**Issue by Eken92** [SBoudrias/Inquirer.js#877]
When having a list with options that "hides" a lot of information within them, is there a way to build a trigger for some kind of "help"/"description". Something like an option to "expand" a list choice.

Let's say I have the following rawlist:
? Select rule
1) rule1
2) rule2
3) rule3

Then I would like to know what the "conditions and actions" are for that rule. So, if I arrow down to rule 2, then by pressing ctrl+e (expand) - or so, then additional text would be provided after that option (providing a string as return value). Like this:

? Select rule
1) rule1
2) rule2
-- No candy on friday
-- No tv after 22
++ Gets a big ice cream by the end of the week
3) rule 3

Would this somehow be possible? Would be a really cool feature.

**Comment by SBoudrias** [comment]
This is possible with the `description` property of choices. Ref https://github.com/SBoudrias/Inquirer.js/tree/main/packages/select#choice-object
