### ISSUE TITLE
Filter for list and checkbox

### ISSUE THREAD

**Issue by joseadrian** [SBoudrias/Inquirer.js#88]
This is what I tried to do but I just did it for the checkbox prompt. I didn't make a pull request because I haven't added the unit test and I'm not sure if the way I implemented it is ok. Also, I had to remove the J/K option to make it work

Here is a preview:

![Checkbox Inquirer](http://i.imgur.com/9cuELTX.gif)

Maybe it can support regex or fuzzy search.

**Comment by Manu-Sanchez** [comment]
Hi I've the same issue, but I decided to implement a solution by myself.

It's quite simpler and probably you'll need to make few changes for fit your requirements.
Probably as it's a great solution I'll be keeping updating it.

I don't want to fight against pyInquirer, but for my needs, I require this filter functionality.

You can find the source code here:
https://github.com/Manu-Sanchez/utils/tree/python_selector

Some kind of feedback or rating will be appretiated 💯
