### ISSUE TITLE
Filename/extension for editor temp file

### ISSUE THREAD

**Issue by risen228** [SBoudrias/Inquirer.js#888]
Hello.

I think it would be useful to make possible to provide filename and extension for temporary file. As I see [here](https://github.com/mrkmg/node-external-editor#api), that will not be difficult.

For example, some IDEs/editors will be able to provide a code highlighting using the file extension.

I can submit a pull request, if you want.

**Comment by SBoudrias** [comment]
Hey @risenforces, this sounds like a good idea. PR welcome, I'll help to review and merge asap.

**Comment by SBoudrias** [comment]
[cleaning up old issues]

Support for this was added with [the `postfix` option](https://github.com/SBoudrias/Inquirer.js/tree/main/packages/editor#options). We forgot to close this issue.
