### ISSUE TITLE
Rawlist prints the value of the selected choice on answer instead of name or short

### ISSUE THREAD

**Issue by schl3ck** [SBoudrias/Inquirer.js#889]
Rawlist prints the value of the selected choice on answer instead of the properties `name` or `short`.

I digged into it, where this probably comes from and I think that it is here:
https://github.com/SBoudrias/Inquirer.js/blob/6a883e64dc238fc0dcc33ac77f6abcd4ca4dff5a/packages/inquirer/lib/prompts/rawlist.js#L61

The function that is bound here, returns what the name suggests, but as this also defines the value that is displayed to the user, it displayes `value` of the selected choice instead of its `name` or `short`.

**Comment by ovidiu141** [comment]
This can be closed
