### ISSUE TITLE
Window SigInt not working.

### ISSUE THREAD

**Issue by shirshak55** [SBoudrias/Inquirer.js#900]
I don't know but in past ctrl+c on gitbash windows used to work. Now it doesn't work just because i used this package :(

Any solution?

**Comment by sqal** [comment]
@shirshak55 check latest release 7.1.0. I had the same issue with ctrl+c in every windows terminal, but the latest version has fixed that issue for me.

**Comment by shirshak55** [comment]
@sqal yes works now. I just hope they don't break like this.
