### ISSUE TITLE
Do not cleanup editor when content is not valid

### ISSUE THREAD

**Issue by marhaupe** [SBoudrias/Inquirer.js#907]
Currently, the temporary file created by the `editor` prompt gets deleted whether or not the `validate` function returns true. Looking at the source of the `external-editor` module, as far as I can tell, it should be fairly easy to delay the file cleanup. Let me know if PRs are welcome for this, I'd very much like to have this functionality.

**Comment by marhaupe** [comment]
Quick Update @SBoudrias: I'm currently using my own fork where I added this functionality. Let me know what I have to do before submitting a PR. As far as I can tell, I have to change the old and the new packages, which I already did. Anything else?

**Comment by SBoudrias** [comment]
This changed at some point, but I'm adding back an option (not default) to clear the value to keep the editor prompt feature set aligned with the input prompt. Cheers!

**Comment by marhaupe** [comment]
Awesome! Cheers for actually getting back to me, appreciate your work.
