### ISSUE TITLE
filter function does not seem to work on confirms

### ISSUE THREAD

**Issue by farisT** [SBoudrias/Inquirer.js#909]
Hi, I have been trying to flip the boolean I receive from a confirm question and the filter doesn't seem to return the desired results

```
      message: `Create a new folder for the ${componentType} and its dependent components?`,
      name: 'flatFile',
      type: 'confirm',
      filter: (input: boolean) => {
        return !input;
      },
```
Even If i hardcode a boolean it will still return the answered value instead of the filtered value

**Comment by SBoudrias** [comment]
Since `inquirer` is depreciated, we won't change this API.

But doing this will be much easier with the modern api:

```js
const answer = !await confirm({
    message: message: `Create a new folder for the ${componentType} and its dependent components?`
});
```
