### ISSUE TITLE
[Question] How can I have an input question with prefilled data?

### ISSUE THREAD

**Issue by brlebtag** [SBoudrias/Inquirer.js#911]
My problem is: I create a dynamic name based on some informations asked before and I want to check with the user if the name is good, otherwise they can fix whatever the way they want.

I'd like to do something like this:

```
const answers = await this.prompt([
                {
                    type: 'input',
                    name: 'fixed',
                    message: 'Ok, you can fix the name now',
                    value: nameToBeFixed
                },
            ]);
```
How can I do that?

Thanks in advance!

**Comment by kschang77** [comment]
Usually, you use default. 

default: (String|Number|Boolean|Array|Function) Default value(s) to use if nothing is entered, or a function that returns the default value(s). If defined as a function, the first parameter will be the current inquirer session answers.

Unless you mean you want the input to be PREPOPULATED with something, so the user can backspace over it?

**Comment by remisture** [comment]
@kschang77 Do you have an example of how to pre-populate the value for an input type (editable)?

**Comment by oom-** [comment]
I'm looking for "PREPOPULATED " too.

**Comment by thiboot** [comment]
Hello,
I'm looking for a pre-populated answer too (to be editable, not default)
Thanks

**Comment by brlebtag** [comment]
Sorry guys. I didn't see the messages.

@kschang77  Yeah I want it to be pre-populated and the user can later edit it. So it is not just a default option.

@thiboot No, I didn't.

**Comment by SBoudrias** [comment]
Latest inquirer will prepopulate the value with the default when pressing `tab` allowing the user to edit it without typing a value from scratch.

I think this solution is acceptable and fixes the UX issue.

**Comment by daviddavid** [comment]
I didn't know about the `tab` functionality. Would be good to include in the input/README.
