### ISSUE TITLE
smaller alternative to RxJS?

### ISSUE THREAD

**Issue by mheiber** [SBoudrias/Inquirer.js#913]
Thanks for your library!

I noticed that [27% of the package size is RxJS](https://bundlephobia.com/result?p=inquirer@7.1.0):

![package size from link above](https://user-images.githubusercontent.com/4691093/79861981-39d4c080-83cd-11ea-95f6-e14ed25c7007.PNG)

We're trying to keep package sizes small to reduce download times for users.

[@react-native-community/rxjs](https://github.com/react-native-community/rxjs) seems seems to be 1/10th the size. A more drastic change would be using something like [xstream](https://github.com/staltz/xstream).

**Comment by lydell** [comment]
This would be great. ESLint is around 36 MB on my machine – almost half of that is rxjs (via inquirer).

**Comment by SBoudrias** [comment]
FWIW, the repo contains beta versions of a fully reimplemented version of Inquirer without rxjs (see https://github.com/SBoudrias/Inquirer.js/issues/692)

It's not complete, but most prompts are functional and deployed to npm already. There's just not any top-level `Inquirer.js` release offering the question list API (it goes like `await checkbox({ ... })`)

You might be interested in trying the beta versions, or helping out 🙏 with refactoring missing prompts.

**Comment by XhmikosR** [comment]
Nice to hear that!

Can you share a little more info like a PR/branch/tag where the rxjs removal is implemented? I can't find it anywhere.

I haven't used rxjs myself, but the number of files it ships is insane :/ And imagine on a big project where the package manager cannot deduplicate rxjs, the effect is even bigger.

**Comment by SBoudrias** [comment]
Of course, this is on the `master` branch, but in different section of the monorepo. Inside the [`packages/**` root](https://github.com/SBoudrias/Inquirer.js/tree/master/packages), every folder except `inquirer` are new prompts implemented without the rxjs dependency.

**Comment by XhmikosR** [comment]
Ah, I was looking at this: https://github.com/SBoudrias/Inquirer.js/blob/a1da6cfc97fe29cdeb1edc8b2aafc20eeaf85dca/packages/inquirer/package.json#L50

Very promising, looking forward to the removal of rxjs!

**Comment by SBoudrias** [comment]
The [new Inquirer](#1214) is now out and stable. So I'll close this ticket as I don't intend to modify the old one aside from basic maintenance.
