### ISSUE TITLE
Editor prompt type enhancement - Allow specifying temp file extension to get syntax highlighting

### ISSUE THREAD

**Issue by akaleeroy** [SBoudrias/Inquirer.js#914]
If the temp files had an extension editors could immediately provide syntax highlighting, linting etc.

[`node-external-editor`](https://github.com/mrkmg/node-external-editor) config provides

> `postfix` (string) _Optional_ A postfix for the file name. Useful if you want to provide an extension.

passed on from the [`tmp`](https://www.npmjs.com/package/tmp) package.

Maybe `type`, `name`, `message` [, **`extension`,** `default`, `filter`, `validate`].  
Or fully `type`, `name`, `message` [, **`tmpConfig`,** `default`, `filter`, `validate`] ?

**Comment by SBoudrias** [comment]
Good idea! If you're willing to send a PR, I'll help to review, merge and release.
