### ISSUE TITLE
Broken support for Node.js v6 with a patch release

### ISSUE THREAD

**Issue by medikoo** [SBoudrias/Inquirer.js#920]
`inquirer` documents that [Node.js v6 is supported](https://github.com/SBoudrias/Inquirer.js/blob/92bad2f2622d523f5ce9e12b42863a1c5605a761/packages/inquirer/package.json#L20)

While it got broken with v7.0.5  release by https://github.com/SBoudrias/Inquirer.js/commit/e2099ed6aca935c13aff4af93fe8bf51155caf38 which upgraded `chalk` to v3 (which doesn't support Node.js v6 anymore)

Such change (assuming project follows semver) should be introduced with a new major

**Comment by LitoMore** [comment]
We dropped support for Node.js 6 since 7.0.0.

https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%407.0.0

**Comment by medikoo** [comment]
Ok, so you probably should fix that line:

https://github.com/SBoudrias/Inquirer.js/blob/92bad2f2622d523f5ce9e12b42863a1c5605a761/packages/inquirer/package.json#L20

**Comment by LitoMore** [comment]
@medikoo Oh, good point! Thank you so much!
