### ISSUE TITLE
Can i store an answer in a variable for export?

### ISSUE THREAD

**Issue by aanghileri** [SBoudrias/Inquirer.js#927]
Im trying to do a interactive menu with a list of options. When you select one of the options, a js file in the same folder will be executed. I need to store one answer in a variable to export it in another js file. Can i do that?

   inquirer.prompt([
            {type:"input",
            name: "appID",
            message: "What is the name of the appID?"}
          ])
          .then(({appNewID}) =>{
            if(appNewID){
                //Do something...
        }
            const iteration2 = require('./iteration2')
            iteration2 
        
     }) 

I have to store the answer from the question "What is the name of the appID" and export it in another js file.

**Comment by ovidiu141** [comment]
I think this is not a library issue and should be closed.
