### ISSUE TITLE
rawlist displays 'value' instead of 'short' after selection

### ISSUE THREAD

**Issue by jns** [SBoudrias/Inquirer.js#929]
Using Inquirer v7.1.0

Summary:
The rawlist type displays the 'value' instead of the 'short' after a user makes selection.

Steps to reproduce:
1) create a choices array of objects with properties `name`, `value`, and `short`
2) Add choices to a 'rawlist' type prompt
3) Run and make a selection.  The 'value' property is displayed after selection instead of 'short'

Note: 
This does not occur for a 'list' type.

**Comment by idbartosz** [comment]
Bump, same with `7.3.3`.

**Comment by CeroOscura** [comment]
Bump, the same issue I've been seeing in 8.0.0
