### ISSUE TITLE
Allow recording of multiple checkbox order

### ISSUE THREAD

**Issue by RecuencoJones** [SBoudrias/Inquirer.js#932]
Digging into [ntl](https://github.com/ruyadorno/ntl) utility, which uses inquirer underneath through [ipt](https://github.com/ruyadorno/ipt), I realized it would be really useful if user could select multiple checkboxes in order.

Let's say I have a multiple checkbox input like this:

```
(x) Build
(x) Lint
( ) Test
```

If I'd select `Lint` then `Build`, the output of that will be `[ 'Build', 'Lint' ]`, which is not really the order I picked for those!

<details>
<summary>
Sample code
</summary>

```javascript
const inquirer = require('inquirer')

async function main() {
  const answers = await inquirer.prompt([
    {
      name: 'steps',
      choices: [
        'Build',
        'Lint',
        'Test'
      ],
      type: 'checkbox'
    }
  ])

  console.log(answers)
}

main()
```

```
? steps: 
 ◯ Build
❯◉ Lint
 ◯ Test
```

```
? steps: 
❯◉ Build
 ◉ Lint
 ◯ Test
```

```
? steps: Build, Lint
{ steps: [ 'Build', 'Lint' ] }
```

</details>

What would be great is to have some sort of option for choices which would allow something like:

```
(2) Build
(1) Lint
( ) Test
```

Every time user selected an option, an order is set to the values, in this case `Lint` was clearly selected before `Build`.
When deselecting an option, indexes will be modified accordingly.
To more easily control this, a trailing Reset option could be added or by default let the user Ctrl^C and start again.

**Comment by RecuencoJones** [comment]
Sample implementation https://github.com/RecuencoJones/Inquirer.js/tree/master/packages/ordinal

**Comment by RecuencoJones** [comment]
@ruyadorno would you be interested in this kind of behavior for ntl?

Maybe we could publish the ordinal prompt as a standalone package

**Comment by ruyadorno** [comment]
sure thing 👍 this looks like a great idea for **ntl**! I think **Inquirer.js** has been favouring their plugin system instead of adding to their core prompts - that said, it wouldn’t be a problem adding the extra plugin to **ipt** 😊

**Comment by RecuencoJones** [comment]
Published as [inquirer-ordinal-prompt](https://www.npmjs.com/package/inquirer-ordinal-prompt)
