### ISSUE TITLE
Help option (eg. via F1)

### ISSUE THREAD

**Issue by DavidUrting** [SBoudrias/Inquirer.js#933]
Hi, 
Is it possible to associate some help text to particular questions in Inquirer?
I think it would be a nice feature if a user can access help (eg. via F1) when he/she has to answer a complex question.
We currenly use Inquirer to guide a developer through 15+ technical steps. Some if these steps need some explanation, especially for junior or new developers.

**Comment by SBoudrias** [comment]
[Cleaning old issues]

This feature request doesn't meet with the goals of the project to become an internal utility.

It is however something I believe can be implemented in the user land. Each prompt can be interrupted with an `AbortController`. You could add a wrapper that'll listen for F1 keypresses, interrupt the prompt, print the help text (or anything you want to do here really), and once ready, prompt again.
