### ISSUE TITLE
change the answer object

### ISSUE THREAD

**Issue by dev-dafab** [SBoudrias/Inquirer.js#935]
I have a usecase where the intermediary answer given by `confirm` question is not needed in the end result of a terminal wizard. 

example:

```
with_dotfile_url ( confirm )
dotfiles_location ( input )
```

possible answers: 

```
// case 1.
{
    dotfiles_location: false
}
```

```
// case 2.
{
    with_dotfile_url: true,
    dotfiles_location: somurl.com/dotfiles
}
```

in case 1. and 2. `with_dotfile_url` is not needed in the final answer.

Is it possible to change the answer object with the current version ? I well may have missed it in documentation, which I readed several time looking for a way to implement my usecase. I know it s possible to transform the output of the answer but not the answer ( and hash value ).

If it s not possible  right now, let me know if this feature would be interesting, I would be more than happy to share my fork ( submit a PR ) implementing this behaviour. 

Thank you for the awesome piece of software. 
Sorry for my poor english.

**Comment by SBoudrias** [comment]
Hey @dev-dafab, this is something that you can easily handle with JS:

```js
const { with_dotfile_url, ...answers } = await inquirer.prompt();
// Now answers do not contains `with_dotfile_url`
```

I don't think building a feature like this within the core would add much value VS the added complexity to the API surface and the extra maintenance it will require over time.
