### ISSUE TITLE
 Lodash dependency causes prototype pollution issue: can you use another package instead of lodash?

### ISSUE THREAD

**Issue by marcoippolito** [SBoudrias/Inquirer.js#938]
Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ peerjs                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ peerjs > opencollective > inquirer > lodash                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1523    

https://www.npmjs.com/advisories/1523

"No fix is currently available. Consider using an alternative package until a fix is made available."

So... can you use another package instead of lodash?

Environment Info:

    System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
   CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
   Binaries:
     Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
     Yarn: 1.22.4 - /usr/bin/yarn
     npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm

    npm ls | grep "inquirer"
    ├─┬ inquirer@7.3.0
    │ │ ├─┬ inquirer@3.0.6

**Comment by SBoudrias** [comment]
You can force downgrade lodash to a version without this issue? Those errors are always present in the npm audit, I'd say it's unlikely to be a major security concern (especially since inquirer is probably not running your production website)
