### ISSUE TITLE
Node V8 Support broken with 7.3.0

### ISSUE THREAD

**Issue by githoniel** [SBoudrias/Inquirer.js#940]
inquirer@7.3.0 is using chalk@4.1.0 which does not support node v8

I think we should bump deps and upgrade to inquirer@8.0.0 dropping legecy node support while keep inquirer@7.X.X work with old node

**Comment by SBoudrias** [comment]
Sorry about this, it's really hard to track breaking old Node version when bumping library. You should use package-lock to make sure this doesn't happen if you run versions who're out of LTS.

Since Node 8 is out of LTS, I'll leave the package as is. Feel free to downgrade to the previous version.

**Comment by IanVS** [comment]
This has broken installations of storybook 5.3, which supports node 8 and relies on inquirer@^7.0.0.  Lock files are fine, but they're not sufficient for me who is trying to install that version of storybook into a project that is so far locked into node 8.

Please be a good citizen and follow semver.  If you'd like to drop node 8 support, that's cool, but the right thing to do would be to release a new major version.  There's no telling how many other packages and libraries might be broken by not doing so.
