### ISSUE TITLE
Handle key events when prompter is in place

### ISSUE THREAD

**Issue by laraprabhu** [SBoudrias/Inquirer.js#949]
When prompter is prompting something to the user, I want to give user a provision to access the history of answers that they answered before. Like a regular command line interface. Say for example: 

What is your emp name? Jon
What is your emp name? Rose
What is your emp name? Pete
What is your emp name? <here if user presses up arrow or down arrow, I want them to navigate up and down through the history of answers>

I can maintain the history in an array. But I don't know, How to handle key events when prompting. I have tried using process.stdin to read the key events and tried to use stdout to set certain text as an answer, but if I hit enter. The set text was ignored as an empty answer.

Can anyone give me a cleaner approach to handle this?

**Comment by ElvisHernandez** [comment]
If I understand your question correctly, you can achieve a crude version of this with the following code.

**Comment by ElvisHernandez** [comment]
If i understand your question correctly, you can achieve this by using the readline module to emit key press events to stdin and then add an event listener to stdin that act accordingly based off of the specific key press event. 

Here's some sample code that implements this in a naive way. Maybe it'll help get you started

```javascript
const readline = require('readline');
const Inquirer = require('inquirer');

// Use readline to feed keypress events to stdin stream
readline.emitKeypressEvents(process.stdin)

// history of answers
const answers = [
    'answer1',
    'answer2',
    'answer3',
    'answer4'
]

// current 
let lastChoice = '';
let i = answers.length;

const emailQuestion = {
    type: 'input',
    name: 'email',
    message: ('Please enter email:'),
    filter: (email) => {
        if (!email.trim()) return lastChoice;
        return email;
    }
};

(async () => {
    const answer = await Inquirer.prompt(emailQuestion);
    console.log(answer)
})();


process.stdin.on('keypress', (_,key) => {

    const { name } = key;

    if (name !== 'up' && name !== 'down' || name === 'return')
        return;

    if (name === 'up') i--;

    if (name === 'down') i++;

    if (i > answers.length - 1) i = 0;

    if (i < 0) i = answers.length - 1;

    lastChoice = answers[i];

    process.stdout.write(lastChoice);
})
```

**Comment by laraprabhu** [comment]
@ElvisHernandez This is awesome. I have written something similar to yours except the usage of `filter`. This works fine, But there are certain issues still exists.

What works:
* Up and down arrow prints what resides in the history array.
* After navigating the history array using Up and Down arrow, pressing enter key considers the value.(this is because of filter).

What doesn't work:
* After hitting enter for the first time. Our event listeners are overridden. That stops history navigation from working.
* After selecting a value from history using up and down navigation, if we try to use backspace, then that is not working and that completely erases the selected value from history.

**Comment by IKoshelev** [comment]
> * After selecting a value from history using up and down navigation, if we try to use backspace, then that is not working and that completely erases the selected value.

I had the same issue. It looks like event listening is sensitive to the order, in which operations are performed. The setup that looks to work for me is:
```
readline.emitKeypressEvents(process.stdin);
openPromptForTheFirstTime();
process.stdin.on('keypress', (_,key) => {...});
```

Also, by default, holding `Shift` or `Ctrl` is not reported for many keys: https://github.com/nodejs/node/issues/2890
