### ISSUE TITLE
How to develop a plugin for Inquirer.js?

### ISSUE THREAD

**Issue by cccRaim** [SBoudrias/Inquirer.js#955]
I find plugin list in README.md.
But I want to develop plugin for myself, I don't know how to code.

I think there should have a `document` for plugin develop.
It is unrealistic to read the source code of each plugin.

**Comment by LitoMore** [comment]
OK. I will make a documentation for that.

**Comment by jamespohalloran** [comment]
Any updates on documentation for custom plugins?

**Comment by SBoudrias** [comment]
Hey @jamespohalloran, I made some progress on documenting the new core API over here https://github.com/SBoudrias/Inquirer.js/tree/master/packages/core - I'd love feedback and/or PRs helping to make that documentation better!
