### ISSUE TITLE
How can I disable help tips?

### ISSUE THREAD

**Issue by hunkjazz** [SBoudrias/Inquirer.js#963]

**Comment by inwardmovement** [comment]
Indeed, could you provide an option to disable tips like "(Use arrow keys)" please?

**Comment by SBoudrias** [comment]
Happy to review a PR adding this to `@inquirer/prompts` through a `theme` flag.

**Comment by SBoudrias** [comment]
PR #1381 is up with this feature. I'll leave open a few days for review and feedback. Feel free to chip in!
