### ISSUE TITLE
Question Object documentation should list required fields

### ISSUE THREAD

**Issue by fireproofsocks** [SBoudrias/Inquirer.js#966]
When defining a list of question objects, it is not clear which fields are required.  For example, the `type` field will default to `input`, but if the `name` field is omitted, nothing seems to work (and no error message is displayed).  I think it would help users a lot of the documentation included a few more clarifications on which fields were required and what the default values are and if the example code used a full functional example.

**Comment by SBoudrias** [comment]
Documentation was fully rewritten since; so I'll close this ticket. Further improvements welcomed.
