### ISSUE TITLE
Checkbox cli not allowing selection

### ISSUE THREAD

**Issue by mcdaddytalk** [SBoudrias/Inquirer.js#970]
MacOS iTerm (using zsh)

![Screen Shot 2020-09-28 at 5 59 25 PM](https://user-images.githubusercontent.com/63208849/94490488-59f68000-01b4-11eb-8e4e-f61e2528e0a4.png)

Directional keys and space not allowing movement or selection

I hope I am simply doing something silly

**Comment by licheng520** [comment]
The List type is also unselected，But the Windows system has a choice

**Comment by Alive-Fish** [comment]
I have met the same issue on MacOS too.

**Comment by SBoudrias** [comment]
Can you post demo or reproductible example? I would assume there's more going on in your own code than replicating the inquirer demos?

**Comment by mcdaddytalk** [comment]
I'll try to post a reproducible example today.  Yes, more going on, but if I can reproduce with something more simple, I'll post it here.

**Comment by mcdaddytalk** [comment]
cannot reproduce with current environment:
zsh 5.8.1 (x86_64-apple-darwin21.0)
node v16.14.0
macOS 12.5
inquirer 9.1.0
