### ISSUE TITLE
Cannot paste from clipboard

### ISSUE THREAD

**Issue by zpittmansf** [SBoudrias/Inquirer.js#977]
When the prompt type is input, pasting the clipboard results in nothing.

Windows 10
inquirer 7.3.3

**Comment by d3r1n** [comment]
use remote wsl or git bash or oh-my-zsh for windows maybe this can solve (in bash you paste with right click if you have something in your clipboard)

**Comment by zpittmansf** [comment]
> use remote wsl or git bash or oh-my-zsh for windows maybe this can solve (in bash you paste with right click if you have something in your clipboard)

I have tried in both powershell and git bash.

**Comment by d3r1n** [comment]
if you just using it for getting normal text input use Built-in NodeJS module ReadLine : 

[NodeJS API](https://nodejs.org/api/readline.html)

Simple Usage (From NodeJS API):

```js
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question('What do you think of Node.js? ', (answer) => {

  console.log(`Thank you for your valuable feedback: ${answer}`);

  rl.close();
});
```

**Comment by SBoudrias** [comment]
Tested this with the new demos and it appears to work properly. I'll close this issue.

You can try quickly with the following command: `npx @inquirer/demo@latest`
