### ISSUE TITLE
Go back to previous prompt on default using backspace/esc keypress?

### ISSUE THREAD

**Issue by florianmaxim** [SBoudrias/Inquirer.js#979]
Wouldn't it make a lot of sense if I could simple go back to the previous prompt by pressing backspace/esc/etc. if I have several prompts one after another?

Or is this already possible and I just didn't find it?

**Comment by nopeless** [comment]
I have same question

**Comment by SBoudrias** [comment]
Modern inquirer `@inquirer/prompts` doesn't provide flow controls anymore; so this request now fall outside the scope we do want to cover. (reason: modern Node doesn't need built-in flow control.)

The library does however expose a `cancel` method to stop an active prompt. So this can be implemented fairly easily in user land with a keypress listener, when press cancel the prompt, and recursively call the prompt function. Or maybe track a pointer of the current question in your code; etc.

Hopefully this helps a little!
