### ISSUE TITLE
Use VS code  in the type 'editor'

### ISSUE THREAD

**Issue by ArturGudiev** [SBoudrias/Inquirer.js#985]
I try to use VS Code as the default editor on Windows. Now it just opens a Notepad. 

I read somewhere (I didn't find it in Documentation) that  I should use $EDITOR or $VISUAL environment variables. 

So I set $EDITOR to `code` value and it didn't open anything. I tried to set the whole path  (`C:\Users\gudiea\AppData\Local\Programs\Microsoft VS Code\Code.exe`) but the result was the same. 

How can I use VS Code in the type `editor` ?

**Comment by bcorcoran** [comment]
This has nothing to do with Inquirer. Perhaps create an issue on https://github.com/microsoft/vscode ?

**Comment by ArturGudiev** [comment]
I think it relates to the Inquirer. Because other editors (e.g., sublime) are not opened as well. Could you please write the exact steps with the examples in the documentation on how to use this type on Windows.

**Comment by bcorcoran** [comment]
It's an issue with your environment variables. Try EDITOR=code before running your script. If it works, it isn't being set properly in your shell profile. This still has nothing to do with Inquirer.

**Comment by Norcy** [comment]
> It's an issue with your environment variables. Try `EDITOR=code` before running your script. If it works, it isn't being set properly in your shell profile. This still has nothing to do with Inquirer.
> 
> For example:
> 
> `EDITOR=code node myAppName`

Work

**Comment by mensah-j** [comment]
> Not work for me. When type Enter, vscode will open but the command line has recevied an empty line then jump next question

Try 
```javascript 
process.env['EDITOR'] = 'code -w';
```
By default `code` returns immediately after execution; the actual editor is a separate process. According to the [VSCode CLI options](https://code.visualstudio.com/docs/editor/command-line), you can use `code -w` or `code --wait` to block until the files are closed.
