### ISSUE TITLE
Is there a way for the terminal to take keyboard focus?

### ISSUE THREAD

**Issue by bencooper222** [SBoudrias/Inquirer.js#986]
I’m using the library as part of a CLI. It’s supposed to prompt the questions when certain events happen. Is there a way for me to get keyboard and window focus when those events happen?

**Comment by SBoudrias** [comment]
[I'm going through old issues.] This ask is related to how different OS does window management - not really something inquirer can help with directly. This logic would live outside the library at any rate. You'd probably `child_process` some native script grabbing the focus; or something like this.
