### ISSUE TITLE
Add support for multiline input

### ISSUE THREAD

**Issue by brianweil** [SBoudrias/Inquirer.js#99]
I would like to add support for multiple lines of text in the input type. I use the prompt for commit messages and sometimes one line is not enough. The UI could be as simple as pressing shift+enter to move to the next line of input. Feedback from the contributors is welcome and appreciated.

**Comment by jameswomack** [comment]
This would be great for doing things like blog posts from the command-line. Hexo would do well to integrate this.

**Comment by RonaldTreur** [comment]
Just to make sure this stays on the radar: +1

**Comment by adjohnson916** [comment]
+1 Any updates on this? I support the `Shift`+`Enter` idea, either as a default to insert newline on any option, or swapped for `Enter` behavior which instead inserts newline on options explicitly configured as multiline.

**Comment by SBoudrias** [comment]
@adjohnson916 PR welcomed.

**Comment by SBoudrias** [comment]
This is now shipped with `v1.1.0`

**Comment by 0phoff** [comment]
I know there is editor support, but is there any chance that you will also support multiline?
I prefer would prefer multiline over editor for my application.

Multiline should allow the user to enter multiple lines, and close when it encounters an empty line (or line with only a dot) or when the user presses CTRL+D.
At least that is the standard behaviour across various command line applications I use.

I tried to look at your code to implement it myself, but I don't really understand how to implement a custom prompt... Is there any documentation or tutorial?

**Comment by aleclarson** [comment]
I have a working implementation [here](https://github.com/aleclarson/inquirer/commit/3b5c14efa29be0efb4c713c40e9b7225822c9739). It adds a `multiline` option to `input` prompts.

I don't think it will merge cleanly into this repository, because I made other changes. But you could try if you're desperate.

**Comment by KoStard** [comment]
Has this feature been merged? I don't see how to receive multi-line input from the user from terminal without opening external windows.

```
import { input } from '@inquirer/prompts';

const answer = await input({
  message: 'Enter a description',
  multiline: true,
});
console.log(answer);
```

I tried this, but it only accepted one line. Also I don't see anything about multiline support in the homepage: https://github.com/SBoudrias/Inquirer.js

I think this issue can be reopened to track the interest in this request.

**Comment by SBoudrias** [comment]
Hi @KoStard, the multi-line comes through the `editor` prompt. There's been some more recent talk over here too https://github.com/SBoudrias/Inquirer.js/discussions/1583 (I'm open to improving this, but transparently, it's not on my todo list ATM. So it's up for the taking.)
