### ISSUE TITLE
How to Interact with Inquirer when execute command with child_process.exec?

### ISSUE THREAD

**Issue by lamysafari** [SBoudrias/Inquirer.js#990]
for exampple:
`const process = exec('some-cli', option, (error, stdout, stderr) => {
      
})`
some-cli uses inquirer
how can I interact with It to get output and send input?

**Comment by SBoudrias** [comment]
You'd need to send keypress events to the `stdin` stream of the spawned process. Kinda like how we handle it in `@inquirer/testing`; see https://github.com/SBoudrias/Inquirer.js/blob/main/packages/testing/src/index.mts#L73
